% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrreprt}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{luacolor}
  \usepackage[soul]{lua-ul}
\else
  \usepackage{soul}
  
\fi
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{5}
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{mdframed}
\usepackage{lipsum}
\usepackage{tcolorbox}
\usepackage{xcolor}
\usepackage[thickspace,nobracket]{actuarialangle}
\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[skins,breakable]{tcolorbox}}
\@ifpackageloaded{fontawesome5}{}{\usepackage{fontawesome5}}
\definecolor{quarto-callout-color}{HTML}{909090}
\definecolor{quarto-callout-note-color}{HTML}{0758E5}
\definecolor{quarto-callout-important-color}{HTML}{CC1914}
\definecolor{quarto-callout-warning-color}{HTML}{EB9113}
\definecolor{quarto-callout-tip-color}{HTML}{00A047}
\definecolor{quarto-callout-caution-color}{HTML}{FC5300}
\definecolor{quarto-callout-color-frame}{HTML}{acacac}
\definecolor{quarto-callout-note-color-frame}{HTML}{4582ec}
\definecolor{quarto-callout-important-color-frame}{HTML}{d9534f}
\definecolor{quarto-callout-warning-color-frame}{HTML}{f0ad4e}
\definecolor{quarto-callout-tip-color-frame}{HTML}{02b875}
\definecolor{quarto-callout-caution-color-frame}{HTML}{fd7e14}
\makeatother
\makeatletter
\@ifpackageloaded{bookmark}{}{\usepackage{bookmark}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={BIOS 526 Modern Regression Analysis},
  pdfauthor={Emily Peterson},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{BIOS 526 Modern Regression Analysis}
\author{Emily Peterson}
\date{2025-01-01}

\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{2}
\tableofcontents
}

\bookmarksetup{startatroot}

\chapter*{Introduction}\label{introduction}
\addcontentsline{toc}{chapter}{Introduction}

\markboth{Introduction}{Introduction}

\includegraphics[width=5.22917in,height=\textheight]{fig/intro.png}

Welcome to Modern Regression!

\textbf{Course Number:} 526 \textbf{Section Number:} 1

\textbf{Credit Hours:} 3 \textbf{Semester:} Fall 2025

\textbf{Class Hours and Location:} Monday \& Wednesday 1:30-2:50pm at
CNR 1051

\textbf{Instructor Name: Emily Peterson (Emily)}
emily.nancy.peterson@emory.edu

\textbf{Teaching Assistants:} Yutong Liu
\href{mailto:yutong.liu@emory.edu}{\nolinkurl{yutong.liu@emory.edu}}
Office hours: Mon 3pm-5pm at GCR 369 or Zoom
(\href{https://nam11.safelinks.protection.outlook.com/?url=https\%3A\%2F\%2Fzoom.us\%2Fj\%2F5503938635&data=05\%7C02\%7Cemily.nancy.peterson\%40emory.edu\%7C1dda9421ad104be2ed9908dcc6b3e9a0\%7Ce004fb9cb0a4424fbcd0322606d5df38\%7C0\%7C0\%7C638603723218676082\%7CUnknown\%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0\%3D\%7C0\%7C\%7C\%7C&sdata=IMRiKrKjfKLpJqKhqgPN\%2BislWFfSoiE1BLuKLg5oEZQ\%3D&reserved=0}{https://zoom.us/j/5503938635})
request remote session via email.

\textbf{Course Description:} This course introduces students to modern
regression techniques commonly used in analyzing public health data.
Specific topics include: (1) methods for modeling longitudinal and
multi-level data that account for within group correlation (e.g.,
mixed-effect models, generalized estimating equations); (2) modeling
non-linear relationships using splines and generalized additive models;
and (3) shrinkage methods and bias-variance tradeoffs.

This course draws motivating examples from environmental and social
epidemiology, health services research, clinical studies, etc. The
course provides a survey of advanced regression approaches with a focus
on data analysis and interpretation. Students will gain an understanding
of methods that will facilitate future independent and collaborative
research for modern research problems. Students will gain practical
experiences using the R language for statistical computing.

This is a required course for MSPH students in BIOS in the fall of their
second year. It is also an elective course for PhD BIOS students in
their second year interested in advanced modeling techniques.

\textbf{Pre-reqs:} BIOS 509 and BIOS 513 or equivalent. Students are
assumed to have background knowledge in linear algebra and multivariate
calculus. Experience with R (BIOS 545).

\textbf{Using this book:} This book consists of the lectures notes used
for this course in modern regression techniques. We will use this book
to review concepts in class. The book is split into separate modules
covering the particular topics in this course. In-class activities and
homework assignments are outlined for each module.

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-warning-color-frame, coltitle=black, opacityback=0, arc=.35mm, breakable, titlerule=0mm, colbacktitle=quarto-callout-warning-color!10!white, toptitle=1mm, title={Warning}, leftrule=.75mm, bottomtitle=1mm, bottomrule=.15mm, rightrule=.15mm, toprule=.15mm, left=2mm, colback=white, opacitybacktitle=0.6]

I am frequently editing notes in this book. I do not suggest reading
ahead in future modules as I may change material or assignments during
the semester.

\end{tcolorbox}

\bookmarksetup{startatroot}

\chapter*{Module 1A Linear Mixed
Models}\label{module-1a-linear-mixed-models}
\addcontentsline{toc}{chapter}{Module 1A Linear Mixed Models}

\markboth{Module 1A Linear Mixed Models}{Module 1A Linear Mixed Models}

\includegraphics{fig/mixedeffects.jpeg}

\textbf{Reading}

\begin{itemize}
\tightlist
\item
  Galecki \& Burzykowski (2013). Linear Mixed Effects Models using R.
\item
  Fox J (2008). Applied Regression Analysis and Generalized Linear
  Models 2nd ed.
\item
  Wood, S. \emph{Generalized Additive Models}. Ch 2.
\item
  \url{https://m-clark.github.io/mixed-models-with-R/random_intercepts.html}
\item
  \url{https://cran.r-project.org/web/packages/lme4/vignettes/lmer.pdf}
\end{itemize}

\subsection*{\texorpdfstring{\textbf{Overview}}{Overview}}\label{overview}
\addcontentsline{toc}{subsection}{\textbf{Overview}}

In this module, you'll learn how to model data with hierarchical or
correlated structures using \textbf{linear mixed models (LMMs).} These
models extend standard regression to handle repeated measures or nested
data structures, commonly found in longitudinal and multilevel public
health data.

\textbf{After completing this module, you will be able to:}

\begin{itemize}
\item
  Identify when LMMs are appropriate
\item
  Distinguish between fixed and random effects
\item
  Fit and interpret random intercept and random slope models in R
\item
  Understand concepts like shrinkage, intraclass correlation, and BLUPs
\item
  Hierarchical formulation of random effects models
\end{itemize}

\subsection*{Motivation and Examples}\label{motivation-and-examples}
\addcontentsline{toc}{subsection}{Motivation and Examples}

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-important-color-frame, coltitle=black, opacityback=0, arc=.35mm, breakable, titlerule=0mm, colbacktitle=quarto-callout-important-color!10!white, toptitle=1mm, title=\textcolor{quarto-callout-important-color}{\faExclamation}\hspace{0.5em}{Motivation:}, leftrule=.75mm, bottomtitle=1mm, bottomrule=.15mm, rightrule=.15mm, toprule=.15mm, left=2mm, colback=white, opacitybacktitle=0.6]

Correlated data structures arise when multiple observations are taken
from the same unit or group: Examples include:

\begin{itemize}
\tightlist
\item
  \textbf{Longitudinal data:} Repeated measures data on each subject

  \begin{itemize}
  \tightlist
  \item
    \(y_{it}\) denotes the measure at time \(t\) for unit \(i\).
  \end{itemize}
\item
  \textbf{Clustered or multilevel data:} Observations within nested
  group structures.

  \begin{itemize}
  \tightlist
  \item
    A collection of units from a population of similar units, e.g.,
    \(y_{ij}\) denotes measure from person \(i\) in demographic group
    \(j\).
  \end{itemize}
\end{itemize}

Ignoring this structure can lead to biased estimates and invalid
inference.

\end{tcolorbox}

\textbf{Motivating Example: The TLC Study:}

The Treatment of Lead-Exposed Children (TLC) was examined using a
placebo-controlled randomized study of succimer (a chelating agent) in
children with blood lead levels of 20-44 micrograms/dL. These data
consist of four repeated measurements of blood lead levels obtained at
baseline (or week 0) , week 1, week 4, and week 6 on 100 children who
were randomly assigned to chelation treament with succimer or placebo.

\begin{longtable}[]{@{}ll@{}}
\toprule\noalign{}
Variable & Description \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\texttt{id} & child identifier \\
\texttt{treatment} & succimer or placebo \\
\texttt{week} & measurement week \\
\texttt{lead} & lead level (outcome) \\
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tlcdata }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\StringTok{"data/tlc.RDS"}\NormalTok{)}
\FunctionTok{head}\NormalTok{(tlcdata)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
    id treatment week lead
1    1   placebo    0 30.8
101  1   placebo    1 26.9
201  1   placebo    4 25.8
301  1   placebo    6 23.8
2    2  succimer    0 26.5
102  2  succimer    1 14.8
\end{verbatim}

\includegraphics{Module_1A_LMM_files/figure-pdf/unnamed-chunk-4-1.pdf}

\subsection*{\texorpdfstring{Why Not OLS? \ul{\textbf{The wrong
approach}}}{Why Not OLS? The wrong approach}}\label{why-not-ols-the-wrong-approach}
\addcontentsline{toc}{subsection}{Why Not OLS? \ul{\textbf{The wrong
approach}}}

If we ignore clustering and fit the standard linear regression (OLS): \[
\begin{align*}
y_{ij}& = \beta_0 + \hat{\beta}_1 x_{ij} + \epsilon_{ij}\\
\epsilon_{ij} & \overset{iid}{\sim} N(0, \sigma^2)
\end{align*}
\] we assume that all observations are independent.

But repeated measurements from the same child are \textbf{not}
independent.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit.lm }\OtherTok{=} \FunctionTok{lm}\NormalTok{(lead }\SpecialCharTok{\textasciitilde{}}\NormalTok{ week, }\AttributeTok{data =}\NormalTok{ tlcdata)}
\FunctionTok{summary}\NormalTok{(fit.lm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Call:
lm(formula = lead ~ week, data = tlcdata)

Residuals:
    Min      1Q  Median      3Q     Max 
-19.775  -3.749   0.328   4.454  43.330 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  22.9760     0.6079  37.793   <2e-16 ***
week         -0.4010     0.1670  -2.401   0.0168 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.966 on 398 degrees of freedom
Multiple R-squared:  0.01428,   Adjusted R-squared:  0.0118 
F-statistic: 5.765 on 1 and 398 DF,  p-value: 0.01681
\end{verbatim}

\textbf{What assumptions of OLS are we violating?}

\begin{itemize}
\item
  \(\hat{\beta}_1\) is an unbiased and consistent estimator of
  \(\beta_1\).
\item
  Errors are not independent which leads to incorrect standard error
  estimates.
\item
  \(\sigma^2\) conflates within and between pig variability.
\item
  Limitations: You cannot forecast individual trajectories.
\end{itemize}

\section*{\texorpdfstring{\ul{The Better Approach: Introducing Linear
Mixed
Models}}{The Better Approach: Introducing Linear Mixed Models}}\label{the-better-approach-introducing-linear-mixed-models}
\addcontentsline{toc}{section}{\ul{The Better Approach: Introducing
Linear Mixed Models}}

\markright{\ul{The Better Approach: Introducing Linear Mixed Models}}

LMMs are extensions of regression in which intercepts and/or slopes are
allowed to vary across individual units. They were developed to deal
with correlated and/or nested data.

Taking our motivating example, we can assign a separate intercept for
each child:

\[
\begin{align*}
y_{ij} &= \beta_{0i} + \beta_1 x_{ij} + \epsilon_{ij}, \\
\epsilon_{ij} & \overset{iid}{\sim} N(0, \sigma^2)
\end{align*}
\]

\textbf{Interpretation:}

\begin{itemize}
\tightlist
\item
  \(\beta_{0i}\) is the \textcolor{red}{child-specific} weight at zero
  and \(\beta_1\) is the constant slope.
\item
  \(\sigma^2\) captures \textcolor{red}{within} child variability.
\item
  The mix of random and fixed effects = mixed modeling.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2024}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.4643}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Effect Type}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Definition}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Example}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Fixed & Population-average effects & Effect of week on lead \\
Random & Child-specific deviation & Child-specific intercept
\(\beta_{0i}\) \\
Random & Child-week deviation & Child-week error \(\epsilon_{ij}\)
\textbar{} \\
\end{longtable}

\subsection*{Random Intercept Model}\label{random-intercept-model}
\addcontentsline{toc}{subsection}{Random Intercept Model}

\includegraphics[width=6.25in,height=\textheight]{fig/randomint.png}

Consider the random intercept model with a vector of predictors
\(x_{ij}\):

\[
\begin{align*}
y_{ij} &=\mu + \theta_i + x_{ij}^T \beta + \epsilon_{ij}\\
\epsilon_{ij} & \overset{iid}{\sim} N(0, \sigma^2)\\
\theta_i & \overset{iid}{\sim} N(0, \tau^2) \\
\theta_i& \perp \epsilon_{ij}
\end{align*}
\]

\begin{itemize}
\item
  \(\mu\) = overall intercept (population mean when \(x_{ij}=0\)).
\item
  \(\theta_i\) = child specific difference from \(\mu\).
\item
  \(\beta_{0i} = \mu + \theta_i\) participant specific intercept or
  child specific average.
\item
  \(\beta\) = time coefficient that does not vary across participants.
\item
  \(\tau^2\) = between participant variability.
\item
  \(\sigma^2\) = residual variance or within group variability
  ``measurement error''.
\end{itemize}

\subsection*{Properties of the Random Intercept
Model}\label{properties-of-the-random-intercept-model}
\addcontentsline{toc}{subsection}{Properties of the Random Intercept
Model}

\emph{Use the expandable panels below to explore key statistical
properties and their derivations.}

\subsection*{Fitting a mixed effects model with a random intercept in
R:}\label{fitting-a-mixed-effects-model-with-a-random-intercept-in-r}
\addcontentsline{toc}{subsection}{Fitting a mixed effects model with a
random intercept in R:}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lmerTest)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Loading required package: lme4
\end{verbatim}

\begin{verbatim}
Loading required package: Matrix
\end{verbatim}

\begin{verbatim}

Attaching package: 'lmerTest'
\end{verbatim}

\begin{verbatim}
The following object is masked from 'package:lme4':

    lmer
\end{verbatim}

\begin{verbatim}
The following object is masked from 'package:stats':

    step
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit.randomeffects }\OtherTok{=} \FunctionTok{lmer}\NormalTok{(lead }\SpecialCharTok{\textasciitilde{}}\NormalTok{ week }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{id), }\AttributeTok{data =}\NormalTok{ tlcdata)}
\FunctionTok{summary}\NormalTok{(fit.randomeffects)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: lead ~ week + (1 | id)
   Data: tlcdata

REML criterion at convergence: 2695.1

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.6337 -0.3461  0.0601  0.4131  6.1167 

Random effects:
 Groups   Name        Variance Std.Dev.
 id       (Intercept) 29.63    5.444   
 Residual             33.98    5.829   
Number of obs: 400, groups:  id, 100

Fixed effects:
            Estimate Std. Error       df t value Pr(>|t|)    
(Intercept)  22.9760     0.7030 161.6442  32.683  < 2e-16 ***
week         -0.4010     0.1222 299.0000  -3.281  0.00116 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
     (Intr)
week -0.478
\end{verbatim}

\textbf{Model Interpretation:} The fixed effect captures the global or
average change in lead level for every one unit change in time, i.e.,
from week 1 to week 2, \(\hat{\beta}_1 = -0.410\), meaning that there is
an average 0.4 decrease in lead for every unit increase in week which
was found to be statistically significant \(p<0.01\).

Now the intercept 22.97 corresponds to the \ul{population-average lead
at week 0}.

The SE of the slope \(se(\hat{\beta_1}) = 0.122\) capturing uncertainty
associated with the estimate.

The random effect of child \(\beta_{0i}\) allows for child-specific
random intercepts, where the variance of the intercepts is 29.63.

\subsection*{Covariance Structure and Matrix
Form}\label{covariance-structure-and-matrix-form}
\addcontentsline{toc}{subsection}{Covariance Structure and Matrix Form}

A random intercept model is also known as a \textcolor{red}{two-level}
variance component model:

\begin{itemize}
\item
  \(\theta_i\) is a \textbf{random intercept} shared by all observations
  in group \(i\) and has a ``intercept-specific'' error \(\tau^2\).
\item
  \(\epsilon_{ij}\) is the \textbf{individual-level residual error}.
\end{itemize}

\subsubsection*{\texorpdfstring{Derivation:
\(\text{Cov}(y_{ij}, y_{ik})\) for
\(j \ne k\)}{Derivation: \textbackslash text\{Cov\}(y\_\{ij\}, y\_\{ik\}) for j \textbackslash ne k}}\label{derivation-textcovy_ij-y_ik-for-j-ne-k}
\addcontentsline{toc}{subsubsection}{Derivation:
\(\text{Cov}(y_{ij}, y_{ik})\) for \(j \ne k\)}

We now derive the \textbf{covariance} between two observations from the
same person \(i\). Let's expand both observations:

\[
\begin{aligned}
y_{ij} &= \mu + \theta_i + \beta x_{ij} + \epsilon_{ij} \\
y_{ik} &= \mu + \theta_i + \beta x_{ik} + \epsilon_{ik}
\end{aligned}
\]

Then,

\[
\text{Cov}(y_{ij}, y_{ik}) = \text{Cov}(\theta_i + \epsilon_{ij},\ \theta_i + \epsilon_{ik})
\]

Using bilinearity of covariance:

\[
= \text{Cov}(\theta_i, \theta_i) + \text{Cov}(\theta_i, \epsilon_{ik}) + \text{Cov}(\epsilon_{ij}, \theta_i) + \text{Cov}(\epsilon_{ij}, \epsilon_{ik})
\]

Now plug in the assumptions:

\begin{itemize}
\tightlist
\item
  \(\text{Var}(\theta_i) = \tau^2\)
\item
  \(\text{Cov}(\theta_i, \epsilon_{ij}) = 0\)
\item
  \(\text{Cov}(\epsilon_{ij}, \epsilon_{ik}) = 0\) for \(j \ne k\)
\end{itemize}

So:

\[
 \text{Cov}(y_{ij}, y_{ik}) = \tau^2\quad  ✅ 
\] Observations from the same group/cluster share the same random
intercept \(\theta_i\), which introduces positive correlation.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{\texorpdfstring{Derivation:
\(\text{Var}(y_{ij})\)}{Derivation: \textbackslash text\{Var\}(y\_\{ij\})}}\label{derivation-textvary_ij}
\addcontentsline{toc}{subsubsection}{Derivation: \(\text{Var}(y_{ij})\)}

Total variance = between-group variance + within-group variance. \[
\text{Var}(y_{ij}) = \text{Var}(\theta_i + \epsilon_{ij}) = \tau^2 + \sigma^2\quad ✅ 
\]

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Covariance Matrix}\label{covariance-matrix}
\addcontentsline{toc}{subsubsection}{Covariance Matrix}

Suppose we observe two individuals, each measured at three time points:

\begin{itemize}
\tightlist
\item
  Subject 1: \(y_{11}, y_{12}, y_{13}\)
\item
  Subject 2: \(y_{21}, y_{22}, y_{23}\)
\end{itemize}

The \textbf{marginal covariance matrix} \(\text{Cov}(\mathbf{y})\) for
the stacked vector:

\[
\mathbf{y} = 
\begin{bmatrix}
y_{11} \\
y_{12} \\
y_{13} \\
y_{21} \\
y_{22} \\
y_{23}
\end{bmatrix}
\]

is:

\[
\text{Cov}(\mathbf{y}) =
\begin{bmatrix}
\tau^2 + \sigma^2 & \tau^2 & \tau^2 & 0 & 0 & 0 \\
\tau^2 & \tau^2 + \sigma^2 & \tau^2 & 0 & 0 & 0 \\
\tau^2 & \tau^2 & \tau^2 + \sigma^2 & 0 & 0 & 0 \\
0 & 0 & 0 & \tau^2 + \sigma^2 & \tau^2 & \tau^2 \\
0 & 0 & 0 & \tau^2 & \tau^2 + \sigma^2 & \tau^2 \\
0 & 0 & 0 & \tau^2 & \tau^2 & \tau^2 + \sigma^2 \\
\end{bmatrix}
\]

\begin{itemize}
\tightlist
\item
  Within a subject, all pairs of outcomes have covariance \(\tau^2\).
\item
  Between subjects, outcomes are independent (covariance = 0).
\item
  Diagonal entries reflect total variance: \(\tau^2 + \sigma^2\).
\end{itemize}

This structure is known as \textbf{compound symmetry} within each
subject (constant pairwise correlation), and \textbf{block-diagonal}
across subjects.

\subsection*{Random Intercept Model in Matrix
Form}\label{random-intercept-model-in-matrix-form}
\addcontentsline{toc}{subsection}{Random Intercept Model in Matrix Form}

Consider the mixed model with random intercepts for \(n\) groups and
define \(N = \sum_{i=1}^n r_i\).

\[
\mathbf{y} = \mathbf{Z} \mathbf{\theta} + \mathbf{X}\mathbf{\beta} + \mathbf{\epsilon}
\]

where

\begin{itemize}
\item
  \(\mathbf{y} = N \times 1\) vector of response
\item
  \(\mathbf{Z} = N \times n\) design matrix of indicator variables for
  each group.
\item
  \(\mathbf{\theta} = n \times 1\) vector of random intercepts.
\item
  \(\mathbf{X} = N\times p\) design matrix of fixed effects (including
  overall intercept).
\item
  \(\mathbf{\beta} = p\times 1\) vector of fixed effects.
\item
  \(\mathbf{\epsilon} = N \times 1\) vector of residual error. :::
\end{itemize}

\subsection*{Intraclass Correlation}\label{intraclass-correlation}
\addcontentsline{toc}{subsection}{Intraclass Correlation}

\begin{itemize}
\item
  Note that the within-group covariance is:
  \(Cov(y_{ij}, y_{ij'}) = \tau^2\) .
\item
  So the correlation between observations within within the same group
  is
\end{itemize}

\[
\rho = Corr(y_{ij}, y_{ij'}) = \frac{\tau^2}{\tau^2 + \sigma^2} \text{ for all }j \neq j'. 
\]

\begin{itemize}
\tightlist
\item
  The value \(\rho\) is often called the
  \textcolor{red}{intraclass correlation}. It measures the degree of
  similarity among same-group observations
  \textcolor{blue}{compared to the residual error} \(\sigma^2\).
\item
  Describes how strongly units in the same group resemble eachother.
\item
  \(\rho \rightarrow 0\) when \(\tau^2 \rightarrow 0\) (i.e.~same
  intercept)
\item
  \(\rho \rightarrow 0\) when \(\sigma^2 \rightarrow \infty\) (i.e.,
  growing measurement error).
\item
  \(\rho \rightarrow 1\) when \(\tau^2 \rightarrow \infty\) (i.e., large
  separation in intercepts).
\item
  \(\rho \rightarrow 1\) when \(\sigma^2 \rightarrow 0\) (i.e., zero
  measurement error).
\item
  The above ICC has an exchangeable structure because the correlation is
  constant between \emph{any pair} of within-group observations.
\end{itemize}

\subsection*{Simulation Varying Between Subject
Variability}\label{simulation-varying-between-subject-variability}
\addcontentsline{toc}{subsection}{Simulation Varying Between Subject
Variability}

\includegraphics{Module_1A_LMM_files/figure-pdf/unnamed-chunk-7-1.pdf}

\subsection*{Simulation Varying Sources of
Error}\label{simulation-varying-sources-of-error}
\addcontentsline{toc}{subsection}{Simulation Varying Sources of Error}

\includegraphics{Module_1A_LMM_files/figure-pdf/unnamed-chunk-8-1.pdf}

\section*{\texorpdfstring{\textcolor{purple}{Summary}}{}}\label{section}
\addcontentsline{toc}{section}{\textcolor{purple}{Summary}}

\markright{\textcolor{purple}{Summary}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.0816}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.9184}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Section}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Description}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{What is the model?} & - In the random intercept model:
\(y_{ij} = \mu + \theta_i + x_{ij}'\beta + \epsilon_{ij} = \mathbf{Z} \theta + \mathbf{X} \beta + \mathbf{e}\)
- \(\mu\) is the population mean (overall average). - \(\theta_i\) are
individual differences in intercepts from \(\mu\). \\
\textbf{Model Assumptions} & - \(\epsilon_{ij} \sim N(0, \sigma^2)\) -
\(Var(\epsilon) = \sigma^2\) (within-subject variance) -
\(\theta_i \sim N(0, \tau^2)\) - \(\theta_i \perp \epsilon_{ij}\) -
\(\rho = \frac{\tau^2}{\tau^2 + \sigma^2}\) (ICC). \\
\textbf{Interpretation} & - \(\theta_i\) = individual deviation from
\(\mu\). - \(\beta_1\) = global effect of \(X\). - Total variance =
\(\sigma^2 + \tau^2\). - ICC: degree of similarity among same-group
observations \textbf{relative} to residual error. \\
\end{longtable}

\bookmarksetup{startatroot}

\chapter*{Module 1B Linear Mixed
Models}\label{module-1b-linear-mixed-models}
\addcontentsline{toc}{chapter}{Module 1B Linear Mixed Models}

\markboth{Module 1B Linear Mixed Models}{Module 1B Linear Mixed Models}

\subsection*{The Joint Density}\label{the-joint-density}
\addcontentsline{toc}{subsection}{The Joint Density}

\begin{itemize}
\tightlist
\item
  To simplify the derivation first consider a random effects model
  \emph{without} fixed effects:
\end{itemize}

\[
y_{ij} = \theta_i + \epsilon_{ij}, \quad \theta_i \overset{iid}{\sim} N(0, \tau^2), \quad \epsilon_{ij} \overset{iid}{\sim} N(0, \sigma^2)
\] - The join density of the data \emph{and} random effects is given by:

\[
\prod_{i,j} f(y_{ij}, \theta_i) = \prod_{i,j} f(y_{ij}|\theta_i) \cdot \prod_i g(\theta_i)
\]

By the chain rule of probability:

\[
f(y_{ij}, \theta_i) = f(y_{ij} \mid \theta_i) \, g(\theta_i),
\]

so we can write:

\[
f(\{y_{ij}\}, \{\theta_i\}) 
= \prod_{i=1}^m \left[ \prod_{j=1}^{n_i} f(y_{ij} \mid \theta_i) \right] g(\theta_i).
\]

The conditional density of \(y_{ij}\) given \(\theta_i\) is:

\[
y_{ij} \mid \theta_i \sim N(\theta_i, \sigma^2),
\]

so

\[
f(y_{ij} \mid \theta_i) = \frac{1}{\sqrt{2 \pi \sigma^2}} 
\exp \left( -\frac{(y_{ij} - \theta_i)^2}{2 \sigma^2} \right).
\]

The density of \(\theta_i\) is:

\[
g(\theta_i) = \frac{1}{\sqrt{2 \pi \tau^2}}
\exp \left( - \frac{\theta_i^2}{2 \tau^2} \right).
\]

Putting these together, the joint density of the data and random effects
is given by:

\[
\prod_{ij} f(y_{ij}, \theta_i) = \prod_{i,j} f(y_{ij}|\theta_i) \cdot \prod_i g(\theta_i)
\] Going through the derivation: \[
f(\{y_{ij}\}, \{\theta_i\}) 
= \prod_{i=1}^m \left[ \left( \prod_{j=1}^{n_i} 
\frac{1}{\sqrt{2 \pi \sigma^2}} 
\exp \left( -\frac{(y_{ij} - \theta_i)^2}{2 \sigma^2} \right) \right) 
\frac{1}{\sqrt{2 \pi \tau^2}} 
\exp \left( - \frac{\theta_i^2}{2 \tau^2} \right) \right].
\]

\section*{\texorpdfstring{Best Linear Unbiased Prediction (BLUP) of
\(\theta_i\)}{Best Linear Unbiased Prediction (BLUP) of \textbackslash theta\_i}}\label{best-linear-unbiased-prediction-blup-of-theta_i}
\addcontentsline{toc}{section}{Best Linear Unbiased Prediction (BLUP) of
\(\theta_i\)}

\markright{Best Linear Unbiased Prediction (BLUP) of \(\theta_i\)}

We aim to find the \textbf{predictor} \(\hat{\theta}_i\) that is linear
in the data, unbiased for \(\theta_i\), and minimizes mean squared error
(the BLUP).

Taking logs (and dropping constants) gives the log-likelihood: \[
\ell(\theta_i) 
= -\frac{1}{2\sigma^2} \sum_{j=1}^{n_i} (y_{ij} - \theta_i)^2 
- \frac{\theta_i^2}{2 \tau^2}.
\]

\textbf{Step 1:} Expand the Quadratic Term Expand the sum of squares: \[
\sum_{j=1}^{n_i} (y_{ij} - \theta_i)^2
= \sum_{j=1}^{n_i} y_{ij}^2 - 2 \theta_i \sum_{j=1}^{n_i} y_{ij} + n_i \theta_i^2.
\]

So: \[
\ell(\theta_i) 
= -\frac{1}{2\sigma^2} 
\left( \sum_{j=1}^{n_i} y_{ij}^2 - 2 \theta_i \sum_{j=1}^{n_i} y_{ij} + n_i \theta_i^2 \right)
- \frac{\theta_i^2}{2 \tau^2}.
\]

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\textbf{Step 2:} Differentiate with Respect to \(\theta_i\) The
derivative is: \[
\frac{\partial \ell}{\partial \theta_i}
= \frac{\sum_{j=1}^{n_i} y_{ij} - n_i \theta_i}{\sigma^2} - \frac{\theta_i}{\tau^2}.
\]

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\textbf{Step 3:} Solve for \(\hat{\theta}_i\) Set the derivative to
zero:

\[
\frac{\sum_{j=1}^{n_i} y_{ij} - n_i \hat{\theta}_i}{\sigma^2} - \frac{\hat{\theta}_i}{\tau^2} = 0.
\]

Multiply by \(\sigma^2\): \[
\sum_{j=1}^{n_i} y_{ij} - n_i \hat{\theta}_i - \frac{\sigma^2}{\tau^2} \hat{\theta}_i = 0.
\]

Rearrange: \[
\sum_{j=1}^{n_i} y_{ij} = \hat{\theta}_i \left( n_i + \frac{\sigma^2}{\tau^2} \right).
\]

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-note-color-frame, breakable, left=2mm, colback=white, bottomrule=.15mm, arc=.35mm, opacityback=0, rightrule=.15mm, toprule=.15mm, leftrule=.75mm]

Thus: \[
\hat{\theta}_i = \frac{\sum_{j=1}^{n_i} y_{ij}}{n_i + \sigma^2 / \tau^2} = \frac{n_i}{n_i + \sigma^2 / \tau^2} \bar{y}_i
\]

where \(\bar{y}_i = \frac{1}{n_i} \sum_{j=1}^{n_i} y_{ij}\).

We can express the BLUP as: \[
\hat{\theta}_i = B_i \, \bar{y}_i,
\]

where the \textbf{shrinkage factor} is: \[
B_i = \frac{n_i}{n_i + \sigma^2/\tau^2}.
\]

\end{tcolorbox}

\textbf{Note that:}

\begin{itemize}
\tightlist
\item
  When \(\tau^2 \to 0\) (no between-group variation),\\
  \(B_i \to 0\) and all random intercepts are shrunk to 0 (the global
  mean).
\item
  When \(\tau^2 \to \infty\) (very large between-group variation),\\
  \(B_i \to 1\) and there is no shrinkage:
  \(\hat{\theta}_i = \bar{y}_i\).
\item
  When \(n_i\) is small, \(B_i\) is small and there is \textbf{more
  shrinkage}, while large \(n_i\) makes \(B_i\) close to 1 (less
  shrinkage).
\end{itemize}

\subsection*{Hierarchical Formulation}\label{hierarchical-formulation}
\addcontentsline{toc}{subsection}{Hierarchical Formulation}

In a random intercept model, we assume group-specific effects
\(\theta_i\) vary around a common mean \(\mu\):

\[
  y_{ij} = \mu + \theta_i + \epsilon_{ij}, 
  \quad \theta_i \sim N(0, \tau^2), 
  \quad \epsilon_{ij} \sim N(0, \sigma^2),
\]

where:

\begin{itemize}
\tightlist
\item
  \(i = 1, \ldots, m\) indexes groups,
\item
  \(j = 1, \ldots, n_i\) indexes observations within group \(i\),
\item
  \(\tau^2\) is the between-group variance,
\item
  \(\sigma^2\) is the within-group variance.
\end{itemize}

Equivalently, this can be viewed as a \textbf{two-level hierarchical
model}:

\begin{itemize}
\tightlist
\item
  \textbf{Level 1 (within-group model):}
  \(y_{ij} \mid \theta_i \sim N(\mu + \theta_i, \sigma^2)\).
\item
  \textbf{Level 2 (random effect model):}
  \(\theta_i \sim N(0, \tau^2)\).
\end{itemize}

\subsection*{Borrowing of Information}\label{borrowing-of-information}
\addcontentsline{toc}{subsection}{Borrowing of Information}

The estimated random intercept \(\hat{\theta}_i\) can be expressed as a
\textbf{weighted combination} of the overall mean \(\mu\) and the
group-specific mean \(\bar{y}_i\):

\[
\hat{\theta}_i 
= \frac{(1/\tau^2) \mu + (n_i / \sigma^2) \bar{y}_i}{1/\tau^2 + n_i / \sigma^2}.
\]

This shows that:

\begin{itemize}
\tightlist
\item
  Groups with \textbf{small} \(n_i\) (few observations) are pulled more
  strongly toward the overall mean \(\mu\),
\item
  Groups with \textbf{large} \(n_i\) rely more on their own mean
  \(\bar{y}_i\).
\end{itemize}

We can also express \(\hat{\theta}_i\) in terms of the
\textbf{intraclass correlation}: \[
\rho = \frac{\tau^2}{\tau^2 + \sigma^2},
\] leading to:

\[
\hat{\theta}_i 
= \frac{\rho^{-1} \mu + n_i (1-\rho)^{-1} \bar{y}_i}{\rho^{-1} + n_i (1-\rho)^{-1}}.
\]

\textbf{Note that:}

\begin{itemize}
\tightlist
\item
  As \(\tau^2 \to 0\), all \(\hat{\theta}_i \to \mu\) (complete
  shrinkage toward the common mean).
\item
  As \(\tau^2 \to \infty\), \(\hat{\theta}_i \to \bar{y}_i\) (no
  shrinkage, group means are used as-is).
\item
  The amount of shrinkage depends jointly on \(\tau^2\), \(\sigma^2\),
  and \(n_i\).
\end{itemize}

\subsection*{Parameter Estimation}\label{parameter-estimation}
\addcontentsline{toc}{subsection}{Parameter Estimation}

\textbf{Theorem}

Let \(Y=X\beta + \epsilon\) and \(E(Y) = X\beta\) and
\(cov(Y) = \sigma^2 V\) where \(X\) is full rank and \(V\) is a known
positive definite matrix. The best linear unbiased estimator (BLUE) of
\(\beta\) is given by:

\[
\hat{\beta}_{GLS} = (X'V^{-1}X)^{-1} X'V^{-1}y
\]

The value of \(\beta\) that maximizes the likelihood function is the GLS
estimate, i.e., \(\hat{\beta}_{MLE} = \hat{\beta}_{GLS}\)

To estimate the fixed effects \(\boldsymbol{\beta}\) and the variance
components \((\sigma^2, \tau^2)\), we use the \textbf{marginal model}:

\[
\mathbf{y} \sim N(\mathbf{X}\boldsymbol{\beta}, \mathbf{V}),
\] where

\[
\mathbf{V} = \mathbf{Z} G \mathbf{Z}^T + R
\] captures both the between-group (\(G = \tau^2 I\)) and within-group
(\(R = \sigma^2 I\)) variability.

In ordinary linear regression \(Y = X \beta + \epsilon\) with
\(\epsilon \sim N(0, \sigma^2 I)\), the OLS estimator

\[
\hat{\beta}_{OLS} = (X^T X)^{-1} X^T y
\]

is optimal because the errors are uncorrelated and have constant
variance.

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-note-color-frame, breakable, left=2mm, colback=white, bottomrule=.15mm, arc=.35mm, opacityback=0, rightrule=.15mm, toprule=.15mm, leftrule=.75mm]

In LMMs, the data are \textbf{correlated}: \[
\text{Cov}(\mathbf{y}) = \mathbf{V} \neq \sigma^2 I.
\] The optimal estimator becomes the \textbf{generalized least squares
(GLS) estimator}:

\[
\hat{\boldsymbol{\beta}} = (\mathbf{X}^T \mathbf{V}^{-1} \mathbf{X})^{-1} \mathbf{X}^T \mathbf{V}^{-1} \mathbf{y}.
\]

\end{tcolorbox}

\subparagraph*{Variance Components: MLE
vs.~REML}\label{variance-components-mle-vs.-reml}
\addcontentsline{toc}{subparagraph}{Variance Components: MLE vs.~REML}

\begin{itemize}
\item
  The MLS estimate of the variance component \(\hat{\sigma}^2_{MLE}\) is
  biased!! Why because if we take the expectation (e.g., in the
  univariate case)
  \(E(\hat{\sigma}^2_{MLE}) = \frac{n-1}{n} \sigma^2 \neq \sigma^2\).
\item
  It is important to note when we calculate the MLE, we use \(\hat{y}\).
  If we used \(\mu\) instead of \(\hat{y}\) , it is not longer biased.
  The intuition behind this is we used some information on estimating
  the mean and we need to account for this in estimating the spread
  around the mean.
\item
  The idea behind REML is we want to remove information about the mean
  from the likelihood and maximize what remains to get an estimate of
  the REML variance \(\hat{V}_{REML}\) that does not depend on the mean.
\item
  The REML estimator is equivalent to the MLE estimated based on
  \ul{transformed} outcomes \(Y^* = AY\) such that the distribution of
  \(Y^*\) does not depend on \(\beta\).
\item
  The MLE estimates of the variance components \((\sigma^2, \tau^2)\)
  are \textbf{biased}, much like the naive variance estimate in OLS: \[
  \hat{\sigma}^2_{MLE} = \frac{1}{n} \sum_{i=1}^n (x_i - \bar{x})^2.
  \]
\item
  \textbf{Restricted Maximum Likelihood (REML)} corrects this bias by
  accounting for the degrees of freedom used to estimate
  \(\boldsymbol{\beta}\): \[
  \hat{\sigma}^2_{REML} = \frac{1}{n-1} \sum_{i=1}^n (x_i - \bar{x})^2.
  \]
\item
  REML is preferred in most applications and is the \textbf{default in
  \texttt{lme4::lmer()}} in R.
\end{itemize}

Important: variance is now included in the estimator. This is different
from \(\hat{\beta}_{MLE} = (X'X)^{-1} X'y\) where the variance does not
appear. This means when outcomes are correlated the variance matters in
estimating \(\beta\). --\textgreater{}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(nlme) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Attaching package: 'nlme'
\end{verbatim}

\begin{verbatim}
The following object is masked from 'package:dplyr':

    collapse
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(gridExtra) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Attaching package: 'gridExtra'
\end{verbatim}

\begin{verbatim}
The following object is masked from 'package:dplyr':

    combine
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lme4)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Loading required package: Matrix
\end{verbatim}

\begin{verbatim}

Attaching package: 'lme4'
\end{verbatim}

\begin{verbatim}
The following object is masked from 'package:nlme':

    lmList
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tlcdata }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\StringTok{"data/tlc.RDS"}\NormalTok{)}


\NormalTok{succimer\_data\_only }\OtherTok{\textless{}{-}}\NormalTok{ tlcdata }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(treatment }\SpecialCharTok{==} \StringTok{"succimer"}\NormalTok{)}

\NormalTok{tlc.gls }\OtherTok{\textless{}{-}} \FunctionTok{gls}\NormalTok{(lead }\SpecialCharTok{\textasciitilde{}} \FunctionTok{relevel}\NormalTok{(}\FunctionTok{as.factor}\NormalTok{(week), }\DecValTok{4}\NormalTok{),  }\AttributeTok{data =}\NormalTok{ succimer\_data\_only, }\CommentTok{\#only running for treatment group }
               
\AttributeTok{correlation =} \FunctionTok{corSymm}\NormalTok{(}\AttributeTok{form =} \SpecialCharTok{\textasciitilde{}}\DecValTok{1}\SpecialCharTok{|}\NormalTok{id), }\CommentTok{\#within correlation by individual }
\AttributeTok{weights =} \FunctionTok{varIdent}\NormalTok{(}\AttributeTok{form =} \SpecialCharTok{\textasciitilde{}}\DecValTok{1}\SpecialCharTok{|}\NormalTok{week)) }\CommentTok{\#weights are determined across time }

\FunctionTok{summary}\NormalTok{(tlc.gls) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Generalized least squares fit by REML
  Model: lead ~ relevel(as.factor(week), 4) 
  Data: succimer_data_only 
       AIC      BIC    logLik
  1308.337 1354.231 -640.1687

Correlation Structure: General
 Formula: ~1 | id 
 Parameter estimate(s):
 Correlation: 
  1     2     3    
2 0.401            
3 0.384 0.731      
4 0.495 0.507 0.455
Variance function:
 Structure: Different standard deviations per stratum
 Formula: ~1 | week 
 Parameter estimates:
       0        1        4        6 
1.000000 1.528082 1.563878 1.841541 

Coefficients:
                              Value Std.Error   t-value p-value
(Intercept)                  20.762  1.307627 15.877618   0e+00
relevel(as.factor(week), 4)0  5.778  1.137826  5.078104   0e+00
relevel(as.factor(week), 4)1 -7.240  1.203585 -6.015361   0e+00
relevel(as.factor(week), 4)4 -5.248  1.273641 -4.120470   1e-04

 Correlation: 
                             (Intr) r(.(),4)0 r(.(),4)1
relevel(as.factor(week), 4)0 -0.840                    
relevel(as.factor(week), 4)1 -0.629  0.614             
relevel(as.factor(week), 4)4 -0.630  0.616     0.790   

Standardized residuals:
       Min         Q1        Med         Q3        Max 
-1.8020146 -0.8258012 -0.1227684  0.5184783  4.6654246 

Residual standard error: 5.020968 
Degrees of freedom: 200 total; 196 residual
\end{verbatim}

Suppose we want the covariance matrix?

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Get covariance matrix for individual i. }

\FunctionTok{getVarCov}\NormalTok{(tlc.gls, }\AttributeTok{individual =} \DecValTok{3}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Marginal variance covariance matrix
       [,1]   [,2]   [,3]   [,4]
[1,] 25.210 15.466 15.138 22.986
[2,] 15.466 58.867 44.029 35.965
[3,] 15.138 44.029 61.657 33.022
[4,] 22.986 35.965 33.022 85.494
  Standard Deviations: 5.021 7.6725 7.8522 9.2463 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Get correlation matrix for individual i. }

\FunctionTok{cov2cor}\NormalTok{(}\FunctionTok{getVarCov}\NormalTok{(tlc.gls, }\AttributeTok{individual =} \DecValTok{3}\NormalTok{)) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Marginal variance covariance matrix
        [,1]    [,2]    [,3]    [,4]
[1,] 1.00000 0.40146 0.38397 0.49512
[2,] 0.40146 1.00000 0.73082 0.50696
[3,] 0.38397 0.73082 1.00000 0.45482
[4,] 0.49512 0.50696 0.45482 1.00000
  Standard Deviations: 1 1 1 1 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#To get the variance weights }

\FunctionTok{summary}\NormalTok{(tlc.gls}\SpecialCharTok{$}\NormalTok{modelStruct}\SpecialCharTok{$}\NormalTok{varStruct) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Variance function:
 Structure: Different standard deviations per stratum
 Formula: ~1 | week 
 Parameter estimates:
       0        1        4        6 
1.000000 1.528082 1.563878 1.841541 
\end{verbatim}

\section*{\texorpdfstring{\textcolor{purple}{Summary}}{}}\label{section-1}
\addcontentsline{toc}{section}{\textcolor{purple}{Summary}}

\markright{\textcolor{purple}{Summary}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.0872}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.9128}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Section}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Description}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{What is the model?} & Random intercept model with hierarchical
structure: \(y_{ij} = \mu + \theta_i + \epsilon_{ij}\), where
\(\theta_i \sim N(0, \tau^2)\) and
\(\epsilon_{ij} \sim N(0, \sigma^2)\). The data's covariance is
\(\mathbf{V} = \mathbf{Z}G\mathbf{Z}^T + R\), with \(G = \tau^2 I\)
(between-group) and \(R = \sigma^2 I\) (within-group). \\
\textbf{BLUP of} \(\theta_i\) & Best Linear Unbiased Prediction:
\(\hat{\theta}_i = B_i \bar{y}_i\) with shrinkage factor
\(B_i = \frac{n_i}{n_i + \sigma^2/\tau^2}\). Small \(n_i\) or small
\(\tau^2\) leads to \textbf{more shrinkage} toward \(\mu\), while large
\(n_i\) or large \(\tau^2\) reduces shrinkage. \\
\textbf{Borrowing of Information} &
\(\hat{\theta}_i = \frac{(1/\tau^2)\mu + (n_i/\sigma^2)\bar{y}_i}{1/\tau^2 + n_i/\sigma^2}\).
Groups with fewer observations are pulled toward the overall mean
\(\mu\), while larger groups rely more on their own group mean
\(\bar{y}_i\). \\
\textbf{Parameter Estimation} & Fixed effects \(\beta\) estimated using
GLS: \(\hat{\beta}_{GLS} = (X^T V^{-1} X)^{-1} X^T V^{-1} y\). Variance
components \((\sigma^2, \tau^2)\) estimated by MLE or REML. \\
\textbf{Variance Components} & MLE of variance components is biased
(like naive OLS variance). \textbf{REML} adjusts for the loss of degrees
of freedom when estimating \(\beta\) and provides unbiased estimates of
\(\sigma^2\) and \(\tau^2\). \\
\textbf{Interpretation} & Total variance = \(\sigma^2 + \tau^2\).
Intraclass correlation: \(\rho = \frac{\tau^2}{\tau^2 + \sigma^2}\). The
magnitude of \(\rho\) reflects within-group similarity relative to
residual variation. \\
\end{longtable}

\bookmarksetup{startatroot}

\chapter*{Module 1C Random Intercepts and
Slopes}\label{module-1c-random-intercepts-and-slopes}
\addcontentsline{toc}{chapter}{Module 1C Random Intercepts and Slopes}

\markboth{Module 1C Random Intercepts and Slopes}{Module 1C Random
Intercepts and Slopes}

From Random Intercepts to Random Slopes:
\includegraphics[width=5.3125in,height=\textheight]{fig/mixedeffects.jpeg}

\begin{itemize}
\tightlist
\item
  Consider the mixed effects model with a vector of predictors
  \(x_{ij}\):
\end{itemize}

\[
y_{ij} = (\beta_0 + \theta_{0i}) + (\beta_1 + \theta_{1i}) x_{ij} + \epsilon_{ij}, \quad \epsilon_{ij} \overset{iid}{\sim} N(0, \sigma^2)
\]

\begin{itemize}
\item
  \$\beta\_\{0i\} = \beta\_0 + \theta{_0i} \$ participant specific
  intercept or child specific average.
\item
  \(\beta_{1i} = \beta_1 + \theta_{1i}\) participant specific rate of
  change or slope.
\item
  \(\beta_0, \beta_1\) the intercept and slope that does not vary across
  participants.
\item
  \(\sigma^2\) within subject variability ie measurement error.
\end{itemize}

\subsection*{Random Effects Covariane
Structure}\label{random-effects-covariane-structure}
\addcontentsline{toc}{subsection}{Random Effects Covariane Structure}

The random effects are modeled jointly as:

\[
\begin{pmatrix}\theta_{0i} \\ \theta_{1i} \end{pmatrix} \sim N \left( \begin{pmatrix} 0 \\ 0 \end{pmatrix}, \begin{pmatrix} \tau^2_0 & \rho \tau_0 \tau_1 \\ 
\rho \tau_0 \tau_1 & \tau_1^2 \end{pmatrix} \right)
\] where:

\begin{itemize}
\tightlist
\item
  \(\tau_0^2\) is the variance of random intercepts,
\item
  \(\tau_1^2\) is the variance of random slopes,
\item
  \(\rho\) is the correlation between intercepts and slopes.
\end{itemize}

This structure allows us to model not just variation in starting points
(intercepts) and rates of change (slopes), but also how they are related
(e.g., do groups with higher baselines tend to change faster?).

\subsubsection*{Fitting the Random Intercept and Slope model in
R}\label{fitting-the-random-intercept-and-slope-model-in-r}
\addcontentsline{toc}{subsubsection}{Fitting the Random Intercept and
Slope model in R}

Lets fit the model using the tlc data:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(gridExtra) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Attaching package: 'gridExtra'
\end{verbatim}

\begin{verbatim}
The following object is masked from 'package:dplyr':

    combine
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lme4)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Loading required package: Matrix
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tlcdata }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\StringTok{"data/tlc.RDS"}\NormalTok{)}

\NormalTok{placebo\_data }\OtherTok{=}\NormalTok{ tlcdata }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(treatment }\SpecialCharTok{==} \StringTok{"placebo"}\NormalTok{)}
\NormalTok{fit\_random }\OtherTok{\textless{}{-}} \FunctionTok{lmer}\NormalTok{(lead }\SpecialCharTok{\textasciitilde{}}\NormalTok{ week }\SpecialCharTok{+}\NormalTok{ (week}\SpecialCharTok{|}\NormalTok{id), }\AttributeTok{data =}\NormalTok{ placebo\_data)}
\FunctionTok{summary}\NormalTok{(fit\_random)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Linear mixed model fit by REML ['lmerMod']
Formula: lead ~ week + (week | id)
   Data: placebo_data

REML criterion at convergence: 1053.3

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-2.20808 -0.49837 -0.02268  0.47100  2.30541 

Random effects:
 Groups   Name        Variance Std.Dev. Corr
 id       (Intercept) 23.3113  4.8282       
          week         0.1581  0.3976   0.02
 Residual              4.5016  2.1217       
Number of obs: 200, groups:  id, 50

Fixed effects:
            Estimate Std. Error t value
(Intercept) 25.68536    0.72018  35.665
week        -0.37213    0.08437  -4.411

Correlation of Fixed Effects:
     (Intr)
week -0.164
\end{verbatim}

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-note-color-frame, breakable, left=2mm, colback=white, bottomrule=.15mm, arc=.35mm, opacityback=0, rightrule=.15mm, toprule=.15mm, leftrule=.75mm]

\textbf{Interpretation:}

\begin{itemize}
\tightlist
\item
  Child-specific intercept:
  \((\beta_0 + \theta_{0i}) \sim N(25.68, 23.31)\).
\item
  Child-specific slope:
  \((\beta_1 + \theta_{1i}) \sim N(-0.372, 0.158)\).
\item
  The correlation \(rho\) between \((\beta_{0i} \beta_{1i}) = 0.02\).
\item
  The 95\% CIs of the subject-specific slopes does not include zero in
  the distribution. This we reject the null that a child's lead levels
  do not increase with time.
\end{itemize}

\end{tcolorbox}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{ggplot}\NormalTok{(placebo\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ week, }\AttributeTok{y =}\NormalTok{ lead, }\AttributeTok{group =}\NormalTok{ id)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =} \FunctionTok{predict}\NormalTok{(fit\_random)), }\AttributeTok{color =} \StringTok{"blue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Random Intercepts and Slopes by Individual"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Week"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Lead Level"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Module_1C_LMM_files/figure-pdf/unnamed-chunk-3-1.pdf}

\section*{Comparing Models}\label{comparing-models}
\addcontentsline{toc}{section}{Comparing Models}

\markright{Comparing Models}

\begin{itemize}
\item
  Is the random intercept plus slope preferred over random intercept
  only?
\item
  AIC: Akaike's Information Criterion.
\item
  AIC is often used in model selection. It is a popular approach to
  choosing which variables should be in the model. \[
  AIC = -2l(\mathbf{\theta}) + 2p
  \] where \(l(\mathbf{\theta})\) is the log-likelihood for all
  parameters \(\mathbf{\theta}\) and \(p\) is the number of parameters.
\item
  The MLE estimate of the variances is biased! (Similar to the estimate
  in simple linear regression).
\item
  The general rule of thumb is a differenc of 2+ is substantially
  better. A lower AIC is better.
\item
  The AIC uses the maximum likelihood so use \(REML=FALSE\) to set the
  parameter estimation to MLE.
\end{itemize}

\bookmarksetup{startatroot}

\chapter*{Module 1 Cheat Sheet}\label{module-1-cheat-sheet}
\addcontentsline{toc}{chapter}{Module 1 Cheat Sheet}

\markboth{Module 1 Cheat Sheet}{Module 1 Cheat Sheet}

\section*{\texorpdfstring{\textcolor{purple}{Overview}}{}}\label{section-2}
\addcontentsline{toc}{section}{\textcolor{purple}{Overview}}

\markright{\textcolor{purple}{Overview}}

\begin{itemize}
\tightlist
\item
  Linear Mixed Models used for correlated or nested data, i.e.,
  longitudinal or clustered data.
\item
  Ignoring correlation leads to biased estimates of standard errors.
\item
  LMMs refer to the combination of both fixed and random effects:

  \begin{itemize}
  \tightlist
  \item
    Fixed effects remain constant across all units
  \item
    Random effects are allowed to vary across units.
  \end{itemize}
\end{itemize}

\section*{\texorpdfstring{\textcolor{purple}{1. Random Intercept Model (Module 1A)}}{}}\label{section-3}
\addcontentsline{toc}{section}{\textcolor{purple}{1. Random Intercept Model (Module 1A)}}

\markright{\textcolor{purple}{1. Random Intercept Model (Module 1A)}}

\textbf{Model:}

\[
y_{ij} = \mu + \theta_i + x_{ij}'\beta + \epsilon_{ij}
= \underbrace{\mathbf{Z}\theta + \mathbf{X}\beta + \mathbf{e}}_{\text{matrix form}},
\]

where:

\begin{itemize}
\tightlist
\item
  \(\mu\): population mean (overall average),
\item
  \(\theta_i\): random intercept for subject \(i\),
  \(\theta_i \sim N(0, \tau^2)\),
\item
  \(\epsilon_{ij} \sim N(0, \sigma^2)\): residual error.
\end{itemize}

\textbf{Model Assumptions:}

\begin{itemize}
\tightlist
\item
  \(\epsilon_{ij} \sim N(0, \sigma^2)\),
\item
  \(\theta_i \sim N(0, \tau^2)\),
\item
  \(Var(\theta_i) = \tau^2\): the between-subject variance (variation in
  intercepts across groups/subjects),
\item
  \(Var(\epsilon_{ij}) = \sigma^2\): the within-subject variance
  (residual variation within a group/subject).
\item
  \(\theta_i \perp \epsilon_{ij}\),
\item
  Intraclass correlation:h ow much of the total variance comes from
  between-subject differences \(\tau^2\) compared to the total variance
  \(\tau^2 + \sigma^2\).
\end{itemize}

\[
  \rho = \frac{\tau^2}{\tau^2 + \sigma^2}.
\]

\textbf{Interpretation:}\\
- \(\theta_i\): deviation of group \(i\) from the global mean \(\mu\),\\
- \(\beta\): global (fixed) effect of predictors,\\
- Total variance: \(\sigma^2 + \tau^2\),\\
- \(\rho\): similarity among observations within the same group.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{\texorpdfstring{\textcolor{purple}{2. Linear Mixed Models (Module 1B)}}{}}\label{section-4}
\addcontentsline{toc}{section}{\textcolor{purple}{2. Linear Mixed Models (Module 1B)}}

\markright{\textcolor{purple}{2. Linear Mixed Models (Module 1B)}}

\textbf{Hierarchical Formulation:}

\[
y_{ij} = \mu + \theta_i + \epsilon_{ij}, \quad
\theta_i \sim N(0, \tau^2), \quad
\epsilon_{ij} \sim N(0, \sigma^2).
\]

\textbf{BLUP of} \(\theta_i\):

\[
\hat{\theta}_i = B_i \bar{y}_i, \quad
B_i = \frac{n_i}{n_i + \sigma^2 / \tau^2},
\]

where \(B_i\) is the \textbf{shrinkage factor}: - Small \(n_i\) or small
\(\tau^2\) → \textbf{more shrinkage} toward \(\mu\), - Large \(n_i\) or
large \(\tau^2\) → less shrinkage.

\textbf{Borrowing of Information:}

\[
\hat{\theta}_i =
\frac{(1/\tau^2)\mu + (n_i/\sigma^2)\bar{y}_i}{1/\tau^2 + n_i/\sigma^2}.
\]

\begin{itemize}
\item
  Groups with small \(n_i\) (few observations) are pulled more strongly
  toward the overall mean \(\mu\),
\item
  Groups with large \(n_i\) rely more on their own mean \(\bar{y}_i\).
\item
  This can also be expressed in terms of \(\rho\):
\end{itemize}

\[
\hat{\theta}_i 
= \frac{\rho^{-1} \mu + n_i (1-\rho)^{-1} \bar{y}_i}{\rho^{-1} + n_i (1-\rho)^{-1}}.
\]

\textbf{Fixed Effects Estimation (GLS):}

Observations from the same subject or group are \textbf{correlated}
because of random effects.\\
This induces a \textbf{non-diagonal covariance structure}:

\[
\text{Cov}(\mathbf{y}) = \mathbf{V} \neq \sigma^2 I,
\]

where \(\mathbf{V}\) captures both \textbf{between-group variation}
(\(\tau^2\) from random effects) and \textbf{within-group variation}
(\(\sigma^2\) from residual error).

Ordinary Least Squares (OLS) is no longer optimal because it
\textbf{ignores this correlation}.

\textbf{GLS (Generalized Least Squares) Estimator} accounts for the
correlation structure by \textbf{weighting observations} according to
\(\mathbf{V}^{-1}\):

\[
\hat{\boldsymbol{\beta}_{GLS}} =
(\mathbf{X}^T \mathbf{V}^{-1} \mathbf{X})^{-1}
\mathbf{X}^T \mathbf{V}^{-1} \mathbf{y}.
\]

where \(V = Z G Z^T + R\) with:

\begin{itemize}
\tightlist
\item
  \(G = \tau^2 I\) (between-group),
\item
  \(R = \sigma^2 I\) (within-group).
\end{itemize}

This reduces \textbf{bias} and improves \textbf{efficiency} (smaller
variance) compared to OLS when data are correlated.

\textbf{Variance Components:}

\begin{itemize}
\item
  \textbf{MLE (Maximum Likelihood Estimation)} of the variance
  components \((\sigma^2, \tau^2)\) is \textbf{biased} because it does
  not account for the uncertainty in estimating the fixed effects
  \(\boldsymbol{\beta}\).
\item
  \textbf{REML (Restricted Maximum Likelihood)} corrects this bias by
  removing the information about the fixed effects from the likelihood.
  The REML estimator for \(\sigma^2\) (in the simple case) is:
\end{itemize}

\[
\hat{\sigma}^2_{\mathrm{REML}} = \frac{1}{n - p} \sum_{i=1}^n (y_i - \hat{y}_i)^2,
\]

where:

\begin{itemize}
\tightlist
\item
  \(n\) is the total number of observations,
\item
  \(p\) is the number of fixed-effect parameters,
\item
  \(y_i - \hat{y}_i\) are the residuals from the fitted model.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{\texorpdfstring{\textcolor{purple}{3. Random Intercepts and Slopes (Module 1C)}}{}}\label{section-5}
\addcontentsline{toc}{section}{\textcolor{purple}{3. Random Intercepts and Slopes (Module 1C)}}

\markright{\textcolor{purple}{3. Random Intercepts and Slopes (Module 1C)}}

\textbf{Model:}

\[
y_{ij} = (\beta_0 + \theta_{0i}) + (\beta_1 + \theta_{1i}) x_{ij} + \epsilon_{ij},
\]

where:

\begin{itemize}
\tightlist
\item
  \(\beta_0, \beta_1\): population-level intercept and slope,
\item
  \(\theta_{0i}, \theta_{1i}\): subject-specific deviations,
\item
  \(\epsilon_{ij} \sim N(0, \sigma^2)\).
\end{itemize}

\textbf{Random Effects Covariance:}

\[
\begin{pmatrix}
\theta_{0i} \\ \theta_{1i}
\end{pmatrix}
\sim N \left(
\begin{pmatrix} 0 \\ 0 \end{pmatrix},
\begin{pmatrix}
\tau_0^2 & \rho \tau_0 \tau_1 \\
\rho \tau_0 \tau_1 & \tau_1^2
\end{pmatrix}
\right),
\]

where \(\rho\) is the correlation between intercept and slope.

\textbf{Interpretation:}\\
- \(\beta_{0i} = \beta_0 + \theta_{0i}\): individual starting point,\\
- \(\beta_{1i} = \beta_1 + \theta_{1i}\): individual rate of change,\\
- Positive \(\rho\): higher intercepts → steeper slopes,\\
- Negative \(\rho\): higher intercepts → flatter slopes.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{\texorpdfstring{\textcolor{purple}{4. Model Comparison and AIC}}{}}\label{section-6}
\addcontentsline{toc}{section}{\textcolor{purple}{4. Model Comparison and AIC}}

\markright{\textcolor{purple}{4. Model Comparison and AIC}}

\begin{itemize}
\tightlist
\item
  \textbf{AIC:}
\end{itemize}

\[
  AIC = -2 \ell(\hat{\theta}) + 2p,
\] where \(p\) is the number of estimated parameters.\\
Lower AIC indicates better model fit.

\begin{itemize}
\tightlist
\item
  \textbf{Model Selection:}

  \begin{itemize}
  \tightlist
  \item
    Compare random intercept vs.~random slope models,
  \item
    Difference of ≥2 in AIC is considered substantial
  \end{itemize}
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\bookmarksetup{startatroot}

\chapter*{Module 2A Generalized Linear
Models}\label{module-2a-generalized-linear-models}
\addcontentsline{toc}{chapter}{Module 2A Generalized Linear Models}

\markboth{Module 2A Generalized Linear Models}{Module 2A Generalized
Linear Models}

\includegraphics{fig/glm.jpeg}

\textbf{Reading}

\begin{itemize}
\tightlist
\item
  Chapter 3, Wood S. Generalized Additive Models, 2017. Has a nice
  self-contained introduction to generalized linear models.
\item
  Gelman \& Hill. Data Analysis using Regression and
  Multilevel/Hierarchical Models.2006.
\end{itemize}

\subsection*{\texorpdfstring{\textbf{Overview}}{Overview}}\label{overview-1}
\addcontentsline{toc}{subsection}{\textbf{Overview}}

In this module, you will learn \textbf{generalized linear models
(GLMs)}, a flexible extension of linear regression that allows for
modeling response variables with error distributions other than the
normal distribution.

\textbf{After completing this module, you will be able to:}

\begin{itemize}
\item
  Explain components of GLMs (link functions, lienar predictor, and
  error distribution)
\item
  Fit and interpret logistic and Poisson regression models.
\item
  Calculate and interpret odds ratios and rate ratios.
\item
  Perform hypothesis testing using Wald and likelihood ratio tests.
\end{itemize}

\subsection*{Motivation and Examples}\label{motivation-and-examples-1}
\addcontentsline{toc}{subsection}{Motivation and Examples}

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-important-color-frame, coltitle=black, opacityback=0, arc=.35mm, breakable, titlerule=0mm, colbacktitle=quarto-callout-important-color!10!white, toptitle=1mm, title=\textcolor{quarto-callout-important-color}{\faExclamation}\hspace{0.5em}{Motivation:}, leftrule=.75mm, bottomtitle=1mm, bottomrule=.15mm, rightrule=.15mm, toprule=.15mm, left=2mm, colback=white, opacitybacktitle=0.6]

If the outcome variable does not follow a normal distribution,
alternative regression methods, such as generalized linear models, are
required.

\begin{itemize}
\tightlist
\item
  \textbf{Bernoulli/Binomial:} Binary outcomes (0/1) or counts of
  successes out of a fixed number of trials.
\item
  \textbf{Poisson data:} Count data representing the number of events
  occurring over a fixed time, area, or rate.
\end{itemize}

Treating these as continuous outcomes can lead to biased estimates,
incorrect standard errors, and invalid inference because the underlying
distributional assumptions of linear regression are violated.

\end{tcolorbox}

\textbf{Motivating Example: Preterm Births Data}

The dataset: a cohort of live births from Georgia born in the year 2001
\(N = (77,340)\).

Variables:

\begin{itemize}
\item
  ptb: indicator for whether a baby from pregnancy \(i\) was born
  preterm (\textless37 weeks).
\item
  age: the mother's age at delivery (centered at age 25).
\item
  male: indicator of the baby's sex (1=male, 0=female)
\item
  tobacco: indicator for mother's tobacco use during pregnancy (1= yes,
  0 = no).
\end{itemize}

Tobacco is treated as the exposure variables. Mothers age is a
covariate.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{load}\NormalTok{(}\StringTok{"/Users/emilypeterson/Library/CloudStorage/OneDrive{-}EmoryUniversity/BIOS 526/BIOS526\_Book/data/PTB.Rdata"}\NormalTok{)}
\FunctionTok{head}\NormalTok{(dat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
        age ptb male tobacco
4849420  30   0    M       0
2320030  23   0    F       0
3512250  23   0    M       0
4132270  23   0    F       0
4307390  32   0    M       0
3630030  29   0    F       0
\end{verbatim}

\includegraphics{Module_2A_GLM_files/figure-pdf/unnamed-chunk-3-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{\texorpdfstring{Why Not linear regression?
\ul{\textbf{The wrong
approach}}}{Why Not linear regression? The wrong approach}}\label{why-not-linear-regression-the-wrong-approach}
\addcontentsline{toc}{subsubsection}{Why Not linear regression?
\ul{\textbf{The wrong approach}}}

Consider the following multiple linear regression model: For
\(i=1, ..., n\).

\[
  y_i = \beta_0 + \sum_{k=1}^K \beta_k x_{ik} + \epsilon_i \qquad e_i \overset{iid}{\sim} N(0, \sigma^2)
\]

This is equivalent to
\(y_i \sim N(\beta_0 + \sum_{k=1}^K \beta_k x_{ik} , \sigma^2)\) where
\(x_{ik}\) is the kth linear predictor for observation \(i\).

Reminder of the assumptions of the above model:

\begin{itemize}
\tightlist
\item
  The \(\beta's\) are fixed unknown constants.
\item
  \(y\) is a linear function of the covariates.
\item
  The expectation of the errors \(e's\) is zero.
\item
  Only \(\epsilon's\) are random.
\end{itemize}

Therefore, \(y_i\) follows a normal distribution and the
\(E(y_i|x_i) = \beta_0 + \sum_{k=1}^K \beta_k x_{ik}\). The linear
regression part is used to model the \textbf{mean function} of \(y_i\).
The assumptions do not hold for other kinds of data, i.e, binary, count
data, etc.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection*{\texorpdfstring{\ul{The Better Approach: Generalized Linear
Regression}}{The Better Approach: Generalized Linear Regression}}\label{the-better-approach-generalized-linear-regression}
\addcontentsline{toc}{subsection}{\ul{The Better Approach: Generalized
Linear Regression}}

A generalized linear model (GLM) extends the linear regression to other
distributions, where the response variable is generated from a
distribution in the \ul{exponential family.}

GLMs provide this flexibility by extending linear regression to a
broader set of distributions---specifically, those that belong to the
\textbf{exponential family}. The exponential family is mathematically
convenient because it allows for a :

\begin{itemize}
\tightlist
\item
  A natural way to link the mean of the response to the linear
  predictors via a link function.
\item
  Simple expressions for the mean and variance, which are essential for
  estimation and inference.
\item
  Unified estimation procedures (e.g., MLE).
\end{itemize}

A GLM involves three ingredients:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  A probability distribution in the Exponential Family.
\item
  A linear model \(x_i'\beta\).
\item
  A \ul{link function} \(g()\) and its inverse \(g^{-1}()\) is the link
  that relates the linear model to the expectation, i.e., transforms the
  mean function to meet the linear model assumptions.

  \[
  \begin{align*}
  E(y_i|x_i) & = \mu_i = g^{-1} (x_i\beta)\\
  Var(y_i|x_i) & = V(\mu_i) =V(g^{-1}(x_i\beta))
  \end{align*}
  \]
\item
  Note: Unlike OLS, the basic form of the GLM does not involve a noise
  variance \ul{(no $\sigma^2$).}
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Exponential Family}\label{exponential-family}
\addcontentsline{toc}{section}{Exponential Family}

\markright{Exponential Family}

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-note-color-frame, breakable, left=2mm, colback=white, bottomrule=.15mm, arc=.35mm, opacityback=0, rightrule=.15mm, toprule=.15mm, leftrule=.75mm]

The basic form for an exponential family density is

\[
f_{\theta} (y) = exp[\{y\theta - b(\theta)\} / a(\phi) + c(y, \phi )]
\]

where \(a, b, c\) are known functions, and \(\phi\) is a known scale
parameter. The ONLY parameter is \(\theta\).

\end{tcolorbox}

In the GLM, \(\theta\) will be a function of \(x_i\beta\).

Examples of distributions in the exponential family include: normal with
known variance (link = identity), Bernoulli (link = logit or probit),
binomial (link = logit or log), gamma, exponential (link = negative
inverse), and others.

Lets derive a general class for the exponential function. \emph{Use the
expandable panels below to explore key statistical properties and their
derivations.}

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-tip-color-frame, breakable, left=2mm, colback=white, bottomrule=.15mm, arc=.35mm, opacityback=0, rightrule=.15mm, toprule=.15mm, leftrule=.75mm]

\vspace{-3mm}\textbf{The Binomial Distribution}\vspace{3mm}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  The Binomial distribution with parameters \(n\) and \(p\) is:
\end{enumerate}

\[f(y \mid p) = \binom{n}{y} p^y (1-p)^{n-y},\]

which can be expressed in the exponential family form:

\[f(y \mid \theta) = \exp \left[ y \theta - b(\theta) + c(y) \right], \]
where
\[\theta = \log \left( \frac{p}{1-p} \right), \quad b(\theta) = n log (1 + e{\theta}), \quad c(y) = \log \binom{n}{y}. \]

The mean and variance are:
\[ E[Y] = np, \qquad \text{Var}(Y) = np(1-p). \]

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-tip-color-frame, breakable, left=2mm, colback=white, bottomrule=.15mm, arc=.35mm, opacityback=0, rightrule=.15mm, toprule=.15mm, leftrule=.75mm]

\vspace{-3mm}\textbf{The Poisson Distribution}\vspace{3mm}

The Poisson distribution with parameter \(\lambda > 0\) is:

\[f(y \mid \lambda) = \frac{\lambda^y e^{-\lambda}}{y!}, \]

which can be expressed in the exponential family form:

\[f(y \mid \theta) = \exp \left[ y \theta - b(\theta) + c(y) \right], \]
where
\[\theta = \log (\lambda), \quad b(\theta) = e^{\theta}, \quad c(y) = - \log (y!). \]

The mean and variance are:
\[E[Y] = \lambda, \qquad \text{Var}(Y) = \lambda. \]

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-tip-color-frame, breakable, left=2mm, colback=white, bottomrule=.15mm, arc=.35mm, opacityback=0, rightrule=.15mm, toprule=.15mm, leftrule=.75mm]

\vspace{-3mm}\textbf{The Gamma Distribution}\vspace{3mm}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  The Gamma distribution (shape \(k\), scale \(\phi\)) has the density:
\end{enumerate}

\[f(y \mid k, \phi) = \frac{1}{\Gamma(k) \phi^k} y^{k-1} e^{-y/\phi}, \quad y > 0. \]

It can be expressed in the exponential family form:

\[f(y \mid \theta) = \exp \left[ \frac{y \theta - b(\theta)}{a(\phi)} + c(y, \phi) \right], \]
where
\[ \theta = -\frac{1}{\phi}, \quad b(\theta) = - \log (-\theta), \quad a(\phi) = \frac{1}{k}, \quad c(y, \phi) = (k-1)\log y - \log \Gamma(k). \]

The mean and variance are:
\[E[Y] = k \phi, \qquad \text{Var}(Y) = k \phi\^2. \]

\end{tcolorbox}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Logistic Regression}\label{logistic-regression}
\addcontentsline{toc}{section}{Logistic Regression}

\markright{Logistic Regression}

\subsubsection*{Bernoulli Model}\label{bernoulli-model}
\addcontentsline{toc}{subsubsection}{Bernoulli Model}

Let's take a binary outcome where \(p_i\) is the probability of success.
For \(i=1,...,n\) assume

\[ 
y_i \sim Bernoulli (p_i)
\]

where \(p_i \in (0,1)\) and the Bernoulli function has the following
characteristics:

\[
\begin{align*}
E(y_i) & = p_i\\
Var(y_i) & =V(p_i) = p_i (1- p_i)\\
f(y_i|p_i) & = p_i ^{y_i} (1-p_i)^{1-y_i}
\end{align*}
\]

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Link Functions}\label{link-functions}
\addcontentsline{toc}{subsubsection}{Link Functions}

We know that \(\mu_i = p_i = P(Y_i=1)\). So we wish to model a
\textbf{link function} \(g()\) that \textbf{enforces a linear
relationship} between the unscaled expectation \(\mu_i\) and the
expectation \(\beta_0 + \sum_{k=1}^K \beta_k x_{ik}\), i.e, we wish to
model

\[
g(\mu_i) = \beta_0 + \sum_{k=1}^K \beta_k x_{ik}
\]

The two most commonly used link functions for binomial data are the
logit and probit functions.

\ul{The \textbf{link function} should have some desirable properties:}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(g()\) should have a range \((-\infty, \infty)\) so that \(\beta's\)
  and \(X's\) can have any value.
\item
  \(g()\) should have a domain that corresponds to all possible values
  of \(\mu_i\), i.e., \((0,1)\) for the binomial distribution.
\item
  \(g()\) should be one-to-one
  \(\mu_i = g^{-1}(\beta_0 + \sum_k \beta_k X_{ik})\).
\item
  \(g()\) should be strictly increasing, i.e.,
  \(g(p_i) \rightarrow \infty\) when \(p_i \rightarrow 1\).
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Logit Link \& Logistic
Function}\label{logit-link-logistic-function}
\addcontentsline{toc}{subsubsection}{Logit Link \& Logistic Function}

The logit link function is defined as:

\[
g(p_i) = log\left(\frac{p_i}{1-p_i}\right) = \beta_0 + \sum_k \beta_k X_{ik}, \qquad (0,1) \rightarrow (-\infty, \infty)
\]

Meaning \(log(p_i/1-p_i) \rightarrow -\infty\) when
\(p_i \rightarrow 0\) and \(log(p_i/1-p_i)\rightarrow \infty\) when
\(p_i \rightarrow 1\).

In general the logistic function is defined as :

\[
p_i = \frac{e^{g(\mu_i)}}{1 + e^{g(\mu_i)}} = \frac{1}{1+ e^{-g(\mu_i)}}, \qquad (-\infty, \infty) \rightarrow (0,1)
\]

\begin{itemize}
\item
  The \(\beta's\) are estimated using the iterative re-weighted MLE
  method.
\item
  There is no \(\epsilon_i\)!!! Meaning the variance is not defined by a
  normally distributed noise term.
\item
  \(g(p_i)\) is interpreted as the \ul{log\_odds of probability of
  success.}
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Interpretation}\label{interpretation}
\addcontentsline{toc}{subsubsection}{Interpretation}

When \(X_i=0\), \(log(\frac{p_i}{1-p_i}) = \beta_0\) which is
interpreted as the baseline or reference log-odds of probability.

\(\beta_1\) is interpreted as the CHANGE in log-odds per one unit change
in \(X_i\). Conversely, \(e^{\beta_1}\) is defines the odds-ratio.

\[
log(\frac{p_i}{1-p_i}) = \beta_0 + \beta_1 x_i, \text{ versus } log(\frac{p^*_i}{1-p^*_i}) = \beta_0 + \beta_1 (x_i + 1)
\]

then

\[
log\left(\frac{p^*_i /1-p^*_i}{p_i /1-p_i}\right) = \beta_1
\]

In the multiple logistic regression, \(\beta_k\) is the log odds ratio
associated with covariate \(k\) while controlling for other covariates.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Odds Ratio \& Indicator
Variables}\label{odds-ratio-indicator-variables}
\addcontentsline{toc}{subsubsection}{Odds Ratio \& Indicator Variables}

Odds Ratio interpretation is helpful for indicator variables. Let
\(x_i=1\) in exposed group and \(x_i=0\) in unexposed group. Then:

\[
e^{\beta_1} = \frac{\{\frac{p(y_i=1|x_i=1}{p(y_i=0|x_i=1}\}}{\frac{p(y_i=1|x_i=0}{p(y_i=0|x_i=-}\}} = \frac{\text{odds(Exposed)}}{\text{odds(Unexposed)}}
\]

\begin{itemize}
\item
  OR\textgreater1 means a positive association
\item
  OR\textless1 means a negative association
\item
  OR=1 means no difference between exposure groups.
\end{itemize}

It is really important to understand that the change in log-odds per one
unit change in \(X_i\) is not constant, i.e, that change in log-odds
depends on the value of \(X_i\).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#The Logit Function}
\NormalTok{p.i }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\AttributeTok{by =} \FloatTok{0.001}\NormalTok{)}
\NormalTok{g\_p.i }\OtherTok{\textless{}{-}} \FunctionTok{log}\NormalTok{(p.i}\SpecialCharTok{/}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{p.i))}
\FunctionTok{plot}\NormalTok{(p.i, g\_p.i, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{, }\AttributeTok{xlab =}\StringTok{"p"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Logit Function"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Module_2A_GLM_files/figure-pdf/unnamed-chunk-4-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#The Logistic Function}
\NormalTok{p\_i }\OtherTok{\textless{}{-}} \FunctionTok{exp}\NormalTok{(g\_p.i)}\SpecialCharTok{/}\NormalTok{(}\DecValTok{1}\SpecialCharTok{+}\FunctionTok{exp}\NormalTok{(g\_p.i))}
\FunctionTok{plot}\NormalTok{(g\_p.i, p\_i, }\AttributeTok{col =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"x"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Logistic Function"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Module_2A_GLM_files/figure-pdf/unnamed-chunk-4-2.pdf}

What are the effects of changing the baseline odds?

\[
\begin{align}
logit(p_i)& = \beta_0 + x_i\\
\mu_i = P(Y_i =1) &= \frac{e^{\beta_0 + x_i}}{1 + e^{\beta_0 + x_i}}
\end{align}
\]

\includegraphics{Module_2A_GLM_files/figure-pdf/unnamed-chunk-5-1.pdf}

Note: The shape is maintained, and the baseline (intercept) probability
changes.

What are the effects of the change in slope?

\[
\begin{align}
logit(p_i)& = \beta_1 x_i\\
\mu_i = P(Y_i =1) = \frac{e^{\beta_1 x_i}}{1 + e^{\beta_1 x_ii}}
\end{align}
\]

\includegraphics{Module_2A_GLM_files/figure-pdf/unnamed-chunk-6-1.pdf}

Note how the steepness changes with difference in slopes. Also note how
the direction changes depending on the effect changes.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Fitting a logistic regression in
R}\label{fitting-a-logistic-regression-in-r}
\addcontentsline{toc}{subsubsection}{Fitting a logistic regression in R}

We come back to our motivating example using data on preterm births in
Georgia (2001).

Fitting the GLM model in R is very similar to fitting a linear
regression model. We need to specify the distribution as
\textcolor{blue}{binomial}and the link function as
\textcolor{blue}{logit}.

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\#\# The GLM Function}

\FunctionTok{load}\NormalTok{(}\StringTok{"/Users/emilypeterson/Library/CloudStorage/OneDrive{-}EmoryUniversity/BIOS 526/BIOS526\_Book/data/PTB.Rdata"}\NormalTok{)}

\NormalTok{fit }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ ptb }\SpecialCharTok{\textasciitilde{}}\NormalTok{ age }\SpecialCharTok{+}\NormalTok{ male }\SpecialCharTok{+}\NormalTok{ tobacco, }
    \AttributeTok{family =} \FunctionTok{binomial}\NormalTok{(}\AttributeTok{link =} \StringTok{"logit"}\NormalTok{),}
    \AttributeTok{data =}\NormalTok{ dat)}

\FunctionTok{summary}\NormalTok{(fit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Call:
glm(formula = ptb ~ age + male + tobacco, family = binomial(link = "logit"), 
    data = dat)

Coefficients:
              Estimate Std. Error z value Pr(>|z|)    
(Intercept) -2.4212664  0.0631355 -38.350  < 2e-16 ***
age         -0.0006295  0.0021596  -0.291  0.77068    
maleM        0.0723659  0.0258672   2.798  0.00515 ** 
tobacco      0.4096495  0.0534627   7.662 1.83e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 44908  on 77339  degrees of freedom
Residual deviance: 44846  on 77336  degrees of freedom
AIC: 44854

Number of Fisher Scoring iterations: 5
\end{verbatim}

\textbf{Model Interpretation}

\begin{itemize}
\item
  Preterm delivery was significantly associated with male babies
  (p-value = 0.005) when controlling for age and mother's smoking
  status. The \ul{odds ratio} of a preterm birth for a male baby versus
  a female baby was 1.07 (95\% CI: 1.02, 1.13).
\item
  \(OR = e^{0.0723} = 1.07\) with 95\% CI = (1.02, 1.13).

  \begin{itemize}
  \item
    How we get CIs: \(e^{(0.0723 \pm 1.96 * 0.0258)}\).

    NOTE: TRANSFORM THE INTERVALS. DO NOT TRANSFORM THE STANDARD ERRORS
    (this requires the delta method).
  \end{itemize}
\item
  Preterm delivery was significantly associated with whether the mother
  smoked during pregnancy (p\textless0.001) when controlling for age and
  the baby's sex.
\item
  \(OR = e^{0.409} = 1.51 (1.36, 1.67)\).
\item
  The baseline proportion (female babies born to mother of age 25 who
  didn't smoke) of preterm delivery was

  \[
  \frac{e^{-2.42}}{1 + e^{-2.42}} = 0.08.
  \]
\item
  We didn't find an effect of mother's age.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Wald Test}\label{wald-test}
\addcontentsline{toc}{subsubsection}{Wald Test}

The \textbf{Wald Test} evaluates the significance of individual
regression coefficients directly by comparing the estimated coefficient
to its standard error. The Wald Test relied on the fact that MLEs of the
coefficients are approximately normally distributed for large samples
(Central Limit Theorem).

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-note-color-frame, breakable, left=2mm, colback=white, bottomrule=.15mm, arc=.35mm, opacityback=0, rightrule=.15mm, toprule=.15mm, leftrule=.75mm]

Wald test under regularity conditions and assuming asympotitc results,

\[
\begin{align}
\hat{\beta} &\sim N(\beta, I(\beta)^{-1})\\
I(\beta) &= E\left\{\left(\frac{\partial l}{\partial \beta}\right)\left(\frac{\partial l}{\partial \beta}\right)'\right\}\\
&= -E\frac{\partial^2 l}{\partial \beta \partial \beta'}
\end{align}
\]

\begin{itemize}
\item
  \(I(\beta)\) is called the Fisher information matrix (see Wood p.106).
  The standard error of \(\hat{\beta}\) is derived from
  \(I(\beta)^{-1}\).
\item
  The Wald test uses the standardized statistic: \[
  Z = \frac{\hat{\beta}_i}{s.e.(\hat{\beta}_i)}
  \]
\end{itemize}

\end{tcolorbox}

\begin{itemize}
\item
  The \(Z-\) column is calculated as
  \(z = \frac{\hat{\beta}_i}{SE(\hat{\beta}_i)}\).
\item
  The p-values are derived from the z-statistic \(H_0 : \beta_i = 0\).
  For example, for \textt{male}, \(z \approx 2.798\) with \(p=0.005\)
  indicating male babies are significantly associated with preterm birth
  holding other variables constant.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Likelihood Ratio Test}\label{likelihood-ratio-test}
\addcontentsline{toc}{subsubsection}{Likelihood Ratio Test}

In logistic regression, we use the Likelihood Ratio Test to determine
whether adding predictors significantly improves model fit, since
standard F-tests from linear regression do not apply. The Likelihood
Ratio Test (LRT) provides a natural way to compare nested models by
examining how much better the full model fits the data compared to a
reduced model (with some parameters set to zero):
\textcolor{blue}{How can we test whether which model is better?}

The likelihood ratio test (LRT) is used to test the null hypothesis that
any subset of the \(\beta's\) is equal to 0. The number of \(\beta's\)
in the full model is \(k+1\), while the number of \(\beta's\) in the
reduced model is \(r+1\). (Remember the reduced model is the model that
results when the \(\beta's\) in the null hypothesis are set to 0). Thus,
the number of \(\beta's\) being tested in the null hypothesis is
\((k+1) - (r+1) = k-r\).

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-note-color-frame, breakable, left=2mm, colback=white, bottomrule=.15mm, arc=.35mm, opacityback=0, rightrule=.15mm, toprule=.15mm, leftrule=.75mm]

The Likelihood Ratio Test is given by:

\[
LR= \frac{max_{H_0}L(\beta)}{max_{H_A}L(\beta)}
\] This gives the ratio of the likelihood of the null model evaluated at
the MLEs to the likelihood of the full model evaluated at the MLEs.

\begin{itemize}
\tightlist
\item
  In the normal case, this is the analogous to the F-test described in
  Chapter 1.
\end{itemize}

The likelihood ratio test statistic is given by:

\[
\lambda_{LR} = -2[l(\hat{\beta}_{reduced}) - l(\hat{\beta}_{full})]
\]

\begin{itemize}
\item
  The difference follows a Chi-square distribution, i.e.,

  \[
  \lambda_{LR} > \chi^2_{\nu, 1-\alpha}
  \]
\end{itemize}

where \(\nu\) denotes the different in number of parameters, i.e.,
\(k-r\) = degrees of freedom.

\end{tcolorbox}

The likelihood for a binary logistic regression is given by:

\[
L(\beta; \mathbf{y}, \mathbf{X}) = \prod_{i=1}^{n} \pi_i^{y_i} (1-\pi_i)^{1-y_i}
\]

This yields a log-likelihood of:

\[
\begin{align*}
l(\beta) &= \sum_{i=1}^n [y_i log(\pi_i)  + (1-y_i) log(1-\pi_i)\\
&= \sum_{i=1}^n [y_i \mathbf{X}_i \beta - log(1+ exp(\mathbf{X}_i \beta))]
\end{align*}
\]

Maximizing the LL has \ul{no closed form solution}, so a technique used
to obtain MLEs \(\hat{\beta}\) is iteratively reweighted least squares
(not covered here).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(car)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Loading required package: carData
\end{verbatim}

\begin{verbatim}

Attaching package: 'car'
\end{verbatim}

\begin{verbatim}
The following object is masked from 'package:dplyr':

    recode
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{Anova}\NormalTok{(fit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Analysis of Deviance Table (Type II tests)

Response: ptb
        LR Chisq Df Pr(>Chisq)    
age        0.085  1   0.770669    
male       7.834  1   0.005126 ** 
tobacco   53.648  1  2.399e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\textbf{Interpretation}

\begin{itemize}
\item
  Comparing the full vs reduced model with everything EXCEPT age, we see
  a \(\chi^2\) statistic of 0.085 with a p-value of 0.77 meaning that
  removing age does not significantly worsen the model fit, i.e., age is
  not a significant predictor when controlling for other variables.
\item
  Removing the male variable significantly worsens model fit \(p<0.01\),
  meaning this is a significant predictor.
\item
  Tobacco use has a \(\chi^2\) statistic of 53.65 and a p-value of
  \textless0.001, meaning it is a highly significant predictor, and
  removing it significantly reduces model fit.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{\texorpdfstring{\textcolor{purple}{Summary}}{}}\label{section-7}
\addcontentsline{toc}{section}{\textcolor{purple}{Summary}}

\markright{\textcolor{purple}{Summary}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1806}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.8194}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Section}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Description}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{What is the model?} & A \textbf{generalized linear model (GLM)}
links the expected response \(E(Y|X) = \mu\) to predictors via a link
function: \(g(\mu) = \beta_0 + \sum_k \beta_k x_{ik}\). The response
\(Y\) must follow a distribution in the \textbf{exponential family}
(e.g., Normal, Bernoulli, Binomial). \\
\textbf{Model Components} & \textbf{1. Random component:} Distribution
of \(Y\) (e.g., Bernoulli for binary data). \textbf{2. Systematic
component:} Linear predictor \(\eta_i = x_i' \beta\). \textbf{3. Link
function:} \(g(\mu_i)\) maps mean response to \(\eta_i\). \\
\textbf{Logistic Regression} & Special case of GLM for \textbf{binary
outcomes} (\(Y \in \{0,1\}\)) using the logit link:
\(g(p) = \log \frac{p}{1-p}\). Coefficients \(\beta_j\) represent
changes in \textbf{log-odds}, while \(e^{\beta_j}\) are \textbf{odds
ratios}. \\
\textbf{Model Assumptions} & - Correct link function (e.g., logit). -
Independent observations. - Mean and variance correctly specified for
Bernoulli data: \(E(Y)=p\), \(Var(Y)=p(1-p)\). \\
\textbf{Hypothesis Testing} & \textbf{Wald Test:} Tests
\(H_0: \beta_j = 0\) using
\(Z = \hat{\beta}_j / \text{SE}(\hat{\beta}_j)\). \textbf{Likelihood
Ratio Test (LRT):} Compares nested models with
\(\lambda_{LR} = -2 [l_{reduced} - l_{full}] \sim \chi^2\). \\
\textbf{Interpretation} & - \(\beta_j\): Change in log-odds of success
for a one-unit increase in \(X_j\), holding other variables constant. -
\(e^{\beta_j}\): Odds ratio (OR) for a one-unit change in \(X_j\). -
Intercept \(\beta_0\): Baseline log-odds for reference group. \\
\end{longtable}

\bookmarksetup{startatroot}

\chapter*{Module 2B Generalized Linear
Models}\label{module-2b-generalized-linear-models}
\addcontentsline{toc}{chapter}{Module 2B Generalized Linear Models}

\markboth{Module 2B Generalized Linear Models}{Module 2B Generalized
Linear Models}

\includegraphics{fig/glm.jpeg}

\section*{Poisson Regression}\label{poisson-regression}
\addcontentsline{toc}{section}{Poisson Regression}

\markright{Poisson Regression}

The Poisson model is used for count data, that is; where each data point
\(y_i\) can equal 0,1,2,\ldots.N. Poisson models are commonly used for
assessing disease and/or mortality counts particularly for rare
diseases.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Model Setup}\label{model-setup}
\addcontentsline{toc}{subsubsection}{Model Setup}

We assume that \(y_i\) follows a Poisson distribution: \[
y_i \sim Poisson(\theta_i) = \frac{e^{-\theta_i}\theta_i^{y_i}}{y_i !}
\]

where \(\theta_i>0\) is the expected count for observation \(i\).

\begin{itemize}
\tightlist
\item
  An important characteristic of the Poisson distribution is that the
  mean and variance are equal:
\end{itemize}

\[
E(y_i ) = Var(y_i) = \theta_i
\] - This is notable because it is a characteristic that determines
whether Poisson is an appropriate model assumption.

\begin{itemize}
\tightlist
\item
  As with linear and logistic regression, the variation in \(y\) can be
  explained with linear predictors \(X\).
\end{itemize}

\[
\theta_i = exp(X_i \beta)
\]

\begin{itemize}
\tightlist
\item
  Here the \ul{link} is the log() link. log() has domain \((0, \infty)\)
  and range \((-\infty, \infty)\) and is strictly increasing.
\end{itemize}

\[
g(\theta_i) = log(\theta_i)
\] which maps \((0, \infty) \to (-\infty, \infty)\).

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Interpretation of
Coefficients}\label{interpretation-of-coefficients}
\addcontentsline{toc}{subsubsection}{Interpretation of Coefficients}

\begin{itemize}
\tightlist
\item
  Consider a simple Poisson regression model with only one covariate:
\end{itemize}

\[
\begin{align*}
y_i &\overset{ind}{\sim} Pois(\lambda_i)\\
log(\lambda_i) & = \beta_0 + \beta_1 x_i
\end{align*}
\]

\begin{itemize}
\item
  The coefficient \(\beta_j\) represents the \textbf{log change} in the
  expected count for a one-unit increase in \(X_j\) holding other
  predictors constant.
\item
  Exponentiating \(\beta_j\) gives the \textbf{incidence rate ratio
  (IRR)}:
\end{itemize}

\[
exp(\beta_j) = \frac{\theta_i^*}{\theta_i}
\]

How did we get that?

\textbf{Baseline scenario:} \((X_{ij} = x)\), with expected count
\((\theta_i )\).

\textbf{One-unit increase in} \((X_{ij})\): \((X_{ij} = x + 1)\), with
expected count \((\theta_i^{*} )\).

The difference in log-mean is:

\[
\log \theta_i^{*} - \log \theta_i = \beta_j.
\] Exponentiating both sides, we have:

\[
e^{\beta_j} = \frac{\theta_i^{*}}{\theta_i},
\]

which is interpreted as the \textbf{incidence rate ratio (IRR)} --- the
multiplicative change in the expected count for a one-unit increase in
\(( X_{ij} )\), holding other variables constant.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Fitting a Poisson Regression in
R}\label{fitting-a-poisson-regression-in-r}
\addcontentsline{toc}{subsubsection}{Fitting a Poisson Regression in R}

We are going to use the preterm birth data from Georgia to illustrate
our approach. For this analysis, the data have been aggregated by 5-year
maternal age groups and stratified by infant sex and maternal tobacco
use. This aggregation allows us to model counts of preterm births
(events) relative to the number of total live births (exposure) using a
Poisson regression.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lme4)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Loading required package: Matrix
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lmerTest)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Attaching package: 'lmerTest'
\end{verbatim}

\begin{verbatim}
The following object is masked from 'package:lme4':

    lmer
\end{verbatim}

\begin{verbatim}
The following object is masked from 'package:stats':

    step
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
The following objects are masked from 'package:stats':

    filter, lag
\end{verbatim}

\begin{verbatim}
The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{load}\NormalTok{(}\StringTok{"/Users/emilypeterson/Library/CloudStorage/OneDrive{-}EmoryUniversity/BIOS 526/BIOS526\_Book/data/PTB.Rdata"}\NormalTok{)}


\NormalTok{dat}\SpecialCharTok{$}\NormalTok{age\_group }\OtherTok{\textless{}{-}} \FunctionTok{cut}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{age,}
                     \AttributeTok{breaks =} \FunctionTok{seq}\NormalTok{(}\DecValTok{15}\NormalTok{, }\DecValTok{45}\NormalTok{, }\DecValTok{5}\NormalTok{),}
                     \AttributeTok{right =} \ConstantTok{FALSE}\NormalTok{,}
                     \AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"16{-}19"}\NormalTok{, }\StringTok{"20{-}24"}\NormalTok{, }\StringTok{"25{-}29"}\NormalTok{, }\StringTok{"30{-}34"}\NormalTok{, }\StringTok{"35{-}39"}\NormalTok{, }\StringTok{"40{-}44"}\NormalTok{))}

\NormalTok{agg\_data }\OtherTok{\textless{}{-}}\NormalTok{ dat }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(age\_group, male, tobacco) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{events =} \FunctionTok{sum}\NormalTok{(ptb),}
    \AttributeTok{total =} \FunctionTok{n}\NormalTok{()}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
`summarise()` has grouped output by 'age_group', 'male'. You can override using
the `.groups` argument.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(agg\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 6 x 5
# Groups:   age_group, male [3]
  age_group male  tobacco events total
  <fct>     <fct>   <int>  <int> <int>
1 16-19     F           0    315  3184
2 16-19     F           1     31   245
3 16-19     M           0    325  3297
4 16-19     M           1     26   276
5 20-24     F           0    696  8257
6 20-24     F           1     61   663
\end{verbatim}

Here we can see the \textbf{number of preterm births (\texttt{events})
for each age-group--sex--tobacco combination}, as well as the
\textbf{total number of live births (\texttt{total})} in that subgroup.

To fit a Poisson regression, we model the counts of events with a
\textbf{log link function}, using the total number of births as an
\textbf{offset}:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit\_poisson }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(events }\SpecialCharTok{\textasciitilde{}}\NormalTok{ age\_group }\SpecialCharTok{+}\NormalTok{ male }\SpecialCharTok{+}\NormalTok{ tobacco,}
                   \AttributeTok{family =}\NormalTok{ poisson,}
                   \AttributeTok{offset =} \FunctionTok{log}\NormalTok{(total),}
                   \AttributeTok{data =}\NormalTok{ agg\_data)}

\FunctionTok{summary}\NormalTok{(fit\_poisson)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Call:
glm(formula = events ~ age_group + male + tobacco, family = poisson, 
    data = agg_data, offset = log(total))

Coefficients:
               Estimate Std. Error z value Pr(>|z|)    
(Intercept)    -2.37223    0.04040 -58.713  < 2e-16 ***
age_group20-24 -0.11935    0.04533  -2.633  0.00847 ** 
age_group25-29 -0.24692    0.04539  -5.441 5.31e-08 ***
age_group30-34 -0.21900    0.04570  -4.792 1.65e-06 ***
age_group35-39 -0.04205    0.05075  -0.829  0.40736    
age_group40-44  0.12036    0.08087   1.488  0.13668    
maleM           0.06634    0.02474   2.682  0.00733 ** 
tobacco         0.34917    0.05029   6.943 3.83e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 148.530  on 23  degrees of freedom
Residual deviance:  29.892  on 16  degrees of freedom
AIC: 202.82

Number of Fisher Scoring iterations: 4
\end{verbatim}

\textbf{Model Interpretation:}

\begin{itemize}
\item
  The intercept (\(\hat{\beta}_0 = -2.37\)) represents the log rate of
  preterm birth for the reference group: mothers aged 16--19, with
  female infants and no tobacco use. Converting to a rate:
  \(e^{-2.37} \approx 0.093\), meaning about 9 preterm births per 100
  live births in this reference group.
\item
  Age effects: Compared to mothers aged 16--19: Ages 20--24 have a 11\%
  lower rate of preterm birth: \(e^{-0.119} \approx 0.89\) (p = 0.008).
  Ages 25--29 have a 22\% lower rate: \(e^{-0.247} \approx 0.78\) (p
  \textless{} 0.001). Ages 30--34 have a 20\% lower rate:
  \(e^{-0.219} \approx 0.80\) (p \textless{} 0.001). No significant
  difference is observed for ages 35--39 or 40--44 (p \textgreater{}
  0.05).
\item
  Infant sex: Male infants have a 6.9\% higher preterm birth rate
  compared to female infants: \(e^{0.066} \approx 1.07\) (p = 0.007).
\item
  Tobacco use: Mothers who smoke have a 42\% higher preterm birth rate
  compared to non-smokers: \(e^{0.349} \approx 1.42\) (p \textless{}
  0.001).
\item
  Goodness-of-fit: The residual deviance (29.89 on 16 df) suggests an
  adequate fit, and the model explains a substantial portion of
  variation compared to the null model (null deviance = 148.53).
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{What is an Offset?}\label{what-is-an-offset}
\addcontentsline{toc}{subsubsection}{What is an Offset?}

In the code above you saw a parameter in the glm
\(\text{offset = log(total)}\). This is called an offset in Poisson
regression.

When modeling \textbf{rates} rather than raw counts, it is critical to
account for the \textbf{population-at-risk} or the \textbf{exposure
time} for each observation. In the context of preterm birth data, the
\textbf{total number of live births} within each age--sex--tobacco
subgroup serves as the population-at-risk. Without this adjustment,
groups with larger populations would naturally have higher counts simply
due to their size, not because they have a higher risk of preterm
births.

\textbf{Why Use an Offset?}

\begin{itemize}
\item
  The Poisson regression models the expected \textbf{count} of events
  \(y_i\) as: \[
  y_i \sim \text{Poisson}(\theta_i)
  \] where \(\theta_i\) is the \textbf{expected count} for the \(i\)th
  subgroup.
\item
  To model \textbf{rates}, we can express: \[
  \text{Rate}_i = \frac{\theta_i}{N_i}
  \] where \(N_i\) is the \textbf{population size} (e.g., total births
  in the subgroup).
\item
  Taking logs: \[
  \log(\theta_i) = \log(N_i) + \log(\text{Rate}_i).
  \] Here, \(\log(N_i)\) is treated as a \textbf{known constant} rather
  than a parameter to estimate.
\item
  This motivates the use of an \textbf{offset term}: \[
  \log(\theta_i) = \log(N_i) + X_i \beta,
  \] which can be written in R as:
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Differences between the Binomial and Poisson
models}\label{differences-between-the-binomial-and-poisson-models}
\addcontentsline{toc}{subsubsection}{Differences between the Binomial
and Poisson models}

The Poisson model is similar to the binomial model for count data but is
applied in slightly different situations.

\begin{itemize}
\item
  If each data point \(y_i\) can be interpreted as the number of
  ``successes'' out of \(n_i\) trials then it is standard to use the
  binomial/logistic model.
\item
  If each data point \(y_i\) does not have a natural limit- it is not
  based on a number of independent trials- then it is standard to use
  the Poisson/log repression model.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{\texorpdfstring{\textcolor{purple}{Summary}}{}}\label{section-8}
\addcontentsline{toc}{section}{\textcolor{purple}{Summary}}

\markright{\textcolor{purple}{Summary}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.0930}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.9070}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Section}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Description}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{What is the model?} & \textbf{Poisson Regression:} Models count
data (\(y_i = 0,1,2,...\)) assuming
\(y_i \sim \text{Poisson}(\theta_i)\), where \(E(y_i) = \theta_i\) and
\(Var(y_i) = \theta_i\). The mean count is linked to predictors by
\(\log(\theta_i) = X_i \beta\). \\
\textbf{Link Function} & Uses the \textbf{log link},
\(g(\theta_i) = \log(\theta_i)\), mapping
\((0, \infty) \rightarrow (-\infty, \infty)\). Coefficients represent
changes in the log of the expected count. \\
\textbf{Interpretation} & \(e^{\beta_j}\) is the \textbf{incidence rate
ratio (IRR)}: the multiplicative change in the expected count for a
one-unit increase in \(X_j\), holding other variables constant. \\
\textbf{Offsets} & Adjusts for \textbf{population-at-risk} or exposure
time. The model becomes \(\log(\theta_i) = \log(N_i) + X_i \beta\),
where \(\log(N_i)\) is an offset term (not estimated). \\
\textbf{Model Assumptions} & - Counts are independent. - Mean equals
variance (no overdispersion). - Correct link function (log). \\
\textbf{Key Differences} & - Use \textbf{Binomial/Logistic} regression
when counts are bounded by a number of trials (\(n_i\)). - Use
\textbf{Poisson} regression when counts have no natural upper limit and
represent rates or events over a fixed exposure. \\
\textbf{Example Findings} & Tobacco use increases preterm birth rate by
\textbf{42\%} (\(IRR \approx 1.42\)), while mothers aged 25--29 have a
\textbf{22\% lower} rate (\(IRR \approx 0.78\)) compared to ages
16--19. \\
\end{longtable}

\bookmarksetup{startatroot}

\chapter*{Module 2 Cheat Sheet}\label{module-2-cheat-sheet}
\addcontentsline{toc}{chapter}{Module 2 Cheat Sheet}

\markboth{Module 2 Cheat Sheet}{Module 2 Cheat Sheet}

\section*{\texorpdfstring{\textcolor{purple}{Overview of GLMs}}{}}\label{section-9}
\addcontentsline{toc}{section}{\textcolor{purple}{Overview of GLMs}}

\markright{\textcolor{purple}{Overview of GLMs}}

\begin{itemize}
\tightlist
\item
  \textbf{Generalized Linear Models (GLMs)} extend linear regression to
  response variables \(Y\) that follow distributions in the
  \textbf{exponential family} (e.g., Normal, Bernoulli, Poisson).
\item
  Components of a GLM:

  \begin{enumerate}
  \def\labelenumi{\arabic{enumi}.}
  \item
    \textbf{Random component:} Specifies the distribution of \(Y\)
    (e.g., Bernoulli for binary, Poisson for counts).
  \item
    \textbf{Systematic component:} Linear predictor
    \(\eta_i = x_i' \beta\).
  \item
    \textbf{Link function:} \(g(\mu_i)\) relates the mean
    \(\mu_i = E(Y_i \mid x_i)\) to \(\eta_i\):

    \[
    \begin{align*}
    g(\mu_i) &= x_i' \beta\\
    E(y_i|x_i)& = \mu_i = g^{-1}(x_i\beta)\\
    Var(y_i|x_I) & = V(\mu_i) = V(g^{-1}(x_i \beta))
    \end{align*}
    \]
  \end{enumerate}
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{\texorpdfstring{\textcolor{purple}{1. Exponential Family}}{}}\label{section-10}
\addcontentsline{toc}{section}{\textcolor{purple}{1. Exponential Family}}

\markright{\textcolor{purple}{1. Exponential Family}}

Many commonly used probability distributions can be expressed in the
\textbf{exponential family} form. A random variable \(Y\) belongs to
this family if its density (or mass) function can be written as:

\[
f(y \mid \theta, \phi) = \exp \left[ \frac{y \theta - b(\theta)}{a(\phi)} + c(y, \phi) \right],
\]

where:

\begin{itemize}
\tightlist
\item
  \textbf{\(\theta\)} is the \textbf{canonical (natural) parameter},
\item
  \textbf{\(b(\theta)\)} is the \textbf{cumulant function}, ensuring
  normalization,
\item
  \textbf{\(a(\phi)\)} is a known scale function (often \(\phi\) is the
  dispersion parameter),
\item
  \textbf{\(c(y, \phi)\)} is a function of \(y\) and \(\phi\) only.
\end{itemize}

\textbf{Key Properties}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Mean and Variance:}

  \begin{itemize}
  \tightlist
  \item
    The mean is given by: \[
    E[Y] = b'(\theta),
    \]
  \item
    The variance is: \[
    \mathrm{Var}(Y) = b''(\theta) \, a(\phi).
    \]
  \end{itemize}
\end{enumerate}

\textbf{Canonical Link Function:} - In a GLM, the \textbf{canonical
link} is defined as: \[
     g(\mu) = \theta,
     \] where \(\mu = E[Y]\).

\begin{itemize}
\tightlist
\item
  \(g()\) should have range \$(- \infty, \infty).
\item
  \(g()\) should be 1-to-1.
\item
  \(g()\) is strictly increasing
\end{itemize}

\section*{\texorpdfstring{\textcolor{purple}{2. Logistic Regression (Binomial Model)}}{}}\label{section-11}
\addcontentsline{toc}{section}{\textcolor{purple}{2. Logistic Regression (Binomial Model)}}

\markright{\textcolor{purple}{2. Logistic Regression (Binomial Model)}}

\textbf{Model:}

\[
Y_i \sim Bernoulli(p_i), \quad g(p_i) = \log \left( \frac{p_i}{1-p_i} \right) = x_i' \beta.
\]

\textbf{Key Points:}

\begin{itemize}
\tightlist
\item
  \(p_i = P(Y_i=1) = \frac{1}{1+e^{-x_i' \beta}}\).
\item
  Coefficients \(\beta_j\) represent changes in \textbf{log-odds}.
\item
  \(e^{\beta_j}\) is the \textbf{odds ratio (OR)} for a one-unit
  increase in \(X_j\) (holding other variables constant).
\end{itemize}

\textbf{Interpretation:}

\begin{itemize}
\tightlist
\item
  \(\beta_0\): Baseline log-odds for the reference group.
\item
  OR \textgreater{} 1: Positive association, OR \textless{} 1: Negative
  association.
\end{itemize}

\textbf{Hypothesis Testing:}

\begin{itemize}
\tightlist
\item
  \textbf{Wald Test:} Significance of individual regression
  coefficients.
\end{itemize}

\[
Z = \frac{\hat{\beta}_j}{SE(\hat{\beta}_j)}$, tests $H_0: \beta_j = 0
\]

\begin{itemize}
\tightlist
\item
  \textbf{Likelihood Ratio Test (LRT):} Tests whether adding predictors
  improves model fit. (Comparing models)
\end{itemize}

\[
  \lambda_{LR} = -2 [ l(\hat{\beta}_{reduced}) - l(\hat{\beta}_{full}) ] \sim \chi^2.
\]

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{\texorpdfstring{\textcolor{purple}{3. Poisson Regression (Count Model)}}{}}\label{section-12}
\addcontentsline{toc}{section}{\textcolor{purple}{3. Poisson Regression (Count Model)}}

\markright{\textcolor{purple}{3. Poisson Regression (Count Model)}}

\textbf{Model:} \[
Y_i \sim \text{Poisson}(\theta_i), \quad \log(\theta_i) = x_i' \beta.
\]

\textbf{Key Points:} - Mean and variance are equal:
\(E(Y_i) = \text{Var}(Y_i) = \theta_i\). - The \textbf{log link} ensures
positivity of \(\theta_i\):

\[
  g(\theta_i) = \log(\theta_i).
\] - \(e^{\beta_j}\) is the \textbf{incidence rate ratio (IRR)}: the
multiplicative change in expected counts for a one-unit increase in
\(X_j\).

\textbf{Offsets:} - For rate modeling, include population size \(N_i\)
as:

\[
  \log(\theta_i) = \log(N_i) + x_i' \beta.
\]

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{\texorpdfstring{\textcolor{purple}{4. Model Assumptions}}{}}\label{section-13}
\addcontentsline{toc}{section}{\textcolor{purple}{4. Model Assumptions}}

\markright{\textcolor{purple}{4. Model Assumptions}}

\begin{itemize}
\tightlist
\item
  \textbf{Logistic Regression:}

  \begin{itemize}
  \tightlist
  \item
    Correct link (logit), independent observations.
  \item
    Mean and variance: \(E(Y_i) = p_i\),
    \(\text{Var}(Y_i) = p_i (1-p_i)\).
  \end{itemize}
\item
  \textbf{Poisson Regression:}

  \begin{itemize}
  \tightlist
  \item
    Counts are independent.
  \item
    Mean equals variance (no overdispersion).
  \item
    Correct link (log).
  \end{itemize}
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{\texorpdfstring{\textcolor{purple}{5. Interpretation Cheat Sheet}}{}}\label{section-14}
\addcontentsline{toc}{section}{\textcolor{purple}{5. Interpretation Cheat Sheet}}

\markright{\textcolor{purple}{5. Interpretation Cheat Sheet}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2342}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.7658}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Component}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Interpretation}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\(\beta_j\) (Logistic) & Change in log-odds for a one-unit increase in
\(X_j\). \\
\(e^{\beta_j}\) (Logistic) & Odds ratio (OR) for a one-unit increase in
\(X_j\). \\
\(\beta_j\) (Poisson) & Change in log expected count for a one-unit
increase in \(X_j\). \\
\(e^{\beta_j}\) (Poisson) & Incidence rate ratio (IRR), multiplicative
change in count for a one-unit increase. \\
Intercept \(\beta_0\) & Baseline log-odds or log-rate for reference
group. \\
\end{longtable}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{\texorpdfstring{\textcolor{purple}{6. Key Tests and Estimation}}{}}\label{section-15}
\addcontentsline{toc}{section}{\textcolor{purple}{6. Key Tests and Estimation}}

\markright{\textcolor{purple}{6. Key Tests and Estimation}}

\begin{itemize}
\tightlist
\item
  \textbf{Maximum Likelihood Estimation (MLE)} used for parameter
  estimation.
\item
  \textbf{Wald Test:} Tests individual coefficients.
\item
  \textbf{LRT (Likelihood Ratio Test):} Compares nested models.
\item
  \textbf{Confidence Intervals:} Transform using
  \(e^{\beta \pm 1.96 \cdot SE(\beta)}\) for ORs/IRRs.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\bookmarksetup{startatroot}

\chapter*{Module 3A Generalized Linear Mixed
Models}\label{module-3a-generalized-linear-mixed-models}
\addcontentsline{toc}{chapter}{Module 3A Generalized Linear Mixed
Models}

\markboth{Module 3A Generalized Linear Mixed Models}{Module 3A
Generalized Linear Mixed Models}

\subsection*{Motivation and Examples}\label{motivation-and-examples-2}
\addcontentsline{toc}{subsection}{Motivation and Examples}

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-important-color-frame, coltitle=black, opacityback=0, arc=.35mm, breakable, titlerule=0mm, colbacktitle=quarto-callout-important-color!10!white, toptitle=1mm, title=\textcolor{quarto-callout-important-color}{\faExclamation}\hspace{0.5em}{Motivation:}, leftrule=.75mm, bottomtitle=1mm, bottomrule=.15mm, rightrule=.15mm, toprule=.15mm, left=2mm, colback=white, opacitybacktitle=0.6]

In many real-world datasets, observations are \textbf{non-normal} and
\textbf{not independent}. For example:

\begin{itemize}
\tightlist
\item
  Repeated measurements on the same subject.
\item
  Clusters of data within counties, hospitals, or schools.
\item
  Panel data where observations are grouped by time or region.
\end{itemize}

\textbf{Why can't we use standard GLMs?}

\begin{itemize}
\item
  A standard GLM assumes independent observations. When data are
  clustered, this assumption is violated, leading to \textbf{biased
  standard errors} and \textbf{incorrect inference}.
\item
  To address this, \textbf{Generalized Linear Mixed Models (GLMMs)}
  extend GLMs by including \textbf{random effects} that account for
  within-group correlation and unobserved heterogeneity.
\item
  Essentially we are combining methods learned in Modules 1 and 2.
\end{itemize}

\end{tcolorbox}

\subsection*{Motivating Example: Crossover
Design}\label{motivating-example-crossover-design}
\addcontentsline{toc}{subsection}{Motivating Example: Crossover Design}

We consider a crossover trial on cerebrovascular deficiency:

Data were obtained from a crossover trial on the disease of
cerebrovascular deficiency. The goal is to investigate the side effects
of a treatment drug compared to a placebo

Design:

\begin{itemize}
\item
  34 patients: an active drug (A) and followed by placebo (B).
\item
  33 patients: a placebo (B) followed by an active drug (A).
\item
  Outcome: a normal (0) or abnormal (1) electrodiagram.
\item
  Each patient has a binary observation at period 1 and period 2.
\item
  Crossover design: can have ``carryover'' effects which confound
  treatment effect estimation. Test whether washout period was adequate.
\end{itemize}

Variables:

\begin{itemize}
\item
  ID \(i\): subject id
\item
  period \(j\): 0 = period 1, 1 = period 2.
\item
  group: 0 = B then A, 1 = A then B
\item
  outcome \(y_{ij}\): 0 = normal ECG response; 1 = abnormal ECG
  response.
\item
  trt: 0 = placebo, 1 = active drug.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"data/crossover.RDS"}\NormalTok{))}

\FunctionTok{head}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  ID group period trt outcome
1  1     1      0   0       0
2  1     1      1   1       0
3  2     1      0   0       0
4  2     1      1   1       0
5  3     1      0   0       0
6  3     1      1   1       0
\end{verbatim}

Consider the following logistic model assuming responses within each
subject are independent.

\begin{itemize}
\item
  Model 1: \(logit P(y_{ij} =1) = \beta_0 + \beta_1 trt_{ij}\)
\item
  Model 2:
  \(logit P(y_{ij} = 1) = \beta_0 + \beta_1 trt_{ij} + \beta_2 period_{ij}\)
\item
  Model 3:
  \(logit P(y_{ij} = 1) = \beta_0 + \beta_1 trt_{ij} + \beta_2 period_{ij} + \beta_3 trt_{ij} \times period_{ij}\)
\end{itemize}

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-tip-color-frame, breakable, left=2mm, colback=white, bottomrule=.15mm, arc=.35mm, opacityback=0, rightrule=.15mm, toprule=.15mm, leftrule=.75mm]

\vspace{-3mm}\textbf{What is the interpretation of \(\beta_1\)?}\vspace{3mm}

The parameter \(\beta_1\) represents the log-odds difference in the
probability of having an abnormal ECG response between the active drug
(trt = 1) and placebo (trt = 0), holding other variables (such as
period) constant.

\begin{itemize}
\tightlist
\item
  \(\exp(\beta_1)\) is the odds ratio of an abnormal ECG response for
  patients on the active drug compared to those on placebo.
\item
  If \(\beta_1 > 0\), the active drug is associated with higher odds of
  abnormal ECG.
\item
  If \(\beta_1 < 0\), the active drug is associated with lower odds of
  abnormal ECG.
\end{itemize}

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-tip-color-frame, breakable, left=2mm, colback=white, bottomrule=.15mm, arc=.35mm, opacityback=0, rightrule=.15mm, toprule=.15mm, leftrule=.75mm]

\vspace{-3mm}\textbf{What is the interpretation of \(\beta_2\)?}\vspace{3mm}

The parameter \(\beta_2\) captures the effect of the study period on the
log-odds of an abnormal ECG response, independent of treatment.
Specifically, \(\beta_2\) represents the change in log-odds of an
abnormal ECG when moving from period 1 (period = 0) to period 2 (period
= 1), holding treatment (trt) constant.

\begin{itemize}
\tightlist
\item
  \(\exp(\beta_2)\) is the odds ratio of an abnormal ECG in period 2
  compared to period 1, after adjusting for treatment.
\item
  A significant \(\beta_2\) may indicate period effects (e.g.,
  differences due to time, learning effects, or insufficient washout).
\end{itemize}

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-tip-color-frame, breakable, left=2mm, colback=white, bottomrule=.15mm, arc=.35mm, opacityback=0, rightrule=.15mm, toprule=.15mm, leftrule=.75mm]

\vspace{-3mm}\textbf{What is the interpretation of \(\beta_3\)?}\vspace{3mm}

The parameter \(\beta_3\) represents the interaction between treatment
and period. It measures how the treatment effect (the difference in
log-odds between active drug and placebo) changes from period 1 to
period 2.

\begin{itemize}
\tightlist
\item
  If \(\beta_3 = 0\), it means the treatment effect is consistent across
  periods.
\item
  If \(\beta_3 \neq 0\), it suggests the treatment effect differs
  between the two periods, which could indicate a carryover effect
  (e.g., residual impact of the drug from the previous period).
\item
  \(\exp(\beta_3)\) quantifies how the odds ratio for treatment
  vs.~placebo changes in period 2 relative to period 1.
\end{itemize}

\end{tcolorbox}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit\_model1 }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ outcome }\SpecialCharTok{\textasciitilde{}} \DecValTok{1}\SpecialCharTok{+}\NormalTok{ trt ,}

    \AttributeTok{family =} \FunctionTok{binomial}\NormalTok{(}\AttributeTok{link =} \StringTok{"logit"}\NormalTok{),}

    \AttributeTok{data =}\NormalTok{ data)}

\NormalTok{fit\_model2 }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ outcome }\SpecialCharTok{\textasciitilde{}} \DecValTok{1}\SpecialCharTok{+}\NormalTok{ trt }\SpecialCharTok{+}\NormalTok{ period ,}

    \AttributeTok{family =} \FunctionTok{binomial}\NormalTok{(}\AttributeTok{link =} \StringTok{"logit"}\NormalTok{),}

    \AttributeTok{data =}\NormalTok{ data)}

\NormalTok{fit\_model3 }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ outcome }\SpecialCharTok{\textasciitilde{}} \DecValTok{1}\SpecialCharTok{+}\NormalTok{ trt }\SpecialCharTok{+}\NormalTok{ period }\SpecialCharTok{+}\NormalTok{ trt}\SpecialCharTok{*}\NormalTok{period,}

    \AttributeTok{family =} \FunctionTok{binomial}\NormalTok{(}\AttributeTok{link =} \StringTok{"logit"}\NormalTok{),}

    \AttributeTok{data =}\NormalTok{ data)}

\FunctionTok{summary}\NormalTok{(fit\_model1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Call:
glm(formula = outcome ~ 1 + trt, family = binomial(link = "logit"), 
    data = data)

Coefficients:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)  -1.0788     0.2808  -3.843 0.000122 ***
trt           0.5600     0.3777   1.483 0.138120    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 166.65  on 133  degrees of freedom
Residual deviance: 164.42  on 132  degrees of freedom
AIC: 168.42

Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(fit\_model2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Call:
glm(formula = outcome ~ 1 + trt + period, family = binomial(link = "logit"), 
    data = data)

Coefficients:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)  -1.2186     0.3441  -3.541 0.000399 ***
trt           0.5582     0.3784   1.475 0.140210    
period        0.2743     0.3768   0.728 0.466626    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 166.65  on 133  degrees of freedom
Residual deviance: 163.89  on 131  degrees of freedom
AIC: 169.89

Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(fit\_model3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Call:
glm(formula = outcome ~ 1 + trt + period + trt * period, family = binomial(link = "logit"), 
    data = data)

Coefficients:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)  -1.5404     0.4499  -3.424 0.000617 ***
trt           1.1097     0.5739   1.934 0.053148 .  
period        0.8473     0.5820   1.456 0.145450    
trt:period   -1.0227     0.7710  -1.326 0.184714    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 166.65  on 133  degrees of freedom
Residual deviance: 162.10  on 130  degrees of freedom
AIC: 170.1

Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.4247}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.1918}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.1918}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.1918}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Covariate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Model 1
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Model 2
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Model 3
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Intercept \(\beta_0\) & -1.08 (0.28) & -1.22 (0.34) & -1.54 (0.45) \\
Treatment \(\beta_1\) & 0.56 (0.38) & 0.56 (0.38) & 1.11 (0.57) \\
Period \(\beta_2\) & & 0.27 (0.38) & 0.85 (0.58) \\
Trt \(\times\) Period \(\beta_3\) & & & -1.02 (0.77) \\
\end{longtable}

\begin{itemize}
\tightlist
\item
  We compared models to check for period \(\beta_2\) and caryyover
  \(\beta_3\) effects.
\item
  Ignoring period effects (Model 1) biases treatment effect \(\beta_1\).
\item
  Model 3: after controlling for period and carryover effects, the
  estimated OR of abnormal ECG in period 1 was \(3.03 = e^{1.11}\) and
  p-value = 0.053. This confirms no strong carryover effect. The 95\%
  confidence interval is
\end{itemize}

\[
(e^{1.11-1.96 * 0.57}, e^{1.11 + 1.96 * 0.57}) = (0.99, 9.27)
\]

\begin{itemize}
\item
  At \(\alpha = 0.05\), we fail to reject the null hypothesis that the
  treatment in period has an impact on the probability of an abnomral
  ECG. However, future research is needed since the p-value is 0.053.
\item
  \(\beta_3\) is negative - the second period effect is smaller for
  those who received active drug during the second period; however, not
  significant.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subparagraph*{Calculating Predicted
Probabilities}\label{calculating-predicted-probabilities}
\addcontentsline{toc}{subparagraph}{Calculating Predicted Probabilities}

Using the estimates from Model 3, we can calculate predicted
probabilities for each treatment/period combination:

Treatment → Placebo group:

\[
\begin{align*}
P(outcome = 1|period=1, trt=1) &= \left(\frac{e^{\beta_0 + \beta_1}}{1 + e^{\beta_0 + \beta_1}}\right) = 0.394\\
P(outcome = 1|period=2, trt=0) &= \left(\frac{e^{\beta_0 + \beta_2}}{1 + e^{\beta_0 + \beta_2}}\right) = 0.333
\end{align*}
\]

Placebo → Treatment group:

\[
\begin{align*}
P(outcome = 1|period=1, trt=0) &= \left(\frac{e^{\beta_0 }}{1 + e^{\beta_0 }}\right) = 0.176\\
P(outcome = 1|period=2, trt=1) &= \left(\frac{e^{\beta_0 + \beta_1 + \beta_2 + \beta_3}}{1 + e^{\beta_0 + \beta_1 + \beta_2 + \beta_3}}\right) = 0.353
\end{align*}
\]

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subparagraph*{Model Comparisons}\label{model-comparisons}
\addcontentsline{toc}{subparagraph}{Model Comparisons}

This is review from Module 2. We can compare models using the LRT and
AIC metrics. Here we want to compare the three nested models

\begin{itemize}
\item
  \textbf{Nested Models:}\\
  Models are nested when the simpler model (reduced) can be obtained by
  setting one or more parameters of the larger model (full) to zero.\\
  \emph{Example:} Model 1 (treatment only) ⊂ Model 2 (treatment +
  period) ⊂ Model 3 (treatment + period + interaction).
\item
  \textbf{Likelihood Ratio Test (LRT):}

  \begin{itemize}
  \tightlist
  \item
    Test statistic:\\
    \[
    \lambda_{LR} = -2 \big[ l(\hat{\beta}_{reduced}) - l(\hat{\beta}_{full}) \big].
    \]
  \item
    Under \(H_0\), \(\lambda_{LR} \sim \chi^2_{df}\), where
    \(df = p_{full} - p_{reduced}\).\\
  \item
    In R: In this example, we will compare model fits 1 and 2.
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit\_reduced }\OtherTok{\textless{}{-}}\NormalTok{ fit\_model1}
\NormalTok{fit\_full }\OtherTok{\textless{}{-}}\NormalTok{ fit\_model2}
\FunctionTok{anova}\NormalTok{(fit\_reduced, fit\_full, }\AttributeTok{test =} \StringTok{"LRT"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Analysis of Deviance Table

Model 1: outcome ~ 1 + trt
Model 2: outcome ~ 1 + trt + period
  Resid. Df Resid. Dev Df Deviance Pr(>Chi)
1       132     164.42                     
2       131     163.89  1  0.53169   0.4659
\end{verbatim}

\begin{itemize}
\item
  A significant LRT p-value means the additional variable(s) improve
  model fit. In our results, we show there is not a significant
  difference between models 1 and 2.
\item
  \textbf{Information Criteria (AIC/BIC):}

  \begin{itemize}
  \tightlist
  \item
    \textbf{AIC:}
  \end{itemize}
\end{itemize}

\[
    AIC = -2 \, l(\hat{\beta}) + 2p,
\] where \(p\) is the number of parameters. Lower AIC indicates better
fit.\\
- Use AIC/BIC penalizes models with larger number of parameters by
\(2p\), so it tests whether added complexity is warranted.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{AIC}\NormalTok{(fit\_model1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 168.418
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{AIC}\NormalTok{(fit\_model2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 169.8863
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{AIC}\NormalTok{(fit\_model3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 170.0983
\end{verbatim}

\begin{itemize}
\tightlist
\item
  A difference of \textbf{2+ in AIC} is often considered meaningful.\\
\item
  The lowest AIC comes from model 1 (but it is only slightly lower)
  meaning the three models perform similarly. There is really nothing
  gained in models 2 and 3.
\end{itemize}

\textbf{What's wrong with this model???}

\begin{itemize}
\item
  It assumes observations are independent, but they are not.

  \(L(\beta; y,x) = \prod_{i=1}^n \prod_{j=1}^{r_i} p_{ij}^{y_{ij}} (1-p_{ij})^{1-y_{ij}}\)
\item
  The product of the individual likelihoods implies the independence
  assumption, i.e., the product treats clustered observations in the
  same way as different participants.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{\texorpdfstring{\textbf{The Better Approach: Generalized
Linear Mixed
Model}}{The Better Approach: Generalized Linear Mixed Model}}\label{the-better-approach-generalized-linear-mixed-model}
\addcontentsline{toc}{section}{\textbf{The Better Approach: Generalized
Linear Mixed Model}}

\markright{\textbf{The Better Approach: Generalized Linear Mixed Model}}

A \textbf{Generalized Linear Mixed Model (GLMM)} is an extension of GLM
that allows for both \textbf{fixed} and \textbf{random} effects. It is
used when data are not normal and are not independent. Main components
of GLMMs:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  A \textbf{GLM structure}: Response variable \(y_{ij}\) from the
  exponential family with link function \(g(\cdot)\).
\item
  \textbf{Random effects}: Group-specific terms (e.g., intercepts or
  slopes) to capture within-group variability. Account for correlation
  or heterogenity within groups.
\item
  \textbf{Fixed effects}: Population level parameters that apply to all
  observations.
\end{enumerate}

For clustered data with groups \(i = 1, \dots, n\) and observations
\(j = 1, \dots, r_i\):

\[
\begin{align*}
y_{ij} &\sim \text{Distribution}(p_{ij}) \\
g(p_{ij})&= \beta_0 + x_{ij}' \beta + \theta_i
\end{align*}
\]

where:

\begin{itemize}
\tightlist
\item
  \(g()\) is the link function that connects the mean of the response
  variable to the linear predictor.
\item
  \(\beta_0\) is the \textbf{overall intercept} (fixed effect).
\item
  \(x_{ij}\) is a vector of covariates.
\item
  \(\beta\) is the vector of \textbf{fixed effects} (population-level
  effects).
\item
  \(\theta_i \sim N(0, \tau^2)\) is a \textbf{random intercept} for
  group \(i\).
\item
  \(\tau^2\) captures between-group variance.
\end{itemize}

\subsection*{Likelihood in GLMM
Estimation}\label{likelihood-in-glmm-estimation}
\addcontentsline{toc}{subsection}{Likelihood in GLMM Estimation}

Let \(\mathbf{y}\) be all the data and \(\mathbf{\theta}\) the vector of
all random effects. So there are \textbf{two} levels of randomness. We
can define the joint distribution \([\mathbf{y}, \mathbf{\theta}]\):

\[
\begin{align*}
[\mathbf{y}, \mathbf{\theta}] &= \prod_{i=1}^{n} [\mathbf{y}_i, \theta_i] \qquad \mathbf{y}_i \text{ are independent}\\
&= \prod_{i=1}^n [\mathbf{y}_i|\theta_i][\theta_i], \quad \text{Chain Rule}\\
&= \prod_{i=1}^n \left(\prod_{j=1}^{r_i} [y_{ij}|\theta_i]\right)[\theta_i] \qquad (\bf{\text{condition independence assumption}})\\
&= \prod_{i=1}^n \left(\prod_{j=1}^{r_i} [y_{ij} |\theta_i]\right) (2\pi \tau^2)^{-1/2} exp(\frac{1}{2\tau^2} \theta_i^2)
\end{align*}
\]

where \(n=\) total number of subjects (groups) and \(r_i\) number of
observations within each subject/group.

The \(y_{ij}\) are \ul{conditionally independent given the random
effects}. This is a critical assumption that clusters are independent
from each other if we fix random effects.

We define the likelihood for the \ul{fixed parameters}. Integrating each
\(\theta_i\), the likelihood is:

\[
L(\beta,\beta_0,\tau^2|\mathbf{y}) = \prod_{i=1}^n \int\left(\prod_{j=1}^{r_i} [y_{ij} |\theta_i]\right) (2\pi \tau^2)^{-1/2} exp(\frac{1}{2\tau^2} \theta_i^2)
\]

\begin{itemize}
\tightlist
\item
  \(n\) integrals is hard to solve.
\end{itemize}

\subsection*{Find the MLE}\label{find-the-mle}
\addcontentsline{toc}{subsection}{Find the MLE}

\begin{itemize}
\item
  Because of our non-linear link function, maximizing the above function
  that involves an integral is quite challenging.
\item
  Statistical software performs numerical integration that involves some
  approximation. Convergence issues are commong in glmms.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection*{Fitting GLMMs}\label{fitting-glmms}
\addcontentsline{toc}{subsection}{Fitting GLMMs}

To handle correlated observations, we include a \textbf{subject-specific
random intercept} \(\theta_i\):

\[
logit P(y_{ij}=1) = \beta_0 + \beta_1 \text{trt}_{ij} + \beta_2 \text{period}_{ij} + \beta_3 (\text{trt} \times \text{period})_{ij} + \theta_i,
\] where \(\theta_i \sim N(0, \tau^2)\).

\begin{itemize}
\tightlist
\item
  \(\theta_i\) represents \textbf{subject-specific deviations} from the
  population-level log-odds \(\beta_0\).
\item
  This structure correctly models the \textbf{within-subject
  correlation}.
\end{itemize}

The random intercept logistic model can be fit using the \(glmer()\)
function with the binomial family.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lme4)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Loading required package: Matrix
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit\_glmm }\OtherTok{\textless{}{-}} \FunctionTok{glmer}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ outcome }\SpecialCharTok{\textasciitilde{}}\NormalTok{ trt}\SpecialCharTok{*}\NormalTok{period }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{ID) ,}

    \AttributeTok{family =} \FunctionTok{binomial}\NormalTok{(}\AttributeTok{link =} \StringTok{"logit"}\NormalTok{),}

    \AttributeTok{data =}\NormalTok{ data)}

\FunctionTok{summary}\NormalTok{(fit\_glmm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Generalized linear mixed model fit by maximum likelihood (Laplace
  Approximation) [glmerMod]
 Family: binomial  ( logit )
Formula: outcome ~ trt * period + (1 | ID)
   Data: data

      AIC       BIC    logLik -2*log(L)  df.resid 
    133.0     147.5     -61.5     123.0       129 

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-1.52490 -0.01098 -0.00454  0.06238  1.59183 

Random effects:
 Groups Name        Variance Std.Dev.
 ID     (Intercept) 551      23.47   
Number of obs: 134, groups:  ID, 67

Fixed effects:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)  -18.925      3.500  -5.407  6.4e-08 ***
trt            9.988      3.102   3.220  0.00128 ** 
period         8.214      3.220   2.551  0.01073 *  
trt:period    -8.234      4.578  -1.799  0.07205 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
           (Intr) trt    period
trt        -0.857              
period     -0.762  0.887       
trt:period  0.634 -0.881 -0.929
\end{verbatim}

\textbf{Interpretation:}

\begin{longtable}[]{@{}lll@{}}
\toprule\noalign{}
Covariate & GLM & GLMM \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Intercept \(\beta_0\) & -1.54 (0.45) & -4.98 (2.12) \\
Treatment \(\beta_1\) & 1.11 (0.57) & 3.58 (2.11) \\
Period \(\beta_2\) & 0.85 (0.58) & 2.78 (2.02) \\
Trt \(\times\) Period \(\beta_3\) & -1.02 (0.77) & -3.32 (3.27) \\
\(\tau^2\) & --- & \(4.92^2\) \\
\end{longtable}

\begin{itemize}
\item
  The point estimates from the random intercept model (GLMM) are
  \textbf{larger}, but their \textbf{standard errors also increased}, so
  inference on direction and significance remains the same.
\item
  The baseline (period 1, placebo) \textbf{log-odds} across subjects
  has:

  \begin{itemize}
  \tightlist
  \item
    A population mean of \(-4.98\),
  \item
    A standard deviation of \(2.12\).
  \end{itemize}
\item
  The middle 95\% of subjects have baseline log-odds between: \[
  -4.98 \pm 1.96 \times 4.92 = (-11.6, \, 2.9),
  \] which corresponds to baseline probabilities of approximately
  \((9 \times 10^{-6}, \, 0.95)\) --- indicating \textbf{very large
  between-subject heterogeneity}!
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 0\tabcolsep) * \real{1.0000}}@{}}
\toprule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\#\#\# Population versus Conditional Interpretations \\
\includegraphics{fig/popfig.png} \\
In a \textbf{GLM}, we estimate the \textbf{marginal model}, where random
effects are integrated out or assumed zero: \\
\(                                                                                                                                                                                                                                                                                                                                                                       
   g(E[y_{ij}]) = \beta X_{ij},                                                                                                                                                                                                                                                                                                                                            
   \) \\
which is interpreted as the \textcolor{red}{population-averaged effect}
or \textcolor{blue}{marginal effect}. In contrast, a \textbf{GLMM}
estimates the slopes \textbf{conditional on random effects}: \\
\(                                                                                                                                                                                                                                                                                                                                                                       
   g(E[y_{ij}|\theta_i]) = \beta X_{ij} + \theta_i,                                                                                                                                                                                                                                                                                                                        
   \) \\
where \(\theta_i\) accounts for subject-specific deviations. These are
known as \textcolor{blue}{conditional effects}. Because GLMs assume
independence, they can underestimate standard errors when clustering is
ignored. \\
To clarify the difference, consider the \textbf{subject-specific
(conditional)} expectation and the \textbf{population-averaged
(marginal)} expectation. For a given subject \(i\), the expected outcome
at observation \(j\) is \\
\(                                                                                                                                                                                                                                                                                                                                                                       
   E(y_{ij} \mid \theta_i) = g^{-1} \big( \beta_0 + \theta_i + \sum_{k=1}^p \beta x_{ijk} \big),                                                                                                                                                                                                                                                                           
   \) \\
where \(g^{-1}\) is the inverse link function, \(\beta_0 + \theta_i\)
represents the subject-specific intercept, and the \(\beta x_{ijk}\)
terms are fixed effects. This expression defines an individual
trajectory, capturing how each subject deviates from the population
mean. \\
The \textbf{population-averaged mean} is obtained by integrating over
the distribution of random effects: \\
\(                                                                                                                                                                                                                                                                                                                                                                       
   E[y_{ij}] = E_{\theta_i} \left[ g^{-1} \big( \beta_0 + \theta_i + \beta'X_{ij} \big) \right].                                                                                                                                                                                                                                                                           
   \) \\
For non-linear link functions such as the logit, this is not equal to
simply applying \(g^{-1}\) to the fixed-effect part: \\
\(                                                                                                                                                                                                                                                                                                                                                                       
   E[g^{-1}(z)] \neq g^{-1}(E[z]).                                                                                                                                                                                                                                                                                                                                         
   \) \\
This explains why the population-averaged curve (the black line in the
figure) does not match the mean of the subject-specific curves. The
non-linearity of \(g^{-1}\) causes averaging across individual
probabilities to produce a curve with a different shape. Thus, GLMs and
GLMMs provide fundamentally different interpretations of the
coefficients \(\beta\). \\
\end{longtable}

\section*{Poisson Regression}\label{poisson-regression-1}
\addcontentsline{toc}{section}{Poisson Regression}

\markright{Poisson Regression}

The \textbf{Poisson model} is used for \textbf{count data}, where each
observation \(y_i\) can take non-negative integer values
\(0, 1, 2, \dots\):

\[
y_i \sim \text{Poisson}(\theta_i) = \frac{e^{-\theta_i} \theta_i^{y_i}}{y_i!}.
\]

As with linear and logistic regression, the mean of \(y\) is related to
covariates through a \textbf{linear predictor}:

\[
\theta_i = \exp(X_i \beta).
\]

The \textbf{canonical link function} is the \textbf{log link}:

\[
g(\theta_i) = \log(\theta_i),
\]

which maps \((0, \infty) \rightarrow (-\infty, \infty)\) and ensures
predicted counts are positive.

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-note-color-frame, breakable, left=2mm, colback=white, bottomrule=.15mm, arc=.35mm, opacityback=0, rightrule=.15mm, toprule=.15mm, leftrule=.75mm]

\vspace{-3mm}\textbf{Reminder: Differences from the Binomial Model}\vspace{3mm}

\begin{itemize}
\tightlist
\item
  \textbf{Binomial/logistic regression} is used when \(y_i\) represents
  the number of ``successes'' out of \(n_i\) trials (bounded count
  data).\\
\item
  \textbf{Poisson regression} is used when \(y_i\) is an unbounded count
  (e.g., number of events over time or space) and not based on a fixed
  number of trials. Commonly used to model rates
\end{itemize}

\end{tcolorbox}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection*{Interpretation of Poisson
Regression}\label{interpretation-of-poisson-regression}
\addcontentsline{toc}{subsection}{Interpretation of Poisson Regression}

Consider a simple model with one covariate:

\[
\begin{aligned}
y_i &\overset{\text{ind}}{\sim} \text{Poisson}(\lambda_i), \\
\log(\lambda_i) &= \beta_0 + \beta_1 x_i.
\end{aligned}
\]

\begin{itemize}
\tightlist
\item
  When \(x_i = 0\), the expected count is \(\lambda_i = e^{\beta_0}\).
\item
  For a one-unit change in \(x_i\): \[
  \beta_1 = \log(\lambda_i^*) - \log(\lambda_i),
  \] where \(\lambda_i^*\) is the expected count at \(x_i + 1\).
\item
  Therefore, \(e^{\beta_1}\) is the \textbf{incidence rate ratio (IRR)},
  the multiplicative change in expected counts for a unit increase in
  \(x_i\).
\item
  Covariate effects are \textbf{multiplicative}, not additive, on the
  original count scale.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection*{Motivating Example: Cancer Incidence in
Ohio}\label{motivating-example-cancer-incidence-in-ohio}
\addcontentsline{toc}{subsection}{Motivating Example: Cancer Incidence
in Ohio}

We analyze \textbf{lung cancer mortality} data across 88 counties in
Ohio, stratified by sex and race.

\textbf{Variables:}

\begin{itemize}
\tightlist
\item
  \(death_{stk}\): number of lung cancer deaths for population stratum
  \(k\) in county \(s\) during year \(t\),
\item
  \(sex_k\): 1 = female, 0 = male,
\item
  \(race_k\): 1 = white, 0 = non-white,
\item
  \(year_t\): 1--9 (1980--1988),
\item
  \(pop_{stk}\): population at risk.
\end{itemize}

\textbf{Research Questions:} - How do sex and race affect lung cancer
death counts? - How much variation exists between counties? - Can we
estimate county-level risks (small-area estimation)?

We will fit a random-intercept Poisson regression model with a log link:

\[
\log E(death_{stk} \mid \theta_s) = \beta_0 + \beta_1 I_{\text{sex} = \text{female}} + \beta_2 I_{\text{race} = \text{white}} + \beta_3 \, \text{year}_t + \theta_s,
\]

where \(\theta_s \sim N(0, \tau^2)\) represents county-level random
intercepts, and \texttt{logpop} is included as an \textbf{offset} to
model lung cancer death rates rather than raw counts.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lme4)}

\NormalTok{cancer }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"data/ohio\_cancer.RDS"}\NormalTok{))}
\FunctionTok{head}\NormalTok{(cancer)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  county sex race year death   pop
1      1   1    1    1     6  8912
2      1   1    1    2     5  9139
3      1   1    1    3     8  9455
4      1   1    1    4     5  9876
5      1   1    1    5     8 10281
6      1   1    1    6     5 10876
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create offset for population at risk}
\NormalTok{cancer}\SpecialCharTok{$}\NormalTok{logpop }\OtherTok{\textless{}{-}} \FunctionTok{log}\NormalTok{(cancer}\SpecialCharTok{$}\NormalTok{pop)}

\CommentTok{\# Fit random{-}intercept Poisson model}
\NormalTok{fit\_poisson }\OtherTok{\textless{}{-}} \FunctionTok{glmer}\NormalTok{(}
\NormalTok{  death }\SpecialCharTok{\textasciitilde{}} \FunctionTok{offset}\NormalTok{(logpop) }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(sex) }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(race) }\SpecialCharTok{+}\NormalTok{ year }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ county),}
  \AttributeTok{family =}\NormalTok{ poisson,}
  \AttributeTok{data =}\NormalTok{ cancer}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Warning in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv, : Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(fit\_poisson)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Generalized linear mixed model fit by maximum likelihood (Laplace
  Approximation) [glmerMod]
 Family: poisson  ( log )
Formula: death ~ offset(logpop) + factor(sex) + factor(race) + year +  
    (1 | county)
   Data: cancer

      AIC       BIC    logLik -2*log(L)  df.resid 
  26905.9   26940.4  -13447.9   26895.9      7387 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-6.6678 -0.5699 -0.2176  0.3900 10.5059 

Random effects:
 Groups Name        Variance Std.Dev.
 county (Intercept) 0.0416   0.204   
Number of obs: 7392, groups:  county, 88

Fixed effects:
                Estimate Std. Error z value Pr(>|z|)    
(Intercept)   -7.7949302  0.0234154 -332.90  < 2e-16 ***
factor(sex)2  -1.1021170  0.0070715 -155.85  < 2e-16 ***
factor(race)2 -0.0474948  0.0103257   -4.60 4.23e-06 ***
year           0.0366854  0.0005224   70.22  < 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) fctr(s)2 fctr(r)2
factor(sx)2 -0.077                  
factor(rc)2 -0.005 -0.005           
year        -0.278 -0.002   -0.036  
optimizer (Nelder_Mead) convergence code: 0 (OK)
Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?
\end{verbatim}

The warning \emph{``Model is nearly unidentifiable: very large
eigenvalue -- Rescale variables?''} indicates potential numerical
instability due to variables on very different scales or high
collinearity among predictors. Although the model converged, it is
recommended to \textbf{center or rescale continuous variables (e.g.,
\texttt{year})} to improve numerical conditioning and ensure stable
parameter estimation.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\textbf{Model Interpretations:}

\subsubsection*{Fixed Effects}\label{fixed-effects}
\addcontentsline{toc}{subsubsection}{Fixed Effects}

\begin{itemize}
\item
  \textbf{Intercept (}\(\hat{\beta}_0 = -7.79\)):\\
  This is the \textbf{baseline log death rate} for non-white males in
  the reference year, in an average county.\\
  Converting to a rate:\\
  \[
  \exp(-7.79) \approx 0.00041,
  \] which is about 0.041 deaths per 100,000 people.
\item
  \textbf{Sex (female) (}\(\hat{\beta}_1 = -1.10\)):\\
  Holding race, year, and county constant, females have \textbf{67\%
  fewer deaths} compared to males:\\
  \[
  \exp(-1.10) \approx 0.33.
  \]
\item
  \textbf{Race (white) (}\(\hat{\beta}_2 = -0.047\)):\\
  White individuals have about \textbf{5\% fewer deaths} compared to
  non-white individuals:\\
  \[
  \exp(-0.047) \approx 0.95.
  \]
\item
  \textbf{Year (}\(\hat{\beta}_3 = 0.0367\)):\\
  Each year is associated with a \textbf{3.7\% increase} in lung cancer
  death rates, holding all other variables constant:\\
  \[
  \exp(0.0367) \approx 1.037.
  \]
\end{itemize}

\subsubsection*{Random Effects}\label{random-effects}
\addcontentsline{toc}{subsubsection}{Random Effects}

\begin{itemize}
\tightlist
\item
  \textbf{County-level variation (}\(\hat{\tau} = 0.204\)):\\
  The standard deviation of county-specific deviations in log death
  rates is 0.204.\\
  The middle 95\% of counties have baseline log rates within: \[
  -7.79 \pm 1.96 \cdot 0.204 = (-8.19, -7.39),
  \] which corresponds to rates ranging from approximately 0.00027 to
  0.00061 per person.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection*{Overdispersion of the Poisson
Assumption}\label{overdispersion-of-the-poisson-assumption}
\addcontentsline{toc}{subsection}{Overdispersion of the Poisson
Assumption}

\begin{itemize}
\item
  In Poisson, the assumption \(E(y_i) = V(y_i)\) is often violated!
\item
  One can add an additional \ul{overdispersion parameter} also called a
  \ul{scale parameter}.
\item
  One can adjust the parameter variance by this scale parameter. This is
  called the \textcolor{red}{quais-poisson} model.

  \[
  \hat{\mathbf{\beta}} \sim N(0, I(\mathbf{\beta})^{-1} \phi)
  \]
\item
  Fitting a quasi-poisson in GLM
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{glm\_quasi }\OtherTok{=} \FunctionTok{glm}\NormalTok{(death }\SpecialCharTok{\textasciitilde{}} \FunctionTok{offset}\NormalTok{(logpop) }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(sex)}\SpecialCharTok{*}\FunctionTok{factor}\NormalTok{(race) }\SpecialCharTok{+}\NormalTok{  (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{county),}
            \AttributeTok{family =} \StringTok{"quasipoisson"}\NormalTok{,}
            \AttributeTok{data =}\NormalTok{ cancer)}

\FunctionTok{summary}\NormalTok{(glm\_quasi)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Call:
glm(formula = death ~ offset(logpop) + factor(sex) * factor(race) + 
    (1 | county), family = "quasipoisson", data = cancer)

Coefficients: (1 not defined because of singularities)
                            Estimate Std. Error   t value Pr(>|t|)    
(Intercept)                -7.280397   0.005707 -1275.600  < 2e-16 ***
factor(sex)2               -1.074482   0.011065   -97.106  < 2e-16 ***
factor(race)2               0.117448   0.017011     6.904 5.47e-12 ***
1 | countyTRUE                    NA         NA        NA       NA    
factor(sex)2:factor(race)2 -0.218442   0.034865    -6.265 3.93e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for quasipoisson family taken to be 2.200393)

    Null deviance: 43628  on 7391  degrees of freedom
Residual deviance: 15976  on 7388  degrees of freedom
AIC: NA

Number of Fisher Scoring iterations: 5
\end{verbatim}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{\texorpdfstring{\textcolor{purple}{Summary}}{}}\label{section-16}
\addcontentsline{toc}{section}{\textcolor{purple}{Summary}}

\markright{\textcolor{purple}{Summary}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.7778}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Section}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Description}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{What is the model?} & A \textbf{Generalized Linear Mixed Model
(GLMM)} extends GLMs by including \textbf{random effects} to account for
correlations within clusters (e.g., subjects, counties). The general
form is: \(g(E[y_{ij}|\theta_i]) = \beta_0 + x_{ij}'\beta + \theta_i\),
where \(\theta_i \sim N(0, \tau^2)\). \\
\textbf{Motivation} & Standard GLMs assume independent observations. In
real-world data, observations are often \textbf{correlated} (e.g.,
repeated measures, cluster data). Ignoring this leads to \textbf{biased
standard errors} and \textbf{invalid inference}. GLMMs address this by
modeling cluster-level variability. \\
\textbf{Model Components} & \textbf{1. Random component:} Distribution
from the exponential family (e.g., Binomial, Poisson). \textbf{2.
Systematic component:} Linear predictor
\(\eta_{ij} = \beta_0 + x_{ij}' \beta + \theta_i\). \textbf{3. Link
function:} \(g(\cdot)\) connects the mean response to the predictor. \\
\textbf{Likelihood} & The joint likelihood involves both fixed and
random effects:
\(L(\beta, \tau^2 | y) = \prod_i \int \left( \prod_j [y_{ij} | \theta_i] \right) [\theta_i] d\theta_i\).
Because this integral is difficult to solve, \textbf{numerical
approximation} (Laplace or adaptive quadrature) is used. \\
\textbf{Interpretation} & Fixed effects (\(\beta_j\)): Population-level
effects. Random effects (\(\theta_i\)): Group-specific deviations.
\textbf{GLM vs.~GLMM:} GLMs provide \textbf{population-averaged}
effects, while GLMMs provide \textbf{conditional} (subject-specific)
effects. \\
\textbf{Example: Crossover} & Logistic GLMM with a random intercept: \$
\logit P(y\_\{ij\}=1) = \beta\_0 + \beta*1* \text{trt}{ij} + \beta*2*
\text{period}{ij} + \beta*3 (*\text{trt}\times \text{period})\{ij\} +
\theta\_i\$. Highlights how ignoring correlation biases treatment
effects. \\
\textbf{Model Comparisons} & \textbf{LRT:} Compares nested models via \$
\lambda*\{LR\} = -2 ( l*\{reduced\} - l\_\{full\} )
\sim \chi\^{}2\_\{df\}\$. \textbf{AIC/BIC:}
\(AIC = -2 l(\hat{\beta}) + 2p\), lower values indicate better fit with
complexity penalty. \\
\textbf{Poisson Regression} & For count data: \$ y\_i
\sim \text{Poisson}(\lambda\_i)\$, with
\(\log(\lambda_i) = \beta_0 + x_i'\beta\). \textbf{Offsets:} Used to
model rates: \(\log E(y_i) = \log(N_i) + x_i' \beta\). \(e^{\beta_j}\) =
\textbf{Incidence Rate Ratio (IRR)}, a multiplicative change in expected
counts. \\
\textbf{Ohio Cancer Example} & Random-intercept Poisson GLMM:
\(\log E(death_{stk} | \theta_s) = \beta_0 + \beta_1 \text{sex} + \beta_2 \text{race} + \beta_3 \text{year} + \theta_s + \log(pop_{stk})\).
Demonstrates county-level heterogeneity and interpretation of IRRs for
sex, race, and year. \\
\end{longtable}

\bookmarksetup{startatroot}

\chapter*{Module 3B Generalized Linear Mixed
Models}\label{module-3b-generalized-linear-mixed-models}
\addcontentsline{toc}{chapter}{Module 3B Generalized Linear Mixed
Models}

\markboth{Module 3B Generalized Linear Mixed Models}{Module 3B
Generalized Linear Mixed Models}

School data example adapted from Gelman and Hill.
\href{https://sites.stat.columbia.edu/gelman/arm/}{Data Analysis Using
Regression and Multilevel/Hierarchical Models}

Guatemalan data example: Rodriguez B and Goldman N (2001). Improved
estimation procedures for multilevel models with binary response: a case
study. Journal of Royal Statistical Society Series A 339-355.

\subsection*{Motivation and Examples}\label{motivation-and-examples-3}
\addcontentsline{toc}{subsection}{Motivation and Examples}

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-important-color-frame, coltitle=black, opacityback=0, arc=.35mm, breakable, titlerule=0mm, colbacktitle=quarto-callout-important-color!10!white, toptitle=1mm, title=\textcolor{quarto-callout-important-color}{\faExclamation}\hspace{0.5em}{Motivation:}, leftrule=.75mm, bottomtitle=1mm, bottomrule=.15mm, rightrule=.15mm, toprule=.15mm, left=2mm, colback=white, opacitybacktitle=0.6]

\textbf{Hierarchical} or \textbf{multilevel} models are used when
observations are nested (.e.g, students within schools, repeated
measures within individuals). Standard regression models ignore
clustering, which leads to \textbf{underestimated standard errors} and
\textbf{biased inference}.

Hierarchical models can be thought of as GLMs that are reparametrized to
separate \textbf{with-in} group and \textbf{between} group sources of
variation with \textbf{nested} data structures. These include:

\begin{itemize}
\tightlist
\item
  Fixed effects for population-level estimates
\item
  Random effects for group-specific deviations.
\item
  Can have multiple levels within one model structure.
\end{itemize}

This has a very Bayesian Flavor! So it is more natural for me to think
this way.

\end{tcolorbox}

\subsection*{Motivating Example: School Math
Scores}\label{motivating-example-school-math-scores}
\addcontentsline{toc}{subsection}{Motivating Example: School Math
Scores}

We consider a three-level hierarchical model of math achievement data.

Levels:

\begin{itemize}
\item
  Level 1 (Year within child):

  \begin{itemize}
  \tightlist
  \item
    \(math_{ijk}\): standardized math score of child \(j\) in school
    \(i\) during year \(k\).
  \item
    \(year_{ijk}\): primary school year (centered at 3.5).
  \item
    \(retained_{ijk}\): indicator for repeating the grade.
  \end{itemize}
\item
  Level 2 (Child within school):

  \begin{itemize}
  \tightlist
  \item
    \(child_{ij}\): child ID.
  \item
    \(female_{ij}\): indicator for female.
  \item
    \(black_{ij}\), \(hispanic_{ij}\): race/ethnicity indicators.
  \end{itemize}
\item
  Level 3 (School):

  \begin{itemize}
  \tightlist
  \item
    \(school_i\): school ID.
  \item
    \(size_i\): number of students in school \(i\).
  \item
    \(lowinc_i\): percentage of low-income students in school \(i\).
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\FunctionTok{getwd}\NormalTok{(), }\StringTok{"/data/achievement.csv"}\NormalTok{))}
\FunctionTok{dim}\NormalTok{(dat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 7230   10
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{6}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  year   math retained female black hispanic size lowinc school child
1  0.5  1.146        0      0     0        1  380   40.3   2020   244
2  1.5  1.134        0      0     0        1  380   40.3   2020   244
3  2.5  2.300        0      0     0        1  380   40.3   2020   244
4 -1.5 -1.303        0      0     0        0  380   40.3   2020   248
5 -0.5  0.439        0      0     0        0  380   40.3   2020   248
6  0.5  2.430        0      0     0        0  380   40.3   2020   248
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(dat, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ year, }\AttributeTok{y =}\NormalTok{ math, }\AttributeTok{group =}\NormalTok{ child, }\AttributeTok{color =} \FunctionTok{factor}\NormalTok{(school))) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.4}\NormalTok{) }\SpecialCharTok{+}      \CommentTok{\# line for each student\textquotesingle{}s trajectory}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.6}\NormalTok{) }\SpecialCharTok{+}     \CommentTok{\# points for observations}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Student Math Scores Over Time"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Year"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Math Score"}\NormalTok{,}
    \AttributeTok{color =} \StringTok{"School"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"none"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Module_3B_GLMMs_files/figure-pdf/unnamed-chunk-2-1.pdf}

The plot above shows individual trajectories of student scores across
years. Colors denote school.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection*{Fitting a Linear Mixed
Model}\label{fitting-a-linear-mixed-model}
\addcontentsline{toc}{subsection}{Fitting a Linear Mixed Model}

Using the methods we have learned so far, we would fit a linear mixed
model (LMM). We can include a random intercept model to account for
student-specific differences in baseline math scores:

\[
\text{math}_{ijk} = \beta_0 + \beta_1 \, \text{year}_{ij} + \beta_2 \, \text{female}_{ij} + \beta_3 \, \text{black}_{ij} + \beta_4 \, \text{hispanic}_{ij} + \beta_5 \, \text{retained}_{ij} + u_{j} + \epsilon_{ijk},
\]

where:\\
- \(i\) indexes students within school \(j\),\\
- \(u_{j} \sim N(0, \tau^2)\) is a \textbf{student-specific random
intercept},\\
- \(\epsilon_{ij} \sim N(0, \sigma^2)\) is the residual error term.

This model \emph{partially pools} the intercepts across students,
borrowing strength from the entire dataset while still allowing each
student to have its own baseline.

\textcolor{red}{Problem!}: Years are \textbf{nested within students},
and \textbf{students are nested within schools}. In other words, the
math scores are measured repeatedly for each student (longitudinal
data), and these students are clustered within schools. So even if we
account for within student correlation, we have not accounted for within
school correlation. A standard LLM fails to account for this
hierarchical data structure.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection*{The Better Approach: Three Level Linear Mixed
Model}\label{the-better-approach-three-level-linear-mixed-model}
\addcontentsline{toc}{subsection}{The Better Approach: Three Level
Linear Mixed Model}

We extend the previous model to account for \textbf{both student-level
and school-level random intercepts}, fully respecting the data hierarchy
(years within students, and students within schools).

\[
\begin{align*}
math_{ijk} & \sim Normal(\mu_{ijk}, \sigma^2)\\
\mu_{ijk} & = \beta_0 + \beta_1 \, \text{year}_{ijk} + \beta_2 \, \text{female}_{ij} + \beta_3 \, \text{black}_{ij} + \beta_4 \, \text{hispanic}_{ij} + \beta_5 \, \text{retained}_{ij} + \underbrace{u_{i}}_{\text{school}}  + \underbrace{u_{ij}}_{\text{student within school}},\\
u_{ij} & \overset{iid}{\sim} N(0, \tau^2)\\
u_i & \overset{iid}{\sim} N(0, \nu^2)\\
\epsilon_{ijk} & \overset{iid}{\sim} N(0, \sigma^2). \quad \text{residual error for year-student-school}
\end{align*}
\]

We can think of \(u_i\) and \(u_{ij}\) as parameters that control for
\textcolor{red}{unmeasured confounders} at the school and student level.

\emph{``One statistician's mean structure is another's covariance
structure.'' (Donald Rubin)}

\begin{itemize}
\item
  In \textbf{frequentist mixed models}, random effects are viewed as
  part of the \textbf{covariance structure} because they induce
  correlation between observations within a cluster. The random effects
  are integrated out when estimating the model, and their variability
  (e.g., \(\tau^2\)) contributes to the marginal covariance matrix.
\item
  In \textbf{Bayesian or hierarchical modeling}, the same random effects
  are treated as part of the \textbf{mean structure} with unknown
  parameters that have prior distributions. We estimate the full
  posterior for both fixed effects and random effects.
\item
  For example, in a linear mixed model:
\end{itemize}

\[
y_{ij} = \beta_0 + \beta_1 x_{ij} + u_i + \epsilon_{ij},
\]

we can think of:

\begin{itemize}
\item
  \textbf{Bayesian method:} \(u_i\) is a \textbf{random deviation} that
  adjusts the mean for cluster \(i\) (part of the mean structure). In
  our 3-level LMM, we place priors on both population-level parameters
  and random effects, e.g., \(\beta_k \sim N(0, 10^2)\).
\item
  \textbf{Frequentist method:} Equivalently, \ul{the marginal
  distribution of $y_{ij}$} can be expressed as:
\end{itemize}

\[
y_{ij} \sim N\!\big(\beta_0 + \beta_1 x_{ij}, \ \tau^2 + \sigma^2\big),
\]

where the extra variance \(\tau^2\) is part of the \textbf{covariance
structure}. We refer to the marginal distribution because in the
frequentist approach the random effects are integrated out, and the
variability they induce enters the covariance structure.

\begin{itemize}
\tightlist
\item
  In our 3-level LMM, these random effects are treated as components
  that induce correlation but are not explicitly estimated as
  parameters.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection*{Pooling (Borrowing Information) at Multiple
Levels}\label{pooling-borrowing-information-at-multiple-levels}
\addcontentsline{toc}{subsection}{Pooling (Borrowing Information) at
Multiple Levels}

Our three-level linear mixed model: \[
math_{ijk} = \beta_0 + \beta_1 year_{ijk} + \cdots + u_i + u_{ij} + \epsilon_{ijk},
\] borrows strength across both \textbf{schools} (Level 3) and
\textbf{students} (Level 2). This is known as \textbf{multi-level
partial pooling}.

\subsubsection*{1. Pooling Across Schools}\label{pooling-across-schools}
\addcontentsline{toc}{subsubsection}{1. Pooling Across Schools}

\begin{itemize}
\item
  \textbf{No pooling (separate means):} Each school mean is just its
  sample mean: \[
  \hat{\mu}_i^{\text{no-pool}} = \bar{y}_i.
  \]
\item
  \textbf{Complete pooling (one mean):} All schools share the overall
  mean: \[
  \hat{\mu}_i^{\text{complete-pool}} = \bar{y}.
  \]
\item
  \textbf{Partial pooling (hierarchical):} \[
  \hat{\mu}_i^{\text{partial-pool}} = w_i \, \bar{y}_i + (1 - w_i)\, \bar{y},
  \] where \[
  w_i = \frac{n_i}{n_i + \frac{\sigma^2}{\nu^2}},
  \] with \(n_i\) = number of observations in school \(i\), \(\nu^2\) =
  between-school variance, and \(\sigma^2\) = residual variance.

  \begin{itemize}
  \tightlist
  \item
    Large schools (big \(n_i\)) get \(w_i \approx 1\) (close to
    \textbf{no pooling}).
  \item
    Small schools (small \(n_i\)) get \(w_i \approx 0\) (closer to
    \textbf{complete pooling}).
  \end{itemize}
\end{itemize}

\subsubsection*{2. Pooling Across Students (Within
Schools)}\label{pooling-across-students-within-schools}
\addcontentsline{toc}{subsubsection}{2. Pooling Across Students (Within
Schools)}

Within each school \(i\), we also pool across students \(j\): \[
  \hat{u}_{ij}^{\text{partial}} = w_{ij} \, (\bar{y}_{ij} - \bar{y}_i),
  \] where \[
  w_{ij} = \frac{n_{ij}}{n_{ij} + \frac{\sigma^2}{\tau^2}},
  \] with \(n_{ij}\) = number of observations for student \(j\), and
\(\tau^2\) = student-level variance.

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-tip-color-frame, breakable, left=2mm, colback=white, bottomrule=.15mm, arc=.35mm, opacityback=0, rightrule=.15mm, toprule=.15mm, leftrule=.75mm]

\vspace{-3mm}\textbf{Derivation of student-level partially pooled estimate}\vspace{3mm}

\subsubsection*{Step 1: Define the Student
Mean}\label{step-1-define-the-student-mean}
\addcontentsline{toc}{subsubsection}{Step 1: Define the Student Mean}

For student \(j\) in school \(i\), the average math score is: \[
\bar{y}_{ij} = \frac{1}{n_{ij}} \sum_{k=1}^{n_{ij}} math_{ijk}.
\]

Substituting the model: \[
\bar{y}_{ij} = \beta_0 + u_i + u_{ij} + \frac{1}{n_{ij}} \sum_{k=1}^{n_{ij}} \epsilon_{ijk}.
\]

Define the \textbf{average residual error}: \[
\bar{\epsilon}_{ij} = \frac{1}{n_{ij}} \sum_{k=1}^{n_{ij}} \epsilon_{ijk},
\] which satisfies \(\bar{\epsilon}_{ij} \sim N(0, \sigma^2 / n_{ij})\).

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Step 2: Center by the School
Mean}\label{step-2-center-by-the-school-mean}
\addcontentsline{toc}{subsubsection}{Step 2: Center by the School Mean}

Subtract the school mean \(\bar{y}_i\) (which contains
\(\beta_0 + u_i\)): \[
\bar{y}_{ij} - \bar{y}_i = u_{ij} + \bar{\epsilon}_{ij}.
\]

This shows that a student's deviation from the school mean is driven by:
- The student's random effect \(u_{ij}\), - The average residual noise
\(\bar{\epsilon}_{ij}\).

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Step 3: Target Quantity}\label{step-3-target-quantity}
\addcontentsline{toc}{subsubsection}{Step 3: Target Quantity}

We want the posterior mean of \(u_{ij}\) given the observed deviation:
\[
\hat{u}_{ij}^{\text{partial}} = E[ u_{ij} \mid \bar{y}_{ij} - \bar{y}_i ].
\]

The prior and likelihood are: \[
u_{ij} \sim N(0, \tau^2),
\] \[
\bar{y}_{ij} - \bar{y}_i \mid u_{ij} \sim N(u_{ij}, \sigma^2 / n_{ij}).
\]

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Step 4: Conditional
Expectation}\label{step-4-conditional-expectation}
\addcontentsline{toc}{subsubsection}{Step 4: Conditional Expectation}

For a bivariate normal vector \((U, Y)\): \[
E[U \mid Y] = \frac{\text{Cov}(U, Y)}{\text{Var}(Y)} \,(Y - E[Y]) + E[U].
\]

Here, \(U = u_{ij}\), \(Y = \bar{y}_{ij} - \bar{y}_i\), and
\(E[U] = 0\): \[
\text{Var}(Y) = \text{Var}(u_{ij} + \bar{\epsilon}_{ij}) = \tau^2 + \frac{\sigma^2}{n_{ij}},
\] \[
\text{Cov}(u_{ij}, Y) = \text{Cov}(u_{ij}, u_{ij} + \bar{\epsilon}_{ij}) = \tau^2.
\]

Thus: \[
E[u_{ij} \mid \bar{y}_{ij} - \bar{y}_i] =
\frac{\tau^2}{\tau^2 + \sigma^2 / n_{ij}} (\bar{y}_{ij} - \bar{y}_i).
\]

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Step 5: Shrinkage Weight}\label{step-5-shrinkage-weight}
\addcontentsline{toc}{subsubsection}{Step 5: Shrinkage Weight}

Define: \[
w_{ij} = \frac{\tau^2}{\tau^2 + \sigma^2 / n_{ij}} = \frac{n_{ij}}{n_{ij} + \frac{\sigma^2}{\tau^2}},
\] so the \textbf{partially pooled student intercept} is: \[
\hat{u}_{ij}^{\text{partial}} = w_{ij} (\bar{y}_{ij} - \bar{y}_i).
\]

\end{tcolorbox}

\begin{itemize}
\item
  \textbf{Students with more data} (\(n_{ij}\) large) →
  \(w_{ij} \approx 1\), so their random intercept is close to their own
  average.
\item
  \textbf{Students with sparse data} (\(n_{ij}\) small) →
  \(w_{ij} \approx 0\), so their intercept is shrunk toward the
  \textbf{school-level mean}.
\item
  The \textbf{random intercepts} \(u_i\) and \(u_{ij}\) ensure that the
  model combines information from all schools and students.\\
\item
  Small or noisy groups borrow strength from the larger dataset, which
  improves stability and reduces overfitting.
\end{itemize}

We can visualize this with a \textbf{shrinkage plot} showing raw school
means vs.~partially pooled estimates, as well as student-level
intercepts:

\includegraphics{Module_3B_GLMMs_files/figure-pdf/unnamed-chunk-3-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection*{Covariance Structures in Hierarchical
GLMMs}\label{covariance-structures-in-hierarchical-glmms}
\addcontentsline{toc}{subsection}{Covariance Structures in Hierarchical
GLMMs}

For the \textbf{three-level linear mixed model}:

\[
\begin{aligned}
math_{ijk} &\sim \text{Normal}(\mu_{ijk}, \sigma^2), \\
\mu_{ijk} &= \beta_0 + u_i + u_{ij} + \beta_1' x_{ijk} + \beta_2' x_{ij} + \beta_3' x_i, \\
u_i &\sim N(0, \nu^2), \quad u_{ij} \sim N(0, \tau^2),
\end{aligned}
\]

where:

\begin{itemize}
\tightlist
\item
  \(u_i\) is the \textbf{school-level random intercept},
\item
  \(u_{ij}\) is the \textbf{student-level random intercept} (nested
  within school \(i\)),
\item
  \(\sigma^2\) is the residual (Level 1) variance for observations
  within a student.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\paragraph*{Conditional Variance}\label{conditional-variance}
\addcontentsline{toc}{paragraph}{Conditional Variance}

Conditioned on the random effects \(u_i\) and \(u_{ij}\), the
distribution of \(math_{ijk}\) is:

\[
math_{ijk}|u_i, u_{ij} \sim N(\mu_{ijk}, \sigma^2)
\]

where \(\mu_{ijk}\) is the linear predictor: \[
E(math_{ijk}|u_i, u_{ij}) = \mu_{ijk} = \beta_0 + \beta^{(1)'} x_{ijk} + \beta^{(2)'} x_{ij} + u_i + u_{ij},
\] and \[
Var(math_{ijk} \mid u_i, u_{ij}) = \sigma^2,
\]

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-tip-color-frame, breakable, left=2mm, colback=white, bottomrule=.15mm, arc=.35mm, opacityback=0, rightrule=.15mm, toprule=.15mm, leftrule=.75mm]

\vspace{-3mm}\textbf{Derivation of conditional variance}\vspace{3mm}

Conditioned on the random effects \(u_i\) and \(u_{ij}\), we can write:
\[
math_{ijk} \mid u_i, u_{ij} = \mu_{ijk} + \epsilon_{ijk}.
\]

Since \(\mu_{ijk}\) is treated as fixed once we condition on \(u_i\) and
\(u_{ij}\), the only remaining random component is \(\epsilon_{ijk}\).
Therefore: \[
\begin{aligned}
Var(math_{ijk} \mid u_i, u_{ij}) 
&= Var(\mu_{ijk} + \epsilon_{ijk} \mid u_i, u_{ij}) \\
&= Var(\epsilon_{ijk}) \\
&= \sigma^2.
\end{aligned}
\]

\end{tcolorbox}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\paragraph*{Total Variance}\label{total-variance}
\addcontentsline{toc}{paragraph}{Total Variance}

This variance \(\sigma^2\) describes the \textbf{Level 1 variability
(within-student, across years)}, assuming the random effects \(u_i\) and
\(u_{ij}\) are fixed.

The \textbf{total variability} in \(math_{ijk}\) can be decomposed into:

\[
Var(math_{ijk}) = \nu^2 + \tau^2 + \sigma^2,
\]

where:

\begin{itemize}
\tightlist
\item
  \(\nu^2\) reflects \textbf{between-school variability},
\item
  \(\tau^2\) reflects \textbf{between-student variability (within
  school)},
\item
  \(\sigma^2\) reflects \textbf{within-student residual variability}.
\end{itemize}

\begin{tcolorbox}[enhanced jigsaw, colframe=quarto-callout-tip-color-frame, breakable, left=2mm, colback=white, bottomrule=.15mm, arc=.35mm, opacityback=0, rightrule=.15mm, toprule=.15mm, leftrule=.75mm]

\vspace{-3mm}\textbf{Derivation of Total Variance}\vspace{3mm}

For the three-level linear mixed model: \[
math_{ijk} = \beta_0 + \beta_1 \, year_{ijk} + \cdots + u_i + u_{ij} + \epsilon_{ijk},
\] we assume: \[
u_i \sim N(0, \nu^2), \quad u_{ij} \sim N(0, \tau^2), \quad \epsilon_{ijk} \sim N(0, \sigma^2),
\] with all random components \textbf{mutually independent}.

We want to show that: \[
Var(math_{ijk}) = \nu^2 + \tau^2 + \sigma^2.
\]

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Step 1: Apply the Law of Total
Variance}\label{step-1-apply-the-law-of-total-variance}
\addcontentsline{toc}{subsubsection}{Step 1: Apply the Law of Total
Variance}

The law of total variance states: \[
Var(Y) = E[Var(Y \mid U)] + Var(E[Y \mid U]),
\] where \(U\) represents any random variables we are conditioning on.

In our case, we condition on both \(u_i\) and \(u_{ij}\): \[
Var(math_{ijk}) = E[Var(math_{ijk} \mid u_i, u_{ij})] + Var(E[math_{ijk} \mid u_i, u_{ij}]).
\]

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Step 2: Compute the Conditional
Variance}\label{step-2-compute-the-conditional-variance}
\addcontentsline{toc}{subsubsection}{Step 2: Compute the Conditional
Variance}

From the model: \[
math_{ijk} \mid u_i, u_{ij} = \mu_{ijk} + \epsilon_{ijk},
\] where
\(\mu_{ijk} = \beta_0 + \beta_1 \, year_{ijk} + \cdots + u_i + u_{ij}\).

Conditioned on \(u_i\) and \(u_{ij}\), the only random term is
\(\epsilon_{ijk}\), so: \[
Var(math_{ijk} \mid u_i, u_{ij}) = Var(\epsilon_{ijk}) = \sigma^2.
\] Therefore: \[
E[Var(math_{ijk} \mid u_i, u_{ij})] = \sigma^2.
\]

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Step 3: Compute the Variance of the Conditional
Expectation}\label{step-3-compute-the-variance-of-the-conditional-expectation}
\addcontentsline{toc}{subsubsection}{Step 3: Compute the Variance of the
Conditional Expectation}

The conditional expectation is: \[
E[math_{ijk} \mid u_i, u_{ij}] = \mu_{ijk} = \beta_0 + \beta_1 \, year_{ijk} + \cdots + u_i + u_{ij}.
\]

The fixed terms \(\beta_0 + \beta_1 \, year_{ijk} + \cdots\) have no
variance, so: \[
Var(E[math_{ijk} \mid u_i, u_{ij}]) = Var(u_i + u_{ij}) = Var(u_i) + Var(u_{ij}),
\] because \(u_i\) and \(u_{ij}\) are independent. Thus: \[
Var(E[math_{ijk} \mid u_i, u_{ij}]) = \nu^2 + \tau^2.
\]

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Step 4: Combine Results}\label{step-4-combine-results}
\addcontentsline{toc}{subsubsection}{Step 4: Combine Results}

Putting it all together: \[
Var(math_{ijk}) = E[Var(math_{ijk} \mid u_i, u_{ij})] + Var(E[math_{ijk} \mid u_i, u_{ij}])
= \sigma^2 + (\nu^2 + \tau^2)
= \nu^2 + \tau^2 + \sigma^2.
\]

\end{tcolorbox}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection*{Conditional vs.~Marginal
Covariance}\label{conditional-vs.-marginal-covariance}
\addcontentsline{toc}{subsubsection}{Conditional vs.~Marginal
Covariance}

For two observations \(math_{ijk}\) and \(math_{ijk'}\) from the
\textbf{same student} \(j\) in the \textbf{same school} \(i\): \[
Cov(math_{ijk}, math_{ijk'} \mid u_i, u_{ij}) = 0,
\] because, conditioned on \(u_i\) and \(u_{ij}\), the residual errors
\(\epsilon_{ijk}\) are independent.

However, the \textbf{marginal covariance} (after integrating over the
random effects) is: \[
Cov(math_{ijk}, math_{ijk'}) = \nu^2 + \tau^2,
\] since both observations share \(u_i\) (school effect) and \(u_{ij}\)
(student effect).

For two students \(j \neq j'\) in the \textbf{same school} \(i\): \[
Cov(math_{ijk}, math_{ij'k'}) = \nu^2,
\] because they share only the school effect \(u_i\).

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection*{Intraclass Correlation Coefficients
(ICC)}\label{intraclass-correlation-coefficients-icc}
\addcontentsline{toc}{subsection}{Intraclass Correlation Coefficients
(ICC)}

The total variance of \(math_{ijk}\) is: \[
Var(math_{ijk}) = \nu^2 + \tau^2 + \sigma^2.
\]

The \textbf{school-level intraclass correlation (ICC)}, which measures
the proportion of variance explained by differences between schools, is:
\[
ICC_{\text{school}} = \frac{\nu^2}{\nu^2 + \tau^2 + \sigma^2}.
\]

The \textbf{student-level ICC (within a school)} is: \[
ICC_{\text{student}} = \frac{\nu^2 + \tau^2}{\nu^2 + \tau^2 + \sigma^2}.
\]

These ICCs quantify how strongly scores are correlated for students
within the same school or the same student across multiple years.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection*{Hierarchical GLMM Fitting in
R}\label{hierarchical-glmm-fitting-in-r}
\addcontentsline{toc}{subsection}{Hierarchical GLMM Fitting in R}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load required package}
\FunctionTok{library}\NormalTok{(lme4)}

\CommentTok{\# Fit the 3{-}level LMM}
\CommentTok{\# math \textasciitilde{} fixed effects + (1 | school/child) fits random intercepts for school and child}
\NormalTok{lmm\_3level }\OtherTok{\textless{}{-}} \FunctionTok{lmer}\NormalTok{(}
\NormalTok{  math }\SpecialCharTok{\textasciitilde{}}\NormalTok{ year }\SpecialCharTok{+}\NormalTok{ female }\SpecialCharTok{+}\NormalTok{ black }\SpecialCharTok{+}\NormalTok{ hispanic }\SpecialCharTok{+}\NormalTok{ retained }\SpecialCharTok{+} 
\NormalTok{    (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ school}\SpecialCharTok{/}\NormalTok{child),  }\CommentTok{\# child is nested within school}
  \AttributeTok{data =}\NormalTok{ dat}
\NormalTok{)}

\CommentTok{\# Display model summary}
\FunctionTok{summary}\NormalTok{(lmm\_3level)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Linear mixed model fit by REML ['lmerMod']
Formula: 
math ~ year + female + black + hispanic + retained + (1 | school/child)
   Data: dat

REML criterion at convergence: 16699.2

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.8443 -0.5854 -0.0272  0.5588  6.1663 

Random effects:
 Groups       Name        Variance Std.Dev.
 child:school (Intercept) 0.6638   0.8148  
 school       (Intercept) 0.1292   0.3594  
 Residual                 0.3445   0.5870  
Number of obs: 7230, groups:  child:school, 1721; school, 60

Fixed effects:
              Estimate Std. Error t value
(Intercept) -3.477e-01  8.095e-02  -4.295
year         7.483e-01  5.396e-03 138.677
female       8.850e-06  4.226e-02   0.000
black       -6.235e-01  7.873e-02  -7.919
hispanic    -3.636e-01  8.813e-02  -4.125
retained     1.487e-01  3.536e-02   4.207

Correlation of Fixed Effects:
         (Intr) year   female black  hispnc
year     -0.020                            
female   -0.264 -0.005                     
black    -0.691 -0.004 -0.003              
hispanic -0.515 -0.009  0.019  0.519       
retained -0.020  0.086  0.017 -0.015 -0.007
\end{verbatim}

\subsection*{Model Interpretations}\label{model-interpretations}
\addcontentsline{toc}{subsection}{Model Interpretations}

\subsubsection*{Random Effects}\label{random-effects-1}
\addcontentsline{toc}{subsubsection}{Random Effects}

\begin{itemize}
\item
  \textbf{School-level variance (}\(\nu^2 = 0.1292\)):\\
  Differences between schools account for some variation in math scores
  (Std. Dev. = 0.359).\\
  This suggests that students from different schools start at different
  baseline math levels.
\item
  \textbf{Student-level variance (}\(\tau^2 = 0.6638\)):\\
  Differences between students (within schools) account for a larger
  portion of variability (Std. Dev. = 0.815), indicating substantial
  heterogeneity across students.
\item
  \textbf{Residual variance (}\(\sigma^2 = 0.3445\)):\\
  Variation in math scores within the same student (across years) after
  accounting for predictors is 0.3445 (Std. Dev. = 0.587).
\item
  \textbf{Number of groups:}\\
  There are 60 schools and 1,721 students across 7,230 total
  observations.
\end{itemize}

\subsubsection*{Fixed Effects}\label{fixed-effects-1}
\addcontentsline{toc}{subsubsection}{Fixed Effects}

\begin{itemize}
\item
  \textbf{Intercept (-0.348):}\\
  The expected math score for a reference student (male, non-Black,
  non-Hispanic, not retained) in year 0 is -0.35 (on the standardized
  scale).
\item
  \textbf{Year (0.748):}\\
  On average, math scores increase by 0.748 units per year,
  \textbf{holding all other factors constant}.\\
  This is a \textbf{strong positive trend} over time (t = 138.7).
\item
  \textbf{Female (0.00001):}\\
  The coefficient for being female is nearly zero (and not statistically
  significant).
\item
  \textbf{Black (-0.623):}\\
  Black students have an average math score 0.62 units lower than
  non-Black students, holding other variables constant (t = -7.92).
\item
  \textbf{Hispanic (-0.364):}\\
  Hispanic students have an average math score 0.36 units lower than
  non-Hispanic students (t = -4.13).
\item
  \textbf{Retained (0.149):}\\
  Students who were retained (repeated a grade) have math scores
  approximately 0.15 units higher than otherwise similar students (t =
  4.21). This may reflect additional time or intervention effects.
\end{itemize}

We can calculate ICCs directly from the variance components of the
model:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Extract variance components}
\NormalTok{vc }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{VarCorr}\NormalTok{(lmm\_3level))}

\CommentTok{\# Variance components}
\NormalTok{var\_school  }\OtherTok{\textless{}{-}}\NormalTok{ vc[vc}\SpecialCharTok{$}\NormalTok{grp }\SpecialCharTok{==} \StringTok{"school"}\NormalTok{, }\StringTok{"vcov"}\NormalTok{]         }\CommentTok{\# ν² (between schools)}
\NormalTok{var\_child   }\OtherTok{\textless{}{-}}\NormalTok{ vc[vc}\SpecialCharTok{$}\NormalTok{grp }\SpecialCharTok{==} \StringTok{"child:school"}\NormalTok{, }\StringTok{"vcov"}\NormalTok{]   }\CommentTok{\# τ² (between students within schools)}
\NormalTok{var\_resid  }\OtherTok{\textless{}{-}}\NormalTok{ vc[vc}\SpecialCharTok{$}\NormalTok{grp }\SpecialCharTok{==} \StringTok{"Residual"}\NormalTok{, }\StringTok{"vcov"}\NormalTok{]      }\CommentTok{\# σ² (within students)}

\CommentTok{\# Total variance}
\NormalTok{var\_total }\OtherTok{\textless{}{-}}\NormalTok{ var\_school }\SpecialCharTok{+}\NormalTok{ var\_child }\SpecialCharTok{+}\NormalTok{ var\_resid}

\CommentTok{\# ICCs}
\NormalTok{ICC\_school  }\OtherTok{\textless{}{-}}\NormalTok{ var\_school }\SpecialCharTok{/}\NormalTok{ var\_total}
\NormalTok{ICC\_student }\OtherTok{\textless{}{-}}\NormalTok{ (var\_school }\SpecialCharTok{+}\NormalTok{ var\_child) }\SpecialCharTok{/}\NormalTok{ var\_total}

\NormalTok{ICC\_school}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 0.113578
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ICC\_student}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 0.6971433
\end{verbatim}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{\texorpdfstring{\textcolor{purple}{Summary}}{}}\label{section-17}
\addcontentsline{toc}{section}{\textcolor{purple}{Summary}}

\markright{\textcolor{purple}{Summary}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.5952}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.4048}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Section}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Description}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{What is the model?} & A \textbf{three-level hierarchical linear
model} extends linear regression to account for \textbf{nested data
structures}---specifically, \textbf{years within students}, and
\textbf{students within schools}. The model includes two random
intercepts: \(y_{ijk} = X_{ijk}\beta + u_i + u_{ij} + \epsilon_{ijk}\),
where \(u_i \sim N(0, \nu^2)\) and \(u_{ij} \sim N(0, \tau^2)\). \\
\textbf{Motivation} & Hierarchical or \textbf{multilevel data} violate
the independence assumption of standard linear models. Ignoring the
nesting---repeated years per student, students within schools---leads to
\textbf{underestimated standard errors} and \textbf{biased inference}.
Hierarchical models account for this by modeling \textbf{correlated
errors at each level}. \\
\textbf{Model Components} & \textbf{Level 1:} residual error
\(\epsilon_{ijk} \sim N(0, \sigma^2)\) \textbf{Level 2:} student-level
random intercept \(u_{ij} \sim N(0, \tau^2)\) \textbf{Level 3:}
school-level random intercept \(u_i \sim N(0, \nu^2)\) The systematic
component is: \(\mu_{ijk} = \beta_0 + X_{ijk} \beta + u_i + u_{ij}\) \\
\textbf{Hierarchical Partial Pooling} & The model performs
\textbf{partial pooling} across both schools and students. -
\textbf{School-level:}
\(\hat{\mu}_i^{\text{partial}} = w_i \bar{y}_i + (1 - w_i)\bar{y}\) with
\(w_i = \frac{n_i}{n_i + \frac{\sigma^2}{\nu^2}}\) -
\textbf{Student-level:}
\(\hat{u}_{ij}^{\text{partial}} = w_{ij} (\bar{y}_{ij} - \bar{y}_i)\)
with \(w_{ij} = \frac{n_{ij}}{n_{ij} + \frac{\sigma^2}{\tau^2}}\) \\
\textbf{Likelihood} & The likelihood reflects \textbf{two nested levels
of integration over random effects}:
\(L(\beta, \nu^2, \tau^2 \mid y) = \prod_i \int \prod_j \int \prod_k p(y_{ijk} \mid u_i, u_{ij}) \, p(u_{ij}) \, du_{ij} \, p(u_i) \, du_i\)
Estimated using \textbf{REML} (frequentist) or \textbf{MCMC} (Bayesian)
methods. \\
\textbf{Interpretation} & - \textbf{Fixed effects (\(\beta\)):} average
effects across all observations (e.g., year, race, gender) -
\textbf{Random effects (\(u_i\), \(u_{ij}\)):} group-specific deviations
- \textbf{Variance components:} \(\nu^2\) (school), \(\tau^2\)
(student), \(\sigma^2\) (within-student error) \\
\textbf{Model Diagnostics} & - \textbf{ICC (school):}
\(ICC_{\text{school}} = \frac{\nu^2}{\nu^2 + \tau^2 + \sigma^2}\) -
\textbf{ICC (student):}
\(ICC_{\text{student}} = \frac{\nu^2 + \tau^2}{\nu^2 + \tau^2 + \sigma^2}\)
ICCs quantify clustering at each level. \\
\textbf{Example (School Math Scores)} & Fitted model:
\(math_{ijk} = \beta_0 + \beta_1 \cdot year_{ijk} + \cdots + u_i + u_{ij} + \epsilon_{ijk}\)
- \textbf{Between-school SD:} 0.359 - \textbf{Between-student SD:} 0.815
- \textbf{Residual SD:} 0.587 These values reflect variability at each
level of the hierarchy. \\
\end{longtable}

\bookmarksetup{startatroot}

\chapter*{Module 3 Cheat Sheet}\label{module-3-cheat-sheet}
\addcontentsline{toc}{chapter}{Module 3 Cheat Sheet}

\markboth{Module 3 Cheat Sheet}{Module 3 Cheat Sheet}

\bookmarksetup{startatroot}

\chapter*{Overview}\label{overview-2}
\addcontentsline{toc}{chapter}{Overview}

\markboth{Overview}{Overview}

\textbf{Module 3} covers:

\begin{itemize}
\tightlist
\item
  \textbf{3A:} Generalized Linear Mixed Models (GLMMs) for non-normal
  data with clustering.
\item
  \textbf{3B:} Hierarchical (Multilevel) Models for nested data
  structures.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\bookmarksetup{startatroot}

\chapter*{Module 3A: Generalized Linear Mixed Models
(GLMMs)}\label{module-3a-generalized-linear-mixed-models-glmms}
\addcontentsline{toc}{chapter}{Module 3A: Generalized Linear Mixed
Models (GLMMs)}

\markboth{Module 3A: Generalized Linear Mixed Models (GLMMs)}{Module 3A:
Generalized Linear Mixed Models (GLMMs)}

\section*{Motivation and Examples}\label{motivation-and-examples-4}
\addcontentsline{toc}{section}{Motivation and Examples}

\markright{Motivation and Examples}

In many real-world datasets, observations are \textbf{non-normal} and
\textbf{not independent}. For example: - Repeated measurements on the
same subject. - Clusters of data within counties, hospitals, or schools.
- Panel data where observations are grouped by time or region.

\textbf{Why can't we use standard GLMs?} - A standard GLM assumes
independent observations. When data are clustered, this assumption is
violated, leading to \textbf{biased standard errors} and
\textbf{incorrect inference}. - To address this, \textbf{Generalized
Linear Mixed Models (GLMMs)} extend GLMs by including \textbf{random
effects} that account for within-group correlation and unobserved
heterogeneity.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{GLMM Model Structure}\label{glmm-model-structure}
\addcontentsline{toc}{section}{GLMM Model Structure}

\markright{GLMM Model Structure}

For observation \(j\) in group \(i\): \[
g(E[y_{ij} \mid     \theta_i]) = \beta_0 + x_{ij}' \beta +  \theta_i,
\] where: - \(g(\cdot)\) is a link function (e.g., logit or log). - \$
\theta\_i \sim N(0, \tau\^{}2)\$ is the random intercept.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Likelihood in GLMMs}\label{likelihood-in-glmms}
\addcontentsline{toc}{section}{Likelihood in GLMMs}

\markright{Likelihood in GLMMs}

The joint likelihood is: \[
L(\beta,    \tau^2 | y) = \prod_{i=1}^n \int \left( \prod_{j=1}^{r_i} [y_{ij} |     \theta_i] 
\right) [   \theta_i] \, d  \theta_i.
\] This integral is approximated numerically (e.g., Laplace
approximation).

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Example: Logistic GLMM}\label{example-logistic-glmm}
\addcontentsline{toc}{section}{Example: Logistic GLMM}

\markright{Example: Logistic GLMM}

\[
logit P(y_{ij}=1) = \beta_0 + \beta_1 \, \text{trt}_{ij} + \beta_2 \, \text{period}_{ij} + \beta_3 (\text{trt}\times \text{period})_{ij} + \theta_i,
\] where \(\theta_i \sim N(0, \tau^2)\).

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Example: Poisson GLMM}\label{example-poisson-glmm}
\addcontentsline{toc}{section}{Example: Poisson GLMM}

\markright{Example: Poisson GLMM}

\[
y_i \sim \text{Poisson}(\lambda_i), \quad \log(\lambda_i) = \beta_0 + x_i' \beta + u_i.
\]

\begin{itemize}
\tightlist
\item
  \(e^{\beta_j}\) = \textbf{Incidence Rate Ratio (IRR)}.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\bookmarksetup{startatroot}

\chapter*{Module 3B: Hierarchical (Multilevel)
Models}\label{module-3b-hierarchical-multilevel-models}
\addcontentsline{toc}{chapter}{Module 3B: Hierarchical (Multilevel)
Models}

\markboth{Module 3B: Hierarchical (Multilevel) Models}{Module 3B:
Hierarchical (Multilevel) Models}

\section*{Motivation}\label{motivation-4}
\addcontentsline{toc}{section}{Motivation}

\markright{Motivation}

\textbf{Hierarchical} or \textbf{multilevel} models are used when
observations are nested (e.g., years within students, students within
schools).\\
Ignoring clustering leads to \textbf{underestimated standard errors} and
\textbf{biased inference}.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Three-Level Linear Mixed
Model}\label{three-level-linear-mixed-model}
\addcontentsline{toc}{section}{Three-Level Linear Mixed Model}

\markright{Three-Level Linear Mixed Model}

\[
\begin{aligned}
math_{ijk} & \sim N(\mu_{ijk}, \sigma^2), \\
\mu_{ijk} & = \beta_0 + \beta_1 \, year_{ijk} + \beta_2 \, female_{ij} + \beta_3 \, black_{ij} + \beta_4 \, hispanic_{ij} + \beta_5 \, retained_{ij} + u_i + u_{ij},
\end{aligned}
\] where: - \(u_i \sim N(0, \nu^2)\) (school-level random intercept), -
\(u_{ij} \sim N(0, \tau^2)\) (student-level random intercept), -
\(\epsilon_{ijk} \sim N(0, \sigma^2)\) (residual).

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Partial Pooling}\label{partial-pooling}
\addcontentsline{toc}{section}{Partial Pooling}

\markright{Partial Pooling}

\textbf{School-level:} \[
\hat{\mu}_i^{\text{partial}} = w_i \bar{y}_i + (1 - w_i) \bar{y}, \quad w_i = \frac{n_i}{n_i + \frac{\sigma^2}{\nu^2}}.
\]

\textbf{Student-level (within schools):} \[
\hat{u}_{ij}^{\text{partial}} = w_{ij} (\bar{y}_{ij} - \bar{y}_i), \quad w_{ij} = \frac{n_{ij}}{n_{ij} + \frac{\sigma^2}{\tau^2}}.
\]

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Variance Decomposition and
ICC}\label{variance-decomposition-and-icc}
\addcontentsline{toc}{section}{Variance Decomposition and ICC}

\markright{Variance Decomposition and ICC}

\[
Var(math_{ijk}) = \nu^2 + \tau^2 + \sigma^2.
\]

\begin{itemize}
\item
  \textbf{School-level ICC:}\\
  \[ ICC_{\text{school}} = \frac{\nu^2}{\nu^2 + \tau^2 + \sigma^2}. \]
\item
  \textbf{Student-level ICC:}\\
  \[ ICC_{\text{student}} = \frac{\nu^2 + \tau^2}{\nu^2 + \tau^2 + \sigma^2}. \]
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\bookmarksetup{startatroot}

\chapter*{Summary}\label{summary}
\addcontentsline{toc}{chapter}{Summary}

\markboth{Summary}{Summary}

\begin{itemize}
\tightlist
\item
  \textbf{GLMMs (3A)}: Handle \textbf{non-normal responses} (e.g.,
  binary, count) with random effects.
\item
  \textbf{Hierarchical Models (3B)}: Extend LMMs for \textbf{multi-level
  nesting} (e.g., students within schools).
\item
  \textbf{Partial pooling} and \textbf{ICCs} quantify and interpret
  clustering.
\end{itemize}




\end{document}
