<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>BIOS 526 Modern Regression Analysis - Module 6 Model Selection, Diagnostics, &amp; Regression Workflow</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Module_5_GAM_Cheat.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Module_6_workflow.html">Module 6 Model Selection, Diagnostics, &amp; Regression Workflow</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">BIOS 526 Modern Regression Analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_0_MLR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 0: Multiple Linear Regression Review</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1A_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1A Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1B_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1B Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1C_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1C Random Intercepts and Slopes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1_LMM_Cheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2A_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2A Generalized Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2B_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2B Generalized Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2C_GLMMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2C Generalized Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2D_GLMMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2D Generalized Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2_GLM_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3A_GEEs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3A Marginal Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3B_GEEs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3B Marginal Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3_GEE_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4A_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4A Basis Expansion and Parametric Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4B_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4B Parametric Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4C_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4C Penalized Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4_Splines_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5A_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5A Generalized Additive Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5B_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5B Generalized Additive Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5_GAM_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_6_workflow.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Module 6 Model Selection, Diagnostics, &amp; Regression Workflow</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#motivation-and-examples" id="toc-motivation-and-examples" class="nav-link active" data-scroll-target="#motivation-and-examples">Motivation and Examples</a></li>
  <li><a href="#define-the-estimand" id="toc-define-the-estimand" class="nav-link" data-scroll-target="#define-the-estimand"><span style="color: purple;">1. Define the Estimand</span></a>
  <ul class="collapse">
  <li><a href="#the-estimand" id="toc-the-estimand" class="nav-link" data-scroll-target="#the-estimand"><span style="color: green;">The Estimand</span></a></li>
  <li><a href="#why-defining-the-estimand-matters" id="toc-why-defining-the-estimand-matters" class="nav-link" data-scroll-target="#why-defining-the-estimand-matters"><span style="color: green;">Why Defining the Estimand Matters</span></a></li>
  <li><a href="#common-pitfalls" id="toc-common-pitfalls" class="nav-link" data-scroll-target="#common-pitfalls"><span style="color: green;">Common Pitfalls</span></a></li>
  <li><a href="#definition-of-the-estimand-our-example" id="toc-definition-of-the-estimand-our-example" class="nav-link" data-scroll-target="#definition-of-the-estimand-our-example"><span style="color: green;">Definition of the Estimand (Our Example)</span></a></li>
  </ul></li>
  <li><a href="#data-structure" id="toc-data-structure" class="nav-link" data-scroll-target="#data-structure"><span style="color: purple;">2. Data Structure</span></a>
  <ul class="collapse">
  <li><a href="#independent-structure" id="toc-independent-structure" class="nav-link" data-scroll-target="#independent-structure"><span style="color: green;">Independent Structure?</span></a></li>
  <li><a href="#marginal-distributions" id="toc-marginal-distributions" class="nav-link" data-scroll-target="#marginal-distributions"><span style="color: green;">Marginal Distributions</span></a></li>
  <li><a href="#exploring-associations" id="toc-exploring-associations" class="nav-link" data-scroll-target="#exploring-associations"><span style="color: green;">Exploring Associations</span></a></li>
  </ul></li>
  <li><a href="#build-an-analysis-plan" id="toc-build-an-analysis-plan" class="nav-link" data-scroll-target="#build-an-analysis-plan"><span style="color: purple;">Build an Analysis Plan</span></a>
  <ul class="collapse">
  <li><a href="#choosing-the-baseline-model" id="toc-choosing-the-baseline-model" class="nav-link" data-scroll-target="#choosing-the-baseline-model"><span style="color: green;">1. Choosing the baseline model</span></a></li>
  <li><a href="#anticipating-nonlinearity" id="toc-anticipating-nonlinearity" class="nav-link" data-scroll-target="#anticipating-nonlinearity"><span style="color: green;">2. Anticipating nonlinearity</span></a></li>
  <li><a href="#pre-specifying-diagnostics" id="toc-pre-specifying-diagnostics" class="nav-link" data-scroll-target="#pre-specifying-diagnostics"><span style="color: green;">3. Pre-specifying diagnostics</span></a></li>
  </ul></li>
  <li><a href="#final-deliverables" id="toc-final-deliverables" class="nav-link" data-scroll-target="#final-deliverables"><span style="color: purple;">4. Final Deliverables</span></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Module 6 Model Selection, Diagnostics, &amp; Regression Workflow</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><strong>Objective</strong></p>
<p>After completing this module, students will be able to (1) define an estimand clearly, (2) identify dependence structures in clustered data, (3) fit and diagnose linear mixed models, (4) identify nonlinearity and incorporate spline smooths, (5) use diagnostics to guide model refinement, and (6) produce a complete model-building workflow and final report.</p>
<section id="motivation-and-examples" class="level3">
<h3 class="anchored" data-anchor-id="motivation-and-examples">Motivation and Examples</h3>
<div class="callout callout-style-default callout-important callout-titled" style="color: red">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Motivation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Why develop a workflow?</p>
<p>Modules 1–5 introduced the major families of regression models—linear models, generalized linear models, mixed models, GEEs, splines, and GAMs. Each module focused on one modeling framework at a time. But <strong>real statistical analysis does not proceed one module at a time.</strong></p>
<p>In real applications, analysts begin with a scientific question, explore the data, build an initial model, diagnose its limitations, and then iteratively refine the model until they reach a defensible, interpretable representation of the data-generating process.</p>
<p>This requires a workflow—a structured sequence of decisions that guides model building, model checking, and model improvement.</p>
<p>A workflow answers the following questions:</p>
<ol type="1">
<li><p>What we are trying to estimate?</p></li>
<li><p>Why we chose a particular modeling strategy?</p></li>
<li><p>How we checked whether that strategy was reasonable?</p></li>
<li><p>How we refined the model when diagnostics suggested problems?</p></li>
<li><p>How we visualized and communicated the final result?</p></li>
</ol>
<p>The best guiding principle is simple but powerful:</p>
<p><span style="color: blue;">Start with the simplest plausible model and build complexity only as needed.</span></p>
</div>
</div>
<p>To ground the workflow in a concrete setting, we turn to a more realistic dataset drawn from gestational-age birth records. The dataset includes:</p>
<ul>
<li><p><strong><code>gw</code></strong>: gestational age (weeks),</p></li>
<li><p><strong><code>age</code></strong>: maternal age at delivery (years),</p></li>
<li><p><strong><code>bw</code></strong>: birthweight (grams).</p></li>
<li><p><strong><code>child_id</code></strong>: Infant unique id.</p></li>
<li><p><strong><code>mother_id</code></strong>: Mother unique id.</p></li>
</ul>
<p>These variables allow us to examine clinically relevant relationships between maternal characteristics and neonatal outcomes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>gabirths <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"/Users/emilypeterson/Library/CloudStorage/OneDrive-EmoryUniversity/BIOS 526/BIOS526_Book/data/GAbirth_full.RDS"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(gabirths)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  gw age   bw child_id mother_id
1 41  33 3540        1     M2211
2 38  23 3287        2     M3362
3 39  36 3438        3      M925
4 40  30 3419        4     M1613
5 40  26 3278        5     M1492
6 38  18 3100        6      M323</code></pre>
</div>
</div>
<p>A common workflow looks like this:</p>
<p><strong>Step 1 — Define the Estimand</strong></p>
<p><strong>Step 2 — EDA: Explore the Data Structure</strong></p>
<p><strong>Step 3 — Build an Analysis Plan</strong></p>
<p><strong>Step 4 — Baseline Model</strong></p>
<p><strong>Step 5 — Specify Diagnostics</strong></p>
<p><strong>Step 6 — Extend the Workflow</strong></p>
<p><strong>Step 7 — Visualization and Communication</strong></p>
</section>
<section id="define-the-estimand" class="level2">
<h2 class="anchored" data-anchor-id="define-the-estimand"><span style="color: purple;">1. Define the Estimand</span></h2>
<p>Before touching a model, we need to get clarity on <strong>the estimand:</strong> what quantity we ultimately want to estimate (what is the scientific question we want to answer?)</p>
<section id="the-estimand" class="level3">
<h3 class="anchored" data-anchor-id="the-estimand"><span style="color: green;">The Estimand</span></h3>
<p>Before fitting any model, we must define the&nbsp;<strong>estimand</strong>—the target quantity we aim to learn from the data. The estimand is not the model and not the estimator; it is the underlying population quantity that our chosen method will approximate.</p>
<p>Different modeling strategies—ordinary least squares, spline-based GAMs, linear mixed models, or GEEs—can all be viewed as alternative approaches to estimating the same function <span class="math inline">\(m(gw,age) = E[bw|age, gw]\)</span> under different assumptions about linearity, smoothness, and correlation.</p>
<p>Being explicit about the estimand serves several purposes. It clarifies which variables must enter the model as predictors or adjustment factors, keeps the scientific question distinct from the modeling tools we use, and provides a stable reference point as we progress from simpler to more flexible models.</p>
<p><span style="color: gray;">In the workflow that follows, every modeling decision—choice of link, inclusion of random effects, introduction of splines or tensor-product smooths—will be justified in terms of how well the resulting model approximates this estimand, i.e., the conditional mean function.</span></p>
<hr>
</section>
<section id="why-defining-the-estimand-matters" class="level3">
<h3 class="anchored" data-anchor-id="why-defining-the-estimand-matters"><span style="color: green;">Why Defining the Estimand Matters</span></h3>
<p>A clearly stated estimand serves several purposes:</p>
<ol type="1">
<li><p>It guides the choice of modeling strategy. Once the estimand is defined, the set of appropriate models becomes clear. If the goal is the conditional mean, linear or generalized linear models are natural starting points. If the goal shifts to conditional quantiles, the entire modeling framework changes.</p></li>
<li><p>It determines which covariates must be included. The estimand dictates the role of each variable—whether maternal age, for example, should be treated as an adjustment factor, a confounder, or a predictor of primary scientific interest.</p></li>
<li><p>It provides a stable reference point across modeling approaches. Different estimators (e.g., OLS, GAMs, or LMMs) may be used to approximate the relationship, but the underlying estimand remains fixed. This allows the analyst to compare models and refine the specification without losing sight of the scientific target.</p></li>
</ol>
<hr>
</section>
<section id="common-pitfalls" class="level3">
<h3 class="anchored" data-anchor-id="common-pitfalls"><span style="color: green;">Common Pitfalls</span></h3>
<ol type="1">
<li><p><strong>Confusing the estimand with the estimator.</strong> “We want to fit a GAM” is not a scientific question; it is a modeling choice. The estimand must be defined before selecting a model.</p></li>
<li><p><strong>Defining the estimand after examining the data.</strong> Allowing the data to determine the estimand blurs the boundary between inference and exploration.</p></li>
<li><p><strong>Using an estimand that is too vague.</strong> Statements such as “We want to understand the effect of gestational age” are incomplete unless the scale, population, and conditioning variables are specified.</p></li>
<li><p>The estimand does not change regardless of model approach; only the estimator changes.</p></li>
</ol>
<hr>
</section>
<section id="definition-of-the-estimand-our-example" class="level3">
<h3 class="anchored" data-anchor-id="definition-of-the-estimand-our-example"><span style="color: green;">Definition of the Estimand (Our Example)</span></h3>
<p>In our example, we are interested in how infant birthweight varies with gestational age and maternal age. A natural target is the&nbsp;<strong>conditional mean birthweight</strong>&nbsp;as a function of these predictors. Here we define <span class="math inline">\(m(.)\)</span> as</p>
<p><span class="math display">\[
m(gw,age)=E[bw∣gw,age],
\]</span></p>
<p>which describes how expected birthweight changes across gestational age while holding maternal age fixed (or vice versa).</p>
<p>This estimand is&nbsp;<u><strong>population-level</strong></u>: it represents the mean birthweight in the target population of births, not the average birthweight within a given mother.</p>
<hr>
</section>
</section>
<section id="data-structure" class="level2">
<h2 class="anchored" data-anchor-id="data-structure"><span style="color: purple;">2. Data Structure</span></h2>
<p>With the estimand defined, the next step is to understand the structure of the data that will inform it. Exploratory Data Analysis (EDA) serves two purposes:</p>
<ol type="1">
<li><p><strong>To learn how the observed data relate to the estimand</strong>, and</p></li>
<li><p><strong>To diagnose the modeling challenges that will arise later</strong><br>
(nonlinearity, skewness, clustering, outliers, heteroskedasticity, etc.).</p></li>
</ol>
<p>EDA is not a formal model, but it shapes every modeling decision that follows.</p>
<hr>
<section id="independent-structure" class="level3">
<h3 class="anchored" data-anchor-id="independent-structure"><span style="color: green;">Independent Structure?</span></h3>
<p><strong>Are the observations independent?</strong></p>
<p>If multiple infants share the same mother, then the birthweights of siblings may be correlated due to genetics, shared environment, or maternal health factors. Independence assumptions underlying OLS or GLM may therefore be violated. Before choosing any model, we inspect how the data are organized.</p>
<p>This simple summary helps determine whether we should consider mixed models (Module 1), GEEs (Module 3), or survey-type adjustments.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>gabirths <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">count</span>(mother_id, <span class="at">name =</span> <span class="st">"n_children"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">arrange</span>(<span class="fu">desc</span>(n_children)) <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  mother_id n_children
1     M1363          5
2     M1448          5
3     M1553          5
4     M2117          5
5      M665          5
6     M1006          4</code></pre>
</div>
</div>
<p>This summary shows that some mothers contribute multiple infants to the dataset. The number of infants per mother ranges from 1 to 5, meaning the data consist of clusters of varying sizes. If we treat each mother as a cluster, the observations are nested within mothers with unequal cluster sizes.</p>
<hr>
</section>
<section id="marginal-distributions" class="level3">
<h3 class="anchored" data-anchor-id="marginal-distributions"><span style="color: green;">Marginal Distributions</span></h3>
<p>To understand the estimand <span class="math inline">\(m(gw, age)\)</span>, we first look at the marginal behavior of its components. <strong>Birthweight</strong>&nbsp;often exhibits right skew, while gestational age may show natural bounds (e.g., preterm &lt; 37 weeks). Maternal age typically spans a broad range and may have nonlinear associations with outcome.</p>
<p>Understanding these shapes helps anticipate whether:</p>
<ul>
<li><p>linearity assumptions will hold,</p></li>
<li><p>transformations may be needed, or</p></li>
<li><p>smooth functions (splines/GAMs) are appropriate.</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       bw             gw             age       
 Min.   : 748   Min.   :26.00   Min.   :15.00  
 1st Qu.:3210   1st Qu.:38.00   1st Qu.:22.00  
 Median :3353   Median :39.00   Median :26.00  
 Mean   :3289   Mean   :38.55   Mean   :26.73  
 3rd Qu.:3466   3rd Qu.:40.00   3rd Qu.:31.00  
 Max.   :3798   Max.   :44.00   Max.   :44.00  </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Module_6_workflow_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can illustrate densities of the outcome and covariate variables both overall and within groups. These can give us a sense of the outcome density as well as dispersion.</p>
<p><strong>Interpretation of Marginal Distributions</strong></p>
<p>The summary statistics provide an initial sense of the scale, variability, and clinical plausibility of each variable:</p>
<ul>
<li><p><strong>Birthweight (<code>bw</code>)</strong>&nbsp;ranges from&nbsp;<em>748 g to 3798 g</em>, with a mean of about&nbsp;<em>3289 g</em>.<br>
The lower tail reflects preterm or growth-restricted infants, while the upper tail reflects large-for-gestational-age infants. The interquartile range (3210–3466 g) covers healthy term births.</p></li>
<li><p><strong>Gestational age (<code>gw</code>)</strong>&nbsp;spans&nbsp;<em>26 to 44 weeks</em>, with a median of&nbsp;<em>39 weeks</em>.<br>
Values below 37 weeks correspond to preterm births, and the distribution is strongly right-skewed toward full-term deliveries, as expected in population-level data.</p></li>
<li><p><strong>Maternal age (<code>age</code>)</strong>&nbsp;ranges from&nbsp;<em>15 to 44 years</em>, with a median of&nbsp;<em>26</em>.<br>
The wide spread suggests that maternal age may contribute both linear and nonlinear variation in birth outcomes.</p></li>
<li><p>The within-mother boxplots reveal substantial <strong>between-mother heterogeneity</strong> in baseline infant birthweight and some variability in spread.</p></li>
</ul>
<p>These features motivate a workflow in which we begin with simple models and then examine whether nonlinear terms or smoothing functions are needed to accurately estimate the estimand.</p>
<hr>
</section>
<section id="exploring-associations" class="level3">
<h3 class="anchored" data-anchor-id="exploring-associations"><span style="color: green;">Exploring Associations</span></h3>
<p>Before specifying a model, we examine the bivariate relationships among birthweight, gestational age, and maternal age. This helps us judge linearity, detect nonlinear patterns, and understand how the predictors relate to the outcome at a population level.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Module_6_workflow_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Module_6_workflow_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Interpretation: The LOESS smoother clearly shows steep growth in early gestational ages with a leveling off around 38–40 weeks, a pattern that linear terms cannot capture. There is a more linear trend between <code>age</code> and <code>bw</code>. This motivates our plan to include smooth functions later.</p>
<hr>
</section>
</section>
<section id="build-an-analysis-plan" class="level2">
<h2 class="anchored" data-anchor-id="build-an-analysis-plan"><span style="color: purple;">Build an Analysis Plan</span></h2>
<p>With the estimand clarified and the data structure understood, the next step is to build an analysis plan—a short, principled outline of how we intend to estimate</p>
<p><span class="math display">\[
m(gw, age) = E[bw|gw, age]
\]</span></p>
<p>An analysis plan is not the model itself. It is a blueprint that anticipates likely modeling challenges and provides a rationale for <strong>where to begin</strong> and <strong>how to proceed</strong> if the initial model is inadequate.<br>
</p>
<p>The plan should answer four questions:</p>
<ol type="1">
<li><p><strong>What model family is appropriate for the outcome?</strong></p></li>
<li><p><strong>Do we expect linearity, or should we plan for flexible nonlinear effects?</strong></p></li>
<li><p><strong>Are the observations independent? If not, how should we handle correlation?</strong></p></li>
<li><p><strong>What diagnostics will determine whether we need more complexity?</strong></p></li>
</ol>
<hr>
<section id="choosing-the-baseline-model" class="level3">
<h3 class="anchored" data-anchor-id="choosing-the-baseline-model"><span style="color: green;">1. Choosing the baseline model</span></h3>
<p>Birthweight is continuous and measured in grams. Although reasonably well behaved for most term infants, its distribution is clearly right-skewed with heavier lower tails due to preterm and growth-restricted births.</p>
<p>Thus, a <span style="color: red;">Gaussian</span> working model is a reasonable starting point for the conditional mean, even if residuals later suggest refinements.</p>
<p>We know that there are repeated children within mother. We have learned that <strong>ignoring this clustering results in invalid inference</strong>. Our initial model needs to respect the structure of the data, which is not independent.</p>
<p>Based on these two conditions, we have multiple model options that capture the estimand of interest:</p>
<ol type="1">
<li>A natural baseline is a <strong>LMM</strong> in which we model birthweight for child <span class="math inline">\(i\)</span> with a random intercept for mother <span class="math inline">\(j\)</span>:</li>
</ol>
<p><span class="math display">\[
\begin{align*}
bw_{ij} &amp;= \beta_0 + \beta_1 gw_{ij} + \beta_2 age_{ij} + \theta_j  + \epsilon_{ij}\\
\epsilon_{ij} &amp;\sim N(0, \sigma^2),\\
\theta_j &amp;\sim N(0, \tau^2).
\end{align*}
\]</span></p>
<p>This model targets the same population-level estimand but does so while properly accounting for the non-independence of infants within mothers. It is intentionally simple and serves as a baseline against which more flexible models can be compared.</p>
<ol start="2" type="1">
<li>Another option is <strong>GEE</strong> which also accounts for within-mother correlation but only models population-level associations and <strong>not subject-specific effects</strong>. GEE requires specifying a working correlation structure (e.g., exchangeable), although inference remains valid even if this structure is misspecified.</li>
</ol>
<p><span class="math display">\[
\begin{align*}
bw_{ij} &amp;= \beta_0 + \beta_1 gw_{ij} + \beta_2 age_{ij} \\
corr(bw_{ij}, bw_{ik}) &amp; = \alpha
\end{align*}
\]</span></p>
<p><strong>Review of Assumptions and Robustness</strong></p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Key Assumptions</th>
<th>Robustness / Properties</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>LMM</strong></td>
<td>- Random effects are correctly specified (typically normal).<br>- Covariance structure must be correctly specified for full efficiency.</td>
<td>- Most efficient if the model is correctly specified.<br>- Provides BLUPs for each mother.<br>- Sensitive to covariance misspecification.</td>
</tr>
<tr class="even">
<td><strong>GEE</strong></td>
<td>- Does not require assumptions about random‐effects distribution.<br>- Requires a working correlation structure (e.g., exchangeable).</td>
<td>- Sandwich (robust) SEs protect against misspecification.<br>- Population‐level interpretation unaffected by random‐effects assumptions.<br>- Reliable even if the working correlation is incorrect.</td>
</tr>
</tbody>
</table>
<p><strong>So how do we choose between them?</strong></p>
<ul>
<li><p>LMM is preferred when we want to model the clustering explicitly, estimate variance components, or examine how much mothers differ from one another. <strong>Subject-specific effects.</strong></p></li>
<li><p>GEE is preferred when we want robust population-average effects and are less concerned with modeling the random-effects structure. <strong>Population level associations only.</strong></p></li>
<li><p>In linear models with an identity link, the fixed-effect estimates from LMM and GEE are usually very similar; they differ mainly in how they treat correlation and what additional quantities they provide.</p></li>
<li><p>Here we use the LMM as the baseline model because it respects clustering and provides useful diagnostics (e.g., BLUPs, ICC), while still targeting the same population-level estimand as a GEE.</p></li>
</ul>
<hr>
</section>
<section id="anticipating-nonlinearity" class="level3">
<h3 class="anchored" data-anchor-id="anticipating-nonlinearity"><span style="color: green;">2. Anticipating nonlinearity</span></h3>
<p>EDA indicates that:</p>
<ul>
<li><p>the relationship between gestational age and birthweight is strongly nonlinear, especially around the late-preterm and early-term range;</p></li>
<li><p>maternal age may have a weak or nonlinear association with birthweight.</p></li>
<li><p>If linearity assumptions fail (which they will), we will introduce <strong>spline-based smooths</strong> for <span class="math inline">\(gw\)</span> and if needed for <span class="math inline">\(age\)</span> <strong>using a GAM model</strong>. Specifically, we will incorporate <strong>penalized b-splines</strong> using the default number of knots <span class="math inline">\((k=10)\)</span> for initial assessment.</p></li>
</ul>
<p><strong>Why penalized splines?</strong></p>
<p>Although many spline bases can be used to model nonlinear relationships, penalized splines offer a principled and practical balance of flexibility and control. In practice, analysts may choose among:</p>
<ul>
<li>Truncated power basis splines: Flexible but highly sensitive to knot placement; prone to overfitting unless carefully tuned.</li>
<li>Cubic B-splines: Smooth and stable, but still require explicit decisions about the number and location of knots and do not include automatic smoothing.</li>
<li>Penalized splines: Use a moderately large basis and a smoothing penalty selected automatically by REML or GCV. These are robust, interpretable, and require minimal manual tuning.</li>
</ul>
<p>For this module, we use penalized splines because they provide automatic control of smoothness, integrate naturally with diagnostic tools (such as the k-index), and offer a modern, reproducible approach to modeling nonlinear effects.</p>
<p><span style="color: red;">Note: Both LMM and GEE can accommodate splines:</span></p>
<ul>
<li><p>In LMM, spline bases (e.g., truncated power basis or B-splines) enter as additional fixed-effect columns in the design matrix <span class="math inline">\(X\)</span>, optionally with random-coefficient penalties (linking back to penalized splines in Module 4).</p></li>
<li><p>In GEE, we can use the same spline basis functions as predictors in the marginal mean, and then estimate <span class="math inline">\(\beta\)</span> and robust SEs with a working correlation.</p></li>
</ul>
<hr>
</section>
<section id="pre-specifying-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="pre-specifying-diagnostics"><span style="color: green;">3. Pre-specifying diagnostics</span></h3>
<p>An analysis plan should not only say <em>what</em> we will fit, but also <em>how</em> we will decide whether each model in the workflow is adequate. Because we have pre-specified a two-step modeling strategy</p>
<ol type="1">
<li>Baseline LMM with linear effects of <code>gw</code> and <code>age</code> and a random intercept for <code>mother_id</code>;</li>
<li>Extended LMM that replaces the linear term in <code>gw</code> with a penalized B-spline,</li>
</ol>
<p>Our diagnostics will also be organized in two phases.</p>
<section id="phase-1-diagnostics-for-the-baseline-linear-lmm" class="level4">
<h4 class="anchored" data-anchor-id="phase-1-diagnostics-for-the-baseline-linear-lmm">Phase 1: Diagnostics for the baseline linear LMM</h4>
<p>Our baseline model is</p>
<p><span class="math display">\[
bw_{ij} = \beta_0 + \beta_1 gw_{ij} + \beta_2 age_{ij} + \theta_j + \epsilon_{ij},
\quad \theta_j \sim N(0, \tau^2), \ \epsilon_{ij} \sim N(0, \sigma^2).
\]</span></p>
<p>After fitting this model with <code>lmer()</code>, we will perform three focused checks.</p>
<ol type="1">
<li>Mean-structure diagnostics: We will examine residuals versus fitted values and residuals versus the key predictors:</li>
</ol>
<ul>
<li>residuals vs.&nbsp;fitted values,<br>
</li>
<li>residuals vs.&nbsp;<code>gw</code>,<br>
</li>
<li>residuals vs.&nbsp;<code>age</code>.</li>
</ul>
<p><em>Decision Rule:</em> If we see clear nonlinear structure with respect to <code>gw</code>, we proceed to Phase 2 and replace the linear term in <code>gw</code> by a cubic B-spline in the LMM.</p>
<ol start="2" type="1">
<li>Distributional diagnostics for residuals.</li>
</ol>
<p>We will check approximate normality of the level-1 errors using a QQ plot of residuals. Moderate deviations are acceptable, since the Gaussian model is being used as a working model for the mean. (However, very heavy tails or extreme asymmetry may indicate that a transformation of <code>bw</code> or a more robust modeling approach is needed.)</p>
<p>At this stage, our primary concern is whether the residuals are sufficiently well-behaved for standard LMM inference to be reliable.</p>
<ol start="3" type="1">
<li>Random-effects diagnostics.</li>
</ol>
<p>Because the correlation among siblings is captured by the mother-level random intercepts, we will inspect the empirical distribution of the BLUPs <span class="math inline">\(\hat\theta_j\)</span>:</p>
<ul>
<li>histogram and Q–Q plot of <span class="math inline">\(\hat\theta_j\)</span> against a normal distribution,<br>
</li>
<li>summary of the estimated variance component <span class="math inline">\(\hat\tau^2\)</span> and the implied intraclass correlation (ICC).</li>
</ul>
<p><em>Decision rule:</em></p>
<ul>
<li><p>If residuals vs gw show curvature → add spline.</p></li>
<li><p>If BLUPs wildly non-normal → flag for sensitivity, but continue.</p></li>
</ul>
</section>
<section id="phase-2-diagnostics-after-adding-a-penalized-b-spline-for-gestational-week" class="level4">
<h4 class="anchored" data-anchor-id="phase-2-diagnostics-after-adding-a-penalized-b-spline-for-gestational-week">Phase 2: Diagnostics after adding a penalized B-spline for gestational week</h4>
<p>If Phase 1 diagnostics indicate substantial nonlinearity in <code>gw</code>, we extend the baseline LMM to</p>
<p><span class="math display">\[
bw_{ij} = \beta_0 + f(gw_{ij}) + \beta_2 age_{ij} + \theta_j + \epsilon_{ij},
\]</span></p>
<p>where <span class="math inline">\(f(\cdot)\)</span> is modeled via a penalized spline basis for gestational week.</p>
<p>After fitting this spline-augmented LMM, the diagnostics focus on whether the spline has successfully captured the nonlinear pattern without overfitting.</p>
<ol type="1">
<li>Visualizing the fitted smooth.</li>
</ol>
<p>We will plot the estimated mean birthweight curve across <code>gw</code> (holding <code>age</code> at a representative value), overlaid with the observed data summarized in bins of gestational age (e.g., mean <code>bw</code> within 1-week bins).</p>
<p>Questions we ask:</p>
<ul>
<li>Does the spline fit capture the clinically plausible shape (e.g., steep growth at earlier weeks, flattening near term)?<br>
</li>
<li>Does it remove the systematic residual patterns we saw in Phase 1?</li>
</ul>
<ol start="2" type="1">
<li>Residual diagnostics revisited. We repeat the key residual plots from Phase 1:</li>
</ol>
<ul>
<li>residuals vs.&nbsp;fitted values,<br>
</li>
<li>residuals vs.&nbsp;<code>gw</code>,<br>
</li>
<li>residuals vs.&nbsp;<code>age</code>,<br>
</li>
<li>Q–Q plot of residuals.</li>
</ul>
<p>Decision rule:</p>
<ul>
<li>If residuals vs.&nbsp;<code>gw</code> now show no strong curvature and the spread is roughly constant across <code>gw</code>, we conclude that the spline has successfully captured the main nonlinear structure in gestational age.<br>
</li>
<li>If substantial structure remains, we may consider increasing the flexibility of the spline (e.g., more internal knots) or, if the pattern appears to be driven by a small number of very preterm or very post-term births, conducting sensitivity analyses with those observations removed.</li>
</ul>
<p>3.Basis-dimension adequacy (K-index)</p>
<p>When using spline bases (as in <code>mgcv::gam()</code>), the <strong>k-index</strong> provides a formal check of whether the chosen basis dimension <code>k</code> was large enough to capture the underlying nonlinear pattern.</p>
<ul>
<li>A k-index <strong>close to 1</strong> with a <strong>non-significant p-value</strong> indicates that the basis dimension was adequate.</li>
<li>A k-index <strong>substantially less than 1</strong> with a <strong>small p-value</strong> suggests that <code>k</code> was too small and additional flexibility is needed (e.g., increase <code>k</code> or add knots).</li>
</ul>
</section>
<section id="phase-3-model-comparison-and-sensitivity-checks" class="level4">
<h4 class="anchored" data-anchor-id="phase-3-model-comparison-and-sensitivity-checks">Phase 3: Model comparison and sensitivity checks</h4>
<p>Once both the linear LMM and the penalized-spline GAM have been fitted and diagnosed, we will compare them using <strong>cross-validation error</strong>. <span style="color: red;">Note: AIC is not appropriate here because of different smoothing functions.</span></p>
<p>The final model choice (which version we present in plots and write-up) will be based on two criteria:</p>
<ol type="1">
<li>It provides a better approximation to the estimand <span class="math inline">\(m(gw, age)\)</span>, as judged by diagnostics;<br>
</li>
<li>It remains interpretable and consistent with clinical knowledge about how birthweight should change with gestational age and maternal age.</li>
</ol>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Workflow Summary: Model-Building Algorithm
</div>
</div>
<div class="callout-body-container callout-body">
<p>This module follows a <strong>two-stage model-building workflow</strong> driven by pre-specified diagnostics.<br>
All steps are anchored to the estimand<br>
</p>
<p><span class="math display">\[ m(gw, age) = E[bw \mid gw, age]. \]</span></p>
<hr>
<section id="phase-1-fit-the-baseline-linear-lmm" class="level5">
<h5 class="anchored" data-anchor-id="phase-1-fit-the-baseline-linear-lmm"><strong>Phase 1 — Fit the Baseline Linear LMM</strong></h5>
<p>Fit the model<br>
</p>
<p><span class="math display">\[
bw_{ij} = \beta_0 + \beta_1 gw_{ij} + \beta_2age_{ij} + \theta_j + \epsilon_{ij}.
\]</span></p>
<p><strong>Diagnostic checks</strong></p>
<ol type="1">
<li><p><strong>Residual vs.&nbsp;fitted plot</strong><br>
• should show no funnel shape or strong curvature.</p></li>
<li><p><strong>Residuals vs.&nbsp;gestational age <code>gw</code></strong><br>
• if residuals trend or curve across <code>gw</code>, linearity in <code>gw</code> is violated.</p></li>
<li><p><strong>Residuals vs.&nbsp;maternal age <code>age</code></strong><br>
• minor drift acceptable; major curvature suggests nonlinear age effects.</p></li>
<li><p><strong>Q–Q plot of residuals</strong><br>
• moderate deviations okay; severe asymmetry → consider variance-stabilizing transformation.</p></li>
<li><p><strong>Random-effects diagnostics</strong><br>
• BLUPs roughly normal; ICC nonzero; no extreme outlier clusters.</p></li>
</ol>
<hr>
</section>
<section id="trigger-for-moving-to-phase-2" class="level5">
<h5 class="anchored" data-anchor-id="trigger-for-moving-to-phase-2"><strong>Trigger for moving to Phase 2</strong></h5>
<p>Proceed to Phase 2 if <strong>any</strong> of the following hold:</p>
<ul>
<li>Clear curvature in residuals vs.&nbsp;<strong>gestational age</strong>.<br>
</li>
<li>Patterned heteroskedasticity across <code>gw</code> (e.g., wider spread at low gestational ages).<br>
</li>
<li>Clinical knowledge + residuals jointly suggest a nonlinear relationship between <code>gw</code> and <code>bw</code>.</li>
</ul>
<p>If none of these occur, the linear LMM is adequate and you may stop here.</p>
<hr>
</section>
<section id="phase-2-fit-the-spline-augmented-lmm" class="level5">
<h5 class="anchored" data-anchor-id="phase-2-fit-the-spline-augmented-lmm"><strong>Phase 2 — Fit the Spline-Augmented LMM</strong></h5>
<p>Replace the linear effect of gestational age with a <strong>cubic B-spline</strong>:</p>
<p><span class="math display">\[bw_{ij} = \beta_0 + f(gw_{ij}) + \beta_2age_{ij} + \theta_j + \epsilon_{ij},
\]</span></p>
<p>where <span class="math inline">\(f(\cdot)\)</span> is a penalized-spline basis.</p>
<p><strong>Diagnostic checks</strong></p>
<ol type="1">
<li><p><strong>Plot the estimated smooth ( f(gw) )</strong><br>
• Should match the clinical growth profile (steep early growth, flattening near term).<br>
• Overlay with binned means to confirm plausibility.</p></li>
<li><p><strong>Residuals vs.&nbsp;<code>gw</code></strong><br>
• Should now be flat (no curvature).</p></li>
<li><p><strong>Residuals vs.&nbsp;fitted</strong><br>
• Should be roughly homoskedastic.</p></li>
<li><p><strong>Q–Q plot</strong><br>
• Should show improvement or remain similar to Phase 1.</p></li>
<li><p><strong>Random-effects BLUPs</strong><br>
• Should not reveal new structure; distribution should remain roughly normal.</p></li>
</ol>
<hr>
</section>
<section id="criteria-for-accepting-the-spline-lmm" class="level5">
<h5 class="anchored" data-anchor-id="criteria-for-accepting-the-spline-lmm"><strong>Criteria for Accepting the Spline LMM</strong></h5>
<p>Choose the spline-augmented model if:</p>
<ul>
<li>it removes nonlinear patterns in residuals,<br>
</li>
<li>it gives a clinically plausible smooth curve across gestational age,<br>
</li>
<li>cross-validation error shows improvement.</li>
</ul>
<p>If the spline adds complexity without improving diagnostics or interpretability, prefer the simpler linear LMM.</p>
</section>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="final-deliverables" class="level2">
<h2 class="anchored" data-anchor-id="final-deliverables"><span style="color: purple;">4. Final Deliverables</span></h2>
<p>At the end of the workflow, the work should culminate in a set of clearly presented, reproducible deliverables that summarize</p>
<ol type="i">
<li>the modeling decisions made,</li>
<li>the diagnostic evidence supporting those decisions, and</li>
<li>the final estimated relationship between birthweight, gestational age, and maternal age.</li>
</ol>
<p>These deliverables serve both as a scientific summary and as documentation of a transparent, principled model-building process.</p>
<section id="a-clearly-stated-estimand" class="level4">
<h4 class="anchored" data-anchor-id="a-clearly-stated-estimand"><strong>1. A clearly stated estimand</strong></h4>
<p>A concise restatement of the target quantity: <span class="math inline">\(m(gw, age) = E[bw \mid gw, age]\)</span>. Explain why this estimand is population-level, how it relates to the scientific question, and how the final model approximates it.</p>
</section>
<section id="a-summary-of-the-modeling-workflow-and-decision-points" class="level4">
<h4 class="anchored" data-anchor-id="a-summary-of-the-modeling-workflow-and-decision-points"><strong>2. A summary of the modeling workflow and decision points</strong></h4>
<p>Provide a brief narrative describing:</p>
<ul>
<li>the baseline linear LMM,<br>
</li>
<li>the diagnostics performed,<br>
</li>
<li>the specific diagnostic patterns that motivated the spline extension (if used),<br>
</li>
<li>why the final model was selected over alternatives.</li>
</ul>
<p>This should read as a short justification of your modeling path, not as a list of R commands.</p>
</section>
<section id="the-final-fitted-model" class="level4">
<h4 class="anchored" data-anchor-id="the-final-fitted-model"><strong>3. The final fitted model</strong></h4>
<p>Present the final selected model in both:</p>
<ul>
<li><strong>statistical form</strong> (equation), and<br>
</li>
<li><strong>computational form</strong> (the final R call to <code>lmer()</code>).</li>
</ul>
<p>Include estimated coefficients for fixed effects, the estimated spline function (if applicable), and the variance component for the random intercept.</p>
</section>
<section id="visualizations-of-the-estimated-mean-structure" class="level4">
<h4 class="anchored" data-anchor-id="visualizations-of-the-estimated-mean-structure"><strong>4. Visualizations of the estimated mean structure</strong></h4>
<p>Provide the primary visualization(s) that communicate the results:</p>
<ul>
<li>The fitted birthweight–gestational age curve <span class="math inline">\(\hat{m}(gw, age_0)\)</span> at a representative value of maternal age.<br>
</li>
<li>If splines are used, a smoothed curve with pointwise confidence bands.<br>
</li>
<li>Optional: overlaid binned means of the raw data for interpretability.</li>
</ul>
<p>These plots demonstrate how the model captures nonlinear growth patterns across gestational age.</p>
</section>
<section id="key-diagnostic-plots-for-the-final-model" class="level4">
<h4 class="anchored" data-anchor-id="key-diagnostic-plots-for-the-final-model"><strong>5. Key diagnostic plots for the final model</strong></h4>
<p>Include the essential diagnostic figures that verify the adequacy of the chosen model:</p>
<ul>
<li>residuals vs.&nbsp;fitted values,<br>
</li>
<li>residuals vs.&nbsp;gestational age,<br>
</li>
<li>Q–Q plot of residuals,<br>
</li>
<li>distribution of random-intercept BLUPs.</li>
</ul>
<p>These confirm that the final model appropriately captures the mean structure and dependence.</p>
</section>
<section id="interpretation-of-substantive-effects" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-of-substantive-effects"><strong>6. Interpretation of substantive effects</strong></h4>
<p>A brief textual interpretation connecting results to the scientific question. Examples:</p>
<ul>
<li>How birthweight increases across gestational age and where the curve flattens.<br>
</li>
<li>The estimated population-level effect of maternal age.<br>
</li>
<li>The estimated between-mother variability (ICC or random-effect variance).</li>
</ul>
</section>
<section id="reproducible-appendix-full-r-workflow" class="level4">
<h4 class="anchored" data-anchor-id="reproducible-appendix-full-r-workflow"><strong>7. Reproducible appendix: Full R Workflow</strong></h4>
<p>Include a compact, end-to-end R script that reproduces:</p>
<ul>
<li>data preparation,<br>
</li>
<li>EDA summaries and plots,<br>
</li>
<li>baseline LMM,<br>
</li>
<li>spline extension (if used),<br>
</li>
<li>diagnostics,<br>
</li>
<li>final plots.</li>
</ul>
<p>This appendix ensures transparency and reproducibility without disrupting the narrative in the main text.</p>
<p>Together, these deliverables provide a complete and rigorously justified estimation of <span class="math inline">\(m(gw, age) = E[bw \mid gw, age]\)</span> demonstrating a full regression workflow from estimand definition to final communication.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Module_5_GAM_Cheat.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Module 5 Cheat Sheet</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->



</body></html>