<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>BIOS 526 Modern Regression Analysis - Module 2A Generalized Linear Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Module_2B_GLM.html" rel="next">
<link href="./Module_1_LMM_Cheet.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Module_2A_GLM.html">Module 2A Generalized Linear Models</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">BIOS 526 Modern Regression Analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_0_MLR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 0: Multiple Linear Regression Review</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1A_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1A Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1B_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1B Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1C_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1C Random Intercepts and Slopes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1_LMM_Cheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2A_GLM.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Module 2A Generalized Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2B_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2B Generalized Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2C_GLMMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2C Generalized Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2D_GLMMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2D Generalized Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2_GLM_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3A_GEEs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3A Marginal Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3B_GEEs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3B Marginal Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3_GEE_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4A_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4A Basis Expansion and Parametric Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4B_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4B Parametric Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4C_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4C Penalized Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4_Splines_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5A_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5A Generalized Additive Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5B_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5B Generalized Additive Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5_GAM_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_6_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 6 Model Selection, Diagnostics, &amp; Regression Workflow</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><strong>Overview</strong></a></li>
  <li><a href="#motivation-and-examples" id="toc-motivation-and-examples" class="nav-link" data-scroll-target="#motivation-and-examples">Motivation and Examples</a></li>
  <li><a href="#the-better-approach-generalized-linear-regression" id="toc-the-better-approach-generalized-linear-regression" class="nav-link" data-scroll-target="#the-better-approach-generalized-linear-regression"><u>The Better Approach: Generalized Linear Regression</u></a></li>
  <li><a href="#exponential-family" id="toc-exponential-family" class="nav-link" data-scroll-target="#exponential-family">Exponential Family</a></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression">Logistic Regression</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span style="color: purple;">Summary</span></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Module 2A Generalized Linear Models</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><img src="fig/glm.jpeg" class="img-fluid"></p>
<p><strong>Reading</strong></p>
<ul>
<li>Chapter 3, Wood S. Generalized Additive Models, 2017. Has a nice self-contained introduction to generalized linear models.</li>
<li>Gelman &amp; Hill. Data Analysis using Regression and Multilevel/Hierarchical Models.2006.</li>
</ul>
<section id="overview" class="level3">
<h3 class="anchored" data-anchor-id="overview"><strong>Overview</strong></h3>
<p>In this module, you will learn <strong>generalized linear models (GLMs)</strong>, a flexible extension of linear regression that allows for modeling response variables with error distributions other than the normal distribution.</p>
<p><strong>After completing this module, you will be able to:</strong></p>
<ul>
<li><p>Explain components of GLMs (link functions, linear predictor, and error distribution)</p></li>
<li><p>Fit and interpret logistic and Poisson regression models.</p></li>
<li><p>Calculate and interpret odds ratios and rate ratios.</p></li>
<li><p>Perform hypothesis testing using Wald and likelihood ratio tests.</p></li>
</ul>
</section>
<section id="motivation-and-examples" class="level3">
<h3 class="anchored" data-anchor-id="motivation-and-examples">Motivation and Examples</h3>
<div class="illustration callout callout-style-default callout-important callout-titled" style="color: red">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Motivation:
</div>
</div>
<div class="callout-body-container callout-body">
<p>If the outcome variable does not follow a normal distribution, alternative regression methods, such as generalized linear models, are required.</p>
<ul>
<li><strong>Bernoulli/Binomial:</strong> Binary outcomes (0/1) or counts of successes out of a fixed number of trials.</li>
<li><strong>Poisson data:</strong> Count data representing the number of events occurring over a fixed time, area, or rate.</li>
</ul>
<p>Treating these as continuous outcomes can lead to biased estimates, incorrect standard errors, and invalid inference because the underlying distributional assumptions of linear regression are violated.</p>
</div>
</div>
<p><strong>Motivating Example: Preterm Births Data</strong></p>
<p>The dataset: a cohort of live births from Georgia born in the year 2001 <span class="math inline">\(N = (77,340)\)</span>.</p>
<p>Variables:</p>
<ul>
<li><p>ptb: indicator for whether a baby from pregnancy <span class="math inline">\(i\)</span> was born preterm (&lt;37 weeks).</p></li>
<li><p>age: the mother’s age at delivery (centered at age 25).</p></li>
<li><p>male: indicator of the baby’s sex (1=male, 0=female)</p></li>
<li><p>tobacco: indicator for mother’s tobacco use during pregnancy (1= yes, 0 = no).</p></li>
</ul>
<p>Tobacco is treated as the exposure variables. Mothers age is a covariate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"/Users/emilypeterson/Library/CloudStorage/OneDrive-EmoryUniversity/BIOS 526/BIOS526_Book/data/PTB.Rdata"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        age ptb male tobacco
4849420  30   0    M       0
2320030  23   0    F       0
3512250  23   0    M       0
4132270  23   0    F       0
4307390  32   0    M       0
3630030  29   0    F       0</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Module_2A_GLM_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<section id="why-not-linear-regression-the-wrong-approach" class="level4">
<h4 class="anchored" data-anchor-id="why-not-linear-regression-the-wrong-approach">Why Not linear regression? <u><strong>The wrong approach</strong></u></h4>
<p>Consider the following multiple linear regression model: For <span class="math inline">\(i=1, ..., n\)</span>.</p>
<p><span class="math display">\[
  y_i = \beta_0 + \sum_{k=1}^K \beta_k x_{ik} + \epsilon_i \qquad e_i \overset{iid}{\sim} N(0, \sigma^2)
\]</span></p>
<p>This is equivalent to <span class="math inline">\(y_i \sim N(\beta_0 + \sum_{k=1}^K \beta_k x_{ik} , \sigma^2)\)</span> where <span class="math inline">\(x_{ik}\)</span> is the <span class="math inline">\(k^{th}\)</span> linear predictor for observation <span class="math inline">\(i\)</span>.</p>
<p>Reminder of the assumptions of the above model:</p>
<ul>
<li>The <span class="math inline">\(\beta's\)</span> are fixed unknown constants.</li>
<li><span class="math inline">\(y\)</span> is a linear function of the covariates.</li>
<li>The expectation of the errors <span class="math inline">\(e's\)</span> is zero.</li>
<li>Only <span class="math inline">\(\epsilon's\)</span> are random.</li>
</ul>
<p>Therefore, <span class="math inline">\(y_i\)</span> follows a normal distribution and the <span class="math inline">\(E(y_i|x_i) = \beta_0 + \sum_{k=1}^K \beta_k x_{ik}\)</span>. The linear regression part is used to model the <strong>mean function</strong> of <span class="math inline">\(y_i\)</span>. The assumptions do not hold for other kinds of data, i.e, binary, count data, etc.</p>
<hr>
</section>
</section>
<section id="the-better-approach-generalized-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="the-better-approach-generalized-linear-regression"><u>The Better Approach: Generalized Linear Regression</u></h3>
<p>A generalized linear model (GLM) extends the linear regression to other distributions, where the response variable is generated from a distribution in the <u>exponential family.</u></p>
<p>GLMs provide this flexibility by extending linear regression to a broader set of distributions—specifically, those that belong to the <strong>exponential family</strong>. The exponential family is mathematically convenient because it allows for a :</p>
<ul>
<li>A natural way to link the mean of the response to the linear predictors via a link function.</li>
<li>Simple expressions for the mean and variance, which are essential for estimation and inference.</li>
<li>Unified estimation procedures (e.g., MLE).</li>
</ul>
<p>A GLM involves three ingredients:</p>
<ol type="1">
<li><p>A probability distribution in the Exponential Family.</p></li>
<li><p>A linear model <span class="math inline">\(x_i'\beta\)</span>.</p></li>
<li><p>A <u>link function</u> <span class="math inline">\(g()\)</span> and its inverse <span class="math inline">\(g^{-1}()\)</span> is the link that relates the linear model to the expectation, i.e., transforms the mean function to meet the linear model assumptions.</p>
<p><span class="math display">\[
\begin{align*}
E(y_i|x_i) &amp; = \mu_i = g^{-1} (x_i\beta)\\
Var(y_i|x_i) &amp; = V(\mu_i) =V(g^{-1}(x_i\beta))
\end{align*}
\]</span></p></li>
<li><p>Note: Unlike OLS, the basic form of the GLM does not involve a noise variance <u>(no <span class="math inline">\(\sigma^2\)</span>).</u></p></li>
</ol>
<hr>
</section>
<section id="exponential-family" class="level2">
<h2 class="anchored" data-anchor-id="exponential-family">Exponential Family</h2>
<div class="illustration callout callout-style-simple callout-note no-icon" style="color: blue">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>The basic form for an exponential family density is</p>
<p><span class="math display">\[
f_{\theta} (y) = exp[\{y\theta - b(\theta)\} / a(\phi) + c(y, \phi )]
\]</span></p>
<p>where <span class="math inline">\(a, b, c\)</span> are known functions, and <span class="math inline">\(\phi\)</span> is a known scale parameter. The ONLY parameter is <span class="math inline">\(\theta\)</span>.</p>
</div>
</div>
</div>
<p>In the GLM, <span class="math inline">\(\theta\)</span> will be a function of <span class="math inline">\(x_i\beta\)</span>.</p>
<p>Examples of distributions in the exponential family include: normal with known variance (link = identity), Bernoulli (link = logit or probit), binomial (link = logit or log), gamma, exponential (link = negative inverse), and others.</p>
<p>The table below summarizes the three most common GLM families side by side:</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Normal</strong></th>
<th><strong>Bernoulli/Binomial</strong></th>
<th><strong>Poisson</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Natural param <span class="math inline">\(\theta\)</span></td>
<td><span class="math inline">\(\mu\)</span></td>
<td><span class="math inline">\(\log\!\frac{p}{1-p}\)</span></td>
<td><span class="math inline">\(\log\lambda\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(b(\theta)\)</span></td>
<td><span class="math inline">\(\theta^2/2\)</span></td>
<td><span class="math inline">\(n\log(1+e^\theta)\)</span></td>
<td><span class="math inline">\(e^\theta\)</span></td>
</tr>
<tr class="odd">
<td>Canonical link <span class="math inline">\(g(\mu)\)</span></td>
<td>identity</td>
<td>logit</td>
<td>log</td>
</tr>
<tr class="even">
<td><span class="math inline">\(E(Y)\)</span></td>
<td><span class="math inline">\(\mu\)</span></td>
<td><span class="math inline">\(np\)</span></td>
<td><span class="math inline">\(\lambda\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\text{Var}(Y)\)</span></td>
<td><span class="math inline">\(\sigma^2\)</span></td>
<td><span class="math inline">\(np(1-p)\)</span></td>
<td><span class="math inline">\(\lambda\)</span></td>
</tr>
<tr class="even">
<td>Use when</td>
<td>continuous, symmetric</td>
<td>binary / bounded counts</td>
<td>unbounded counts / rates</td>
</tr>
</tbody>
</table>
<p>Lets derive a general class for the exponential function. <em>Use the expandable panels below to explore key statistical properties and their derivations.</em></p>
<div class="callout callout-style-simple callout-tip no-icon callout-titled" style="color:gray">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The Binomial Distribution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>The Binomial distribution with parameters <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span> is:</li>
</ol>
<p><span class="math display">\[f(y \mid p) = \binom{n}{y} p^y (1-p)^{n-y},\]</span></p>
<p>which can be expressed in the exponential family form:</p>
<p><span class="math display">\[f(y \mid \theta) = \exp \left[ y \theta - b(\theta) + c(y) \right], \]</span> where <span class="math display">\[\theta = \log \left( \frac{p}{1-p} \right), \quad b(\theta) = n \log (1 + e^{\theta}), \quad c(y) = \log \binom{n}{y}. \]</span></p>
<p>The mean and variance are: <span class="math display">\[ E[Y] = np, \qquad \text{Var}(Y) = np(1-p). \]</span></p>
<p><strong>Why the logit is the canonical link:</strong> <span class="math inline">\(\theta = \log\!\frac{p}{1-p}\)</span> falls directly out of matching the Binomial density to the exponential family form — it is not a modeling choice. Verify using <span class="math inline">\(E(Y) = b'(\theta)\)</span>: <span class="math display">\[
b'(\theta) = \frac{d}{d\theta}\, n\log(1+e^\theta) = \frac{ne^\theta}{1+e^\theta} = np \ \checkmark
\]</span> and <span class="math inline">\(\text{Var}(Y) = b''(\theta) \cdot a(\phi)\)</span>: <span class="math display">\[
b''(\theta) = \frac{ne^\theta}{(1+e^\theta)^2} = np(1-p) \ \checkmark
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon callout-titled" style="color:gray">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The Poisson Distribution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The Poisson distribution with parameter <span class="math inline">\(\lambda &gt; 0\)</span> is:</p>
<p><span class="math display">\[f(y \mid \lambda) = \frac{\lambda^y e^{-\lambda}}{y!}, \]</span></p>
<p>which can be expressed in the exponential family form:</p>
<p><span class="math display">\[f(y \mid \theta) = \exp \left[ y \theta - b(\theta) + c(y) \right], \]</span> where <span class="math display">\[\theta = \log (\lambda), \quad b(\theta) = e^{\theta}, \quad c(y) = - \log (y!). \]</span></p>
<p>The mean and variance are: <span class="math display">\[E[Y] = \lambda, \qquad \text{Var}(Y) = \lambda. \]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon callout-titled" style="color:gray">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The Gamma Distribution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol start="3" type="1">
<li>The Gamma distribution (shape <span class="math inline">\(k\)</span>, scale <span class="math inline">\(\phi\)</span>) has the density:</li>
</ol>
<p><span class="math display">\[f(y \mid k, \phi) = \frac{1}{\Gamma(k) \phi^k} y^{k-1} e^{-y/\phi}, \quad y &gt; 0. \]</span></p>
<p>It can be expressed in the exponential family form:</p>
<p><span class="math display">\[f(y \mid \theta) = \exp \left[ \frac{y \theta - b(\theta)}{a(\phi)} + c(y, \phi) \right], \]</span> where <span class="math display">\[ \theta = -\frac{1}{k\phi}, \quad b(\theta) = - \log (-\theta), \quad a(\phi) = \frac{1}{k}, \quad c(y, \phi) = (k-1)\log y - \log \Gamma(k). \]</span></p>
<p>The mean and variance are: <span class="math display">\[E[Y] = k \phi, \qquad \text{Var}(Y) = k \phi^2. \]</span></p>
</div>
</div>
</div>
<hr>
</section>
<section id="logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression">Logistic Regression</h2>
<section id="bernoulli-model" class="level4">
<h4 class="anchored" data-anchor-id="bernoulli-model">Bernoulli Model</h4>
<p>Let’s take a binary outcome where <span class="math inline">\(p_i\)</span> is the probability of success. For <span class="math inline">\(i=1,...,n\)</span> assume</p>
<p><span class="math display">\[
y_i \sim Bernoulli (p_i)
\]</span></p>
<p>where <span class="math inline">\(p_i \in (0,1)\)</span> and the Bernoulli function has the following characteristics:</p>
<p><span class="math display">\[
\begin{align*}
E(y_i) &amp; = p_i\\
Var(y_i) &amp; =V(p_i) = p_i (1- p_i)\\
f(y_i|p_i) &amp; = p_i ^{y_i} (1-p_i)^{1-y_i}
\end{align*}
\]</span></p>
<hr>
</section>
<section id="link-functions" class="level4">
<h4 class="anchored" data-anchor-id="link-functions">Link Functions</h4>
<p>We know that <span class="math inline">\(\mu_i = p_i = P(Y_i=1)\)</span>. So we wish to model a <strong>link function</strong> <span class="math inline">\(g()\)</span> that <strong>enforces a linear relationship</strong> between the unscaled expectation <span class="math inline">\(\mu_i\)</span> and the expectation <span class="math inline">\(\beta_0 + \sum_{k=1}^K \beta_k x_{ik}\)</span>, i.e, we wish to model</p>
<p><span class="math display">\[
g(\mu_i) = \beta_0 + \sum_{k=1}^K \beta_k x_{ik}
\]</span></p>
<p>The two most commonly used link functions for binomial data are the logit and probit functions.</p>
<p><u>The <strong>link function</strong> should have some desirable properties:</u></p>
<ol type="1">
<li><span class="math inline">\(g()\)</span> should have a range <span class="math inline">\((-\infty, \infty)\)</span> so that <span class="math inline">\(\beta's\)</span> and <span class="math inline">\(X's\)</span> can have any value.</li>
<li><span class="math inline">\(g()\)</span> should have a domain that corresponds to all possible values of <span class="math inline">\(\mu_i\)</span>, i.e., <span class="math inline">\((0,1)\)</span> for the binomial distribution.</li>
<li><span class="math inline">\(g()\)</span> should be one-to-one <span class="math inline">\(\mu_i = g^{-1}(\beta_0 + \sum_k \beta_k X_{ik})\)</span>.</li>
<li><span class="math inline">\(g()\)</span> should be strictly increasing, i.e., <span class="math inline">\(g(p_i) \rightarrow \infty\)</span> when <span class="math inline">\(p_i \rightarrow 1\)</span>.</li>
</ol>
<hr>
</section>
<section id="logit-link-logistic-function" class="level4">
<h4 class="anchored" data-anchor-id="logit-link-logistic-function">Logit Link &amp; Logistic Function</h4>
<p>The logit link function is defined as:</p>
<p><span class="math display">\[
g(p_i) = log\left(\frac{p_i}{1-p_i}\right) = \beta_0 + \sum_k \beta_k X_{ik}, \qquad (0,1) \rightarrow (-\infty, \infty)
\]</span></p>
<p>Meaning <span class="math inline">\(log(p_i/1-p_i) \rightarrow -\infty\)</span> when <span class="math inline">\(p_i \rightarrow 0\)</span> and <span class="math inline">\(log(p_i/1-p_i)\rightarrow \infty\)</span> when <span class="math inline">\(p_i \rightarrow 1\)</span>.</p>
<p>In general the logistic function is defined as :</p>
<p><span class="math display">\[
p_i = \frac{e^{g(\mu_i)}}{1 + e^{g(\mu_i)}} = \frac{1}{1+ e^{-g(\mu_i)}}, \qquad (-\infty, \infty) \rightarrow (0,1)
\]</span></p>
<ul>
<li><p>The <span class="math inline">\(\beta's\)</span> are estimated using the iterative re-weighted MLE method.</p></li>
<li><p>There is no <span class="math inline">\(\epsilon_i\)</span>!!! Meaning the variance is not defined by a normally distributed noise term.</p></li>
<li><p><span class="math inline">\(g(p_i)\)</span> is interpreted as the <u>log_odds of probability of success.</u></p></li>
</ul>
<hr>
</section>
<section id="interpretation" class="level4">
<h4 class="anchored" data-anchor-id="interpretation">Interpretation</h4>
<p>When <span class="math inline">\(X_i=0\)</span>, <span class="math inline">\(log(\frac{p_i}{1-p_i}) = \beta_0\)</span> which is interpreted as the baseline or reference log-odds of probability.</p>
<p><span class="math inline">\(\beta_1\)</span> is interpreted as the CHANGE in log-odds per one unit change in <span class="math inline">\(X_i\)</span>. Conversely, <span class="math inline">\(e^{\beta_1}\)</span> is defines the odds-ratio.</p>
<p><span class="math display">\[
log(\frac{p_i}{1-p_i}) = \beta_0 + \beta_1 x_i, \text{ versus } log(\frac{p^*_i}{1-p^*_i}) = \beta_0 + \beta_1 (x_i + 1)
\]</span></p>
<p>then</p>
<p><span class="math display">\[
log\left(\frac{p^*_i/(1-p^*_i)}{p_i/(1-p_i)}\right) = \beta_1
\]</span></p>
<div class="callout callout-style-simple callout-note no-icon" style="color: black">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Key property:</strong> <span class="math inline">\(e^{\beta_1}\)</span> does not depend on <span class="math inline">\(x_i\)</span> — the odds ratio is <strong>constant</strong> across all baseline values of <span class="math inline">\(X\)</span>. This is the <strong>proportional odds</strong> property of the logistic model.</p>
</div>
</div>
</div>
<p>In the multiple logistic regression, <span class="math inline">\(\beta_k\)</span> is the log odds ratio associated with covariate <span class="math inline">\(k\)</span> while controlling for other covariates.</p>
<hr>
</section>
<section id="odds-ratio-indicator-variables" class="level4">
<h4 class="anchored" data-anchor-id="odds-ratio-indicator-variables">Odds Ratio &amp; Indicator Variables</h4>
<p>Odds Ratio interpretation is helpful for indicator variables. Let <span class="math inline">\(x_i=1\)</span> in exposed group and <span class="math inline">\(x_i=0\)</span> in unexposed group. Then:</p>
<p><span class="math display">\[
e^{\beta_1} = \frac{\{\frac{p(y_i=1|x_i=1)}{p(y_i=0|x_i=1)}\}}{\frac{p(y_i=1|x_i=0)}{p(y_i=0|x_i=0)}\}} = \frac{\text{odds(Exposed)}}{\text{odds(Unexposed)}}
\]</span></p>
<ul>
<li><p>OR&gt;1 means a positive association</p></li>
<li><p>OR&lt;1 means a negative association</p></li>
<li><p>OR=1 means no difference between exposure groups.</p></li>
</ul>
<p>It is really important to understand that the change in log-odds per one unit change in <span class="math inline">\(X_i\)</span> is not constant, i.e, that change in log-odds depends on the value of <span class="math inline">\(X_i\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#The Logit Function</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>p.i <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.001</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>g_p.i <span class="ot">&lt;-</span> <span class="fu">log</span>(p.i<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p.i))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p.i, g_p.i, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">xlab =</span><span class="st">"p"</span>, <span class="at">ylab =</span> <span class="st">"Logit Function"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Module_2A_GLM_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#The Logistic Function</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>p_i <span class="ot">&lt;-</span> <span class="fu">exp</span>(g_p.i)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">exp</span>(g_p.i))</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(g_p.i, p_i, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">xlab =</span> <span class="st">"x"</span>, <span class="at">ylab =</span> <span class="st">"Logistic Function"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Module_2A_GLM_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>What are the effects of changing the baseline odds?</p>
<p><span class="math display">\[
\begin{align}
logit(p_i)&amp; = \beta_0 + x_i\\
\mu_i = P(Y_i =1) &amp;= \frac{e^{\beta_0 + x_i}}{1 + e^{\beta_0 + x_i}}
\end{align}
\]</span></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Module_2A_GLM_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Note: The shape is maintained, and the baseline (intercept) probability changes.</p>
<p>What are the effects of the change in slope?</p>
<p><span class="math display">\[
\begin{align}
logit(p_i)&amp; = \beta_1 x_i\\
\mu_i = P(Y_i =1) = \frac{e^{\beta_1 x_i}}{1 + e^{\beta_1 x_i}}
\end{align}
\]</span></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Module_2A_GLM_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Note how the steepness changes with difference in slopes. Also note how the direction changes depending on the effect changes.</p>
<hr>
</section>
<section id="fitting-a-logistic-regression-in-r" class="level4">
<h4 class="anchored" data-anchor-id="fitting-a-logistic-regression-in-r">Fitting a logistic regression in R</h4>
<p>We come back to our motivating example using data on preterm births in Georgia (2001).</p>
<p>Fitting the GLM model in R is very similar to fitting a linear regression model. We need to specify the distribution as <span style="color: blue;">binomial</span>and the link function as <span style="color: blue;">logit</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">### The GLM Function</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"/Users/emilypeterson/Library/CloudStorage/OneDrive-EmoryUniversity/BIOS 526/BIOS526_Book/data/PTB.Rdata"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">formula =</span> ptb <span class="sc">~</span> age <span class="sc">+</span> male <span class="sc">+</span> tobacco, </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> dat)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = ptb ~ age + male + tobacco, family = binomial(link = "logit"), 
    data = dat)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -2.4212664  0.0631355 -38.350  &lt; 2e-16 ***
age         -0.0006295  0.0021596  -0.291  0.77068    
maleM        0.0723659  0.0258672   2.798  0.00515 ** 
tobacco      0.4096495  0.0534627   7.662 1.83e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 44908  on 77339  degrees of freedom
Residual deviance: 44846  on 77336  degrees of freedom
AIC: 44854

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p><strong>Model Interpretation</strong></p>
<ul>
<li><p>Preterm delivery was significantly associated with male babies (p-value = 0.005) when controlling for age and mother’s smoking status. The <u>odds ratio</u> of a preterm birth for a male baby versus a female baby was 1.07 (95% CI: 1.02, 1.13).</p></li>
<li><p><span class="math inline">\(OR = e^{0.0723} = 1.07\)</span> with 95% CI = (1.02, 1.13).</p>
<ul>
<li><p>How we get CIs: <span class="math inline">\(e^{(0.0723 \pm 1.96 * 0.0258)}\)</span>.</p>
<p>NOTE: TRANSFORM THE INTERVALS. DO NOT TRANSFORM THE STANDARD ERRORS (this requires the delta method).</p></li>
</ul></li>
<li><p>Preterm delivery was significantly associated with whether the mother smoked during pregnancy (p&lt;0.001) when controlling for age and the baby’s sex.</p></li>
<li><p><span class="math inline">\(OR = e^{0.409} = 1.51 (1.36, 1.67)\)</span>.</p></li>
<li><p>The baseline proportion (female babies born to mother of age 25 who didn’t smoke) of preterm delivery was</p>
<p><span class="math display">\[
\frac{e^{-2.42}}{1 + e^{-2.42}} = 0.08.
\]</span></p></li>
<li><p>We didn’t find an effect of mother’s age.</p></li>
</ul>
<hr>
</section>
<section id="wald-test" class="level4">
<h4 class="anchored" data-anchor-id="wald-test">Wald Test</h4>
<p>The <strong>Wald Test</strong> evaluates the significance of individual regression coefficients directly by comparing the estimated coefficient to its standard error. The Wald Test relied on the fact that MLEs of the coefficients are approximately normally distributed for large samples (Central Limit Theorem).</p>
<div class="illustration callout callout-style-simple callout-note no-icon" style="color: blue">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Wald test under regularity conditions and assuming asymptotic results,</p>
<p><span class="math display">\[
\begin{align}
\hat{\beta} &amp;\sim N(\beta, I(\beta)^{-1})\\
I(\beta) &amp;= E\left\{\left(\frac{\partial l}{\partial \beta}\right)\left(\frac{\partial l}{\partial \beta}\right)'\right\}\\
&amp;= -E\frac{\partial^2 l}{\partial \beta \partial \beta'}
\end{align}
\]</span></p>
<ul>
<li><p><span class="math inline">\(I(\beta)\)</span> is called the Fisher information matrix (see Wood p.106). The standard error of <span class="math inline">\(\hat{\beta}\)</span> is derived from <span class="math inline">\(I(\beta)^{-1}\)</span>.</p></li>
<li><p>The Wald test uses the standardized statistic: <span class="math display">\[
Z = \frac{\hat{\beta}_i}{s.e.(\hat{\beta}_i)}
\]</span></p></li>
</ul>
</div>
</div>
</div>
<ul>
<li><p>The <span class="math inline">\(Z-\)</span> column is calculated as <span class="math inline">\(z = \frac{\hat{\beta}_i}{SE(\hat{\beta}_i)}\)</span>.</p></li>
<li><p>The p-values are derived from the z-statistic <span class="math inline">\(H_0 : \beta_i = 0\)</span>. For example, for , <span class="math inline">\(z \approx 2.798\)</span> with <span class="math inline">\(p=0.005\)</span> indicating male babies are significantly associated with preterm birth holding other variables constant.</p></li>
</ul>
<hr>
</section>
<section id="likelihood-ratio-test" class="level4">
<h4 class="anchored" data-anchor-id="likelihood-ratio-test">Likelihood Ratio Test</h4>
<p>In logistic regression, we use the Likelihood Ratio Test to determine whether adding predictors significantly improves model fit, since standard F-tests from linear regression do not apply. The Likelihood Ratio Test (LRT) provides a natural way to compare nested models by examining how much better the full model fits the data compared to a reduced model (with some parameters set to zero): <span style="color: blue;">How can we test whether which model is better?</span></p>
<p>The likelihood ratio test (LRT) is used to test the null hypothesis that any subset of the <span class="math inline">\(\beta's\)</span> is equal to 0. The number of <span class="math inline">\(\beta's\)</span> in the full model is <span class="math inline">\(k+1\)</span>, while the number of <span class="math inline">\(\beta's\)</span> in the reduced model is <span class="math inline">\(r+1\)</span>. (Remember the reduced model is the model that results when the <span class="math inline">\(\beta's\)</span> in the null hypothesis are set to 0). Thus, the number of <span class="math inline">\(\beta's\)</span> being tested in the null hypothesis is <span class="math inline">\((k+1) - (r+1) = k-r\)</span>.</p>
<div class="illustration callout callout-style-simple callout-note no-icon" style="color: blue">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>The Likelihood Ratio Test is given by:</p>
<p><span class="math display">\[
LR= \frac{max_{H_0}L(\beta)}{max_{H_A}L(\beta)}
\]</span> This gives the ratio of the likelihood of the null model evaluated at the MLEs to the likelihood of the full model evaluated at the MLEs.</p>
<ul>
<li>In the normal case, this is the analogous to the F-test described in Chapter 1.</li>
</ul>
<p>The likelihood ratio test statistic is given by:</p>
<p><span class="math display">\[
\lambda_{LR} = -2[l(\hat{\beta}_{reduced}) - l(\hat{\beta}_{full})]
\]</span></p>
<ul>
<li><p>The difference follows a Chi-square distribution, i.e.,</p>
<p><span class="math display">\[
\lambda_{LR} &gt; \chi^2_{\nu, 1-\alpha}
\]</span></p></li>
</ul>
<p>where <span class="math inline">\(\nu\)</span> denotes the different in number of parameters, i.e., <span class="math inline">\(k-r\)</span> = degrees of freedom.</p>
</div>
</div>
</div>
<p>The likelihood for a binary logistic regression is given by:</p>
<p><span class="math display">\[
L(\beta; \mathbf{y}, \mathbf{X}) = \prod_{i=1}^{n} \pi_i^{y_i} (1-\pi_i)^{1-y_i}
\]</span></p>
<p>This yields a log-likelihood of:</p>
<p><span class="math display">\[
\begin{align*}
l(\beta) &amp;= \sum_{i=1}^n [y_i log(\pi_i)  + (1-y_i) log(1-\pi_i)\\
&amp;= \sum_{i=1}^n [y_i \mathbf{X}_i \beta - log(1+ exp(\mathbf{X}_i \beta))]
\end{align*}
\]</span></p>
<p>Maximizing the LL has <u>no closed form solution</u>, so a technique used to obtain MLEs <span class="math inline">\(\hat{\beta}\)</span> is iteratively reweighted least squares (not covered here).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table (Type II tests)

Response: ptb
        LR Chisq Df Pr(&gt;Chisq)    
age        0.085  1   0.770669    
male       7.834  1   0.005126 ** 
tobacco   53.648  1  2.399e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li><p>Comparing the full vs reduced model with everything EXCEPT age, we see a <span class="math inline">\(\chi^2\)</span> statistic of 0.085 with a p-value of 0.77 meaning that removing age does not significantly worsen the model fit, i.e., age is not a significant predictor when controlling for other variables.</p></li>
<li><p>Removing the male variable significantly worsens model fit <span class="math inline">\(p&lt;0.01\)</span>, meaning this is a significant predictor.</p></li>
<li><p>Tobacco use has a <span class="math inline">\(\chi^2\)</span> statistic of 53.65 and a p-value of &lt;0.001, meaning it is a highly significant predictor, and removing it significantly reduces model fit.</p></li>
</ul>
<hr>
</section>
<section id="wald-vs.-lrt-when-to-use-which" class="level4">
<h4 class="anchored" data-anchor-id="wald-vs.-lrt-when-to-use-which">Wald vs.&nbsp;LRT: When to Use Which</h4>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Wald Test</strong></th>
<th><strong>Likelihood Ratio Test</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Statistic</td>
<td><span class="math inline">\(Z = \hat{\beta}_j / \text{SE}(\hat{\beta}_j)\)</span></td>
<td><span class="math inline">\(\lambda_{LR} = -2[l_{\text{reduced}} - l_{\text{full}}]\)</span></td>
</tr>
<tr class="even">
<td>Distribution</td>
<td><span class="math inline">\(N(0,1)\)</span></td>
<td><span class="math inline">\(\chi^2_{k-r}\)</span></td>
</tr>
<tr class="odd">
<td>Best for</td>
<td>Single coefficient</td>
<td>Nested model comparison</td>
</tr>
<tr class="even">
<td>Requires</td>
<td>Large <span class="math inline">\(n\)</span> (asymptotics)</td>
<td>Same data, same likelihood type</td>
</tr>
<tr class="odd">
<td>More reliable in small <span class="math inline">\(n\)</span>?</td>
<td>No</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>In R</td>
<td><code>summary(fit)</code></td>
<td><code>anova(..., test="LRT")</code> or <code>car::Anova(fit)</code></td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary"><span style="color: purple;">Summary</span></h2>
<table class="table">
<colgroup>
<col style="width: 22%">
<col style="width: 77%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Section</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>What is the model?</strong></td>
<td>A <strong>generalized linear model (GLM)</strong> links the expected response <span class="math inline">\(E(Y|X) = \mu\)</span> to predictors via a link function: <span class="math inline">\(g(\mu) = \beta_0 + \sum_k \beta_k x_{ik}\)</span>. <br> The response <span class="math inline">\(Y\)</span> must follow a distribution in the <strong>exponential family</strong> (e.g., Normal, Bernoulli, Binomial).</td>
</tr>
<tr class="even">
<td><strong>Model Components</strong></td>
<td><strong>1. Random component:</strong> Distribution of <span class="math inline">\(Y\)</span> (e.g., Bernoulli for binary data). <br> <strong>2. Systematic component:</strong> Linear predictor <span class="math inline">\(\eta_i = x_i' \beta\)</span>. <br> <strong>3. Link function:</strong> <span class="math inline">\(g(\mu_i)\)</span> maps mean response to <span class="math inline">\(\eta_i\)</span>.</td>
</tr>
<tr class="odd">
<td><strong>Logistic Regression</strong></td>
<td>Special case of GLM for <strong>binary outcomes</strong> (<span class="math inline">\(Y \in \{0,1\}\)</span>) using the logit link: <span class="math inline">\(g(p) = \log \frac{p}{1-p}\)</span>. <br> Coefficients <span class="math inline">\(\beta_j\)</span> represent changes in <strong>log-odds</strong>, while <span class="math inline">\(e^{\beta_j}\)</span> are <strong>odds ratios</strong>.</td>
</tr>
<tr class="even">
<td><strong>Model Assumptions</strong></td>
<td>- Correct link function (e.g., logit). <br> - Independent observations. <br> - Mean and variance correctly specified for Bernoulli data: <span class="math inline">\(E(Y)=p\)</span>, <span class="math inline">\(Var(Y)=p(1-p)\)</span>.</td>
</tr>
<tr class="odd">
<td><strong>Hypothesis Testing</strong></td>
<td><strong>Wald Test:</strong> Tests <span class="math inline">\(H_0: \beta_j = 0\)</span> using <span class="math inline">\(Z = \hat{\beta}_j / \text{SE}(\hat{\beta}_j)\)</span>. <br> <strong>Likelihood Ratio Test (LRT):</strong> Compares nested models with <span class="math inline">\(\lambda_{LR} = -2 [l_{reduced} - l_{full}] \sim \chi^2\)</span>.</td>
</tr>
<tr class="even">
<td><strong>Interpretation</strong></td>
<td>- <span class="math inline">\(\beta_j\)</span>: Change in log-odds of success for a one-unit increase in <span class="math inline">\(X_j\)</span>, holding other variables constant. <br> - <span class="math inline">\(e^{\beta_j}\)</span>: Odds ratio (OR) for a one-unit change in <span class="math inline">\(X_j\)</span>. <br> - Intercept <span class="math inline">\(\beta_0\)</span>: Baseline log-odds for reference group.</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Module_1_LMM_Cheet.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Module 1 Cheat Sheet</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Module_2B_GLM.html" class="pagination-link">
        <span class="nav-page-text">Module 2B Generalized Linear Models</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>