<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>BIOS 526 Modern Regression Analysis - Module 0: Multiple Linear Regression Review</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Module_1A_LMM.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Module_0_MLR.html">Module 0: Multiple Linear Regression Review</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">BIOS 526 Modern Regression Analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_0_MLR.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Module 0: Multiple Linear Regression Review</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1A_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1A Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1B_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1B Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1C_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1C Random Intercepts and Slopes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1_LMM_Cheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2A_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2A Generalized Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2B_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2B Generalized Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2C_GLMMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2C Generalized Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2D_GLMMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2D Generalized Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2_GLM_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3A_GEEs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3A Marginal Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3B_GEEs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3B Marginal Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3_GEE_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4A_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4A Basis Expansion and Parametric Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4B_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4B Parametric Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4C_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4C Penalized Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4_Splines_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5A_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5A Generalized Additive Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5B_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5B Generalized Additive Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5_GAM_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_6_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 6 Model Selection, Diagnostics, &amp; Regression Workflow</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#motivation-and-examples" id="toc-motivation-and-examples" class="nav-link active" data-scroll-target="#motivation-and-examples">Motivation and Examples</a></li>
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression"><u>Simple Linear Regression</u></a></li>
  <li><a href="#ols-calculation-in-r" id="toc-ols-calculation-in-r" class="nav-link" data-scroll-target="#ols-calculation-in-r">OLS Calculation in R</a></li>
  <li><a href="#statistical-linear-regression-inference" id="toc-statistical-linear-regression-inference" class="nav-link" data-scroll-target="#statistical-linear-regression-inference"><u>Statistical Linear Regression &amp; Inference</u></a></li>
  <li><a href="#prediction-interval-for-a-new-observation" id="toc-prediction-interval-for-a-new-observation" class="nav-link" data-scroll-target="#prediction-interval-for-a-new-observation"><u>Prediction Interval for a New Observation</u></a></li>
  <li><a href="#model-diagnostics" id="toc-model-diagnostics" class="nav-link" data-scroll-target="#model-diagnostics"><u>Model Diagnostics</u></a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing"><u>Hypothesis Testing</u></a></li>
  <li><a href="#confounding" id="toc-confounding" class="nav-link" data-scroll-target="#confounding"><u>Confounding</u></a></li>
  <li><a href="#adjusting-for-confounding" id="toc-adjusting-for-confounding" class="nav-link" data-scroll-target="#adjusting-for-confounding">Adjusting for Confounding:</a>
  <ul class="collapse">
  <li><a href="#categorical-variables" id="toc-categorical-variables" class="nav-link" data-scroll-target="#categorical-variables">Categorical Variables</a></li>
  </ul></li>
  <li><a href="#variance-inflation-factors" id="toc-variance-inflation-factors" class="nav-link" data-scroll-target="#variance-inflation-factors">Variance Inflation Factors</a></li>
  <li><a href="#interaction-effects-effect-modification" id="toc-interaction-effects-effect-modification" class="nav-link" data-scroll-target="#interaction-effects-effect-modification">Interaction Effects: Effect Modification</a></li>
  <li><a href="#f-test-of-interaction" id="toc-f-test-of-interaction" class="nav-link" data-scroll-target="#f-test-of-interaction">F-test of interaction</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span style="color: purple;">Summary</span></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Module 0: Multiple Linear Regression Review</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell" data-hide="true">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.4.3</code></pre>
</div>
</div>
<p><strong>Readings</strong></p>
<ul>
<li>Review matrix algebra <a href="https://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf">Matrix Cookbook</a>.</li>
<li>BIOS 509 notes on Applied Linear Regression.<br>
</li>
<li>Gelman &amp; Hill-style regression intuition (figure referenced in class).</li>
</ul>
<p><strong>Overview &amp; Concepts:</strong> In this module you will get a brief review of concepts learned in BIOS 509 including the multiple linear regression (MLR) framework for <strong>estimation, interpretation, prediction, and diagnostics</strong>. This material will not be included in the labs or quizzes, but is simply a review guide for you to brush up on material needed for Modules 1-3.</p>
<ul>
<li><p>Linear regression model in matrix notation</p></li>
<li><p>Inference for regression coefficient estimates, expected values, and predictions.</p></li>
<li><p>Dummy variables</p></li>
<li><p>Effect modification and confounding</p></li>
</ul>
<hr>
<section id="motivation-and-examples" class="level3">
<h3 class="anchored" data-anchor-id="motivation-and-examples">Motivation and Examples</h3>
<div class="illustration callout callout-style-default callout-important callout-titled" style="color: red">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Multiple Linear Regression (MLR)</strong> is the standard extension of simple linear regression to include two or more predictors.</p>
<p>Formally:</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_{i1} + \cdots + \beta_p x_{ip} + \epsilon_i,
\quad \epsilon_i \sim N(0,\sigma^2)
\]</span></p>
<p><span class="math inline">\(y_i\)</span> = outcome (continuous response)</p>
<p><span class="math inline">\(x_{ij}\)</span> = predictor variables (continuous or categorical)</p>
<p><span class="math inline">\(\beta_j\)</span> = regression coefficients (effects of predictors, holding others constant)</p>
<p><span class="math inline">\(\epsilon_i\)</span> = error term</p>
<p><strong>Matrix form</strong></p>
<p><span class="math display">\[
\mathbf{y} = \mathbf{X}\boldsymbol{\beta} + \boldsymbol{\epsilon},
\quad \mathbb{E}[\boldsymbol{\epsilon}] = \mathbf{0},
\quad \operatorname{Var}(\boldsymbol{\epsilon}) = \sigma^2 \mathbf{I}
\]</span></p>
<p><strong>Key points about MLR:</strong></p>
<ul>
<li><p>Goal: quantify how multiple predictors are simultaneously associated with an outcome.</p></li>
<li><p>Interpretation: each <span class="math inline">\(\beta_j\)</span> is the average change in <span class="math inline">\(y\)</span> for a one-unit change in <span class="math inline">\(x_{j}\)</span>, holding other predictors fixed.</p></li>
<li><p>Uses: adjust for confounding, test effect modification (interactions), improve prediction accuracy.</p></li>
<li><p>Assumptions: linearity, independence, constant variance (homoscedasticity), and normally distributed errors.</p></li>
</ul>
<p>In short: MLR models a continuous outcome as a linear combination of multiple explanatory variables, enabling adjusted and interpretable population-level associations.</p>
</div>
</div>
<p><strong>Motivating Example:(NLSY):</strong> maternal traits vs.&nbsp;child cognitive score (age 3).</p>
<p>We want to answer the question: <strong>What maternal traits are associated with a child’s cognitive score at age 3?</strong></p>
<p>Variables:</p>
<ul>
<li><code>score</code>: cognitive test score (outcome)</li>
<li><code>age</code>: maternal age at delivery (numeric)</li>
<li><code>edu</code>: maternal education — 1: &lt;HS, 2: HS, 3: some college, 4: college+</li>
</ul>
<p><strong>Model (baseline):</strong></p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1 \text{age}_i + \epsilon_i\]</span></p>
<p><strong>MLR (with confounding):</strong></p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1\text{age}_i + \beta_2\mathbb{1}(\text{edu}=2) + \beta_3\mathbb{1}(\text{edu}=3) + \beta_4\mathbb{1}(\text{edu}=4) + \epsilon_i
\]</span></p>
<p>Below we give some quick visuals</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 400
Columns: 3
$ score &lt;dbl&gt; 120, 89, 78, 42, 115, 97, 94, 68, 103, 94, 117, 64, 72, 104, 78,…
$ edu   &lt;dbl&gt; 2, 1, 2, 1, 4, 1, 1, 2, 3, 3, 2, 4, 2, 2, 3, 1, 1, 3, 3, 2, 2, 2…
$ age   &lt;dbl&gt; 21, 17, 19, 20, 26, 20, 20, 24, 19, 24, 24, 29, 19, 23, 26, 22, …</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Module_0_MLR_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
<section id="simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression"><u>Simple Linear Regression</u></h2>
<p>Linear regression is a method that summarizes how the average values of a numerical outcome variable vary over subpopulations (covariate values) defined by linear functions of predictors. Two goals of linear regression:</p>
<ol type="1">
<li><p><em>Prediction of outcome values given fixed predictor values.</em></p></li>
<li><p><em>Assessment of impact of predictors on the outcome (Estimation).</em></p></li>
</ol>
<p>Let <span class="math inline">\(y_i\)</span> denote the test score for a given child <span class="math inline">\(i\)</span>. <span class="math inline">\(age_i\)</span> denotes the corresponding maternal age at delivery for mom <span class="math inline">\(i\)</span> corresponding to child <span class="math inline">\(i\)</span>, and <span class="math inline">\(\epsilon_i\)</span> denotes the error term. We will consider the following linear model:</p>
<p><span id="eq-one"><span class="math display">\[y_i = \beta_0 + \beta_1 \cdot age_i + \epsilon_i, \quad i = 1,2,3,...,400 \tag{1}\]</span></span></p>
<p>We can write Eq. 1 in matrix form by stacking observations by row:</p>
<p><span class="math display">\[\begin{align}
\mathbf{Y}&amp; = \begin{bmatrix} y_1 \\ y_2\\ \vdots \\ y_n \end{bmatrix} =
\begin{bmatrix}
\beta_0 + \beta_1 x_1\\ \beta_0 + \beta_1 x_2 \\ \vdots \\ \beta_0 + \beta_1 x_n \end{bmatrix} + \begin{bmatrix} \epsilon_1 \\ \epsilon_2 \\  \vdots \\ \epsilon_n \end{bmatrix}\\
&amp; = \begin{bmatrix} 1 &amp; x_1\\1 &amp; x_2\\ \vdots \\ 1 &amp; x_n\end{bmatrix} \begin{bmatrix}\beta_0 \\ \beta_1\end{bmatrix} + \begin{bmatrix} \epsilon_1 \\ \epsilon_2 \\  \vdots \\ \epsilon_n \end{bmatrix}\\
&amp;= \mathbf{X\beta + \epsilon}
\end{align}\]</span></p>
<p>Clearly, we cannot find <span class="math inline">\(\mathbf{\beta}\)</span> such that this model fits all of our data perfectly.</p>
<p><strong>Model Assumptions:</strong></p>
<ul>
<li><p><span class="math inline">\(y_i\)</span> is a linear function of <span class="math inline">\(age_i\)</span>, i.e, <span class="math inline">\(E(\mathbf{Y}) = \mathbf{X\beta} = \mathbf{Age\beta}\)</span> is linear in the <span class="math inline">\(\beta's\)</span>.</p></li>
<li><p><span class="math inline">\(\beta_0=\)</span> the test score for a child born of a mother at age=0 (not meaningful!)</p></li>
<li><p><span class="math inline">\(\beta_1=\)</span> average increase in test score associated with one year increase in maternal age.</p></li>
<li><p><span class="math inline">\(E(\epsilon_i) = 0\)</span> [Expectation of the errors is zero].</p></li>
</ul>
<hr>
<section id="least-squares-solution" class="level4">
<h4 class="anchored" data-anchor-id="least-squares-solution"><u>Least Squares Solution</u></h4>
<p><strong>Our aim is to find estimates of</strong> <span class="math inline">\(\beta_0\)</span> <strong>and</strong> <span class="math inline">\(\beta_1\)</span> <strong>that “best” fit the data, but what does “best” mean?</strong></p>
<p>We seek <span class="math inline">\((\hat{\beta}_0, \hat{\beta}_1)\)</span> that minimizes a <span style="color: red;">loss function</span>.</p>
<p>Our approach is to minimize the sum of <span style="color: red;">squared differences</span> between <span class="math inline">\(\mathbf{Y}\)</span> and <span class="math inline">\(\hat{Y} = \mathbf{X\hat{\beta}}\)</span>, i.e., this defines the differences between <span class="math inline">\(\mathbf{Y}\)</span> and the predicted value <span class="math inline">\(\hat{Y}\)</span> based on a fixed set of <span class="math inline">\(\beta's\)</span>.</p>
<div class="illustration callout callout-style-simple callout-note no-icon callout-titled" style="color: blue">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Theorem
</div>
</div>
<div class="callout-body-container callout-body">
<p>If <span class="math inline">\(\mathbf{Y} = \mathbf{X\beta} + \mathbf{\epsilon}\)</span> then the value of <span class="math inline">\(\hat{\beta}\)</span> that minimizes <span class="math inline">\((\mathbf{Y - \hat{Y}})^T(\mathbf{Y - \hat{Y}})\)</span> is <span class="math inline">\(\hat{\beta} = (X'X)^{-1} X'y\)</span>.</p>
<ul>
<li><p><span class="math inline">\(\mathbf{\hat{Y}} = \mathbf{X \hat{\beta}}\)</span> is the fitted (predicted) value.</p></li>
<li><p><span class="math inline">\(\mathbf{\hat{\epsilon}} = \mathbf{Y} - \mathbf{X\hat{\beta}}\)</span> defines the residual error.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon callout-titled" style="color:gray">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Derivation (matrix calculus)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We estimate <span class="math inline">\(\hat\beta\)</span> by minimizing the <strong>residual sum of squares</strong> (RSS):</p>
<p><span class="math display">\[
\hat\beta = argmin_{\beta}\; S(\beta),
\qquad
S(\beta)=|\mathbf{y}-\mathbf{X}\beta|_2^2
=(\mathbf{y}-\mathbf{X}\beta)^\top(\mathbf{y}-\mathbf{X}\beta).
\]</span></p>
<p><strong>Expand the residual quadratic:</strong> <span class="math display">\[
\begin{aligned}
S(\beta)
&amp;= \mathbf{y}^\top\mathbf{y}
- 2\,\beta^\top\mathbf{X}^\top\mathbf{y}
+ \beta^\top\mathbf{X}^\top\mathbf{X}\,\beta.
\end{aligned}
\]</span></p>
<p><strong>Differentiate and set to zero (normal equations):</strong> <span class="math display">\[
\nabla_\beta S(\beta)
= -2\,\mathbf{X}^\top\mathbf{y}
+ 2\,\mathbf{X}^\top\mathbf{X}\,\beta
= \mathbf{0}
\quad\Longrightarrow\quad
\mathbf{X}^\top\mathbf{X}\,\hat\beta
= \mathbf{X}^\top\mathbf{y}.
\]</span></p>
<p><strong>Solution (full column rank</strong> <span class="math inline">\(\mathbf{X}\)</span>: <span class="math display">\[
\hat\beta_{OLS}
= (\mathbf{X}^\top\mathbf{X})^{-1}\mathbf{X}^\top\mathbf{y}.
\]</span> For OLS, we have a nice closed-form solution.</p>
<p>Other loss functions or models often require iterative optimization routines.</p>
<p><strong>Fitted values &amp; projection:</strong> <span class="math display">\[
\hat{\mathbf{y}}=\mathbf{X}\hat\beta
= \underbrace{\mathbf{X}(\mathbf{X}^\top\mathbf{X})^{-1}\mathbf{X}^\top}_{\mathbf{H}}\mathbf{y},
\quad
\text{with }\mathbf{H}^\top=\mathbf{H},\;\mathbf{H}^2=\mathbf{H},\;\operatorname{tr}(\mathbf{H})=p \text{ (number of predictors)}.
\]</span></p>
<p><strong>Orthogonality of residuals: We assume independence between covariate values and residuals.</strong> <span class="math display">\[
\mathbf{r}=\mathbf{y}-\hat{\mathbf{y}},\qquad
\mathbf{X}^\top\mathbf{r}=\mathbf{0}.
\]</span></p>
</div>
</div>
</div>
</section>
<section id="geometric-interpretation-of-the-ols-estimate" class="level4">
<h4 class="anchored" data-anchor-id="geometric-interpretation-of-the-ols-estimate">Geometric Interpretation of the OLS estimate</h4>
<p>The fitted values <span class="math inline">\(\hat{y}\)</span> are a linear transformation of <span class="math inline">\(y\)</span>. We see from the figure <span class="math inline">\(y\)</span> in real space is projected on <span class="math inline">\(\hat{y}\)</span> in model space.</p>
<ul>
<li><p>The <u>HAT</u> <u>matrix</u> is defined as <span class="math inline">\(\mathbf{H} = \mathbf{X(X^{T} X)^{-1}X^T}\)</span>. It is a projection matrix that projects <span class="math inline">\(y\)</span> <span class="math inline">\(\rightarrow\)</span> <span class="math inline">\(\hat{y}\)</span>.</p>
<p><span class="math display">\[
\begin{align}
\mathbf{\hat{y}} &amp;= \mathbf{X\hat{\beta}}\\
&amp;= \mathbf{X(X'X)^{-1}X'y}
\end{align}
\]</span></p></li>
<li><p>The projection matrix is idempotent, i.e., <span class="math inline">\(HH=H\)</span>.</p></li>
<li><p>The trace <span class="math inline">\(=\)</span> rank of <span class="math inline">\(X\)</span> or the number of covariates plus intercept, i.e, <span class="math inline">\(tr(H) = p\)</span>.</p></li>
<li><p><span class="math inline">\(\hat{\mathbf{Y}}\)</span> and <span class="math inline">\(\mathbf{\hat{\epsilon}}\)</span> are independent, i.e., orthogonal (perpendicular in model space).</p></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig/OLSgeo2.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">A geometrical interpretation of least squares.</figcaption>
</figure>
</div>
<hr>
</section>
<section id="properties-of-the-ols-estimator-hatbeta" class="level4">
<h4 class="anchored" data-anchor-id="properties-of-the-ols-estimator-hatbeta"><u>Properties of the OLS Estimator <span class="math inline">\(\hat{\beta}\)</span></u></h4>
<ol type="1">
<li>If <span class="math inline">\(E(Y) = X\beta\)</span> then <span class="math inline">\(\hat{\beta}\)</span> is unbiased for <span class="math inline">\(\beta\)</span>.</li>
</ol>
<p><span class="math display">\[
\begin{align}
E(\hat{\beta}) &amp; = E[(X^TX)^{-1} X^Ty]\\
&amp; = (X^T X)^{-1} X^T E(y)\\
&amp; =(X^T X)^{-1} X^T X \beta\\
&amp; = \beta
\end{align}
\]</span></p>
<ol start="2" type="1">
<li><p><span class="math inline">\(\hat{\beta}\)</span> is consistent estimation of <span class="math inline">\(\beta\)</span> under very general assumptions, i.e., <span class="math inline">\(lim_{n\rightarrow \infty} P(|\hat{\beta} - \beta|&gt;\epsilon) = 0\)</span>.</p></li>
<li><p><span class="math inline">\(\mathbf{\hat{Y}}\)</span> is an unbiased estimator of the mean trend <span class="math inline">\(\mathbf{X\beta}\)</span>.</p></li>
<li><p>If <span class="math inline">\(cov(y) = \sigma^2 I\)</span>, the covariance of the estimator <span class="math inline">\(cov(\mathbf{\hat{\beta}}) = \sigma^2 (X'X)^{-1}\)</span>.</p></li>
</ol>
<p><strong>Find the</strong> <span class="math inline">\(\operatorname{Cov}(\hat{\beta})\)</span></p>
<p>We have the linear model <span class="math display">\[
\mathbf{y} = \mathbf{X}\beta + \boldsymbol{\epsilon},
\qquad \mathbb{E}[\boldsymbol{\epsilon}] = \mathbf{0},
\qquad \operatorname{Var}(\boldsymbol{\epsilon}) = \sigma^2 \mathbf{I}.
\]</span></p>
<p>The OLS estimator is <span class="math display">\[
\hat{\beta} = (\mathbf{X}^\top \mathbf{X})^{-1}\mathbf{X}^\top \mathbf{y}
= \beta + (\mathbf{X}^\top \mathbf{X})^{-1}\mathbf{X}^\top \boldsymbol{\epsilon}.
\]</span></p>
<p>Therefore,</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{Cov}(\hat{\beta})
&amp;= \operatorname{Var}\!\left[(\mathbf{X}^\top \mathbf{X})^{-1}\mathbf{X}^\top \boldsymbol{\epsilon}\right] \\
&amp;= (\mathbf{X}^\top \mathbf{X})^{-1}\mathbf{X}^\top
      \underbrace{\operatorname{Var}(\boldsymbol{\epsilon})}_{\sigma^2 \mathbf{I}}
      \mathbf{X}(\mathbf{X}^\top \mathbf{X})^{-1} \\
&amp;= \sigma^2 \, (\mathbf{X}^\top \mathbf{X})^{-1}.
\end{aligned}
\]</span></p>
<div class="illustration callout callout-style-simple callout-note no-icon callout-titled" style="color: blue">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Gauss-Markov Theorem:
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Gauss-Markov Theorem states that, under the classical linear regression assumptions, the OLS estimator is the <strong>Best Linear Unbiased Estimator (BLUE)</strong> of the coefficients—that is, it has the lowest variance among all linear and unbiased estimators.</p>
<ul>
<li><p><span class="math inline">\(\mathbf{Y} = \mathbf{X\beta} +\epsilon\)</span></p></li>
<li><p><span class="math inline">\(E(\epsilon) = 0\)</span> and <span class="math inline">\(cov(\epsilon) = \sigma^2 I\)</span></p></li>
<li><p><span class="math inline">\(var(\hat{\beta}) = \sigma^2 (X'X)^{-1}\)</span></p></li>
<li><p><span class="math inline">\(\hat{\beta}\)</span> is the best (minimum variance) unbiased estimator (BLUE) for <span class="math inline">\(\mathbf{\beta}\)</span>.</p></li>
</ul>
</div>
</div>
<hr>
</section>
</section>
<section id="ols-calculation-in-r" class="level2">
<h2 class="anchored" data-anchor-id="ols-calculation-in-r">OLS Calculation in R</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate beta manually</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>X <span class="ot">=</span> <span class="fu">cbind</span>(<span class="dv">1</span>, dat<span class="sc">$</span>age) <span class="co">#Design Matrix</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> dat<span class="sc">$</span>score <span class="co">#Response/Outcome Vector</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">=</span> <span class="fu">solve</span>( <span class="fu">t</span>(X) <span class="sc">%*%</span> X) <span class="sc">%*%</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> Y</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>beta</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           [,1]
[1,] 67.7826813
[2,]  0.8402729</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Visualize the univariate association</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(score <span class="sc">~</span> age, <span class="at">data =</span> dat, <span class="at">xlab =</span> <span class="st">"Age"</span>, <span class="at">ylab =</span> <span class="st">"Score"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(beta, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Module_0_MLR_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We see that the regression coefficient estimate for age is <span class="math inline">\(0.840\)</span>. This means that for every 0.840 unit increase in <span class="math inline">\(age\)</span>, there is a 1-unit increase in <span class="math inline">\(child score\)</span>.</p>
<hr>
</section>
<section id="statistical-linear-regression-inference" class="level2">
<h2 class="anchored" data-anchor-id="statistical-linear-regression-inference"><u>Statistical Linear Regression &amp; Inference</u></h2>
<p><span style="color:red;">The relation between OLS, Normality, and Maximum Likelihood</span></p>
<p>So far, we have not discussed the distribution of the errors. For OLS we <strong>did not need</strong> to make any distributional assumption.</p>
<p><span class="math display">\[
\hat{\beta}_{OLS} = (X^TX)^{-1}X^Ty
\]</span></p>
<p>But for inference (SEs, CIs, p-values), we need to make some distributional assumptions for the errors. Let’s now assume…</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 age_i + \epsilon_i, \quad i=1, ..., 400
\]</span> where <span class="math inline">\(\epsilon \overset{iid}{\sim} N(0, \sigma^2)\)</span>.</p>
<p>What does i.i.d mean? <u>identically and independently distributed.</u> This implies the following model:</p>
<ul>
<li><p><span class="math inline">\(y_i\)</span> is normally distributed.</p></li>
<li><p>This parametrization is equal to</p>
<p><span class="math display">\[y_i \sim N(\beta_0 + \beta_1 x_i,\sigma^2)\]</span>.</p></li>
<li><p>where <span class="math inline">\(\beta_0 + \beta_1 x_i\)</span> captures the trend</p></li>
<li><p>where <span class="math inline">\(\sigma^2\)</span> captures the variability (uncertainty) around the trend. It is constant, i.e., the same across all observations.</p></li>
<li><p><strong>In matrix form:</strong> <span class="math inline">\(\mathbf{Y} \sim N(\mathbf{X\beta}, \Sigma)\)</span> where <span class="math inline">\(\Sigma = \sigma^2I\)</span>.</p></li>
<li><p><span class="math inline">\(\sigma^2\)</span> is unknown!</p></li>
</ul>
<hr>
<section id="the-maximum-likelihood" class="level4">
<h4 class="anchored" data-anchor-id="the-maximum-likelihood"><u>The Maximum Likelihood</u></h4>
<p>The likelihood of the normal distribution is given by</p>
<p><span class="math display">\[
L(\beta, \sigma^2, y) = (2\pi \sigma^2)^{-n/2} exp\left(\frac{-1}{2\sigma^2} (Y-X\beta)'(Y-X\beta)\right)
\]</span></p>
<p>Taking the log of the likelihood, we get:</p>
<p><span class="math display">\[
l(\beta, \sigma^2, y) = \frac{-n}{2} log(2\pi\sigma^2) - \frac{1}{2\sigma^2} (Y-X\beta)'(Y-X\beta)
\]</span></p>
<p>To find <strong>Maximum Likelihood Estimators</strong> we take partial derivatives and set the equal to zero to find the estimators that maximize the log-likelihood.</p>
<p>What do we get?</p>
<ul>
<li><p><span class="math inline">\(\hat{\beta}_{MLE} = (X'X)^{-1}X'y\)</span> so <span class="math inline">\(\hat{\beta}_{MLE} = \hat{\beta}_{OLS}\)</span> <u>under normality</u>.</p></li>
<li><p><span class="math inline">\(\hat{\sigma}^2_{MLE} = \frac{1}{n} (Y-X\hat{\beta})'(Y-X\hat{\beta})\)</span>.</p></li>
<li><p><span class="math inline">\(E(\hat{\sigma}^2_{MLE}) \neq \sigma^2\)</span> so it is NOT unbiased.</p></li>
<li><p>An unbiased estimator for <span class="math inline">\(\sigma^2\)</span> is given by <span class="math inline">\(s^2 = \frac{1}{n-p} (Y-X\beta)'(Y-X\beta)\)</span>.</p></li>
</ul>
<table class="table">
<caption>Summary of OLS vs.&nbsp;MLE approaches</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 20%">
<col style="width: 53%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>OLS</th>
<th>MLE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Distributional assumption</td>
<td>NONE</td>
<td>Normal <span class="math inline">\(Y\sim N(X\beta, \sigma^2I)\)</span></td>
</tr>
<tr class="even">
<td>Estimator <span class="math inline">\(\hat{\beta}\)</span></td>
<td><span class="math inline">\((X'X)^{-1}X'y\)</span></td>
<td><span class="math inline">\((X'X)^{-1}X'y\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(cov(\hat{\beta})\)</span></td>
<td><span class="math inline">\(\sigma^2 (X'X)^{-1}\)</span></td>
<td><span class="math inline">\(\sigma^2 (X'X)^{-1}\)</span></td>
</tr>
<tr class="even">
<td>Estimator <span class="math inline">\(\hat{\sigma}^2\)</span></td>
<td>Cannot get</td>
<td><span class="math inline">\(\frac{1}{n} (Y-X\hat{\beta})'(Y-X\hat{\beta})\)</span> is biased</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="estimating-the-residual-error" class="level4">
<h4 class="anchored" data-anchor-id="estimating-the-residual-error"><u>Estimating the Residual Error</u></h4>
<p>We saw above that the MLE estimator of the residual error: <span class="math inline">\(\hat{\sigma}^2 = \frac{1} (Y-X\beta)^T(Y-X\beta)\)</span>. But this estimator is biased, i.e., <span class="math inline">\(E(\hat{\sigma}^2) \neq \sigma^2\)</span>.</p>
<p>The <strong>unbiased</strong> estimator of the error variance is the <strong>mean squared error (MSE)</strong> of the residuals: <span class="math inline">\(\hat{\sigma}^2 = \frac{1}{n-p} (Y-X\hat{\beta})'(Y-X\hat{\beta})\)</span>.</p>
<p>where <span class="math inline">\(p\)</span> is the number of fitted coefficients (including the intercept). Dividing by <span class="math inline">\(n-p\)</span> (the <strong>residual degrees of freedom</strong>) corrects the small-sample bias that would arise if we divided by <span class="math inline">\(n\)</span>.</p>
<p>Its square root, <span class="math inline">\(\hat\sigma\)</span>, is the <strong>residual standard error</strong>—the typical deviation of observations around the regression line, reported in outcome units.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Here p = 2</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">=</span> <span class="fu">lm</span>(score <span class="sc">~</span> age, <span class="at">data =</span> dat)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ age, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-67.109 -11.798   2.971  14.860  55.210 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  67.7827     8.6880   7.802 5.42e-14 ***
age           0.8403     0.3786   2.219    0.027 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 20.34 on 398 degrees of freedom
Multiple R-squared:  0.01223,   Adjusted R-squared:  0.009743 
F-statistic: 4.926 on 1 and 398 DF,  p-value: 0.02702</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Can we confirm this manually</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>yhat <span class="ot">=</span> fit<span class="sc">$</span>fitted.values <span class="co">#Predicted Values</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>y <span class="ot">=</span> dat<span class="sc">$</span>score <span class="co">#Observed Values</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>N <span class="ot">=</span> <span class="fu">length</span>(y)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>P<span class="ot">=</span><span class="dv">2</span> <span class="co">#number columns in design matrix</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>sq_error <span class="ot">=</span> (y<span class="sc">-</span>yhat)<span class="sc">^</span><span class="dv">2</span> <span class="co">#Squared errors</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>sigma_squared_est <span class="ot">&lt;-</span> <span class="fu">sum</span>(sq_error)<span class="sc">/</span>(N<span class="sc">-</span>P) <span class="co">#Unbiased est of the variance</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>sigma_est <span class="ot">=</span> <span class="fu">sqrt</span>(sigma_squared_est) <span class="co">#Unbiased est of the std. error</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>sigma_est</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20.34027</code></pre>
</div>
</div>
<p>Indeed we see that the estimated residual standard error is <span class="math inline">\(20.3\)</span>. But what does this really mean?</p>
<p>We can visualize uncertainty in the regression line (mean). The <strong>pointwise 95% confidence band</strong> for the mean at covariate value <span class="math inline">\(x\)</span> is:</p>
<p><span class="math display">\[
\hat{y}(x)\ \pm\ t_{n-2,\ 0.975}\ \hat{\sigma}\,
\sqrt{\frac{1}{n} + \frac{(x-\bar x)^2}{S_{xx}}}\,,
\]</span> where</p>
<p><span class="math display">\[
\hat{y}(x)=\hat\beta_0+\hat\beta_1 x,\quad
\bar x=\frac{1}{n}\sum_{i=1}^n x_i,\quad
S_{xx}=\sum_{i=1}^n (x_i-\bar x)^2,\quad
\hat{\sigma}^2=\frac{\sum_{i=1}^n (y_i - \hat y_i)^2}{n-2}.
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Include 95% confidence intervals in your summary</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>nd  <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">age =</span> <span class="fu">seq</span>(<span class="fu">min</span>(dat<span class="sc">$</span>age), <span class="fu">max</span>(dat<span class="sc">$</span>age), <span class="at">length.out =</span> <span class="dv">200</span>))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>ci  <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">predict</span>(fit, <span class="at">newdata =</span> nd, <span class="at">interval =</span> <span class="st">"confidence"</span>, <span class="at">level =</span> <span class="fl">0.95</span>))</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>plt <span class="ot">&lt;-</span> <span class="fu">cbind</span>(nd, ci)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat, <span class="fu">aes</span>(age, score), <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> plt, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">ymin =</span> lwr, <span class="at">ymax =</span> upr), <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> plt, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> fit), <span class="at">linewidth =</span> <span class="fl">1.1</span>, <span class="at">color =</span> <span class="st">"darkgreen"</span>) <span class="sc">+</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Maternal age (years)"</span>, <span class="at">y =</span> <span class="st">"Child score"</span>,</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"OLS fit with 95% CI for the mean response"</span>) <span class="sc">+</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Module_0_MLR_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Model Interpretation:</strong> A one year increase in mother’s age at delivery was associated with a 0.84 (p-value= 0.027) increase in the child’s average test score, where test score was measured at age 3. The association was statistically significant at a type I error rate of 0.05.</p>
<p>There was considerable heterogeneity in test scores <span class="math inline">\((\hat{\sigma} = 20.34)\)</span>. Therefore, the regression model does not predict individual test scores well <span class="math inline">\((R^2 = 0.012)\)</span>. 1.2% of variances is explained by mother’s age.</p>
<hr>
</section>
</section>
<section id="prediction-interval-for-a-new-observation" class="level2">
<h2 class="anchored" data-anchor-id="prediction-interval-for-a-new-observation"><u>Prediction Interval for a New Observation</u></h2>
<p>Let <span class="math inline">\(\tilde{y}_i\)</span> be a new observation with covariate value <span class="math inline">\(age_i\)</span>. How can you obtain its predictive uncertainty? We want to capture the uncertainty in our predicted estimate of the expected value <span class="math inline">\(\hat{y}_i = X\hat{\beta}\)</span> PLUS the uncertainty due to measurement error <span class="math inline">\(\epsilon_i\)</span>.</p>
<p><span class="math display">\[
\tilde{y}_i = \hat{\beta}_0 + \hat{\beta}_1 age_i + \epsilon_i, \quad \epsilon_i \sim N(0, \sigma^2)
\]</span></p>
<p>The total uncertainty surrounding the predicted value <span class="math inline">\(\tilde{y}_i\)</span> can be broken down as the sum of two components.</p>
<p><span class="math display">\[
Var(
\tilde{y}_i) = Var(\hat{\beta}_0 + \hat{\beta}_1 age_i) + Var(\epsilon_i)
\]</span></p>
<ul>
<li>We know the first term on the right, <span class="math inline">\(Var(\hat{\beta}) = \sigma^2 (X'X)^{-1}\)</span> and so <span class="math inline">\(Var(X\hat{\beta}) = \sigma^2 (x_i^{'} (X'X)^{-1} x_i)\)</span>.</li>
<li>We know the variance of the error term <span class="math inline">\(Var(\epsilon_i) = \sigma^2\)</span>.</li>
</ul>
<p>We plug in our estimators to get the predicted variance</p>
<p><span class="math display">\[ \tilde{\sigma}^2 = \widehat{\mathrm{Var}}(\tilde{y}_i)
= \hat{\sigma}^2\, x_i^\top (X^\top X)^{-1} x_i + \hat{\sigma}^2,\quad
\tilde{y}_i \pm t_{n-p,0.975}\sqrt{\widehat{\mathrm{Var}}(\tilde{y}_i)}\]</span></p>
<p>From this derivation we can see that <span class="math inline">\(\tilde{\sigma}^2 \geq \hat{\sigma}^2\)</span>. So the 95% prediction interval is going to be wider than the 95% confidence interval.</p>
<p>The approximate 95% prediction interval is given by <span class="math inline">\(\tilde{y}_i \pm 1.96 \tilde{\sigma}\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> age, <span class="at">data =</span> dat)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 2) Make a smooth grid over age</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>nd <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">age =</span> <span class="fu">seq</span>(<span class="fu">min</span>(dat<span class="sc">$</span>age), <span class="fu">max</span>(dat<span class="sc">$</span>age), <span class="at">length.out =</span> <span class="dv">200</span>))</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 3) Get intervals</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">predict</span>(fit, <span class="at">newdata =</span> nd, <span class="at">interval =</span> <span class="st">"confidence"</span>,  <span class="at">level =</span> <span class="fl">0.95</span>))</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>pi <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">predict</span>(fit, <span class="at">newdata =</span> nd, <span class="at">interval =</span> <span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.95</span>))</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>plot_df <span class="ot">&lt;-</span> <span class="fu">cbind</span>(nd,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fit =</span> ci<span class="sc">$</span>fit,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>                 <span class="at">lwr_ci =</span> ci<span class="sc">$</span>lwr, <span class="at">upr_ci =</span> ci<span class="sc">$</span>upr,</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>                 <span class="at">lwr_pi =</span>  pi<span class="sc">$</span>lwr, <span class="at">upr_pi =</span>  pi<span class="sc">$</span>upr)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="co"># 4) Plot: points, prediction band (wider), mean CI band (narrower), fitted line</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># prediction band (wider)</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> plot_df,</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">ymin =</span> lwr_pi, <span class="at">ymax =</span>upr_pi), <span class="at">alpha =</span> <span class="fl">0.12</span>, <span class="at">fill =</span> <span class="st">"green"</span>) <span class="sc">+</span></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># mean CI band (narrower)</span></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> plot_df,</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">ymin =</span> lwr_ci, <span class="at">ymax =</span>upr_ci),</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># fitted line</span></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> plot_df,</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>            <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> fit),</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>            <span class="at">linewidth =</span> <span class="fl">1.1</span>) <span class="sc">+</span></span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>  <span class="co"># points last so they sit on top</span></span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat,</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>             <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> score),</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Maternal age (years)"</span>, <span class="at">y =</span> <span class="st">"Child score"</span>,</span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"OLS: 95% CI (mean) and 95% PI (individual)"</span>) <span class="sc">+</span></span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Module_0_MLR_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
<section id="model-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="model-diagnostics"><u>Model Diagnostics</u></h2>
<p><strong>Residual vs.&nbsp;Fitted</strong></p>
<ul>
<li><p><span class="math inline">\(\hat{\epsilon}_i\)</span> should be independent of <span class="math inline">\(\hat{y}_i\)</span>, i.e., no patterns.</p></li>
<li><p>Linearity: Red line should be flat, ie banded around 0.</p></li>
<li><p>Constant variance (homoscedasticity).</p></li>
</ul>
<p><strong>Normal Q-Q Plot</strong></p>
<ul>
<li><p>Standardized residual <span class="math inline">\(\hat{\epsilon}_i/ (\hat{ \sigma} \sqrt{1-h_{ii}})\)</span> should be a standard normal.</p></li>
<li><p>We expect the points to follow a straight line, Check non-normality, particularly skewed tails.</p></li>
</ul>
<p><strong>Scale-Location</strong></p>
<ul>
<li>Similar to residual vs fitted, but use standardized residual. Diagnose heteroscedasticity (eg red line increasing).</li>
</ul>
<p><strong>Residual vs Leverage</strong></p>
<ul>
<li>Leverage <span class="math inline">\(h_{ii}\)</span> is how far away <span class="math inline">\(x_i\)</span> is from other <span class="math inline">\(x_j\)</span> where <span class="math inline">\(h_{ii} = \frac{\partial \hat{y}_i}{\partial y_i}\)</span>.</li>
<li>Cook’s Distance: measures how much model changes when remove <span class="math inline">\(ith\)</span> point; &gt;1 is problematic.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Module_0_MLR_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing"><u>Hypothesis Testing</u></h2>
<p>With the linear regression model established, we now turn to hypothesis testing to determine whether the relationships observed between the independent and dependent variables are statistically significant.</p>
<ul>
<li><p>(Intercept): <span class="math inline">\(H_0 : \beta_0 = 0\)</span> when <span class="math inline">\(age =0\)</span>. In other words test scores are equal to zero for a mother at <span class="math inline">\(age=0\)</span> versus <span class="math inline">\(H_a: \beta_0 \neq 0\)</span>.</p></li>
<li><p>Age: <span class="math inline">\(H_0: \beta_1=0\)</span> In words, the slope of age is equal to zero or there is no linear effect. <span class="math inline">\(H_a: \beta_1 \neq 0\)</span> if there is a significant linear effect.</p></li>
</ul>
<p>For a given covariate <span class="math inline">\(\beta_j\)</span>, we make the following assumption:</p>
<p><span class="math display">\[
\hat{\beta}_j \sim \mathcal{N}(\beta_j, \mathrm{Var}(\hat{\beta}_j))
\]</span></p>
<p>The variance of <span class="math inline">\(\hat{\beta}_j\)</span> is:</p>
<p><span class="math display">\[
\mathrm{Var}(\hat{\beta}_j) = \sigma^2 (X^TX)^{-1}_{jj}
\]</span></p>
<p>Since <span class="math inline">\(\sigma^2\)</span> is unknown, we estimate it using the residual sum of squares:</p>
<p><span class="math display">\[
\hat{\sigma}^2 = \frac{1}{n - p} \sum_{i=1}^{n} \hat{\varepsilon}_i^2 = \frac{1}{n - p} \| y - X\hat{\beta} \|^2
\]</span></p>
<p>The <strong>standard error</strong> of <span class="math inline">\(\hat{\beta}_j\)</span> is then:</p>
<p><span class="math display">\[
\mathrm{SE}(\hat{\beta}_j) = \sqrt{\hat{\sigma}^2 (X^TX)^{-1}_{jj}}
\]</span></p>
<p>We test the null hypothesis:</p>
<p><span class="math display">\[
H_0: \beta_j = 0 \quad \text{vs.} \quad H_a: \beta_j \ne 0
\]</span></p>
<p>The test statistic follows a <span class="math inline">\(t\)</span>-distribution under the null hypothesis:</p>
<p><span class="math display">\[
t = \frac{\hat{\beta}_j}{\mathrm{SE}(\hat{\beta}_j)} \sim t_{n - p}
\]</span></p>
<p>We compare this statistic to critical values of the <span class="math inline">\(t\)</span>-distribution or use its corresponding p-value to decide whether to reject <span class="math inline">\(H_0\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ age, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-67.109 -11.798   2.971  14.860  55.210 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  67.7827     8.6880   7.802 5.42e-14 ***
age           0.8403     0.3786   2.219    0.027 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 20.34 on 398 degrees of freedom
Multiple R-squared:  0.01223,   Adjusted R-squared:  0.009743 
F-statistic: 4.926 on 1 and 398 DF,  p-value: 0.02702</code></pre>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-tip callout-titled" style="color: green">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
TEST YOUR KNOWLEDGE
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Let <span class="math inline">\(H=X(X'X)^{-1}X'\)</span> and let <span class="math inline">\(\hat{Y} = HY\)</span>. Then <span class="math inline">\(H\hat{Y} = ?\)</span></li>
<li>Show the derivation for <span class="math inline">\(cov(\hat{\beta})\)</span>.</li>
<li>What is the unbiased estimator of <span class="math inline">\(\sigma^2\)</span>?</li>
<li>The unbiased estimator for <span class="math inline">\(\sigma^2\)</span> contains a parameter <span class="math inline">\(p\)</span>. What does <span class="math inline">\(p\)</span> represent?</li>
<li>Below code is given to simulate data from a “true” model. Run the code to get simulated quantities of covariates <span class="math inline">\(X\)</span> and outcomes <span class="math inline">\(Y\)</span>.</li>
<li>What is the “true” intercept in the below simulation?</li>
<li>What is the “true” covariate coefficient value in the below simulation?</li>
<li>Fit the linear model. Find the estimates of the <span class="math inline">\(\beta’s\)</span> and global variance <span class="math inline">\(\sigma^2\)</span>.</li>
<li>Interpret the findings of the model in terms of null versus alternative hypotheses.</li>
<li>Create diagnostic plots and determine if model assumptions have been met.</li>
</ol>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Set seed for reproducibility</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1232</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Set the "true" values of the betas.</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>beta0 <span class="ot">=</span> <span class="fl">0.1</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>beta1 <span class="ot">=</span> <span class="fl">0.5</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>beta2 <span class="ot">=</span> <span class="sc">-</span><span class="fl">0.2</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Simulated data from two normals</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span><span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">2</span>)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span><span class="dv">100</span>, <span class="dv">5</span>, <span class="dv">5</span>)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span><span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Generate the simulated y values</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>X <span class="ot">=</span> <span class="fu">cbind</span>(<span class="dv">1</span>, x1, x2)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>Beta <span class="ot">=</span> <span class="fu">c</span>(beta0, beta1, beta2)</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> X <span class="sc">%*%</span> Beta <span class="sc">+</span> error</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="do">###Finish this code to run the proposed model and diagnostics.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
</section>
<section id="confounding" class="level2">
<h2 class="anchored" data-anchor-id="confounding"><u>Confounding</u></h2>
<p>We found that older mothers had children on average with higher test scores. However, higher maternal education was associated with higher age as shown below.</p>
<p><strong>How do we estimate the age association with outcome accounting for the effect (confounding) of education?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat) <span class="sc">+</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="fu">as.factor</span>(edu),age)) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mother Education"</span>, <span class="at">y=</span> <span class="st">"Age at Delivery"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Module_0_MLR_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="confounding-1" class="level6">
<h6 class="anchored" data-anchor-id="confounding-1">Confounding</h6>
<ul>
<li><p>Causes spurious correlation.</p></li>
<li><p>Referred to as “omitted variable bias”</p></li>
<li><p>We want to <u>control/account for</u> confounding associations!</p></li>
<li><p>How do we account for confounding?</p></li>
</ul>
<p><strong>Include confounders in the regression equation</strong> <span class="math inline">\(\rightarrow\)</span> MULTIPLE LINEAR REGRESSION: <span class="math inline">\(y \sim x+z\)</span></p>
<ul>
<li><p><u>Assumptions of linear regression plus omitted variable assumption:</u></p>
<ul>
<li><p>Residuals are independent AND normal.</p></li>
<li><p>Global variance (homoscedasticity).</p></li>
<li><p>Linearity of all included covariates.</p></li>
<li><p>All variables that are not included in the model have coefficient equal to zero (omitted variable bias = 0).</p></li>
</ul></li>
</ul>
</section>
</section>
<section id="adjusting-for-confounding" class="level2">
<h2 class="anchored" data-anchor-id="adjusting-for-confounding">Adjusting for Confounding:</h2>
<ul>
<li><p>Consider the above model: <span class="math inline">\(y_i = \beta_0 + \beta_1 E_{2i} + \beta_2 E_{3i} + \beta_3 E_{4i} + \beta_4 age_i + \epsilon_i\)</span>.</p></li>
<li><p>Each education group has their own coefficient.</p></li>
<li><p>The slope of maternal age is constant across education groups (parallel lines).</p></li>
<li><p><span class="math inline">\(\beta_4\)</span> is the association between score and age, <span style="color: red;">accounting for different averages in score</span> in different education groups.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">=</span> <span class="fu">lm</span>(score <span class="sc">~</span> <span class="fu">factor</span>(edu)  <span class="sc">+</span> age, <span class="at">data =</span> dat)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ factor(edu) + age, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-58.853 -12.112   1.779  14.687  58.298 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   72.2360     8.8700   8.144 5.07e-15 ***
factor(edu)2   9.9365     2.5953   3.829 0.000150 ***
factor(edu)3   8.8416     3.2203   2.746 0.006316 ** 
factor(edu)4  17.6809     4.7065   3.757 0.000198 ***
age            0.2877     0.3985   0.722 0.470736    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 19.92 on 395 degrees of freedom
Multiple R-squared:  0.0598,    Adjusted R-squared:  0.05028 
F-statistic:  6.28 on 4 and 395 DF,  p-value: 6.59e-05</code></pre>
</div>
</div>
<ul>
<li>Age effect is no longer statistically significant after accounting for mother’s education level.</li>
<li>This model assumes an identical effect of age across ALL education groups.</li>
<li>Is this assumption realistic?</li>
</ul>
<hr>
<section id="categorical-variables" class="level3">
<h3 class="anchored" data-anchor-id="categorical-variables">Categorical Variables</h3>
<ul>
<li><p>First we examine the effects of education on scores.</p></li>
<li><p><span class="math inline">\(edu\)</span> is coded as 1,2,3,4. We do NOT want to code this as continuous!!</p></li>
</ul>
<p><strong>Approach 1: an indicator (dummy) for each group.</strong></p>
<p><span class="math display">\[
X_{1i} = 1_{[edu_i=1]}, X_{2i} = 1_{[edu_2=1]}, X_{3i} = 1_{[edu_i=3]}, X_{4i} = 1_{[edu_i=4]}
\]</span></p>
<p>If we have <span class="math inline">\(edu_i = [1,1,2,2,3,3,4,4]\)</span>, the design matrix is</p>
<p><span class="math display">\[
X\beta = \begin{pmatrix}
1 &amp; 0 &amp; 0 &amp; 0\\
1 &amp; 0 &amp; 0 &amp; 0\\
0 &amp; 1 &amp; 0 &amp; 0\\
0 &amp; 1 &amp; 0 &amp; 0\\
0 &amp; 0 &amp; 1 &amp; 0\\
0 &amp; 0 &amp; 1 &amp; 0\\
0 &amp; 0 &amp; 0 &amp; 1\\
0 &amp; 0 &amp; 0 &amp; 1
\end{pmatrix} \cdot \begin{pmatrix} \beta_1 \\ \beta_2 \\ \beta_3 \\ \beta_4 \end{pmatrix}
\]</span></p>
<ul>
<li>Note we remove the intercept. If we try to include an intercept, there is linear dependency between columns and there is no unique solution.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>E1 <span class="ot">=</span> <span class="fu">as.numeric</span>(dat<span class="sc">$</span>edu <span class="sc">==</span><span class="dv">1</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>E2 <span class="ot">=</span> <span class="fu">as.numeric</span>(dat<span class="sc">$</span>edu <span class="sc">==</span><span class="dv">2</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>E3 <span class="ot">=</span> <span class="fu">as.numeric</span>(dat<span class="sc">$</span>edu <span class="sc">==</span><span class="dv">3</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>E4 <span class="ot">=</span> <span class="fu">as.numeric</span>(dat<span class="sc">$</span>edu <span class="sc">==</span><span class="dv">4</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>E1[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0 1 0 1 0 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">=</span> <span class="fu">lm</span>(dat<span class="sc">$</span>score <span class="sc">~</span> E1 <span class="sc">+</span> E2 <span class="sc">+</span> E3 <span class="sc">+</span> E4  <span class="sc">-</span><span class="dv">1</span>) <span class="co">#use -1 to remove the intercept</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = dat$score ~ E1 + E2 + E3 + E4 - 1)

Residuals:
   Min     1Q Median     3Q    Max 
-58.45 -12.70   1.61  15.23  57.55 

Coefficients:
   Estimate Std. Error t value Pr(&gt;|t|)    
E1   78.447      2.159   36.33   &lt;2e-16 ***
E2   88.703      1.367   64.88   &lt;2e-16 ***
E3   87.789      2.284   38.44   &lt;2e-16 ***
E4   97.333      3.831   25.41   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 19.91 on 396 degrees of freedom
Multiple R-squared:  0.9508,    Adjusted R-squared:  0.9503 
F-statistic:  1913 on 4 and 396 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>What does each element of <span class="math inline">\(\beta\)</span> vector mean?
<ul>
<li><span class="math inline">\(\hat{\beta}_1\)</span> is equivalent to taking the average of scores for kids with mother’s <span class="math inline">\(edu=1\)</span>. So each <span class="math inline">\(\hat{\beta}\)</span> is equivalent to calculating the mean IQ for each education group.</li>
</ul></li>
</ul>
<p><strong>Approach 2: Intercept plus three indicators for groups 2,3, and 4.</strong></p>
<p><span class="math inline">\(X_{1i} = 1 , X_{2i} = 1_{[edu_2=1]}, X_{3i} = 1_{[edu_i=3]}, X_{4i} = 1_{[edu_i=4]}\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">=</span> <span class="fu">lm</span>(dat<span class="sc">$</span>score <span class="sc">~</span> <span class="fu">factor</span>(dat<span class="sc">$</span>edu))</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = dat$score ~ factor(dat$edu))

Residuals:
   Min     1Q Median     3Q    Max 
-58.45 -12.70   1.61  15.23  57.55 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        78.447      2.159  36.330  &lt; 2e-16 ***
factor(dat$edu)2   10.256      2.556   4.013 7.18e-05 ***
factor(dat$edu)3    9.342      3.143   2.973  0.00313 ** 
factor(dat$edu)4   18.886      4.398   4.294 2.21e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 19.91 on 396 degrees of freedom
Multiple R-squared:  0.05856,   Adjusted R-squared:  0.05142 
F-statistic:  8.21 on 3 and 396 DF,  p-value: 2.59e-05</code></pre>
</div>
</div>
<ul>
<li><span class="math inline">\(\hat{\beta}\)</span> represents the difference in average score with respect to the <span class="math inline">\(edu=1\)</span> group., i.e., 10.256 is the average difference between no high school group and high school group.</li>
</ul>
<hr>
</section>
</section>
<section id="variance-inflation-factors" class="level2">
<h2 class="anchored" data-anchor-id="variance-inflation-factors">Variance Inflation Factors</h2>
<ul>
<li><p>One must always be on the lookout for issues with multicollinearity!</p></li>
<li><p>The general issues is that when two variables are highly correlated, it is hard to disentangle their effects.</p></li>
<li><p>Mathematically, the standard errors are inflated. Suppose we have a design matrix <span class="math inline">\(\mathbf{X} = [x_1, ..., x_p]\)</span> and we want to calculate the variance inflation factor (VIF). We regress <span class="math inline">\(x_1\)</span> against <span class="math inline">\(x_2, ..., x_p\)</span>.</p></li>
<li><p>Let <span class="math inline">\(R_1^2\)</span> be the associated R-squared for <span class="math inline">\(x_1\)</span>. Then <span class="math inline">\(VIF_1 = \frac{1}{1-R_1^2}\)</span>.</p></li>
<li><p>It can be shown that <span class="math inline">\(Var(\hat{\beta}_j) = VIF_j \cdot \frac{\sigma^2}{(n-1)s_{x_j}^2}\)</span>.</p></li>
<li><p>Different rules of thumb <span class="math inline">\(VIFs&gt;5\)</span> are cause for concern.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create some correlated data</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>age2 <span class="ot">=</span> dat<span class="sc">$</span>age<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="at">n=</span><span class="dv">400</span>, <span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">=</span> <span class="fu">lm</span>(dat<span class="sc">$</span>score <span class="sc">~</span> <span class="fu">factor</span>(dat<span class="sc">$</span>edu) <span class="sc">+</span> dat<span class="sc">$</span>age <span class="sc">+</span> dat<span class="sc">$</span>age2)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     GVIF Df GVIF^(1/(2*Df))
factor(dat$edu)  1.189686  3        1.029371
dat$age         94.039443  1        9.697394
dat$age2        94.128083  1        9.701963</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Is this bigger than 5. Age is highly collinear as expected.</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Now try it without age2. Do you see any problems?</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
</section>
<section id="interaction-effects-effect-modification" class="level2">
<h2 class="anchored" data-anchor-id="interaction-effects-effect-modification">Interaction Effects: Effect Modification</h2>
<ul>
<li>We can relax the assumption of identical age effect by including <span style="color: red;">interaction</span> terms.</li>
<li>Again the reference group is <span class="math inline">\(edu=1\)</span> or <span class="math inline">\(E_{1i}\)</span>.</li>
</ul>
<p><span class="math display">\[
\begin{align*}
y_i &amp;= \beta_0  +\beta_1 E_{2i} + \beta_2 E_{3i} + \beta_3 E_{4i} + \beta_4 age_i + \\
&amp; \beta_5 E_{2i} age_i + \beta_6 E_{3i} age_i + \beta_7 E_{4i} age_i + \epsilon_i
\end{align*}
\]</span></p>
<ul>
<li>For each edu group: We account for modified effects by examining whether <span class="math inline">\(\beta_5, \beta_6\)</span>, and <span class="math inline">\(\beta_7\)</span> are zero.</li>
</ul>
<p><span class="math display">\[
y_i  = \begin{cases} \beta_0 = \beta_4 age_i &amp;\text{ if edu =1}\\
\beta_0 + \beta_1 + (\beta_4 + \beta_5) age_i&amp; \text{ if edu =2}\\
\beta_0 + \beta_2 + (\beta_4 + \beta_6) age_i &amp;\text{ if edu =3}\\
\beta_0 + \beta_3 + (\beta_4 + \beta_7) age_i &amp;\text{ if edu =4}
\end{cases}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">=</span> <span class="fu">lm</span>(score <span class="sc">~</span> <span class="fu">factor</span>(edu) <span class="sc">*</span> age, <span class="at">data =</span> dat)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ factor(edu) * age, data = dat)

Residuals:
   Min     1Q Median     3Q    Max 
-56.70 -11.80   2.07  14.58  54.34 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      105.2202    17.6127   5.974  5.2e-09 ***
factor(edu)2     -33.0929    21.5732  -1.534   0.1258    
factor(edu)3     -53.4970    27.9460  -1.914   0.0563 .  
factor(edu)4      36.4537    49.5065   0.736   0.4620    
age               -1.2402     0.8097  -1.532   0.1264    
factor(edu)2:age   1.9704     0.9764   2.018   0.0443 *  
factor(edu)3:age   2.7862     1.2293   2.266   0.0240 *  
factor(edu)4:age  -0.4799     1.9635  -0.244   0.8070    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 19.81 on 392 degrees of freedom
Multiple R-squared:  0.07705,   Adjusted R-squared:  0.06057 
F-statistic: 4.675 on 7 and 392 DF,  p-value: 4.756e-05</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>there are higher-order terms (interactions) in this model
consider setting type = 'predictor'; see ?vif</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                        GVIF Df GVIF^(1/(2*Df))
factor(edu)     9.093097e+05  3        9.842800
age             4.821946e+00  1        2.195893
factor(edu):age 1.039839e+06  3       10.065322</code></pre>
</div>
</div>
<ul>
<li><p><span style="color: red;">Note how the variance is inflated</span></p></li>
<li><p>This is common with interaction variables since by construction there is dependence between an interaction variable and the main effects.</p></li>
<li><p>In general, it means we need larger sample sizes to examine interactions.</p></li>
<li><p>It is <span style="color: red;">important</span> to visualize the data and model results.</p></li>
<li><p>We see the lines are not parallel and the intercept differs across groups.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(age, score)) <span class="sc">+</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> edu, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Module_0_MLR_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
<section id="f-test-of-interaction" class="level2">
<h2 class="anchored" data-anchor-id="f-test-of-interaction">F-test of interaction</h2>
<p>To test whether the interaction was significant, look at whether the inclusion of the interaction significantly “improved” model fit.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The interaction between education and age does not improve model fit.</li>
<li><span class="math inline">\(H_A\)</span>: The interaction improves model fit.</li>
</ul>
<p>Suppose we want to choose between these two models, i.e., Full model vs.&nbsp;Reduced model. We use the F-statistic:</p>
<div class="illustration callout callout-style-default callout-important callout-titled" style="color: red">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
F-statistic to perform model comparison
</div>
</div>
<div class="callout-body-container callout-body">
<p>The F statistic is a ratio of two chi-square distributions to test whether the full model gives additional information, e.g., does <span class="math inline">\(\beta_5 = \beta_6 = \beta_7 =0\)</span>?</p>
<p><span class="math display">\[
F = \frac{ \text{RSS}_{\text{reduced}} - \text{RSS}_{\text{full}} }{ p_{\text{full}} - p_{\text{reduced}} } \Bigg/ \frac{ \text{RSS}_{\text{full}} }{ n - p_{\text{full}} },.
\]</span> Another parametrization for the F-test is given by:</p>
<p><span class="math display">\[
F = \frac{y'(H_{full} - H_{reduced})y/p-1}{y'(I-H_{full})y/n-p} = \frac{\chi^2_{p-1-k}/p-1-k}{X^2_{n-p}/n-p} \geq F_{\alpha, k, n-k-1}
\]</span></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>fit_inter <span class="ot">=</span> <span class="fu">lm</span>(score <span class="sc">~</span> <span class="fu">factor</span>(edu) <span class="sc">*</span> age, <span class="at">data =</span> dat) <span class="co">#Full Model</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>fit_nointer <span class="ot">=</span> <span class="fu">lm</span>(score<span class="sc">~</span> <span class="fu">factor</span>(edu) <span class="sc">+</span> age, <span class="at">data =</span> dat) <span class="co">#Reduced Model</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_nointer, fit_inter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: score ~ factor(edu) + age
Model 2: score ~ factor(edu) * age
  Res.Df    RSS Df Sum of Sq      F  Pr(&gt;F)  
1    395 156733                              
2    392 153857  3    2876.5 2.4429 0.06376 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li>Overall, there is only limited statistical evidence of an interaction!</li>
</ul>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary"><span style="color: purple;">Summary</span></h2>
<table class="table">
<colgroup>
<col style="width: 11%">
<col style="width: 88%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Section</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Model (MLR)</strong></td>
<td><span class="math inline">\(\mathbf y=\mathbf X\beta+\boldsymbol\epsilon\)</span>, with <span class="math inline">\(E[\boldsymbol\epsilon]=\mathbf 0\)</span>, <span class="math inline">\(\operatorname{Var}(\boldsymbol\epsilon)=\sigma^2\mathbf I\)</span>. Each <span class="math inline">\(\beta_j\)</span> is an <strong>adjusted</strong> effect.</td>
</tr>
<tr class="even">
<td><strong>Estimation (OLS)</strong></td>
<td>Minimize RSS <span class="math inline">\(\sum (y_i-\hat y_i)^2\)</span> ⇒ <span class="math inline">\(\hat\beta=(\mathbf X^\top\mathbf X)^{-1}\mathbf X^\top\mathbf y\)</span>. Fitted values <span class="math inline">\(\hat{\mathbf y}=\mathbf H\mathbf y\)</span>, <span class="math inline">\(\mathbf H=\mathbf X(\mathbf X^\top\mathbf X)^{-1}\mathbf X^\top\)</span>.</td>
</tr>
<tr class="odd">
<td><strong>Key properties</strong></td>
<td><span class="math inline">\(E[\hat\beta]=\beta\)</span>; <span class="math inline">\(\operatorname{Cov}(\hat\beta)=\sigma^2(\mathbf X^\top\mathbf X)^{-1}\)</span>; residuals are orthogonal to columns of <span class="math inline">\(\mathbf X\)</span>.</td>
</tr>
<tr class="even">
<td><strong>Normality for inference</strong></td>
<td>For SEs/CIs/p-values assume <span class="math inline">\(\boldsymbol\epsilon\sim\mathcal N(\mathbf 0,\sigma^2\mathbf I)\)</span>. <strong>Point estimates don’t require normality.</strong></td>
</tr>
<tr class="odd">
<td><strong>Residual variance</strong></td>
<td><span class="math inline">\(\hat\sigma^2=\mathrm{SSE}/(n-p)\)</span> with <span class="math inline">\(\mathrm{SSE}=\sum (y_i-\hat y_i)^2\)</span>, <span class="math inline">\(p\)</span> includes the intercept. <span class="math inline">\(\hat\sigma\)</span> = residual standard error.</td>
</tr>
<tr class="even">
<td><strong>Mean CI &amp; Prediction PI</strong></td>
<td>95% <strong>CI</strong> bands quantify uncertainty in the <strong>mean</strong> <span class="math inline">\(\hat y(x)\)</span>; 95% <strong>PI</strong> adds error variance and is <strong>wider</strong> (for new observations).</td>
</tr>
<tr class="odd">
<td><strong>Diagnostics</strong></td>
<td>Residuals vs fitted (linearity/variance), Normal Q–Q (normality), Scale–Location (homoscedasticity), Residuals vs leverage/Cook’s <span class="math inline">\(D\)</span> (influence).</td>
</tr>
<tr class="even">
<td><strong>Hypothesis tests</strong></td>
<td><span class="math inline">\(t\)</span>-tests for individual coefficients (e.g., slope of age). Partial <span class="math inline">\(F\)</span>-tests for blocks of terms (e.g., interactions).</td>
</tr>
<tr class="odd">
<td><strong>Confounding</strong></td>
<td>Adjust by including confounders in <span class="math inline">\(\mathbf X\)</span> to obtain <strong>population-level, adjusted</strong> associations.</td>
</tr>
<tr class="even">
<td><strong>Categorical predictors</strong></td>
<td>Use <span class="math inline">\(k-1\)</span> indicators with an intercept (reference coding) for group mean differences.</td>
</tr>
<tr class="odd">
<td><strong>Multicollinearity (VIF)</strong></td>
<td><span class="math inline">\(\text{VIF}_j = 1/(1-R_j^2)\)</span>; values <span class="math inline">\(\gtrsim 5\)</span> are a concern (rule of thumb in these notes).</td>
</tr>
<tr class="even">
<td><strong>Interactions</strong></td>
<td>Add terms like <span class="math inline">\(x:\text{group}\)</span> for group-specific slopes; without interactions slopes are common across groups.</td>
</tr>
<tr class="odd">
<td><strong>F-test of interaction</strong></td>
<td>Compare <strong>full</strong> vs <strong>reduced</strong> models to test whether interaction terms improve fit.</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Introduction</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Module_1A_LMM.html" class="pagination-link">
        <span class="nav-page-text">Module 1A Linear Mixed Models</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>