<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>BIOS 526 Modern Regression Analysis - Module 2B Generalized Linear Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Module_2C_GLMMs.html" rel="next">
<link href="./Module_2A_GLM.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Module_2B_GLM.html">Module 2B Generalized Linear Models</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">BIOS 526 Modern Regression Analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_0_MLR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 0: Multiple Linear Regression Review</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1A_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1A Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1B_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1B Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1C_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1C Random Intercepts and Slopes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1_LMM_Cheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2A_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2A Generalized Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2B_GLM.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Module 2B Generalized Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2C_GLMMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2C Generalized Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2D_GLMMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2D Generalized Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2_GLM_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3A_GEEs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3A Marginal Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3B_GEEs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3B Marginal Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3_GEE_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4A_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4A Basis Expansion and Parametric Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4B_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4B Parametric Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4C_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4C Penalized Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4_Splines_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5A_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5A Generalized Additive Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5B_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5B Generalized Additive Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5_GAM_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_6_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 6 Model Selection, Diagnostics, &amp; Regression Workflow</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#poisson-regression" id="toc-poisson-regression" class="nav-link active" data-scroll-target="#poisson-regression">Poisson Regression</a>
  <ul class="collapse">
  <li><a href="#poisson-overdispersion" id="toc-poisson-overdispersion" class="nav-link" data-scroll-target="#poisson-overdispersion">Poisson Overdispersion</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span style="color: purple;">Summary</span></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Module 2B Generalized Linear Models</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><img src="fig/glm.jpeg" class="img-fluid"></p>
<section id="poisson-regression" class="level2">
<h2 class="anchored" data-anchor-id="poisson-regression">Poisson Regression</h2>
<p>The Poisson model is used for count data, that is; where each data point <span class="math inline">\(y_i\)</span> can equal 0,1,2,….N. Poisson models are commonly used for assessing disease and/or mortality counts particularly for rare diseases.</p>
<hr>
<section id="model-setup" class="level4">
<h4 class="anchored" data-anchor-id="model-setup">Model Setup</h4>
<p>We assume that <span class="math inline">\(y_i\)</span> follows a Poisson distribution: <span class="math display">\[
y_i \sim Poisson(\theta_i) = \frac{e^{-\theta_i}\theta_i^{y_i}}{y_i !}
\]</span></p>
<p>where <span class="math inline">\(\theta_i&gt;0\)</span> is the expected count for observation <span class="math inline">\(i\)</span>.</p>
<ul>
<li>An important characteristic of the Poisson distribution is that the mean and variance are equal:</li>
</ul>
<p><span class="math display">\[
E(y_i ) = Var(y_i) = \theta_i
\]</span> - This is notable because it is a characteristic that determines whether Poisson is an appropriate model assumption.</p>
<ul>
<li>As with linear and logistic regression, the variation in <span class="math inline">\(y\)</span> can be explained with linear predictors <span class="math inline">\(X\)</span>.</li>
</ul>
<p><span class="math display">\[
\theta_i = exp(X_i \beta)
\]</span></p>
<ul>
<li>Here the <u>link</u> is the log() link. log() has domain <span class="math inline">\((0, \infty)\)</span> and range <span class="math inline">\((-\infty, \infty)\)</span> and is strictly increasing.</li>
</ul>
<p><span class="math display">\[
g(\theta_i) = log(\theta_i)
\]</span> which maps <span class="math inline">\((0, \infty) \to (-\infty, \infty)\)</span>.</p>
<hr>
</section>
<section id="interpretation-of-coefficients" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-of-coefficients">Interpretation of Coefficients</h4>
<ul>
<li>Consider a simple Poisson regression model with only one covariate:</li>
</ul>
<p><span class="math display">\[
\begin{align*}
y_i &amp;\overset{ind}{\sim} Pois(\theta_i)\\
log(\theta_i) &amp; = \beta_0 + \beta_1 x_i
\end{align*}
\]</span></p>
<ul>
<li><p>The coefficient <span class="math inline">\(\beta_j\)</span> represents the <strong>log change</strong> in the expected count for a one-unit increase in <span class="math inline">\(X_j\)</span> holding other predictors constant.</p></li>
<li><p>Exponentiating <span class="math inline">\(\beta_j\)</span> gives the <strong>incidence rate ratio (IRR)</strong>:</p></li>
</ul>
<p><span class="math display">\[
exp(\beta_j) = \frac{\theta_i^*}{\theta_i}
\]</span></p>
<p>How did we get that?</p>
<p><strong>Baseline scenario:</strong> <span class="math inline">\((X_{ij} = x)\)</span>, with expected count <span class="math inline">\((\theta_i )\)</span>.</p>
<p><strong>One-unit increase in</strong> <span class="math inline">\((X_{ij})\)</span>: <span class="math inline">\((X_{ij} = x + 1)\)</span>, with expected count <span class="math inline">\((\theta_i^{*} )\)</span>.</p>
<p>The difference in log-mean is:</p>
<p><span class="math display">\[
\log \theta_i^{*} - \log \theta_i = \beta_j.
\]</span> Exponentiating both sides, we have:</p>
<p><span class="math display">\[
e^{\beta_j} = \frac{\theta_i^{*}}{\theta_i},
\]</span></p>
<p>which is interpreted as the <strong>incidence rate ratio (IRR)</strong> — the multiplicative change in the expected count for a one-unit increase in <span class="math inline">\(( X_{ij} )\)</span>, holding other variables constant.</p>
<hr>
</section>
<section id="fitting-a-poisson-regression-in-r" class="level4">
<h4 class="anchored" data-anchor-id="fitting-a-poisson-regression-in-r">Fitting a Poisson Regression in R</h4>
<p>We are going to use the preterm birth data from Georgia to illustrate our approach. For this analysis, the data have been aggregated by 5-year maternal age groups and stratified by infant sex and maternal tobacco use. This aggregation allows us to model counts of preterm births (events) relative to the number of total live births (exposure) using a Poisson regression.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"/Users/emilypeterson/Library/CloudStorage/OneDrive-EmoryUniversity/BIOS 526/BIOS526_Book/data/PTB.Rdata"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>age_group <span class="ot">&lt;-</span> <span class="fu">cut</span>(dat<span class="sc">$</span>age,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">15</span>, <span class="dv">45</span>, <span class="dv">5</span>),</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>                     <span class="at">right =</span> <span class="cn">FALSE</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"15-19"</span>, <span class="st">"20-24"</span>, <span class="st">"25-29"</span>, <span class="st">"30-34"</span>, <span class="st">"35-39"</span>, <span class="st">"40-44"</span>))</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>agg_data <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(age_group, male, tobacco) <span class="sc">%&gt;%</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">events =</span> <span class="fu">sum</span>(ptb),</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">total =</span> <span class="fu">n</span>()</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(agg_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
# Groups:   age_group, male [3]
  age_group male  tobacco events total
  &lt;fct&gt;     &lt;fct&gt;   &lt;int&gt;  &lt;int&gt; &lt;int&gt;
1 15-19     F           0    315  3184
2 15-19     F           1     31   245
3 15-19     M           0    325  3297
4 15-19     M           1     26   276
5 20-24     F           0    696  8257
6 20-24     F           1     61   663</code></pre>
</div>
</div>
<p>Here we can see the <strong>number of preterm births (<code>events</code>) for each age-group–sex–tobacco combination</strong>, as well as the <strong>total number of live births (<code>total</code>)</strong> in that subgroup.</p>
<p>To fit a Poisson regression, we model the counts of events with a <strong>log link function</strong>, using the total number of births as an <strong>offset</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>fit_poisson <span class="ot">&lt;-</span> <span class="fu">glm</span>(events <span class="sc">~</span> age_group <span class="sc">+</span> male <span class="sc">+</span> tobacco,</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">family =</span> poisson,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">offset =</span> <span class="fu">log</span>(total),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> agg_data)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_poisson)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = events ~ age_group + male + tobacco, family = poisson, 
    data = agg_data, offset = log(total))

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)    -2.37223    0.04040 -58.713  &lt; 2e-16 ***
age_group20-24 -0.11935    0.04533  -2.633  0.00847 ** 
age_group25-29 -0.24692    0.04539  -5.441 5.31e-08 ***
age_group30-34 -0.21900    0.04570  -4.792 1.65e-06 ***
age_group35-39 -0.04205    0.05075  -0.829  0.40736    
age_group40-44  0.12036    0.08087   1.488  0.13668    
maleM           0.06634    0.02474   2.682  0.00733 ** 
tobacco         0.34917    0.05029   6.943 3.83e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 148.530  on 23  degrees of freedom
Residual deviance:  29.892  on 16  degrees of freedom
AIC: 202.82

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><strong>Model Interpretation:</strong></p>
<ul>
<li><p>The intercept (<span class="math inline">\(\hat{\beta}_0 = -2.37\)</span>) represents the log rate of preterm birth for the reference group: mothers aged 15–19, with female infants and no tobacco use. Converting to a rate: <span class="math inline">\(e^{-2.37} \approx 0.093\)</span>, meaning about 9 preterm births per 100 live births in this reference group.</p></li>
<li><p>Age effects: Compared to mothers aged 15–19: Ages 20–24 have a 11% lower rate of preterm birth: <span class="math inline">\(e^{-0.119} \approx 0.89\)</span> (p = 0.008). Ages 25–29 have a 22% lower rate: <span class="math inline">\(e^{-0.247} \approx 0.78\)</span> (p &lt; 0.001). Ages 30–34 have a 20% lower rate: <span class="math inline">\(e^{-0.219} \approx 0.80\)</span> (p &lt; 0.001). No significant difference is observed for ages 35–39 or 40–44 (p &gt; 0.05).</p></li>
<li><p>Infant sex: Male infants have a 6.9% higher preterm birth rate compared to female infants: <span class="math inline">\(e^{0.066} \approx 1.07\)</span> (p = 0.007).</p></li>
<li><p>Tobacco use: Mothers who smoke have a 42% higher preterm birth rate compared to non-smokers: <span class="math inline">\(e^{0.349} \approx 1.42\)</span> (p &lt; 0.001).</p></li>
<li><p>Goodness-of-fit: The residual deviance (29.89 on 16 df) suggests an adequate fit, and the model explains a substantial portion of variation compared to the null model (null deviance = 148.53).</p></li>
</ul>
<hr>
</section>
<section id="what-is-an-offset" class="level4">
<h4 class="anchored" data-anchor-id="what-is-an-offset">What is an Offset?</h4>
<p>In the code above you saw a parameter in the glm <span class="math inline">\(\text{offset = log(total)}\)</span>. This is called an offset in Poisson regression.</p>
<p>When modeling <strong>rates</strong> rather than raw counts, it is critical to account for the <strong>population-at-risk</strong> or the <strong>exposure time</strong> for each observation. In the context of preterm birth data, the <strong>total number of live births</strong> within each age–sex–tobacco subgroup serves as the population-at-risk. Without this adjustment, groups with larger populations would naturally have higher counts simply due to their size, not because they have a higher risk of preterm births.</p>
<p><strong>Why Use an Offset?</strong></p>
<ul>
<li><p>The Poisson regression models the expected <strong>count</strong> of events <span class="math inline">\(y_i\)</span> as: <span class="math display">\[
y_i \sim \text{Poisson}(\theta_i)
\]</span> where <span class="math inline">\(\theta_i\)</span> is the <strong>expected count</strong> for the <span class="math inline">\(i\)</span>th subgroup.</p></li>
<li><p>To model <strong>rates</strong>, we can express: <span class="math display">\[
\text{Rate}_i = \frac{\theta_i}{N_i}
\]</span> where <span class="math inline">\(N_i\)</span> is the <strong>population size</strong> (e.g., total births in the subgroup).</p></li>
<li><p>Taking logs: <span class="math display">\[
\log(\theta_i) = \log(N_i) + \log(\text{Rate}_i).
\]</span> Here, <span class="math inline">\(\log(N_i)\)</span> is treated as a <strong>known constant</strong> rather than a parameter to estimate.</p></li>
<li><p>This motivates the use of an <strong>offset term</strong>: <span class="math display">\[
\log(\theta_i) = \log(N_i) + X_i \beta,
\]</span>.</p></li>
</ul>
<hr>
</section>
<section id="poisson-overdispersion" class="level3">
<h3 class="anchored" data-anchor-id="poisson-overdispersion">Poisson Overdispersion</h3>
<p>One of the most important assumptions of the Poisson model is <strong>equidispersion</strong>, meaning the variance of the outcome equals the mean:</p>
<p><span class="math display">\[
E(y_i) = Var(y_i) = \theta_i.
\]</span></p>
<p>In real data, especially with health outcomes, this assumption often fails. <strong>Overdispersion</strong> occurs when the variance is larger than the mean:</p>
<p><span class="math display">\[
Var(y_i) &gt; E(y_i).
\]</span></p>
<p>This can lead to: - Standard errors that are too small<br>
- Confidence intervals that are too narrow<br>
- p-values that are too optimistic</p>
<hr>
<section id="how-to-check-for-overdispersion" class="level4">
<h4 class="anchored" data-anchor-id="how-to-check-for-overdispersion">How to Check for Overdispersion</h4>
<p>A common diagnostic is the <strong>dispersion statistic</strong>, defined as:</p>
<p><span class="math display">\[
\hat{\phi} = \frac{\text{Residual Deviance}}{\text{Residual Degrees of Freedom}}
\]</span></p>
<ul>
<li>If <span class="math inline">\(\hat{\phi} \approx 1\)</span>, the equidispersion assumption holds.<br>
</li>
<li>If <span class="math inline">\(\hat{\phi} &gt; 1.5\)</span>, the data are likely overdispersed.<br>
</li>
<li>If <span class="math inline">\(\hat{\phi} &lt; 1\)</span>, underdispersion may be present (less common).</li>
</ul>
<p>In R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate dispersion statistic</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">deviance</span>(fit_poisson) <span class="sc">/</span> <span class="fu">df.residual</span>(fit_poisson)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.868255</code></pre>
</div>
</div>
<hr>
</section>
<section id="remedies-for-overdispersion" class="level4">
<h4 class="anchored" data-anchor-id="remedies-for-overdispersion">Remedies for Overdispersion</h4>
<p><strong>Quasi-Poisson Model:</strong></p>
<p>The quasi-Poisson approach allows the variance to be proportional to the mean but inflated by a dispersion parameter:</p>
<p><span class="math display">\[
Var(y_i) = \phi \cdot \theta_i
\]</span></p>
<ul>
<li>Implemented in R with <code>family = quasipoisson</code>.<br>
</li>
<li>Coefficient estimates remain the same as Poisson, but <strong>standard errors are corrected</strong>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>fit_quasi <span class="ot">&lt;-</span> <span class="fu">glm</span>(events <span class="sc">~</span> age_group <span class="sc">+</span> male <span class="sc">+</span> tobacco,</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> quasipoisson,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">offset =</span> <span class="fu">log</span>(total),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> agg_data)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_quasi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = events ~ age_group + male + tobacco, family = quasipoisson, 
    data = agg_data, offset = log(total))

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    -2.37223    0.05722 -41.459  &lt; 2e-16 ***
age_group20-24 -0.11935    0.06420  -1.859 0.081512 .  
age_group25-29 -0.24692    0.06427  -3.842 0.001440 ** 
age_group30-34 -0.21900    0.06472  -3.384 0.003788 ** 
age_group35-39 -0.04205    0.07187  -0.585 0.566663    
age_group40-44  0.12036    0.11453   1.051 0.308915    
maleM           0.06634    0.03504   1.894 0.076508 .  
tobacco         0.34917    0.07122   4.903 0.000159 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for quasipoisson family taken to be 2.005549)

    Null deviance: 148.530  on 23  degrees of freedom
Residual deviance:  29.892  on 16  degrees of freedom
AIC: NA

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<hr>
</section>
<section id="differences-between-the-binomial-and-poisson-models" class="level4">
<h4 class="anchored" data-anchor-id="differences-between-the-binomial-and-poisson-models">Differences between the Binomial and Poisson models</h4>
<p>The Poisson model is similar to the binomial model for count data but is applied in slightly different situations.</p>
<ul>
<li><p>If each data point <span class="math inline">\(y_i\)</span> can be interpreted as the number of “successes” out of <span class="math inline">\(n_i\)</span> trials then it is standard to use the binomial/logistic model.</p></li>
<li><p>If each data point <span class="math inline">\(y_i\)</span> does not have a natural limit- it is not based on a number of independent trials- then it is standard to use the Poisson/log repression model.</p></li>
</ul>
<hr>
</section>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary"><span style="color: purple;">Summary</span></h2>
<table class="table">
<colgroup>
<col style="width: 9%">
<col style="width: 90%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Section</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>What is the model?</strong></td>
<td><strong>Poisson Regression:</strong> Models count data (<span class="math inline">\(y_i = 0,1,2,...\)</span>) assuming <span class="math inline">\(y_i \sim \text{Poisson}(\theta_i)\)</span>, where <span class="math inline">\(E(y_i) = \theta_i\)</span> and <span class="math inline">\(Var(y_i) = \theta_i\)</span>. The mean count is linked to predictors by <span class="math inline">\(\log(\theta_i) = X_i \beta\)</span>.</td>
</tr>
<tr class="even">
<td><strong>Link Function</strong></td>
<td>Uses the <strong>log link</strong>, <span class="math inline">\(g(\theta_i) = \log(\theta_i)\)</span>, mapping <span class="math inline">\((0, \infty) \rightarrow (-\infty, \infty)\)</span>. Coefficients represent changes in the log of the expected count.</td>
</tr>
<tr class="odd">
<td><strong>Interpretation</strong></td>
<td><span class="math inline">\(e^{\beta_j}\)</span> is the <strong>incidence rate ratio (IRR)</strong>: the multiplicative change in the expected count for a one-unit increase in <span class="math inline">\(X_j\)</span>, holding other variables constant.</td>
</tr>
<tr class="even">
<td><strong>Offsets</strong></td>
<td>Adjusts for <strong>population-at-risk</strong> or exposure time. The model becomes <span class="math inline">\(\log(\theta_i) = \log(N_i) + X_i \beta\)</span>, where <span class="math inline">\(\log(N_i)\)</span> is an offset term (not estimated).</td>
</tr>
<tr class="odd">
<td><strong>Model Assumptions</strong></td>
<td>- Counts are independent. <br> - Mean equals variance (no overdispersion). <br> - Correct link function (log).</td>
</tr>
<tr class="even">
<td><strong>Overdispersion</strong></td>
<td>Check using <strong>dispersion statistic</strong> (<span class="math inline">\(\hat{\phi} = \tfrac{\text{Residual Deviance}}{\text{df}}\)</span>). <br> If <span class="math inline">\(\hat{\phi} &gt; 1\)</span>, use: <br> - <strong>Quasi-Poisson</strong> (adjusts SEs). <br> - <strong>Negative Binomial</strong> (flexible variance).</td>
</tr>
<tr class="odd">
<td><strong>Key Differences</strong></td>
<td>- Use <strong>Binomial/Logistic</strong> regression when counts are bounded by a number of trials (<span class="math inline">\(n_i\)</span>). <br> - Use <strong>Poisson</strong> regression when counts have no natural upper limit and represent rates or events over a fixed exposure.</td>
</tr>
<tr class="even">
<td><strong>Example Findings</strong></td>
<td>Tobacco use increases preterm birth rate by <strong>42%</strong> (<span class="math inline">\(IRR \approx 1.42\)</span>), while mothers aged 25–29 have a <strong>22% lower</strong> rate (<span class="math inline">\(IRR \approx 0.78\)</span>) compared to ages 15–19.</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Module_2A_GLM.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Module 2A Generalized Linear Models</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Module_2C_GLMMs.html" class="pagination-link">
        <span class="nav-page-text">Module 2C Generalized Linear Mixed Models</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>