<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>BIOS 526 Modern Regression Analysis - Module 4A Basis Expansion and Parametric Splines</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Module_4B_Splines.html" rel="next">
<link href="./Module_3_GEE_Cheat.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Module_4A_Splines.html">Module 4A Basis Expansion and Parametric Splines</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">BIOS 526 Modern Regression Analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_0_MLR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 0: Multiple Linear Regression Review</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1A_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1A Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1B_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1B Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1C_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1C Random Intercepts and Slopes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1_LMM_Cheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2A_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2A Generalized Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2B_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2B Generalized Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2C_GLMMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2C Generalized Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2D_GLMMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2D Generalized Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2_GLM_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3A_GEEs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3A Marginal Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3B_GEEs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3B Marginal Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3_GEE_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4A_Splines.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Module 4A Basis Expansion and Parametric Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4B_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4B Parametric Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4C_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4C Penalized Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4_Splines_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5A_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5A Generalized Additive Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5B_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5B Generalized Additive Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5_GAM_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_6_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 6 Model Selection, Diagnostics, &amp; Regression Workflow</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><strong>Overview</strong></a></li>
  <li><a href="#motivation-and-examples" id="toc-motivation-and-examples" class="nav-link" data-scroll-target="#motivation-and-examples">Motivation and Examples</a></li>
  <li><a href="#a-better-approach-basis-expansions-and-splines" id="toc-a-better-approach-basis-expansions-and-splines" class="nav-link" data-scroll-target="#a-better-approach-basis-expansions-and-splines"><u>A Better Approach: Basis Expansions and Splines</u></a></li>
  <li><a href="#summary-table-of-basis-function-types" id="toc-summary-table-of-basis-function-types" class="nav-link" data-scroll-target="#summary-table-of-basis-function-types">Summary Table of Basis Function Types</a></li>
  <li><a href="#polynomial-regression" id="toc-polynomial-regression" class="nav-link" data-scroll-target="#polynomial-regression">Polynomial Regression</a></li>
  <li><a href="#fitting-a-polynomial-regression-in-r" id="toc-fitting-a-polynomial-regression-in-r" class="nav-link" data-scroll-target="#fitting-a-polynomial-regression-in-r">Fitting a Polynomial Regression in R</a></li>
  <li><a href="#piecewise-regression" id="toc-piecewise-regression" class="nav-link" data-scroll-target="#piecewise-regression">Piecewise Regression</a>
  <ul class="collapse">
  <li><a href="#fitting-piecewise-polynomial-regression-models-in-r" id="toc-fitting-piecewise-polynomial-regression-models-in-r" class="nav-link" data-scroll-target="#fitting-piecewise-polynomial-regression-models-in-r">Fitting Piecewise Polynomial Regression Models in R</a></li>
  <li><a href="#discontinuities-at-the-boundaries" id="toc-discontinuities-at-the-boundaries" class="nav-link" data-scroll-target="#discontinuities-at-the-boundaries">Discontinuities at the Boundaries</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span style="color: purple;">Summary</span></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Module 4A Basis Expansion and Parametric Splines</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><img src="fig/bsplines.png" class="img-fluid"></p>
<p><strong>Reading</strong></p>
<p>Tutorial on Splines by Samuel Jackson (click here).</p>
<p>Intro to Splines (click here).</p>
<section id="overview" class="level3">
<h3 class="anchored" data-anchor-id="overview"><strong>Overview</strong></h3>
<p>In this module, you will learn <strong>Basis expansions and parametric splines</strong>, flexible extensions of linear regression that enable modeling complex, non-linear relationships between predictors and the response variable.</p>
<p><strong>After completing this module, you will understand:</strong></p>
<ul>
<li><p>Basis Functions and knots</p></li>
<li><p>Piecewise Linear Splines</p></li>
<li><p>Piecewise Cubic Splines</p></li>
<li><p>Bias-Variance Tradeoff</p></li>
<li><p>Criteria for model prediction performance (CV, GCV, AIC).</p></li>
</ul>
</section>
<section id="motivation-and-examples" class="level3">
<h3 class="anchored" data-anchor-id="motivation-and-examples">Motivation and Examples</h3>
<div class="illustration callout callout-style-default callout-important callout-titled" style="color: red">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Motivation:
</div>
</div>
<div class="callout-body-container callout-body">
<p>Linear regression assumes a linear relationship between predictors and the response. However, real-world data often exhibit <strong>non-linear patterns</strong> that cannot be captured well by straight lines.</p>
<ul>
<li><strong>Basis expansions</strong> allow us to transform predictors using functions (e.g., polynomials) to model non-linear relationships.</li>
<li><strong>Parametric splines</strong> provide even more flexibility by fitting piecewise polynomials that are smooth at points called knots.</li>
</ul>
<p>Using these methods helps avoid mis-specifying the functional form of the model, leading to <strong>more accurate fits</strong>, <strong>better predictions</strong>, and <strong>valid inference</strong>.</p>
</div>
</div>
<p><strong>Motivating Example: Birthweight and Mothers Age</strong> In a 2023 study of low birth weight among infants in Georgia, data were collected for <span class="math inline">\(N = 5{,}000\)</span> infants. Gestational age (in weeks) and maternal age were recorded to assess the relationship between gestational age and infant birthweight (in grams). The dataset includes the following variables:</p>
<ul>
<li><p><span class="math inline">\(gw\)</span> : gestational age in weeks.</p></li>
<li><p><span class="math inline">\(age\)</span>: maternal age at delivery</p></li>
<li><p><span class="math inline">\(bw\)</span> birthweight at delivery in grams</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="Module_4A_Splines_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>We see a non-linear relationship between <span class="math inline">\(gw\)</span> and <span class="math inline">\(bw\)</span> of a newborn.</li>
</ul>
<hr>
<section id="why-not-linear-regression-the-wrong-approach" class="level4">
<h4 class="anchored" data-anchor-id="why-not-linear-regression-the-wrong-approach">Why Not linear regression? <u><strong>The wrong approach</strong></u></h4>
<p>Let’s fit a linear regression model as a baseline to assess how well it captures this relationship. We’ll then compare it to more flexible approaches, such as basis expansions or splines, to see if they provide a better fit.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bw ~ gw, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-761.50  -83.01   16.80  100.80  348.80 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2177.513     39.351  -55.34   &lt;2e-16 ***
gw            141.808      1.019  139.10   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 144.2 on 4998 degrees of freedom
Multiple R-squared:  0.7947,    Adjusted R-squared:  0.7947 
F-statistic: 1.935e+04 on 1 and 4998 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Module_4A_Splines_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><p>The linear fit does not capture the non-linear trend in the relationship between gestational age (<span class="math inline">\(gw\)</span>) and birthweight (<span class="math inline">\(bw\)</span>).</p></li>
<li><p>Overestimates birthweight at lower and higher gestational ages.</p></li>
<li><p>Doesn’t capture curvature in the true relationship.</p></li>
<li><p>Suggests the need for a more flexible modeling approach, such as basis expansions or splines, to better capture the underlying structure.</p></li>
</ul>
<hr>
</section>
</section>
<section id="a-better-approach-basis-expansions-and-splines" class="level3">
<h3 class="anchored" data-anchor-id="a-better-approach-basis-expansions-and-splines"><u>A Better Approach: Basis Expansions and Splines</u></h3>
<p><strong><span style="color: blue;">Basis Expansion</span></strong></p>
<ul>
<li>Consider the regression model:</li>
</ul>
<p><span class="math display">\[
y_i = g(x_i) + \epsilon_i,
\]</span></p>
<p>where <span class="math inline">\(g(x_i)\)</span> represents the true, possibly non-linear relationship between the predictor <span class="math inline">\(x_i\)</span> and the response <span class="math inline">\(y_i\)</span>, and <span class="math inline">\(\epsilon_i\)</span> is the error term.</p>
<ul>
<li>One common approach is to express <span class="math inline">\(g(x_i)\)</span> as a linear combination of <span class="math inline">\(M\)</span> known basis functions <span class="math inline">\(b_m(x_i)\)</span>:</li>
</ul>
<p><span class="math display">\[
g(x_i) = \sum_{m=1}^M \beta_m b_m(x_i),
\]</span></p>
<p>where <span class="math inline">\(\beta_m\)</span> are unknown coefficients to be estimated.</p>
<ul>
<li><p><span class="math inline">\(b_m(x_i)\)</span> are called <strong>Basis Function</strong> and are chosen and fixed <strong>a priori</strong>, serving as known transformations of the original predictor <span class="math inline">\(x_i\)</span>.</p></li>
<li><p>Our task is to estimate the coefficients <span class="math inline">\(\beta_m\)</span> corresponding to these transformed variables.</p></li>
<li><p>Basis functions provide a flexible framework to model complex, non-linear relationships by representing <span class="math inline">\(g(x)\)</span> as a combination of simpler functions. They are fundamental tools in functional data analysis and optimization, enabling the modeling of curves as piecewise or smoothly varying functions.</p></li>
</ul>
<p>Below are some common examples of Basis Functions:</p>
<div class="callout callout-style-simple callout-tip no-icon callout-titled" style="color:gray">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
1. <strong>Polynomial Basis</strong>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Definition:</strong> A polynomial basis uses powers of the predictor variable to model non-linear trends. The basis functions are:</p>
<p><span class="math display">\[
b_1(x) = 1,\quad b_2(x) = x,\quad b_3(x) = x^2,\quad \ldots,\quad b_M(x) = x^{M-1}
\]</span></p>
<p><strong>Model:</strong></p>
<p><span class="math display">\[
g(x) = \beta_0 + \beta_1 x + \beta_2 x^2 + \cdots + \beta_{M-1} x^{M-1}
\]</span></p>
<p><strong>Use Case:</strong> Polynomial bases are useful when the underlying relationship is smooth and continuous, such as quadratic or cubic trends. However, high-degree polynomials can lead to <strong>overfitting</strong> and <strong>numerical instability</strong>, especially near the boundaries (Runge’s phenomenon).</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon callout-titled" style="color:gray">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
2. <strong>Indicator Basis (Step Functions)</strong>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Definition:</strong> An indicator basis partitions the domain of ( x ) into intervals and defines a separate basis function for each interval:</p>
<p><span class="math display">\[
b_m(x) =
\begin{cases}
1 &amp; \text{if } x \in I_m \\
0 &amp; \text{otherwise}
\end{cases}
\]</span></p>
<p>where ( I_m ) is the ( m^ ) interval.</p>
<p><strong>Model:</strong></p>
<p><span class="math display">\[
g(x) = \sum_{m=1}^M \beta_m \cdot \mathbb{1}_{\{x \in I_m\}}
\]</span></p>
<p><strong>Use Case:</strong> This approach is useful for <strong>piecewise constant</strong> modeling, especially when the data exhibit abrupt changes or discontinuities. However, the resulting model is not smooth, and predictions can jump sharply at the boundaries between intervals.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon callout-titled" style="color:gray">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
3. <strong>Periodic Basis (Fourier Series)</strong>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Definition:</strong> Periodic bases use sine and cosine functions to capture repeating patterns in the data. A typical Fourier basis includes terms like:</p>
<p><span class="math display">\[
b_1(x) = \sin(2\pi x),\quad b_2(x) = \cos(2\pi x),\quad b_3(x) = \sin(4\pi x),\quad \ldots
\]</span></p>
<p><strong>Model:</strong></p>
<p><span class="math display">\[
g(x) = \beta_1 \sin(2\pi x) + \beta_2 \cos(2\pi x) + \cdots
\]</span></p>
<p><strong>Use Case:</strong> Periodic bases are ideal for <strong>cyclical data</strong>, such as seasonal trends (e.g., monthly temperatures, daily traffic volume). They provide a smooth, continuous fit and naturally model data that repeat over a fixed period.</p>
</div>
</div>
</div>
</section>
<section id="summary-table-of-basis-function-types" class="level3">
<h3 class="anchored" data-anchor-id="summary-table-of-basis-function-types">Summary Table of Basis Function Types</h3>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Basis Type</th>
<th>Captures</th>
<th>Smoothness</th>
<th>Use Case</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Polynomial</td>
<td>Global smooth trends</td>
<td>Smooth</td>
<td>Curved but continuous relationships</td>
</tr>
<tr class="even">
<td>Indicator</td>
<td>Piecewise constant</td>
<td>Discontinuous</td>
<td>Sharp jumps or categorization</td>
</tr>
<tr class="odd">
<td>Periodic</td>
<td>Cyclical/repeating trends</td>
<td>Smooth</td>
<td>Seasonal or periodic data</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="polynomial-regression" class="level3">
<h3 class="anchored" data-anchor-id="polynomial-regression">Polynomial Regression</h3>
<p>Let’s fit a <u>Polynomial Regression</u> to the birthweight outcomes:</p>
<p><span class="math display">\[
\begin{align*}
\text{Quadratic } y_i &amp; = \beta_0 + \beta_1 x_i + \beta_2 x_i^2 + e_i\\
\text{Cubic } y_i &amp; = \beta_0 + \beta_1 x_i + \beta_2 x_i^2 +  \beta_3 x_i^3 + e_i\\
\end{align*}
\]</span></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Module_4A_Splines_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The <strong>linear</strong> model provides a general upward trend, but it fails to capture subtle curvature in the data, particularly at the extremes of gestational age. The <strong>quadratic</strong> model improves the fit by introducing curvature, better capturing the accelerating increase in birthweight with gestational age. However, it tends to oversimplify the relationship near the boundaries. The <strong>cubic</strong> model offers the most flexible fit among the three, capturing inflection points and more nuanced trends in the data. While it improves predictive accuracy, especially in the mid-gestational range, it also may introduce slight overfitting near the edges. Overall, higher-degree polynomials offer more flexibility but must be used cautiously to avoid instability and overfitting, particularly with extrapolation.</p>
<p>Note that all polynomial functions often cannot model the ends very well.</p>
<hr>
</section>
<section id="fitting-a-polynomial-regression-in-r" class="level3">
<h3 class="anchored" data-anchor-id="fitting-a-polynomial-regression-in-r">Fitting a Polynomial Regression in R</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Quadratic polynomial model</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(bw <span class="sc">~</span> gw <span class="sc">+</span> <span class="fu">I</span>(gw<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> dat)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Cubic polynomial model</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>fit3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(bw <span class="sc">~</span> gw <span class="sc">+</span> <span class="fu">I</span>(gw<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(gw<span class="sc">^</span><span class="dv">3</span>), <span class="at">data =</span> dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Quadratic Model (<code>fit2</code>)</th>
<th>Cubic Model (<code>fit3</code>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Model formula</strong></td>
<td><span class="math display">\[ bw \sim gw + gw^2 \]</span></td>
<td><span class="math display">\[ bw \sim gw + gw^2 + gw^3 \]</span></td>
</tr>
<tr class="even">
<td><strong>Residual standard error</strong></td>
<td>113.8</td>
<td>110.1</td>
</tr>
<tr class="odd">
<td><strong>Adjusted ( R^2 )</strong></td>
<td>0.872</td>
<td>0.880</td>
</tr>
<tr class="even">
<td><strong>F-statistic</strong></td>
<td>17,030 (p &lt; 2.2e-16)</td>
<td>12,240 (p &lt; 2.2e-16)</td>
</tr>
<tr class="odd">
<td><strong>Coefficient significance</strong></td>
<td>All terms highly significant (p &lt; 2e-16)</td>
<td>All terms highly significant (p &lt; 2e-16)</td>
</tr>
<tr class="even">
<td><strong>Max residual</strong></td>
<td>451.45</td>
<td>300.81</td>
</tr>
<tr class="odd">
<td><strong>Interpretation of coefficients</strong></td>
<td>Negative quadratic term indicates decreasing marginal effect of gestational weeks on birthweight</td>
<td>Cubic term allows more flexible curvature capturing subtle inflections</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Both quadratic and cubic models explain a large proportion of variance in birthweight, with adjusted <span class="math inline">\(R^2\)</span> above 0.87.</p></li>
<li><p>The cubic model shows a modest improvement over quadratic:</p>
<ul>
<li>Lower residual standard error (110.1 vs 113.8)</li>
<li>Slightly higher adjusted <span class="math inline">\(R^2\)</span> (0.880 vs 0.872)</li>
<li>Smaller maximum residuals (300.81 vs 451.45)</li>
</ul></li>
<li><p>All polynomial terms are highly statistically significant, confirming nonlinear relationships between gestational age and birthweight.</p></li>
<li><p>The cubic term adds flexibility, capturing subtle curvature and inflection points missed by the quadratic model.</p></li>
<li><p>However, the improvement is modest and higher-degree polynomials risk overfitting.</p></li>
</ul>
<hr>
</section>
<section id="piecewise-regression" class="level2">
<h2 class="anchored" data-anchor-id="piecewise-regression">Piecewise Regression</h2>
<p>One intuitive approach to modeling <strong>non-linear relationships</strong> between a predictor and the response is to divide the range of the predictor into several <strong>meaningful subregions</strong>. For example, consider pregnancy length as a predictor:</p>
<ul>
<li><strong>Preterm:</strong> less than 37 weeks<br>
</li>
<li><strong>Full-term:</strong> 37 to 41 weeks<br>
</li>
<li><strong>Post-term:</strong> more than 42 weeks</li>
</ul>
<p>Rather than fitting a single global polynomial across the entire range, we can model the relationship using polynomial functions <span style="color: blue;">separately within each region</span>. This technique allows for greater flexibility and can better capture local patterns in the data without overfitting globally.</p>
<p>The values that define the boundaries between these regions—such as 37 and 42 weeks in the example above—are called <span style="color: blue;">knots</span>.</p>
<p><strong>Knots</strong> are central to methods such as piecewise regression, where the domain of the predictor is split at these points, and separate (yet smoothly connected) polynomial functions are fit in each subregion. This structure enables models to adapt to changes in the shape of the data while preserving continuity and smoothness.</p>
<p>Piecewise regression can be interpreted as a model in which the basis functions of <span class="math inline">\(x_i\)</span> are allowed to interact with indicator (dummy) variables that define distinct regions of the predictor’s domain. For example:</p>
<p>where</p>
<p><span class="math display">\[
D_{1i} =
\begin{cases}
1 &amp; 37 \leq x_i &lt; 42\\
0 &amp; OW
\end{cases}
\]</span></p>
<p><span class="math display">\[
D_{2i} =
\begin{cases}
1 &amp;  x_i \geq 42\\
0 &amp; OW
\end{cases}
\]</span></p>
<p>We have two cut-points (knots) which yields three regions. We only need two dummy variables for three regions.</p>
<p>The piecewise quadratic regression model is expressed as:</p>
<p><span class="math display">\[
\begin{aligned}
y_i =\ &amp; \beta_0 + \beta_1 x_i + \beta_2 x_i^2 &amp; \text{(Preterm baseline)} \\
&amp; + \beta_3 D_{1i} + \beta_4 x_i D_{1i} + \beta_5 x_i^2 D_{1i} &amp; \text{(Full-term adjustment)} \\
&amp; + \beta_6 D_{2i} + \beta_7 x_i D_{2i} + \beta_8 x_i^2 D_{2i} &amp; \text{(Post-term adjustment)}\\
&amp; + \epsilon
\end{aligned}
\]</span></p>
<hr>
<section id="fitting-piecewise-polynomial-regression-models-in-r" class="level3">
<h3 class="anchored" data-anchor-id="fitting-piecewise-polynomial-regression-models-in-r">Fitting Piecewise Polynomial Regression Models in R</h3>
<p>In this section, we demonstrate how to fit piecewise polynomial regression models by dividing the predictor variable — gestational weeks (<span class="math inline">\(gw\)</span>) — into meaningful regions defined above and fitting separate polynomial models within each region. We use indicator variables for the regions and interact them with polynomial terms of <span class="math inline">\(gw\)</span>.</p>
<p>We divide the gestational weeks into three regions based on clinical definitions:</p>
<ul>
<li><strong>Preterm:</strong> <span class="math inline">\(gw &lt; 37\)</span> weeks<br>
</li>
<li><strong>Full-term:</strong> <span class="math inline">\(37 \leq gw \leq 41\)</span> weeks<br>
</li>
<li><strong>Post-term:</strong> <span class="math inline">\(gw \geq 42\)</span> weeks</li>
</ul>
<p>In R, we create logical vectors to indicate these regions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Ind1 <span class="ot">=</span> dat<span class="sc">$</span>gw <span class="sc">&gt;=</span> <span class="dv">37</span> <span class="sc">&amp;</span> dat<span class="sc">$</span>gw <span class="sc">&lt;=</span> <span class="dv">41</span> <span class="co">#Full term indicator</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>Ind2 <span class="ot">=</span> dat<span class="sc">$</span>gw <span class="sc">&gt;=</span> <span class="dv">42</span>                <span class="co">#Post-term indicator</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The preterm region is implicitly defined where both <code>Ind1</code> and <code>Ind2</code> are FALSE.</p>
<!-- We fit a linear model where the slope and intercept can differ by region through interaction terms: -->
<!-- Here, $gw * (Ind1 + Ind2)$ expands to include: -->
<!-- -   The main effect of $gw$ ($\beta_1$): This represents the baseline linear effect of gestational week on birthweight in the preterm region ($gw < 37$). For each additional week, birthweight changes by $\beta_1$ grams. -->
<!-- -   The main effects of $Ind_1$ and $Ind_2$ ($\beta_2$, $\beta_3$): These capture shifts in the intercept for the full-term and post-term regions, respectively, relative to the preterm baseline. In other words, they reflect differences in baseline birthweight at $gw=0$ (hypothetical) between regions. -->
<!-- Interaction terms between $gw$ and indicators: -->
<!-- -   $gw : Ind_1$ (Estimate = 1202, significant): The slope of $gw$ in the full-term region is 1202 grams per week higher than in the preterm region. This means birthweight increases more steeply with gestational weeks in the full-term window. -->
<!-- -   $gw : Ind_2$ (Estimate = 2488, not significant): Suggests a higher slope in the post-term region, but this is not statistically significant, so no strong evidence the slope differs from preterm here. -->
<!-- Interaction terms between $gw^2$ and indicators: -->
<!-- -   $gw^2 : Ind_1$ (Estimate = -16.85, significant): Indicates that the quadratic curvature in the full-term region bends downward more sharply compared to the preterm region, capturing a deceleration in growth. -->
<!-- -   $gw^2 : Ind_2$ (Estimate = -31.34, partial): Suggests similar curvature change in the post-term region, though significance would need to be checked. -->
<!-- -   This model includes only linear terms for `gw` and allows both the intercept and the slope of `gw` to vary across the gestational age regions defined by `Ind1` and `Ind2`. -->
<p>To model non-linear relationships between birthweight (<code>bw</code>) and gestational weeks (<code>gw</code>) that may vary across different gestational age regions (e.g., preterm, full-term, post-term), we may extend the model to include quadratic terms for <code>gw</code>.</p>
<p>The piecewise quadratic regression model with interaction terms can be written as:</p>
<p><span class="math display">\[
bw_i = \beta_0 + \beta_1 gw_i + \beta_2 gw_i^2 + \beta_3 Ind1_i + \beta_4 Ind2_i + \beta_5 (gw_i \times Ind1_i) + \beta_6 (gw_i \times Ind2_i) + \beta_7 (gw_i^2 \times Ind1_i) + \beta_8 (gw_i^2 \times Ind2_i) + \epsilon_i
\]</span></p>
<p>This model allows both the intercept and the linear and quadratic effects of gestational weeks to vary across the three gestational age regions. This flexibility enables better modeling of complex, region-specific relationships between gestational age and birthweight.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>fit5 <span class="ot">=</span> <span class="fu">lm</span> (bw<span class="sc">~</span>(gw <span class="sc">+</span> <span class="fu">I</span>(gw<span class="sc">^</span><span class="dv">2</span>))<span class="sc">*</span>(Ind1<span class="sc">+</span> Ind2), <span class="at">data =</span> dat)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="do">###Important</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># In R formulas, the caret symbol (^) is not interpreted as exponentiation but as a formula operator indicating interactions or polynomial expansions of terms.</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Writing (gw^2) without wrapping it in the I() function causes R to treat it as "gw to the power of 2" in the formula sense (interactions), not as the squared variable $gw^2$.</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># This leads to an unintended model structure that does not include the quadratic term properly, and may result in errors or nonsensical coefficients.</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>dontdothis <span class="ot">=</span> <span class="fu">lm</span>(bw<span class="sc">~</span>(gw<span class="sc">+</span>(gw<span class="sc">^</span><span class="dv">2</span>))<span class="sc">*</span>(Ind1<span class="sc">+</span> Ind2), <span class="at">data =</span> dat)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>fit6 <span class="ot">=</span> <span class="fu">lm</span> (bw<span class="sc">~</span>(gw<span class="sc">+</span><span class="fu">I</span>(gw<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(gw<span class="sc">^</span><span class="dv">3</span>))<span class="sc">*</span>(Ind1<span class="sc">+</span> Ind2), <span class="at">data =</span> dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Module_4A_Splines_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Limitations in Piecewise Polynomials:</strong></p>
<ul>
<li><p>Limited flexibility in capturing complex trends: Although polynomial fits (linear, quadratic, cubic) are applied separately in each region, they often produce similar shapes, which may fail to represent subtle changes in the relationship between gestational age and birthweight—especially where the effect weakens at higher gestational weeks.</p></li>
<li><p>Lack of smoothness at knots: The fitted curves generally do not join smoothly at the boundaries (knots) between regions. This can cause abrupt changes or discontinuities in the predicted values or their slopes, which is unrealistic for most natural processes.</p></li>
<li><p>High model complexity: Fitting separate polynomials for each region requires estimating many parameters, increasing the degrees of freedom and the potential for overfitting, particularly with limited data.</p></li>
</ul>
<hr>
</section>
<section id="discontinuities-at-the-boundaries" class="level3">
<h3 class="anchored" data-anchor-id="discontinuities-at-the-boundaries">Discontinuities at the Boundaries</h3>
<p>Piecewise polynomial regression fits separate polynomial models within different intervals of the predictor variable separated by <em>knots</em>. While this allows for flexible modeling of nonlinear relationships, an important drawback is the potential for <strong>discontinuities</strong> at these knot points.</p>
<p><u><strong>What is a discontinuity?</strong></u> A discontinuity occurs when the fitted function or its derivatives have abrupt changes at the knot locations. For example, suppose the predictor <span class="math inline">\(x\)</span> is divided into two regions by a knot at <span class="math inline">\(k\)</span>. We fit two separate polynomial functions:</p>
<p><span class="math display">\[
g_1(x) = \beta_0^{(1)} + \beta_1^{(1)} x + \beta_2^{(1)} x^2, \quad x &lt; k
\]</span></p>
<p><span class="math display">\[
g_2(x) = \beta_0^{(2)} + \beta_1^{(2)} x + \beta_2^{(2)} x^2, \quad x \geq k
\]</span></p>
<p>If these functions are not constrained to be equal at <span class="math inline">\(x = k\)</span>, then the value of <span class="math inline">\(g_1(k)\)</span> may differ from <span class="math inline">\(g_2(k)\)</span>, causing a <strong>jump</strong> in the predicted curve.</p>
<ol type="1">
<li><u><strong>Discontinuity in the function:</strong></u> If <span class="math inline">\(g_1(k) \neq g_2(k)\)</span>, the function is <strong>discontinuous</strong> at <span class="math inline">\(k\)</span>. This means the predicted response suddenly changes as we cross the knot, which is usually unrealistic for continuous processes like birthweight increasing with gestational age.</li>
<li><u><strong>Discontinuity in derivatives:</strong></u> Even if <span class="math inline">\(g_1(k) = g_2(k)\)</span>, the slope or curvature may still jump,e.g.,</li>
</ol>
<ul>
<li><p>If <span class="math inline">\(g_1'(k) \neq g_2'(k)\)</span>, the first derivative (slope) is discontinuous.</p></li>
<li><p>If <span class="math inline">\(g_1''(k) \neq g_2''(k)\)</span>, the second derivative (curvature) is discontinuous.</p></li>
</ul>
<p>Discontinuities in derivatives make the fitted curve look “kinked” or less smooth at the knots.</p>
<p><u><strong>Why does this matter?</strong></u> Discontinuities reduce the <strong>smoothness</strong> of the regression curve. For biological or physical processes, smooth transitions are often expected.Piecewise polynomial regression without additional constraints does <strong>not guarantee continuity or smoothness</strong> at the knots.</p>
<hr>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary"><span style="color: purple;">Summary</span></h2>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Section</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>What is the Model?</strong></td>
<td>A <strong>basis expansion model</strong> expresses an unknown function <span class="math inline">\(g(x)\)</span> as a linear combination of known basis functions: <br> <span class="math inline">\(g(x_i) = \sum_{m=1}^M \beta_m b_m(x_i)\)</span> <br> The goal is to flexibly model nonlinear relationships by choosing appropriate basis functions <span class="math inline">\(b_m(\cdot)\)</span>.</td>
</tr>
<tr class="even">
<td><strong>Polynomial Basis</strong></td>
<td>Uses powers of <span class="math inline">\(x\)</span> as basis functions: <br> <span class="math inline">\(b_1(x) = 1, \quad b_2(x) = x, \quad b_3(x) = x^2, \quad \ldots, \quad b_M(x) = x^{M-1}\)</span> <br> Leads to polynomial regression models like quadratic or cubic regression.</td>
</tr>
<tr class="odd">
<td><strong>Piecewise Polynomial Basis</strong></td>
<td>Divides the domain of <span class="math inline">\(x\)</span> into intervals with <strong>knots</strong> and fits separate polynomials on each interval. <br> Uses indicator functions <span class="math inline">\(D_i\)</span> to select intervals, e.g., <span class="math inline">\(y_i = \beta_0 + \beta_1 x_i + \beta_2 x_i^2 + \beta_3 D_{1i} + \beta_4 x_i D_{1i} + \ldots\)</span></td>
</tr>
<tr class="even">
<td><strong>Indicator Variables (Knots)</strong></td>
<td><span class="math inline">\(D_{1i}, D_{2i}, \ldots\)</span> are defined to indicate which interval <span class="math inline">\(x_i\)</span> belongs to, enabling piecewise definitions of the function. <br> E.g., <span class="math inline">\(D_{1i} = 1\)</span> if <span class="math inline">\(x_i\)</span> in interval 1, else 0. <br> Allows flexibility but can cause discontinuities at knots if not constrained.</td>
</tr>
<tr class="odd">
<td><strong>Parametric Splines</strong></td>
<td>Piecewise polynomials with constraints (e.g., continuity, smoothness) at knots to avoid jumps or sharp corners. <br> Ensures the function and its derivatives match at knots, yielding smooth curves useful in regression and smoothing applications.</td>
</tr>
<tr class="even">
<td><strong>Why Use Basis Expansions?</strong></td>
<td>To model <strong>nonlinear</strong> effects in regression flexibly while retaining a linear structure in parameters <span class="math inline">\(\beta_m\)</span>, enabling standard estimation methods like least squares. <br> Basis expansions allow balancing flexibility and interpretability.</td>
</tr>
<tr class="odd">
<td><strong>Key R Modeling Note</strong></td>
<td>In R formulas, polynomial terms like <span class="math inline">\(x^2\)</span> must be wrapped in <code>I()</code> to indicate arithmetic, e.g., <code>I(x^2)</code>, otherwise caret <code>^</code> is interpreted as formula syntax (e.g., interaction).</td>
</tr>
<tr class="even">
<td><strong>Continuity and Smoothness</strong></td>
<td>Without constraints, piecewise polynomials can be <strong>discontinuous</strong> or have sharp corners at knots. <br> Parametric splines enforce conditions so that the function is continuous and smooth (derivatives continuous) across knots, improving fit quality and interpretability.</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Module_3_GEE_Cheat.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Module 3 Cheat Sheet</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Module_4B_Splines.html" class="pagination-link">
        <span class="nav-page-text">Module 4B Parametric Splines</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>