<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Module 2D Generalized Linear Mixed Models – BIOS 526 Modern Regression Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Module_2_GLM_Cheat.html" rel="next">
<link href="./Module_2C_GLMMs.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Module_2D_GLMMs.html">Module 2D Generalized Linear Mixed Models</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">BIOS 526 Modern Regression Analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_0_MLR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 0: Multiple Linear Regression Review</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1A_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1A Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1B_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1B Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1C_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1C Random Intercepts and Slopes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1_LMM_Cheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2A_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2A Generalized Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2B_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2B Generalized Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2C_GLMMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2C Generalized Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2D_GLMMs.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Module 2D Generalized Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2_GLM_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3A_GEEs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3A Marginal Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3B_GEEs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3B Marginal Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3_GEE_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4A_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4A Basis Expansion and Parametric Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4B_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4B Parametric Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4C_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4C Penalized Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4_Splines_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5A_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5A Generalized Additive Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5B_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5B Generalized Additive Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5_GAM_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_6_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 6 Model Selection, Diagnostics, &amp; Regression Workflow</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#motivation-and-examples" id="toc-motivation-and-examples" class="nav-link active" data-scroll-target="#motivation-and-examples">Motivation and Examples</a></li>
  <li><a href="#motivating-example-school-math-scores" id="toc-motivating-example-school-math-scores" class="nav-link" data-scroll-target="#motivating-example-school-math-scores">Motivating Example: School Math Scores</a></li>
  <li><a href="#fitting-a-linear-mixed-model" id="toc-fitting-a-linear-mixed-model" class="nav-link" data-scroll-target="#fitting-a-linear-mixed-model">Fitting a Linear Mixed Model</a></li>
  <li><a href="#the-better-approach-three-level-linear-mixed-model" id="toc-the-better-approach-three-level-linear-mixed-model" class="nav-link" data-scroll-target="#the-better-approach-three-level-linear-mixed-model">The Better Approach: Three Level Linear Mixed Model</a></li>
  <li><a href="#pooling-borrowing-information-at-multiple-levels" id="toc-pooling-borrowing-information-at-multiple-levels" class="nav-link" data-scroll-target="#pooling-borrowing-information-at-multiple-levels">Pooling (Borrowing Information) at Multiple Levels</a></li>
  <li><a href="#covariance-structures-in-hierarchical-glmms" id="toc-covariance-structures-in-hierarchical-glmms" class="nav-link" data-scroll-target="#covariance-structures-in-hierarchical-glmms">Covariance Structures in Hierarchical GLMMs</a></li>
  <li><a href="#intraclass-correlation-coefficients-icc" id="toc-intraclass-correlation-coefficients-icc" class="nav-link" data-scroll-target="#intraclass-correlation-coefficients-icc">Intraclass Correlation Coefficients (ICC)</a></li>
  <li><a href="#hierarchical-glmm-fitting-in-r" id="toc-hierarchical-glmm-fitting-in-r" class="nav-link" data-scroll-target="#hierarchical-glmm-fitting-in-r">Hierarchical GLMM Fitting in R</a></li>
  <li><a href="#model-interpretations" id="toc-model-interpretations" class="nav-link" data-scroll-target="#model-interpretations">Model Interpretations</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span style="color: purple;">Summary</span></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Module 2D Generalized Linear Mixed Models</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>School data example adapted from Gelman and Hill. <a href="https://sites.stat.columbia.edu/gelman/arm/">Data Analysis Using Regression and Multilevel/Hierarchical Models</a></p>
<p>Guatemalan data example: Rodriguez B and Goldman N (2001). Improved estimation procedures for multilevel models with binary response: a case study. Journal of Royal Statistical Society Series A 339-355.</p>
<section id="motivation-and-examples" class="level3">
<h3 class="anchored" data-anchor-id="motivation-and-examples">Motivation and Examples</h3>
<div class="illustration callout callout-style-default callout-important callout-titled" style="color: red">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Motivation:
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Hierarchical</strong> or <strong>multilevel</strong> models are used when observations are nested (.e.g, students within schools, repeated measures within individuals). Standard regression models ignore clustering, which leads to <strong>underestimated standard errors</strong> and <strong>biased inference</strong>.</p>
<p>Hierarchical models can be thought of as GLMs that are reparametrized to separate <strong>with-in</strong> group and <strong>between</strong> group sources of variation with <strong>nested</strong> data structures. These include:</p>
<ul>
<li>Fixed effects for population-level estimates</li>
<li>Random effects for group-specific deviations.</li>
<li>Can have multiple levels within one model structure.</li>
</ul>
<p>This has a very Bayesian Flavor! So it is more natural for me to think this way.</p>
</div>
</div>
</section>
<section id="motivating-example-school-math-scores" class="level3">
<h3 class="anchored" data-anchor-id="motivating-example-school-math-scores">Motivating Example: School Math Scores</h3>
<p>We consider a three-level hierarchical model of math achievement data.</p>
<p>Levels:</p>
<ul>
<li><p>Level 1 (Year within child):</p>
<ul>
<li><span class="math inline">\(math_{ijk}\)</span>: standardized math score of child <span class="math inline">\(j\)</span> in school <span class="math inline">\(i\)</span> during year <span class="math inline">\(k\)</span>.</li>
<li><span class="math inline">\(year_{ijk}\)</span>: primary school year (centered at 3.5).</li>
<li><span class="math inline">\(retained_{ijk}\)</span>: indicator for repeating the grade.</li>
</ul></li>
<li><p>Level 2 (Child within school):</p>
<ul>
<li><span class="math inline">\(child_{ij}\)</span>: child ID.</li>
<li><span class="math inline">\(female_{ij}\)</span>: indicator for female.</li>
<li><span class="math inline">\(black_{ij}\)</span>, <span class="math inline">\(hispanic_{ij}\)</span>: race/ethnicity indicators.</li>
</ul></li>
<li><p>Level 3 (School):</p>
<ul>
<li><span class="math inline">\(school_i\)</span>: school ID.</li>
<li><span class="math inline">\(size_i\)</span>: number of students in school <span class="math inline">\(i\)</span>.</li>
<li><span class="math inline">\(lowinc_i\)</span>: percentage of low-income students in school <span class="math inline">\(i\)</span>.</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">paste0</span>(<span class="fu">getwd</span>(), <span class="st">"/data/achievement.csv"</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7230   10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dat[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  year   math retained female black hispanic size lowinc school child
1  0.5  1.146        0      0     0        1  380   40.3   2020   244
2  1.5  1.134        0      0     0        1  380   40.3   2020   244
3  2.5  2.300        0      0     0        1  380   40.3   2020   244
4 -1.5 -1.303        0      0     0        0  380   40.3   2020   248
5 -0.5  0.439        0      0     0        0  380   40.3   2020   248
6  0.5  2.430        0      0     0        0  380   40.3   2020   248</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> math, <span class="at">group =</span> child, <span class="at">color =</span> <span class="fu">factor</span>(school))) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span>      <span class="co"># line for each student's trajectory</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span>     <span class="co"># points for observations</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Student Math Scores Over Time"</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Math Score"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"School"</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Module_2D_GLMMs_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot above shows individual trajectories of student scores across years. Colors denote school.</p>
<hr>
</section>
<section id="fitting-a-linear-mixed-model" class="level3">
<h3 class="anchored" data-anchor-id="fitting-a-linear-mixed-model">Fitting a Linear Mixed Model</h3>
<p>Using the methods we have learned so far, we would fit a linear mixed model (LMM). We can include a random intercept model to account for student-specific differences in baseline math scores:</p>
<p><span class="math display">\[
\text{math}_{ijk} = \beta_0 + \beta_1 \, \text{year}_{ijk} + \beta_2 \, \text{female}_{ij} + \beta_3 \, \text{black}_{ij} + \beta_4 \, \text{hispanic}_{ij} + \beta_5 \, \text{retained}_{ij} + u_{i} + \epsilon_{ijk},
\]</span></p>
<p>where:<br>
- <span class="math inline">\(i\)</span> indexes students within school <span class="math inline">\(j\)</span>,<br>
- <span class="math inline">\(u_{i} \sim N(0, \tau^2)\)</span> is a <strong>student-specific random intercept</strong>,<br>
- <span class="math inline">\(\epsilon_{ijk} \sim N(0, \sigma^2)\)</span> is the residual error term.</p>
<p>This model <em>partially pools</em> the intercepts across students, borrowing strength from the entire dataset while still allowing each student to have its own baseline.</p>
<p><span style="color: red;">Problem!</span>: Years are <strong>nested within students</strong>, and <strong>students are nested within schools</strong>. In other words, the math scores are measured repeatedly for each student (longitudinal data), and these students are clustered within schools. So even if we account for within student correlation, we have not accounted for within school correlation. A standard LLM fails to account for this hierarchical data structure.</p>
<hr>
</section>
<section id="the-better-approach-three-level-linear-mixed-model" class="level3">
<h3 class="anchored" data-anchor-id="the-better-approach-three-level-linear-mixed-model">The Better Approach: Three Level Linear Mixed Model</h3>
<p>We extend the previous model to account for <strong>both student-level and school-level random intercepts</strong>, fully respecting the data hierarchy (years within students, and students within schools).</p>
<p><span class="math display">\[
\begin{align*}
math_{ijk} &amp; \sim Normal(\mu_{ijk}, \sigma^2)\\
\mu_{ijk} &amp; = \beta_0 + \beta_1 \, \text{year}_{ijk} + \beta_2 \, \text{female}_{ij} + \beta_3 \, \text{black}_{ij} + \beta_4 \, \text{hispanic}_{ij} + \beta_5 \, \text{retained}_{ij} + \underbrace{u_{i}}_{\text{school}}  + \underbrace{u_{ij}}_{\text{student within school}},\\
u_{ij} &amp; \overset{iid}{\sim} N(0, \tau^2)\\
u_i &amp; \overset{iid}{\sim} N(0, \nu^2)\\
\epsilon_{ijk} &amp; \overset{iid}{\sim} N(0, \sigma^2). \quad \text{residual error for year-student-school}
\end{align*}
\]</span></p>
<p>We can think of <span class="math inline">\(u_i\)</span> and <span class="math inline">\(u_{ij}\)</span> as parameters that control for <span style="color: red;">unmeasured confounders</span> at the school and student level.</p>
<p><em>“One statistician’s mean structure is another’s covariance structure.” (Donald Rubin)</em></p>
<ul>
<li><p>In <strong>frequentist mixed models</strong>, random effects are viewed as part of the <strong>covariance structure</strong> because they induce correlation between observations within a cluster. The random effects are integrated out when estimating the model, and their variability (e.g., <span class="math inline">\(\tau^2\)</span>) contributes to the marginal covariance matrix.</p></li>
<li><p>In <strong>Bayesian or hierarchical modeling</strong>, the same random effects are treated as part of the <strong>mean structure</strong> with unknown parameters that have prior distributions. We estimate the full posterior for both fixed effects and random effects.</p></li>
<li><p>For example, in a linear mixed model:</p></li>
</ul>
<p><span class="math display">\[
y_{ij} = \beta_0 + \beta_1 x_{ij} + u_i + \epsilon_{ij},
\]</span></p>
<p>we can think of:</p>
<ul>
<li><p><strong>Bayesian method:</strong> <span class="math inline">\(u_i\)</span> is a <strong>random deviation</strong> that adjusts the mean for cluster <span class="math inline">\(i\)</span> (part of the mean structure). In our 3-level LMM, we place priors on both population-level parameters and random effects, e.g., <span class="math inline">\(\beta_k \sim N(0, 10^2)\)</span>.</p></li>
<li><p><strong>Frequentist method:</strong> Equivalently, <u>the marginal distribution of <span class="math inline">\(y_{ij}\)</span></u> can be expressed as:</p></li>
</ul>
<p><span class="math display">\[
y_{ij} \sim N\!\big(\beta_0 + \beta_1 x_{ij}, \ \tau^2 + \sigma^2\big),
\]</span></p>
<p>where the extra variance <span class="math inline">\(\tau^2\)</span> is part of the <strong>covariance structure</strong>. We refer to the marginal distribution because in the frequentist approach the random effects are integrated out, and the variability they induce enters the covariance structure.</p>
<ul>
<li>In our 3-level LMM, these random effects are treated as components that induce correlation but are not explicitly estimated as parameters.</li>
</ul>
<hr>
</section>
<section id="pooling-borrowing-information-at-multiple-levels" class="level3">
<h3 class="anchored" data-anchor-id="pooling-borrowing-information-at-multiple-levels">Pooling (Borrowing Information) at Multiple Levels</h3>
<p>Our three-level linear mixed model: <span class="math display">\[
math_{ijk} = \beta_0 + \beta_1 year_{ijk} + \cdots + u_i + u_{ij} + \epsilon_{ijk},
\]</span> borrows strength across both <strong>schools</strong> (Level 3) and <strong>students</strong> (Level 2). This is known as <strong>multi-level partial pooling</strong>.</p>
<section id="pooling-across-schools" class="level4">
<h4 class="anchored" data-anchor-id="pooling-across-schools">1. Pooling Across Schools</h4>
<ul>
<li><p><strong>No pooling (separate means):</strong> Each school mean is just its sample mean: <span class="math display">\[
\hat{\mu}_i^{\text{no-pool}} = \bar{y}_i.
\]</span></p></li>
<li><p><strong>Complete pooling (one mean):</strong> All schools share the overall mean: <span class="math display">\[
\hat{\mu}_i^{\text{complete-pool}} = \bar{y}.
\]</span></p></li>
<li><p><strong>Partial pooling (hierarchical):</strong> <span class="math display">\[
\hat{\mu}_i^{\text{partial-pool}} = w_i \, \bar{y}_i + (1 - w_i)\, \bar{y},
\]</span> where <span class="math display">\[
w_i = \frac{n_i}{n_i + \frac{\sigma^2}{\nu^2}},
\]</span> with <span class="math inline">\(n_i\)</span> = number of observations in school <span class="math inline">\(i\)</span>, <span class="math inline">\(\nu^2\)</span> = between-school variance, and <span class="math inline">\(\sigma^2\)</span> = residual variance.</p>
<ul>
<li>Large schools (big <span class="math inline">\(n_i\)</span>) get <span class="math inline">\(w_i \approx 1\)</span> (close to <strong>no pooling</strong>).</li>
<li>Small schools (small <span class="math inline">\(n_i\)</span>) get <span class="math inline">\(w_i \approx 0\)</span> (closer to <strong>complete pooling</strong>).</li>
</ul></li>
</ul>
</section>
<section id="pooling-across-students-within-schools" class="level4">
<h4 class="anchored" data-anchor-id="pooling-across-students-within-schools">2. Pooling Across Students (Within Schools)</h4>
<p>Within each school <span class="math inline">\(i\)</span>, we also pool across students <span class="math inline">\(j\)</span>: <span class="math display">\[
  \hat{u}_{ij}^{\text{partial}} = w_{ij} \, (\bar{y}_{ij} - \bar{y}_i),
  \]</span> where <span class="math display">\[
  w_{ij} = \frac{n_{ij}}{n_{ij} + \frac{\sigma^2}{\tau^2}},
  \]</span> with <span class="math inline">\(n_{ij}\)</span> = number of observations for student <span class="math inline">\(j\)</span>, and <span class="math inline">\(\tau^2\)</span> = student-level variance.</p>
<div class="callout callout-style-simple callout-tip no-icon callout-titled" style="color:black">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Derivation of student-level partially pooled estimate
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="step-1-define-the-student-mean" class="level4">
<h4 class="anchored" data-anchor-id="step-1-define-the-student-mean">Step 1: Define the Student Mean</h4>
<p>For student <span class="math inline">\(j\)</span> in school <span class="math inline">\(i\)</span>, the average math score is: <span class="math display">\[
\bar{y}_{ij} = \frac{1}{n_{ij}} \sum_{k=1}^{n_{ij}} math_{ijk}.
\]</span></p>
<p>Substituting the model: <span class="math display">\[
\bar{y}_{ij} = \beta_0 + u_i + u_{ij} + \frac{1}{n_{ij}} \sum_{k=1}^{n_{ij}} \epsilon_{ijk}.
\]</span></p>
<p>Define the <strong>average residual error</strong>: <span class="math display">\[
\bar{\epsilon}_{ij} = \frac{1}{n_{ij}} \sum_{k=1}^{n_{ij}} \epsilon_{ijk},
\]</span> which satisfies <span class="math inline">\(\bar{\epsilon}_{ij} \sim N(0, \sigma^2 / n_{ij})\)</span>.</p>
<hr>
</section>
<section id="step-2-center-by-the-school-mean" class="level4">
<h4 class="anchored" data-anchor-id="step-2-center-by-the-school-mean">Step 2: Center by the School Mean</h4>
<p>Subtract the school mean <span class="math inline">\(\bar{y}_i\)</span> (which contains <span class="math inline">\(\beta_0 + u_i\)</span>): <span class="math display">\[
\bar{y}_{ij} - \bar{y}_i = u_{ij} + \bar{\epsilon}_{ij}.
\]</span></p>
<p>This shows that a student’s deviation from the school mean is driven by: - The student’s random effect <span class="math inline">\(u_{ij}\)</span>, - The average residual noise <span class="math inline">\(\bar{\epsilon}_{ij}\)</span>.</p>
<hr>
</section>
<section id="step-3-target-quantity" class="level4">
<h4 class="anchored" data-anchor-id="step-3-target-quantity">Step 3: Target Quantity</h4>
<p>We want the posterior mean of <span class="math inline">\(u_{ij}\)</span> given the observed deviation: <span class="math display">\[
\hat{u}_{ij}^{\text{partial}} = E[ u_{ij} \mid \bar{y}_{ij} - \bar{y}_i ].
\]</span></p>
<p>The prior and likelihood are: <span class="math display">\[
u_{ij} \sim N(0, \tau^2),
\]</span> <span class="math display">\[
\bar{y}_{ij} - \bar{y}_i \mid u_{ij} \sim N(u_{ij}, \sigma^2 / n_{ij}).
\]</span></p>
<hr>
</section>
<section id="step-4-conditional-expectation" class="level4">
<h4 class="anchored" data-anchor-id="step-4-conditional-expectation">Step 4: Conditional Expectation</h4>
<p>For a bivariate normal vector <span class="math inline">\((U, Y)\)</span>: <span class="math display">\[
E[U \mid Y] = \frac{\text{Cov}(U, Y)}{\text{Var}(Y)} \,(Y - E[Y]) + E[U].
\]</span></p>
<p>Here, <span class="math inline">\(U = u_{ij}\)</span>, <span class="math inline">\(Y = \bar{y}_{ij} - \bar{y}_i\)</span>, and <span class="math inline">\(E[U] = 0\)</span>: <span class="math display">\[
\text{Var}(Y) = \text{Var}(u_{ij} + \bar{\epsilon}_{ij}) = \tau^2 + \frac{\sigma^2}{n_{ij}},
\]</span> <span class="math display">\[
\text{Cov}(u_{ij}, Y) = \text{Cov}(u_{ij}, u_{ij} + \bar{\epsilon}_{ij}) = \tau^2.
\]</span></p>
<p>Thus: <span class="math display">\[
E[u_{ij} \mid \bar{y}_{ij} - \bar{y}_i] =
\frac{\tau^2}{\tau^2 + \sigma^2 / n_{ij}} (\bar{y}_{ij} - \bar{y}_i).
\]</span></p>
<hr>
</section>
<section id="step-5-shrinkage-weight" class="level4">
<h4 class="anchored" data-anchor-id="step-5-shrinkage-weight">Step 5: Shrinkage Weight</h4>
<p>Define: <span class="math display">\[
w_{ij} = \frac{\tau^2}{\tau^2 + \sigma^2 / n_{ij}} = \frac{n_{ij}}{n_{ij} + \frac{\sigma^2}{\tau^2}},
\]</span> so the <strong>partially pooled student intercept</strong> is: <span class="math display">\[
\hat{u}_{ij}^{\text{partial}} = w_{ij} (\bar{y}_{ij} - \bar{y}_i).
\]</span></p>
</section>
</div>
</div>
</div>
<ul>
<li><p><strong>Students with more data</strong> (<span class="math inline">\(n_{ij}\)</span> large) → <span class="math inline">\(w_{ij} \approx 1\)</span>, so their random intercept is close to their own average.</p></li>
<li><p><strong>Students with sparse data</strong> (<span class="math inline">\(n_{ij}\)</span> small) → <span class="math inline">\(w_{ij} \approx 0\)</span>, so their intercept is shrunk toward the <strong>school-level mean</strong>.</p></li>
<li><p>The <strong>random intercepts</strong> <span class="math inline">\(u_i\)</span> and <span class="math inline">\(u_{ij}\)</span> ensure that the model combines information from all schools and students.<br>
</p></li>
<li><p>Small or noisy groups borrow strength from the larger dataset, which improves stability and reduces overfitting.</p></li>
</ul>
<p>We can visualize this with a <strong>shrinkage plot</strong> showing raw school means vs.&nbsp;partially pooled estimates, as well as student-level intercepts:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Module_2D_GLMMs_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="covariance-structures-in-hierarchical-glmms" class="level3">
<h3 class="anchored" data-anchor-id="covariance-structures-in-hierarchical-glmms">Covariance Structures in Hierarchical GLMMs</h3>
<p>For the <strong>three-level linear mixed model</strong>:</p>
<p><span class="math display">\[
\begin{aligned}
math_{ijk} &amp;\sim \text{Normal}(\mu_{ijk}, \sigma^2), \\
\mu_{ijk} &amp;= \beta_0 + u_i + u_{ij} + \beta_1' x_{ijk} + \beta_2' x_{ij} + \beta_3' x_i, \\
u_i &amp;\sim N(0, \nu^2), \quad u_{ij} \sim N(0, \tau^2),
\end{aligned}
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(u_i\)</span> is the <strong>school-level random intercept</strong>,</li>
<li><span class="math inline">\(u_{ij}\)</span> is the <strong>student-level random intercept</strong> (nested within school <span class="math inline">\(i\)</span>),</li>
<li><span class="math inline">\(\sigma^2\)</span> is the residual (Level 1) variance for observations within a student.</li>
</ul>
<hr>
<section id="conditional-variance" class="level5">
<h5 class="anchored" data-anchor-id="conditional-variance">Conditional Variance</h5>
<p>Conditioned on the random effects <span class="math inline">\(u_i\)</span> and <span class="math inline">\(u_{ij}\)</span>, the distribution of <span class="math inline">\(math_{ijk}\)</span> is:</p>
<p><span class="math display">\[
math_{ijk}|u_i, u_{ij} \sim N(\mu_{ijk}, \sigma^2)
\]</span></p>
<p>where <span class="math inline">\(\mu_{ijk}\)</span> is the linear predictor: <span class="math display">\[
E(math_{ijk}|u_i, u_{ij}) = \mu_{ijk} = \beta_0 + \beta^{(1)'} x_{ijk} + \beta^{(2)'} x_{ij} + u_i + u_{ij},
\]</span> and <span class="math display">\[
Var(math_{ijk} \mid u_i, u_{ij}) = \sigma^2,
\]</span></p>
<div class="callout callout-style-simple callout-tip no-icon callout-titled" style="color:black">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Derivation of conditional variance
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Conditioned on the random effects <span class="math inline">\(u_i\)</span> and <span class="math inline">\(u_{ij}\)</span>, we can write: <span class="math display">\[
math_{ijk} \mid u_i, u_{ij} = \mu_{ijk} + \epsilon_{ijk}.
\]</span></p>
<p>Since <span class="math inline">\(\mu_{ijk}\)</span> is treated as fixed once we condition on <span class="math inline">\(u_i\)</span> and <span class="math inline">\(u_{ij}\)</span>, the only remaining random component is <span class="math inline">\(\epsilon_{ijk}\)</span>. Therefore: <span class="math display">\[
\begin{aligned}
Var(math_{ijk} \mid u_i, u_{ij})
&amp;= Var(\mu_{ijk} + \epsilon_{ijk} \mid u_i, u_{ij}) \\
&amp;= Var(\epsilon_{ijk}) \\
&amp;= \sigma^2.
\end{aligned}
\]</span></p>
</div>
</div>
</div>
<hr>
</section>
<section id="total-variance" class="level5">
<h5 class="anchored">Total Variance</h5>
<p>This variance <span class="math inline">\(\sigma^2\)</span> describes the <strong>Level 1 variability (within-student, across years)</strong>, assuming the random effects <span class="math inline">\(u_i\)</span> and <span class="math inline">\(u_{ij}\)</span> are fixed.</p>
<p>The <strong>total variability</strong> in <span class="math inline">\(math_{ijk}\)</span> can be decomposed into:</p>
<p><span class="math display">\[
Var(math_{ijk}) = \nu^2 + \tau^2 + \sigma^2,
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\nu^2\)</span> reflects <strong>between-school variability</strong>,</li>
<li><span class="math inline">\(\tau^2\)</span> reflects <strong>between-student variability (within school)</strong>,</li>
<li><span class="math inline">\(\sigma^2\)</span> reflects <strong>within-student residual variability</strong>.</li>
</ul>
<div class="callout callout-style-simple callout-tip no-icon callout-titled" style="color:black">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Derivation of Total Variance
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>For the three-level linear mixed model: <span class="math display">\[
math_{ijk} = \beta_0 + \beta_1 \, year_{ijk} + \cdots + u_i + u_{ij} + \epsilon_{ijk},
\]</span> we assume: <span class="math display">\[
u_i \sim N(0, \nu^2), \quad u_{ij} \sim N(0, \tau^2), \quad \epsilon_{ijk} \sim N(0, \sigma^2),
\]</span> with all random components <strong>mutually independent</strong>.</p>
<p>We want to show that: <span class="math display">\[
Var(math_{ijk}) = \nu^2 + \tau^2 + \sigma^2.
\]</span></p>
<hr>
<section id="step-1-apply-the-law-of-total-variance" class="level4">
<h4 class="anchored" data-anchor-id="step-1-apply-the-law-of-total-variance">Step 1: Apply the Law of Total Variance</h4>
<p>The law of total variance states: <span class="math display">\[
Var(Y) = E[Var(Y \mid U)] + Var(E[Y \mid U]),
\]</span> where <span class="math inline">\(U\)</span> represents any random variables we are conditioning on.</p>
<p>In our case, we condition on both <span class="math inline">\(u_i\)</span> and <span class="math inline">\(u_{ij}\)</span>: <span class="math display">\[
Var(math_{ijk}) = E[Var(math_{ijk} \mid u_i, u_{ij})] + Var(E[math_{ijk} \mid u_i, u_{ij}]).
\]</span></p>
<hr>
</section>
<section id="step-2-compute-the-conditional-variance" class="level4">
<h4 class="anchored" data-anchor-id="step-2-compute-the-conditional-variance">Step 2: Compute the Conditional Variance</h4>
<p>From the model: <span class="math display">\[
math_{ijk} \mid u_i, u_{ij} = \mu_{ijk} + \epsilon_{ijk},
\]</span> where <span class="math inline">\(\mu_{ijk} = \beta_0 + \beta_1 \, year_{ijk} + \cdots + u_i + u_{ij}\)</span>.</p>
<p>Conditioned on <span class="math inline">\(u_i\)</span> and <span class="math inline">\(u_{ij}\)</span>, the only random term is <span class="math inline">\(\epsilon_{ijk}\)</span>, so: <span class="math display">\[
Var(math_{ijk} \mid u_i, u_{ij}) = Var(\epsilon_{ijk}) = \sigma^2.
\]</span> Therefore: <span class="math display">\[
E[Var(math_{ijk} \mid u_i, u_{ij})] = \sigma^2.
\]</span></p>
<hr>
</section>
<section id="step-3-compute-the-variance-of-the-conditional-expectation" class="level4">
<h4 class="anchored" data-anchor-id="step-3-compute-the-variance-of-the-conditional-expectation">Step 3: Compute the Variance of the Conditional Expectation</h4>
<p>The conditional expectation is: <span class="math display">\[
E[math_{ijk} \mid u_i, u_{ij}] = \mu_{ijk} = \beta_0 + \beta_1 \, year_{ijk} + \cdots + u_i + u_{ij}.
\]</span></p>
<p>The fixed terms <span class="math inline">\(\beta_0 + \beta_1 \, year_{ijk} + \cdots\)</span> have no variance, so: <span class="math display">\[
Var(E[math_{ijk} \mid u_i, u_{ij}]) = Var(u_i + u_{ij}) = Var(u_i) + Var(u_{ij}),
\]</span> because <span class="math inline">\(u_i\)</span> and <span class="math inline">\(u_{ij}\)</span> are independent. Thus: <span class="math display">\[
Var(E[math_{ijk} \mid u_i, u_{ij}]) = \nu^2 + \tau^2.
\]</span></p>
<hr>
</section>
<section id="step-4-combine-results" class="level4">
<h4 class="anchored" data-anchor-id="step-4-combine-results">Step 4: Combine Results</h4>
<p>Putting it all together: <span class="math display">\[
Var(math_{ijk}) = E[Var(math_{ijk} \mid u_i, u_{ij})] + Var(E[math_{ijk} \mid u_i, u_{ij}])
= \sigma^2 + (\nu^2 + \tau^2)
= \nu^2 + \tau^2 + \sigma^2.
\]</span></p>
</section>
</div>
</div>
</div>
<hr>
<!--##### Marginal Variance

After integrating over the random effects, observations within the same **student** or **school** become correlated because they share the same random intercepts.

- **Within-student correlation (same student, same school):**  
  Multiple observations for the same student share both $u_{ij}$ (student-level effect) and $u_i$ (school-level effect).

- **Within-school correlation (different students in the same school):**  
  Observations from different students in the same school share the same $u_i$ but have different $u_{ij}$.

Formally, for two observations $math_{ijk}$ and $math_{ijk'}$ from the **same student** $j$ in the **same school** $i$, we have:
$$
Cov(math_{ijk}, math_{ijk'} \mid u_i, u_{ij}) = 0,
$$
because, given $u_i$ and $u_{ij}$, the residuals $\epsilon_{ijk}$ are independent.

However, the **marginal covariance** (after integrating over the random effects $u_i$ and $u_{ij}$) is **non-zero** because these observations share the same random intercepts, inducing correlation.




----->
</section>
<section id="conditional-vs.-marginal-covariance" class="level4">
<h4 class="anchored" data-anchor-id="conditional-vs.-marginal-covariance">Conditional vs.&nbsp;Marginal Covariance</h4>
<p>For two observations <span class="math inline">\(math_{ijk}\)</span> and <span class="math inline">\(math_{ijk'}\)</span> from the <strong>same student</strong> <span class="math inline">\(j\)</span> in the <strong>same school</strong> <span class="math inline">\(i\)</span>: <span class="math display">\[
Cov(math_{ijk}, math_{ijk'} \mid u_i, u_{ij}) = 0,
\]</span> because, conditioned on <span class="math inline">\(u_i\)</span> and <span class="math inline">\(u_{ij}\)</span>, the residual errors <span class="math inline">\(\epsilon_{ijk}\)</span> are independent.</p>
<p>However, the <strong>marginal covariance</strong> (after integrating over the random effects) is: <span class="math display">\[
Cov(math_{ijk}, math_{ijk'}) = \nu^2 + \tau^2,
\]</span> since both observations share <span class="math inline">\(u_i\)</span> (school effect) and <span class="math inline">\(u_{ij}\)</span> (student effect).</p>
<p>For two students <span class="math inline">\(j \neq j'\)</span> in the <strong>same school</strong> <span class="math inline">\(i\)</span>: <span class="math display">\[
Cov(math_{ijk}, math_{ij'k'}) = \nu^2,
\]</span> because they share only the school effect <span class="math inline">\(u_i\)</span>.</p>
<hr>
</section>
</section>
<section id="intraclass-correlation-coefficients-icc" class="level3">
<h3 class="anchored" data-anchor-id="intraclass-correlation-coefficients-icc">Intraclass Correlation Coefficients (ICC)</h3>
<p>The total variance of <span class="math inline">\(math_{ijk}\)</span> is: <span class="math display">\[
Var(math_{ijk}) = \nu^2 + \tau^2 + \sigma^2.
\]</span></p>
<p>The <strong>school-level intraclass correlation (ICC)</strong>, which measures the proportion of variance explained by differences between schools, is: <span class="math display">\[
ICC_{\text{school}} = \frac{\nu^2}{\nu^2 + \tau^2 + \sigma^2}.
\]</span></p>
<p>The <strong>student-level ICC (within a school)</strong> is: <span class="math display">\[
ICC_{\text{student}} = \frac{\nu^2 + \tau^2}{\nu^2 + \tau^2 + \sigma^2}.
\]</span></p>
<p>These ICCs quantify how strongly scores are correlated for students within the same school or the same student across multiple years.</p>
<hr>
</section>
<section id="hierarchical-glmm-fitting-in-r" class="level3">
<h3 class="anchored" data-anchor-id="hierarchical-glmm-fitting-in-r">Hierarchical GLMM Fitting in R</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required package</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the 3-level LMM</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># math ~ fixed effects + (1 | school/child) fits random intercepts for school and child</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>lmm_3level <span class="ot">&lt;-</span> <span class="fu">lmer</span>(</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  math <span class="sc">~</span> year <span class="sc">+</span> female <span class="sc">+</span> black <span class="sc">+</span> hispanic <span class="sc">+</span> retained <span class="sc">+</span> </span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">|</span> school<span class="sc">/</span>child),  <span class="co"># child is nested within school</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Display model summary</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmm_3level)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: 
math ~ year + female + black + hispanic + retained + (1 | school/child)
   Data: dat

REML criterion at convergence: 16699.2

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.8443 -0.5854 -0.0272  0.5588  6.1663 

Random effects:
 Groups       Name        Variance Std.Dev.
 child:school (Intercept) 0.6638   0.8148  
 school       (Intercept) 0.1292   0.3594  
 Residual                 0.3445   0.5870  
Number of obs: 7230, groups:  child:school, 1721; school, 60

Fixed effects:
              Estimate Std. Error t value
(Intercept) -3.477e-01  8.095e-02  -4.295
year         7.483e-01  5.396e-03 138.677
female       8.850e-06  4.226e-02   0.000
black       -6.235e-01  7.873e-02  -7.919
hispanic    -3.636e-01  8.813e-02  -4.125
retained     1.487e-01  3.536e-02   4.207

Correlation of Fixed Effects:
         (Intr) year   female black  hispnc
year     -0.020                            
female   -0.264 -0.005                     
black    -0.691 -0.004 -0.003              
hispanic -0.515 -0.009  0.019  0.519       
retained -0.020  0.086  0.017 -0.015 -0.007</code></pre>
</div>
</div>
<!--<span style='color: red;'>What warning is this??</span>

Convergence issues can happen for several reasons:

-   **Model complexity**: The model may be too complex, with too many random effects or predictors that cause instability in the estimation process.

-   **Insufficient data**: You might not have enough data to estimate all parameters properly, especially for random effects.

-   **Scaling issues**: Poor scaling of variables can make the optimization problem numerically unstable.

-   **Starting values**: Sometimes, the optimizer doesn't start close enough to a good solution.

-   Use the `control` argument in **`glmer`** to allow more iterations or to relax convergence criteria.

````{=html}
<!--```{r}
fit_opt <- glmer(immun ~ kid2p + momEdPri + momEdSec + husEdPri + husEdSec + rural + pcInd81 + (1|mom) + (1|cluster), family = binomial, data = dat, control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e5)))

summary(fit_opt)
```-->
</section>
<section id="model-interpretations" class="level3">
<h3 class="anchored" data-anchor-id="model-interpretations">Model Interpretations</h3>
<section id="random-effects" class="level4">
<h4 class="anchored" data-anchor-id="random-effects">Random Effects</h4>
<ul>
<li><p><strong>School-level variance (</strong><span class="math inline">\(\nu^2 = 0.1292\)</span>):<br>
Differences between schools account for some variation in math scores (Std. Dev. = 0.359).<br>
This suggests that students from different schools start at different baseline math levels.</p></li>
<li><p><strong>Student-level variance (</strong><span class="math inline">\(\tau^2 = 0.6638\)</span>):<br>
Differences between students (within schools) account for a larger portion of variability (Std. Dev. = 0.815), indicating substantial heterogeneity across students.</p></li>
<li><p><strong>Residual variance (</strong><span class="math inline">\(\sigma^2 = 0.3445\)</span>):<br>
Variation in math scores within the same student (across years) after accounting for predictors is 0.3445 (Std. Dev. = 0.587).</p></li>
<li><p><strong>Number of groups:</strong><br>
There are 60 schools and 1,721 students across 7,230 total observations.</p></li>
</ul>
</section>
<section id="fixed-effects" class="level4">
<h4 class="anchored" data-anchor-id="fixed-effects">Fixed Effects</h4>
<ul>
<li><p><strong>Intercept (-0.348):</strong><br>
The expected math score for a reference student (male, non-Black, non-Hispanic, not retained) in year 0 is -0.35 (on the standardized scale).</p></li>
<li><p><strong>Year (0.748):</strong><br>
On average, math scores increase by 0.748 units per year, <strong>holding all other factors constant</strong>.<br>
This is a <strong>strong positive trend</strong> over time (t = 138.7).</p></li>
<li><p><strong>Female (0.00001):</strong><br>
The coefficient for being female is nearly zero (and not statistically significant).</p></li>
<li><p><strong>Black (-0.623):</strong><br>
Black students have an average math score 0.62 units lower than non-Black students, holding other variables constant (t = -7.92).</p></li>
<li><p><strong>Hispanic (-0.364):</strong><br>
Hispanic students have an average math score 0.36 units lower than non-Hispanic students (t = -4.13).</p></li>
<li><p><strong>Retained (0.149):</strong><br>
Students who were retained (repeated a grade) have math scores approximately 0.15 units higher than otherwise similar students (t = 4.21). This may reflect additional time or intervention effects.</p></li>
</ul>
<p>We can calculate ICCs directly from the variance components of the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract variance components</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>vc <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">VarCorr</span>(lmm_3level))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Variance components</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>var_school  <span class="ot">&lt;-</span> vc[vc<span class="sc">$</span>grp <span class="sc">==</span> <span class="st">"school"</span>, <span class="st">"vcov"</span>]         <span class="co"># ν² (between schools)</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>var_child   <span class="ot">&lt;-</span> vc[vc<span class="sc">$</span>grp <span class="sc">==</span> <span class="st">"child:school"</span>, <span class="st">"vcov"</span>]   <span class="co"># τ² (between students within schools)</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>var_resid  <span class="ot">&lt;-</span> vc[vc<span class="sc">$</span>grp <span class="sc">==</span> <span class="st">"Residual"</span>, <span class="st">"vcov"</span>]      <span class="co"># σ² (within students)</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Total variance</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>var_total <span class="ot">&lt;-</span> var_school <span class="sc">+</span> var_child <span class="sc">+</span> var_resid</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co"># ICCs</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>ICC_school  <span class="ot">&lt;-</span> var_school <span class="sc">/</span> var_total</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>ICC_student <span class="ot">&lt;-</span> (var_school <span class="sc">+</span> var_child) <span class="sc">/</span> var_total</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>ICC_school</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.113578</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>ICC_student</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6971433</code></pre>
</div>
</div>
<hr>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary"><span style="color: purple;">Summary</span></h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Section</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>What is the model?</strong></td>
<td>A <strong>three-level hierarchical linear model</strong> extends linear regression to account for <strong>nested data structures</strong>—specifically, <strong>years within students</strong>, and <strong>students within schools</strong>. <br> The model includes two random intercepts: <br> <span class="math inline">\(y_{ijk} = X_{ijk}\beta + u_i + u_{ij} + \epsilon_{ijk}\)</span>, where <span class="math inline">\(u_i \sim N(0, \nu^2)\)</span> and <span class="math inline">\(u_{ij} \sim N(0, \tau^2)\)</span>.</td>
</tr>
<tr class="even">
<td><strong>Motivation</strong></td>
<td>Hierarchical or <strong>multilevel data</strong> violate the independence assumption of standard linear models. Ignoring the nesting—repeated years per student, students within schools—leads to <strong>underestimated standard errors</strong> and <strong>biased inference</strong>. Hierarchical models account for this by modeling <strong>correlated errors at each level</strong>.</td>
</tr>
<tr class="odd">
<td><strong>Model Components</strong></td>
<td><strong>Level 1:</strong> residual error <span class="math inline">\(\epsilon_{ijk} \sim N(0, \sigma^2)\)</span> <br> <strong>Level 2:</strong> student-level random intercept <span class="math inline">\(u_{ij} \sim N(0, \tau^2)\)</span> <br> <strong>Level 3:</strong> school-level random intercept <span class="math inline">\(u_i \sim N(0, \nu^2)\)</span> <br> The systematic component is: <span class="math inline">\(\mu_{ijk} = \beta_0 + X_{ijk} \beta + u_i + u_{ij}\)</span></td>
</tr>
<tr class="even">
<td><strong>Hierarchical Partial Pooling</strong></td>
<td>The model performs <strong>partial pooling</strong> across both schools and students. <br> - <strong>School-level:</strong> <span class="math inline">\(\hat{\mu}_i^{\text{partial}} = w_i \bar{y}_i + (1 - w_i)\bar{y}\)</span> with <span class="math inline">\(w_i = \frac{n_i}{n_i + \frac{\sigma^2}{\nu^2}}\)</span> <br> - <strong>Student-level:</strong> <span class="math inline">\(\hat{u}_{ij}^{\text{partial}} = w_{ij} (\bar{y}_{ij} - \bar{y}_i)\)</span> with <span class="math inline">\(w_{ij} = \frac{n_{ij}}{n_{ij} + \frac{\sigma^2}{\tau^2}}\)</span></td>
</tr>
<tr class="odd">
<td><strong>Likelihood</strong></td>
<td>The likelihood reflects <strong>two nested levels of integration over random effects</strong>: <br> <span class="math inline">\(L(\beta, \nu^2, \tau^2 \mid y) = \prod_i \int \prod_j \int \prod_k p(y_{ijk} \mid u_i, u_{ij}) \, p(u_{ij}) \, du_{ij} \, p(u_i) \, du_i\)</span> <br> Estimated using <strong>REML</strong> (frequentist) or <strong>MCMC</strong> (Bayesian) methods.</td>
</tr>
<tr class="even">
<td><strong>Interpretation</strong></td>
<td>- <strong>Fixed effects (</strong><span class="math inline">\(\beta\)</span>): average effects across all observations (e.g., year, race, gender) <br> - <strong>Random effects (</strong><span class="math inline">\(u_i\)</span>, <span class="math inline">\(u_{ij}\)</span>): group-specific deviations <br> - <strong>Variance components:</strong> <span class="math inline">\(\nu^2\)</span> (school), <span class="math inline">\(\tau^2\)</span> (student), <span class="math inline">\(\sigma^2\)</span> (within-student error)</td>
</tr>
<tr class="odd">
<td><strong>Model Diagnostics</strong></td>
<td>- <strong>ICC (school):</strong> <span class="math inline">\(ICC_{\text{school}} = \frac{\nu^2}{\nu^2 + \tau^2 + \sigma^2}\)</span> <br> - <strong>ICC (student):</strong> <span class="math inline">\(ICC_{\text{student}} = \frac{\nu^2 + \tau^2}{\nu^2 + \tau^2 + \sigma^2}\)</span> <br> ICCs quantify clustering at each level.</td>
</tr>
<tr class="even">
<td><strong>Example (School Math Scores)</strong></td>
<td>Fitted model: <br> <span class="math inline">\(math_{ijk} = \beta_0 + \beta_1 \cdot year_{ijk} + \cdots + u_i + u_{ij} + \epsilon_{ijk}\)</span> <br> - <strong>Between-school SD:</strong> 0.359 <br> - <strong>Between-student SD:</strong> 0.815 <br> - <strong>Residual SD:</strong> 0.587 <br> These values reflect variability at each level of the hierarchy.</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Module_2C_GLMMs.html" class="pagination-link" aria-label="Module 2C Generalized Linear Mixed Models">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Module 2C Generalized Linear Mixed Models</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Module_2_GLM_Cheat.html" class="pagination-link" aria-label="Module 2 Cheat Sheet">
        <span class="nav-page-text">Module 2 Cheat Sheet</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>