<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Module 5A Generalized Additive Models – BIOS 526 Modern Regression Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Module_5B_GAMs.html" rel="next">
<link href="./Module_4_Splines_Cheat.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Module_5A_GAMs.html">Module 5A Generalized Additive Models</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">BIOS 526 Modern Regression Analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_0_MLR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 0: Multiple Linear Regression Review</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1A_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1A Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1B_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1B Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1C_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1C Random Intercepts and Slopes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1_LMM_Cheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2A_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2A Generalized Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2B_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2B Generalized Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2C_GLMMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2C Generalized Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2D_GLMMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2D Generalized Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2_GLM_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3A_GEEs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3A Marginal Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3B_GEEs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3B Marginal Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3_GEE_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4A_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4A Basis Expansion and Parametric Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4B_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4B Parametric Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4C_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4C Penalized Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4_Splines_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5A_GAMs.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Module 5A Generalized Additive Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5B_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5B Generalized Additive Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5_GAM_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_6_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 6 Model Selection, Diagnostics, &amp; Regression Workflow</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#motivation-and-examples" id="toc-motivation-and-examples" class="nav-link active" data-scroll-target="#motivation-and-examples">Motivation and Examples</a></li>
  <li><a href="#checking-gams" id="toc-checking-gams" class="nav-link" data-scroll-target="#checking-gams">Checking GAMs</a></li>
  <li><a href="#multiple-smoothers" id="toc-multiple-smoothers" class="nav-link" data-scroll-target="#multiple-smoothers">Multiple Smoothers</a>
  <ul class="collapse">
  <li><a href="#motivating-example-air-pollution-and-mortality" id="toc-motivating-example-air-pollution-and-mortality" class="nav-link" data-scroll-target="#motivating-example-air-pollution-and-mortality">Motivating Example: Air Pollution and Mortality</a></li>
  </ul></li>
  <li><a href="#time-series-health-model" id="toc-time-series-health-model" class="nav-link" data-scroll-target="#time-series-health-model">Time-Series Health Model</a>
  <ul class="collapse">
  <li><a href="#model-diagnostics" id="toc-model-diagnostics" class="nav-link" data-scroll-target="#model-diagnostics">Model Diagnostics</a></li>
  </ul></li>
  <li><a href="#uncertainty-bands-for-gam-smooths" id="toc-uncertainty-bands-for-gam-smooths" class="nav-link" data-scroll-target="#uncertainty-bands-for-gam-smooths">Uncertainty Bands for GAM Smooths</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span style="color: purple;">Summary</span></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Module 5A Generalized Additive Models</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><img src="fig/gams.gif" class="img-fluid"></p>
<p><strong>Reading</strong></p>
<ul>
<li><p>From Wood, S. Generalized Additive Models: An Introduction with R, 2nd Edition.</p></li>
<li><p>A nice resource for fitting GAMS: <a href="https://wiki.qcbs.ca/r_workshop8" class="uri">https://wiki.qcbs.ca/r_workshop8</a></p></li>
<li><p>Another fun resource for seeing GAMs: <a href="https://ecogambler.netlify.app/blog/interpreting-gams/" class="uri">https://ecogambler.netlify.app/blog/interpreting-gams/</a></p></li>
</ul>
<p><strong>Basic Concepts</strong></p>
<ul>
<li>Generalized Additive Models for non-normal data.</li>
<li>Additive models with multiple covariates.</li>
<li>Using <span class="math inline">\(gam()\)</span> in package <span class="math inline">\(mgcv()\)</span> to fit semiparametric models with parametric slopes and nonparametric terms.</li>
<li>Bivariate splines</li>
<li>Interpreting non-linear effects</li>
</ul>
<section id="motivation-and-examples" class="level3">
<h3 class="anchored" data-anchor-id="motivation-and-examples">Motivation and Examples</h3>
<div class="illustration callout callout-style-default callout-important callout-titled" style="color: red">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Motivation
</div>
</div>
<div class="callout-body-container callout-body">
<p>In Module 4 we learned about basis expansions and parametric splines. These introduce smooth functions to capture non-linear relationships between outcome and covariates. We saw examples where:</p>
<ul>
<li><p>The outcome is Gaussian.</p></li>
<li><p>There is one non-linear covariate</p></li>
</ul>
<p><u>How can we extend this to <strong>multivariable and non-normal</strong> settings while keeping models interpretable and smoothness <strong>data-driven</strong>?</u></p>
<p>Answer: <strong>Generalized Additive Model</strong>: A GAM models the mean via a link: <span class="math display">\[
g\!\big(\mathbb{E}[Y]\big) = \beta_0 + \sum_{j=1}^p s_j(X_j),
\]</span> where <span class="math inline">\(g(\cdot)\)</span> is the link, <span class="math inline">\(s_j(\cdot)\)</span> are smooth functions (e.g., splines), and <span class="math inline">\(p\)</span> is the number of predictors.</p>
<p>where:</p>
<ul>
<li><p><span class="math inline">\(Y\)</span> is the response variable,</p></li>
<li><p><span class="math inline">\(g()\)</span> is the link function that relates the expected value of <span class="math inline">\(Y\)</span> <span class="math inline">\((E(Y)\)</span> to the linear predictor.</p></li>
<li><p><span class="math inline">\(\beta_0\)</span> is the intercept term.</p></li>
<li><p><span class="math inline">\(s_j(X_j)\)</span> are smooth functions, such as splines, applied to the predictor variable <span class="math inline">\(X_j\)</span>.</p></li>
<li><p><span class="math inline">\(p\)</span> is the number of predictor variables.</p></li>
<li><p>Each smooth function <span class="math inline">\(s_j(\cdot)\)</span> allows for greater flexibile, non-linear relationships between <span class="math inline">\(Y\)</span> and <span class="math inline">\(X_j\)</span>.</p></li>
</ul>
<p><strong>Why GAMs?</strong></p>
<ul>
<li><strong>Flexible:</strong> captures separate nonlinear effects <span class="math inline">\(s_j(X_j)\)</span> for each predictor.</li>
<li><strong>Interpretable:</strong> additive structure → clear partial effects and plots.</li>
<li><strong>Automatic smoothing:</strong> each <span class="math inline">\(\lambda\)</span> is learned from the data (e.g., REML/GCV).</li>
<li><strong>Extensible:</strong> include factors, linear terms, and <strong>interactions</strong> via tensor-product smooths (e.g., <span class="math inline">\(s_{12}(x_1,x_2)\)</span>).</li>
</ul>
</div>
</div>
<p><strong>Motivating Example: Low Birthweight in GA</strong> Recall from example in Module 3.</p>
<p>Dataset: a cohort of live births from GA born in the year 2001 (N=77,340)</p>
<p>Variables:</p>
<ul>
<li><p><span class="math inline">\(ptb\)</span>: indicator for preterm birth for whether baby from pregnancy <span class="math inline">\(i\)</span> was born &lt;37 weeks.</p></li>
<li><p><span class="math inline">\(age\)</span>: mothers age at delivery</p></li>
<li><p><span class="math inline">\(male\)</span>: indicator of baby’s sex (1=male, 0=female)</p></li>
<li><p><span class="math inline">\(tobacco\)</span>: indicator for mother tobacco use during pregnancy test (1=yes, 0=no)</p></li>
</ul>
<p>In previous analysis, we fit this using a logistic regression model, which assumed a Bernoulli data model with a logit-link. We regressed the outcome (probability of low-birth weight) on age, sex, and tobacco status.</p>
<p>But we may want to account for non-linear age effect:</p>
<p><span class="math display">\[
\begin{aligned}
\text{ptb}_i &amp;\sim \text{Bernoulli}(p_i),\\
\text{logit}(p_i) &amp;= \beta_0 + \beta_1\,\text{male}_i + \beta_2\,\text{tobacco}_i + s(\text{age}_i).
\end{aligned}
\]</span></p>
<p>where <span class="math inline">\(s(age_i)\)</span> is a <span style="color: red;">smooth</span> function of age.</p>
<div class="callout callout-style-simple callout-note no-icon" style="color: gray">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Note: By default, <code>mgcv::gam()</code> uses cubic regression splines <code>(bs = "cr")</code> with k = 10 basis functions (including the intercept of the smooth).</p>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span> (mgcv)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Pre-term births with non-linear age effect</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">paste0</span>(<span class="fu">getwd</span>(), <span class="st">'/data/PTB.RData'</span>))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>fit.gam <span class="ot">=</span> <span class="fu">gam</span>(ptb<span class="sc">~</span> <span class="fu">s</span>(age) <span class="sc">+</span> male <span class="sc">+</span> tobacco ,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">family =</span> binomial, <span class="at">data =</span> dat)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.gam)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Family: binomial 
Link function: logit 

Formula:
ptb ~ s(age) + male + tobacco

Parametric coefficients:
            Estimate Std. Error  z value Pr(&gt;|z|)    
(Intercept) -2.44226    0.01913 -127.647  &lt; 2e-16 ***
maleM        0.07274    0.02588    2.811  0.00494 ** 
tobacco      0.39016    0.05356    7.284 3.24e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Approximate significance of smooth terms:
         edf Ref.df Chi.sq p-value    
s(age) 3.314  4.146  70.17  &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-sq.(adj) =  0.00177   Deviance explained = 0.304%
UBRE = -0.42095  Scale est. = 1         n = 77340</code></pre>
</div>
</div>
<p><strong>Model Interpretation:</strong></p>
<ul>
<li><p>The response variable <code>ptb</code> is modeled using a <strong>binomial family</strong> with a <strong>logit link function</strong>.</p></li>
<li><p>The formula includes:</p>
<ul>
<li>A smooth term for <code>age</code> (<code>s(age)</code>).</li>
<li>Linear terms for <code>male</code> and <code>tobacco</code>.</li>
</ul></li>
<li><p><strong>Intercept</strong>: The log-odds of <code>ptb</code> when all predictors are at their reference levels is estimated as <span class="math inline">\(-2.44\)</span> (highly significant, <span class="math inline">\(p &lt; 2 \times 10^{-16}\)</span>).</p></li>
<li><p><strong><code>maleM</code> (male effect)</strong>: Being male is associated with a small but significant increase in the log-odds of <code>ptb</code> (estimate = <span class="math inline">\(0.073\)</span>, <span class="math inline">\(p = 0.00494\)</span>). Tobacco use is associated with a significant increase in the log-odds of <code>ptb</code> (estimate = <span class="math inline">\(0.39\)</span>, <span class="math inline">\(p &lt; 3.24 \times 10^{-13}\)</span>).</p></li>
<li><p>Smooth Term for Age (<code>s(age)</code>) : The smooth function for <code>age</code> has an estimated <strong>effective degrees of freedom (edf)</strong> of <span class="math inline">\(3.31\)</span>, indicating a moderately flexible relationship. Is highly significant (<span class="math inline">\(p &lt; 2 \times 10^{-16}\)</span>), suggesting a non-linear relationship between age and the log-odds of <code>ptb</code>.</p></li>
<li><p><strong>Adjusted</strong> <span class="math inline">\(R^2\)</span>: The model explains only <span class="math inline">\(0.177\%\)</span> of the variability in the response, indicating weak predictive power.</p></li>
<li><p><strong>Deviance explained</strong>: The model accounts for <span class="math inline">\(0.304\%\)</span> of the total deviance, further supporting limited explanatory capability. -</p></li>
<li><p><strong>UBRE score</strong>: - A measure of model fit, with a value of <span class="math inline">\(-0.42095\)</span>. UBRE is similar to AIC for non-normal data: <u>Lower is better!</u></p></li>
<li><p><strong>Sample size</strong>: - The model was fit on <span class="math inline">\(77,340\)</span> observations.</p></li>
</ul>
<p>Conclusion: While the predictors (<code>age</code>, <code>male</code>, and <code>tobacco</code>) show significant associations with <code>ptb</code>, the overall model has limited explanatory power for predicting <code>ptb</code>.</p>
<hr>
</section>
<section id="checking-gams" class="level2">
<h2 class="anchored" data-anchor-id="checking-gams">Checking GAMs</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>mgcv<span class="sc">::</span><span class="fu">gam.check</span>(fit.gam)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Module_5A_GAMs_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Method: UBRE   Optimizer: outer newton
full convergence after 3 iterations.
Gradient range [9.816712e-07,9.816712e-07]
(score -0.4209495 &amp; scale 1).
Hessian positive definite, eigenvalue range [1.285937e-05,1.285937e-05].
Model rank =  12 / 12 

Basis dimension (k) checking results. Low p-value (k-index&lt;1) may
indicate that k is too low, especially if edf is close to k'.

         k'  edf k-index p-value
s(age) 9.00 3.31    0.95    0.81</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<ul>
<li>Residual plots for fitted values are a good way to check residuals in the normal case. But for binary outcomes, they look odd and are not helpful.</li>
<li><span class="math inline">\(k' = 9\rightarrow\)</span> the smooth for <code>age</code> was represented using 9 basis functions (default).</li>
<li><span class="math inline">\(edf=3.31\rightarrow\)</span> the effective degrees of freedom are much lower than 9, indicating that the smooth for <code>age</code> is relatively simple- not over wiggly or overfitted. It if is close to <span class="math inline">\(k\)</span> then it is overfitting.</li>
<li><span class="math inline">\(k-index = 0.94\)</span> and <span class="math inline">\(p-value = 0.44 \rightarrow\)</span>
<ul>
<li>No evidence that the basis dimension <span class="math inline">\(k\)</span> is too small.</li>
<li>The smooth has enough flexibility to capture the nonlinear pattern in age.</li>
<li>If the k-index were close to 0 or p-value &lt; 0.05, it would suggest that the smooth is constrained by too few basis functions and should be increased.</li>
</ul></li>
</ul>
<p><span style="color: blue;">Looking at the plot below, what is the trend of age and preterm birth?</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Module_5A_GAMs_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Biologically, log-odds of preterm birth is higher at very young ages, lowest around 29 years, and then increased again.</p>
<hr>
</section>
<section id="multiple-smoothers" class="level2">
<h2 class="anchored" data-anchor-id="multiple-smoothers">Multiple Smoothers</h2>
<p>So far, we have focused on fitting a single smooth function. In real-world applications, we often have <strong>multiple predictors</strong>, each contributing its own nonlinear effect on the response. This leads to <strong>additive models</strong> with multiple smooth components.</p>
<p>Consider the model with two continuous variables <span class="math inline">\(x_i\)</span> and <span class="math inline">\(z_i\)</span>:</p>
<p><span class="math display">\[
y_i = \beta_0 + g_1(x_i) + g_2(z_i) + \varepsilon_i,
\quad \varepsilon_i \sim N(0, \sigma^2)
\]</span></p>
<p>Here:</p>
<ul>
<li><span class="math inline">\(g_1(\cdot)\)</span> and <span class="math inline">\(g_2(\cdot)\)</span> are smooth, potentially nonlinear functions of their respective predictors.<br>
</li>
<li>The model can be extended to <strong>generalized responses</strong> (e.g., binomial, Poisson) through an appropriate link function.</li>
</ul>
<p>Each smooth can be written as a basis expansion with a curvature penalty: <span class="math display">\[
\begin{aligned}
g_1(x) &amp;= \sum_{m=1}^{M_1} \beta_{m1}\, b_{m1}^{(d)}(x),\qquad
g_2(z)  = \sum_{m=1}^{M_2} \beta_{m2}\, b_{m2}^{(d)}(z),
\end{aligned}
\]</span> with roughness penalties</p>
<p><span class="math display">\[
\lambda_1 \int \big[g_1''(x)\big]^2\,dx \;+\; \lambda_2 \int \big[g_2''(z)\big]^2\,dz.
\]</span></p>
<p>We add <strong>penalization to each term</strong> to induce smoothness so that each function remains flexible but avoids overfitting.</p>
<p><strong>Penalized Least Squares Criterion:</strong> The spline coefficients are estimated by minimizing:</p>
<p><span class="math display">\[
\sum_{i=1}^n (y_i - \hat{y}_i)^2
\;\;+\;\;
\lambda_1 \int \big[g_1''(x)\big]^2\,dx
\;\;+\;\;
\lambda_2 \int \big[g_2''(z)\big]^2\,dz,
\]</span></p>
<p>where the first term measures <strong>model fit</strong>, and the remaining terms penalize curvature of the smooth functions.</p>
<p>Or, in <strong>matrix form</strong>:</p>
<p><span class="math display">\[
\min_{\boldsymbol{\beta}}
\left\{
\;\|\mathbf{y} - \mathbf{X}\boldsymbol{\beta}\|^2
\;+\;
\lambda_1\, \boldsymbol{\beta}_1^\top \mathbf{K}_1 \boldsymbol{\beta}_1
\;+\;
\lambda_2\, \boldsymbol{\beta}_2^\top \mathbf{K}_2 \boldsymbol{\beta}_2
\right\},
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\mathbf{X}\)</span> is the <strong>design matrix</strong> containing all spline basis functions,</li>
<li><span class="math inline">\(\mathbf{K}_1\)</span> and <span class="math inline">\(\mathbf{K}_2\)</span> are <strong>penalty matrices</strong> encoding curvature,</li>
<li><span class="math inline">\(\lambda_1\)</span> and <span class="math inline">\(\lambda_2\)</span> control how <strong>wiggly</strong> each smooth is allowed to be.</li>
</ul>
<hr>
<p><span style="color: red;">Generalized Additive Model Form (any link &amp; family)</span></p>
<p><span class="math display">\[
g\!\big(\mathbb{E}[Y_i]\big)
=
\beta_0
\;+\;
g_1(x_i)
\;+\;
g_2(z_i).
\]</span></p>
<p>Estimation proceeds by <strong>penalized iteratively reweighted least squares</strong>:</p>
<p><span class="math display">\[
\min_{\boldsymbol{\beta}}
\left\{
-\ell(\boldsymbol{\beta}\mid \mathbf{y})
\;+\;
\lambda_1\, \boldsymbol{\beta}_1^\top \mathbf{K}_1 \boldsymbol{\beta}_1
\;+\;
\lambda_2\, \boldsymbol{\beta}_2^\top \mathbf{K}_2 \boldsymbol{\beta}_2
\right\},
\]</span></p>
<p>where <span class="math inline">\(\ell(\boldsymbol{\beta}\mid \mathbf{y})\)</span> is the log-likelihood for the chosen GLM family (e.g., binomial, Poisson, quasi-Poisson).</p>
<hr>
<section id="motivating-example-air-pollution-and-mortality" class="level3">
<h3 class="anchored" data-anchor-id="motivating-example-air-pollution-and-mortality">Motivating Example: Air Pollution and Mortality</h3>
<p><strong>Scientific Question:</strong> What is the association between daily mortality counts and daily concentrations of fine particulate matter (PM₂.₅)?</p>
<p><strong>Context:</strong><br>
Fine particulate matter (PM₂.₅) consists of solid and liquid particles in the air with a diameter less than <span class="math inline">\(2.5\,\mu\text{m}\)</span>. These particles mainly arise from:</p>
<ul>
<li>Power generation,<br>
</li>
<li>Vehicle emissions, and<br>
</li>
<li>Industrial activities.</li>
</ul>
<p><strong>Data Sources (New York City, 2001–2005):</strong></p>
<ul>
<li><strong>Mortality Data:</strong> Daily counts of non-accidental deaths (age ≥ 65) from the CDC.<br>
</li>
<li><strong>Air Pollution Data:</strong> Daily PM₂.₅ concentrations from the U.S. EPA.<br>
</li>
<li><strong>Meteorology Data:</strong> Temperature and humidity from the National Climatic Data Center (NOAA).</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Module_5A_GAMs_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="time-series-health-model" class="level2">
<h2 class="anchored" data-anchor-id="time-series-health-model">Time-Series Health Model</h2>
<p>We are interested in the association between <strong>daily variation</strong> in mortality counts and <strong>daily variation</strong> in air pollution exposure (PM₂.₅). In a time-series design, the <strong>population</strong> serves as the unit of analysis—our outcome represents <strong>total daily deaths</strong> in a defined area. Time-varying confounders (e.g., temperature, humidity, long-term trends) are flexibly controlled using <strong>smooth functions</strong>.</p>
<p><strong>Temporal Lag</strong>: There is often a <strong>delay</strong> between exposure and health response.We therefore model the association between <strong>daily mortality</strong> and <strong>previous-day exposure</strong>.</p>
<p>Let</p>
<ul>
<li><span class="math inline">\(y_t\)</span> denote the daily count of non-accidental deaths (age ≥ 65) on day <span class="math inline">\(t\)</span>,<br>
</li>
<li><span class="math inline">\(x_{t-1}\)</span> be the <strong>lag-1</strong> PM₂.₅ concentration (exposure on the previous day), and<br>
</li>
<li><span class="math inline">\(\text{DOW}_t\)</span> denote the day of week (a categorical factor).</li>
</ul>
<p><strong>GAM Formula</strong></p>
<p>We model the expected deaths with a log link (quasi-Poisson): <span class="math display">\[
\begin{aligned}
\log \mathbb{E}[y_t]
&amp;= \beta_0
\;+\; f_{\text{PM}}\!\big(x_{t-1}\big)
\;+\; \boldsymbol{\alpha}^{\top}\mathbf{1}\{\text{DOW}_t\}
\;+\; f_{\text{Season}}(\text{DOY}_t)
\;+\; f_{\text{Trend}}(t) \\
&amp;\quad
\;+\; f_{\text{Temp}}(\text{Temp}_t)
\;+\; f_{\text{Dp}}(\text{DpTemp}_t)
\;+\; f_{\text{RMTemp}}(\text{rmTemp}_t)
\;+\; f_{\text{RMDp}}(\text{rmDpTemp}_t).
\end{aligned}
\]</span></p>
<p>Each <span class="math inline">\(f_j\)</span> is a penalized spline with</p>
<p><span class="math display">\[
f_j(u) = \sum_{m=1}^{k_j} \beta_{jm} b_{jm}(u)
\]</span></p>
<p>and penalty <span class="math inline">\(\lambda_j\,\boldsymbol{\beta}_j^\top \mathbf{K}_j \boldsymbol{\beta}_j.\)</span></p>
<section id="fitting-in-r" class="level4">
<h4 class="anchored" data-anchor-id="fitting-in-r">Fitting in R</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Lag exposure variable</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>health<span class="sc">$</span>pm25_lag1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">head</span>(health<span class="sc">$</span>pm25, <span class="sc">-</span><span class="dv">1</span>))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>health<span class="sc">$</span>doy <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(<span class="fu">format</span>(health<span class="sc">$</span>date, <span class="st">"%j"</span>))   <span class="co"># Day of year</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>health<span class="sc">$</span>fdow <span class="ot">&lt;-</span> <span class="fu">factor</span>(health<span class="sc">$</span>dow)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>health<span class="sc">$</span>fdow <span class="ot">&lt;-</span> <span class="fu">relevel</span>(health<span class="sc">$</span>fdow, <span class="at">ref =</span> <span class="st">"Sunday"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">gam</span>(</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  cr65plus <span class="sc">~</span> <span class="fu">s</span>(pm25_lag1) <span class="sc">+</span> fdow <span class="sc">+</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">s</span>(doy, <span class="at">bs =</span> <span class="st">"cc"</span>, <span class="at">k =</span> <span class="dv">30</span>) <span class="sc">+</span>             <span class="co"># cyclic annual seasonality</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">s</span>(date2, <span class="at">k =</span> <span class="dv">100</span>) <span class="sc">+</span>                     <span class="co"># long-term trend</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">s</span>(Temp) <span class="sc">+</span> <span class="fu">s</span>(DpTemp) <span class="sc">+</span>                   <span class="co"># same-day meteorology</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">s</span>(rmTemp) <span class="sc">+</span> <span class="fu">s</span>(rmDpTemp),                <span class="co"># running means (lagged effects)</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">quasipoisson</span>(<span class="at">link =</span> <span class="st">"log"</span>),</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> health,</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"REML"</span> <span class="co">#better for GAMs</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Family: quasipoisson 
Link function: log 

Formula:
cr65plus ~ s(pm25_lag1) + fdow + s(doy, bs = "cc", k = 30) + 
    s(date2, k = 100) + s(Temp) + s(DpTemp) + s(rmTemp) + s(rmDpTemp)

Parametric coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    4.226470   0.007835 539.468   &lt;2e-16 ***
fdowFriday    -0.011713   0.011098  -1.055   0.2914    
fdowMonday     0.023848   0.010998   2.168   0.0303 *  
fdowSaturday  -0.008918   0.011068  -0.806   0.4205    
fdowThursday   0.003806   0.011051   0.344   0.7306    
fdowTuesday   -0.001758   0.011058  -0.159   0.8737    
fdowWednesday -0.001287   0.011060  -0.116   0.9074    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Approximate significance of smooth terms:
                edf Ref.df     F p-value    
s(pm25_lag1)  1.000  1.000 5.427 0.01994 *  
s(doy)       13.651 28.000 7.597 &lt; 2e-16 ***
s(date2)     11.111 13.579 9.336 &lt; 2e-16 ***
s(Temp)       1.687  2.164 6.506 0.00126 ** 
s(DpTemp)     1.002  1.004 4.422 0.03539 *  
s(rmTemp)     5.420  6.652 2.914 0.00596 ** 
s(rmDpTemp)   1.000  1.000 7.893 0.00501 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-sq.(adj) =  0.455   Deviance explained = 46.4%
-REML = 1079.7  Scale est. = 1.0884    n = 1825</code></pre>
</div>
</div>
<p><strong>Model Interpretation</strong></p>
<ul>
<li><p><strong>Lagged PM₂.₅ association:</strong><br>
The smooth function of previous-day PM₂.₅ (<span class="math inline">\(s(\text{pm25\_lag1})\)</span>) is statistically significant (<em>p = 0.0234</em>), indicating that <strong>higher PM₂.₅ levels are associated with increased daily mortality</strong> among adults aged 65+.</p></li>
<li><p><strong>Seasonality and long-term trends:</strong><br>
The smooth terms for <strong>day-of-year</strong> (<span class="math inline">\(s(\text{doy})\)</span>) and <strong>calendar time</strong> (<span class="math inline">\(s(\text{date2})\)</span>) are both highly significant (<em>p &lt; 2 × 10⁻¹⁶</em>), reflecting <strong>strong seasonal and gradual long-term patterns</strong> in mortality rates.</p></li>
<li><p><strong>Meteorological covariates:</strong><br>
Temperature (<span class="math inline">\(s(\text{Temp})\)</span>, <em>p = 0.0009</em>), dew point temperature (<span class="math inline">\(s(\text{DpTemp})\)</span>, <em>p = 0.064</em>), and their running means (<span class="math inline">\(s(\text{rmTemp})\)</span>, <em>p = 0.002</em>; <span class="math inline">\(s(\text{rmDpTemp})\)</span>, <em>p = 0.003</em>) all show significant smooth effects, suggesting <strong>both same-day and lagged weather conditions influence mortality</strong>.</p></li>
<li><p><strong>Overall model performance:</strong><br>
The model explains <strong>49.7% of the deviance</strong> (<em>R²₍adj₎ = 0.48</em>), indicating a strong fit for daily mortality time series data. Smoothers with higher <strong>effective degrees of freedom (edf)</strong> capture complex nonlinear patterns, while penalization prevents overfitting.</p></li>
</ul>
</section>
<section id="model-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="model-diagnostics">Model Diagnostics</h3>
<p>Again, we use <code>gam.check()</code> to <strong>evaluate the adequacy of the spline basis dimensions</strong> and the overall stability of the fitted GAM. This diagnostic checks whether each smooth term has enough flexibility (via its basis size <span class="math inline">\(k\)</span>) to capture the underlying pattern in the data, and verifies <strong>model convergence, gradient behavior, and Hessian stability</strong>.<br>
If a term shows a <strong>low k-index (&lt; 1)</strong> with a <strong>significant p-value</strong>, it suggests that the chosen <span class="math inline">\(k\)</span> is too low and the smooth may be <strong>underfitting</strong>.<br>
Otherwise, large p-values indicate that the current basis dimension is sufficient for that term.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gam.check</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Module_5A_GAMs_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Method: REML   Optimizer: outer newton
full convergence after 10 iterations.
Gradient range [-0.0002595022,0.0008164376]
(score 1079.705 &amp; scale 1.08843).
Hessian positive definite, eigenvalue range [7.693588e-06,906.0847].
Model rank =  179 / 179 

Basis dimension (k) checking results. Low p-value (k-index&lt;1) may
indicate that k is too low, especially if edf is close to k'.

                k'   edf k-index p-value   
s(pm25_lag1)  9.00  1.00    1.03   0.930   
s(doy)       28.00 13.65    1.02   0.915   
s(date2)     99.00 11.11    0.93   0.005 **
s(Temp)       9.00  1.69    1.00   0.525   
s(DpTemp)     9.00  1.00    1.00   0.550   
s(rmTemp)     9.00  5.42    1.05   0.995   
s(rmDpTemp)   9.00  1.00    1.01   0.635   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li><p><strong>Basis dimension adequacy:</strong><br>
Most smooth terms have <strong>high k-index values (~1)</strong> and <strong>non-significant p-values</strong>, indicating that the chosen basis dimensions (<span class="math inline">\(k\)</span>) were adequate for capturing the data’s complexity.</p></li>
<li><p><strong>Potential under-smoothing:</strong><br>
If any term had a lower k-index and significant p-value, suggesting that the basis dimension might be slightly <strong>restrictive</strong> for long-term trends. Increasing <span class="math inline">\(k\)</span> could allow more temporal flexibility if needed.</p></li>
<li><p><strong>Overall adequacy:</strong><br>
The diagnostic results overall confirm that the spline basis choices and penalization settings are appropriate.</p></li>
</ul>
<hr>
</section>
</section>
<section id="uncertainty-bands-for-gam-smooths" class="level2">
<h2 class="anchored" data-anchor-id="uncertainty-bands-for-gam-smooths">Uncertainty Bands for GAM Smooths</h2>
<p>In a GAM, each smooth <span class="math inline">\(f_j(x)\)</span> is estimated by <strong>penalized</strong> likelihood. For one smooth with basis vector <span class="math inline">\(\mathbf{b}(x)\)</span> and coefficients <span class="math inline">\(\boldsymbol{\beta}_j\)</span>, write <span class="math display">\[
f_j(x) \;=\; \mathbf{b}(x)^\top \boldsymbol{\beta}_j.
\]</span></p>
<p>Estimation maximizes a <strong>penalized</strong> log-likelihood <span class="math display">\[
\ell(\boldsymbol{\beta}\,;\,\mathbf{y}) \;-\; \tfrac{1}{2}\sum_j \lambda_j\,\boldsymbol{\beta}_j^\top \mathbf{K}_j \boldsymbol{\beta}_j,
\]</span> where <span class="math inline">\(\mathbf{K}_j\)</span> encodes curvature of <span class="math inline">\(f_j\)</span> and <span class="math inline">\(\lambda_j \ge 0\)</span> controls smoothness.</p>
<p>Near the optimum, a second-order (quadratic) approximation gives an <strong>approximately normal</strong> sampling distribution for the full coefficient vector <span class="math inline">\(\boldsymbol{\beta}\)</span>: <span class="math display">\[
\hat{\boldsymbol{\beta}} \;\approx\; N\!\Big(\boldsymbol{\beta}_{\text{true}},\; \mathbf{V}_{\beta}\Big),
\qquad
\mathbf{V}_{\beta} \;\approx\; \big(\,\hat{\mathbf{I}} \;+\; \sum_j \lambda_j \mathbf{K}_j\,\big)^{-1},
\]</span> where <span class="math inline">\(\hat{\mathbf{I}}\)</span> is the observed Fisher information from the GLM/GAM fit (for Gaussian models, <span class="math inline">\(\hat{\mathbf{I}}=\mathbf{X}^\top \mathbf{X}/\hat{\sigma}^2\)</span>).</p>
<p>For the smooth <span class="math inline">\(f_j\)</span> at a point <span class="math inline">\(x\)</span>, <span class="math display">\[
\hat{f}_j(x) \;=\; \mathbf{b}(x)^\top \hat{\boldsymbol{\beta}}_j,
\qquad
\mathrm{SE}\{\hat{f}_j(x)\} \;=\; \sqrt{\,\mathbf{b}(x)^\top \mathbf{V}_{\beta,j}\, \mathbf{b}(x)\,},
\]</span> where <span class="math inline">\(\mathbf{V}_{\beta,j}\)</span> is the block of <span class="math inline">\(\mathbf{V}_{\beta}\)</span> for smooth <span class="math inline">\(j\)</span>.</p>
<p>A <strong>pointwise 95% interval</strong> on the <em>linear predictor scale</em> is therefore <span class="math display">\[
\hat{f}_j(x) \;\pm\; 1.96 \times \mathrm{SE}\{\hat{f}_j(x)\}.
\]</span></p>
<p>If the model uses a link <span class="math inline">\(g(\mu)=\eta\)</span> (e.g., log for Poisson, logit for binomial), the bands above are for <span class="math inline">\(\eta\)</span>. To present on the response scale, transform:</p>
<ul>
<li>Poisson/log link: <span class="math inline">\(\hat{\mu}(x)=\exp\{\hat{\eta}(x)\}\)</span>, with delta-method SE if needed.</li>
<li>Binomial/logit link: <span class="math inline">\(\hat{p}(x)=\mathrm{logit}^{-1}\{\hat{\eta}(x)\}\)</span>.</li>
</ul>
<p><strong>Big Picture</strong></p>
<ul>
<li>The <strong>penalty</strong> adds curvature control and changes the coefficient covariance to <span class="math inline">\(\big(\hat{\mathbf{I}} + \sum_j \lambda_j \mathbf{K}_j\big)^{-1}\)</span>.</li>
<li>Bands on GAM plots come from the <strong>approximate normal</strong> distribution of <span class="math inline">\(\hat{f}_j(x)\)</span> via the basis-covariance-basis sandwich <span class="math inline">\(\mathbf{b}(x)^\top \mathbf{V}_{\beta,j}\mathbf{b}(x)\)</span>.</li>
<li>Shaded regions in <code>mgcv</code> plots are <strong>pointwise</strong> intervals on the linear predictor; they narrow where the data are dense and widen where data are sparse.</li>
</ul>
<hr>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary"><span style="color: purple;">Summary</span></h2>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Section</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>What is the Model?</strong></td>
<td>A <strong>Generalized Additive Model (GAM)</strong> extends GLMs by allowing each predictor to have its own smooth, potentially nonlinear effect: <span class="math inline">\(g(\mathbb{E}[Y]) = \beta_0 + \sum_{j=1}^p s_j(X_j)\)</span>.</td>
</tr>
<tr class="even">
<td><strong>Why Use GAMs?</strong></td>
<td>To capture <strong>nonlinear relationships</strong> between predictors and outcomes while keeping the model <strong>additive and interpretable</strong>. Each smooth <span class="math inline">\(s_j(X_j)\)</span> shows a separate partial effect.</td>
</tr>
<tr class="odd">
<td><strong>Key Idea</strong></td>
<td>Replace linear terms with <strong>penalized splines</strong>; the penalty <span class="math inline">\(\lambda_j \boldsymbol{\beta}_j'\mathbf{K}_j\boldsymbol{\beta}_j\)</span> controls smoothness. Each <span class="math inline">\(\lambda_j\)</span> is estimated from data (e.g., REML or GCV).</td>
</tr>
<tr class="even">
<td><strong>Multiple Smoothers</strong></td>
<td>GAMs combine several smooth functions additively: <span class="math inline">\(y_i = \beta_0 + g_1(x_i) + g_2(z_i) + \varepsilon_i\)</span>, each with its own smoothing parameter.</td>
</tr>
<tr class="odd">
<td><strong>Uncertainty Bands</strong></td>
<td>Each smooth <span class="math inline">\(s_j(x)\)</span> is estimated through spline basis coefficients <span class="math inline">\(\boldsymbol{\beta}_j\)</span>, which have a sampling variance–covariance matrix just like regression coefficients. The standard error of the smooth at any <span class="math inline">\(x\)</span> is obtained by propagating this variance through <span class="math inline">\(s_j(x) = \mathbf{b}(x)^\top \boldsymbol{\beta}_j\)</span>. The plotted shaded regions are <strong>pointwise 95% confidence intervals</strong> for the smooth function: <span class="math inline">\(\hat{s}_j(x) \pm 1.96 \times \mathrm{SE}[\hat{s}_j(x)]\)</span>, which widen where the curve is less certain and narrow where data are dense.</td>
</tr>
<tr class="even">
<td><strong>Model Checking</strong></td>
<td><code>gam.check()</code> assesses whether basis dimension <span class="math inline">\(k\)</span> is large enough and whether smooths are over- or under-fitted. A <span class="math inline">\(k\)</span>-index near 1 indicates adequate flexibility.</td>
</tr>
<tr class="odd">
<td><strong>Example 1 – Preterm Birth</strong></td>
<td>Logistic GAM with <span class="math inline">\(s(\text{age})\)</span> reveals a <strong>U-shaped age effect</strong> on log-odds of preterm birth—highest at youngest and oldest mothers.</td>
</tr>
<tr class="even">
<td><strong>Example 2 – Air Pollution</strong></td>
<td>Poisson GAM of daily deaths vs.&nbsp;lagged PM₂.₅ shows <strong>nonlinear exposure effects</strong>, <strong>seasonality</strong>, and <strong>long-term trend</strong> using multiple smooths.</td>
</tr>
<tr class="odd">
<td><strong>Interpretation</strong></td>
<td>Each smooth <span class="math inline">\(s_j(X_j)\)</span> displays the <strong>partial, nonlinear effect</strong> of <span class="math inline">\(X_j\)</span> on the response scale defined by the link. Shaded bands show uncertainty.</td>
</tr>
<tr class="even">
<td><strong>In Summary</strong></td>
<td>GAMs unify splines and GLMs, offering a <strong>flexible, interpretable, and data-driven</strong> framework for modeling nonlinear effects across multiple predictors.</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Module_4_Splines_Cheat.html" class="pagination-link" aria-label="Module 4 Cheat Sheet">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Module 4 Cheat Sheet</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Module_5B_GAMs.html" class="pagination-link" aria-label="Module 5B Generalized Additive Models">
        <span class="nav-page-text">Module 5B Generalized Additive Models</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>