<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Module 3A Marginal Models – BIOS 526 Modern Regression Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Module_3B_GEEs.html" rel="next">
<link href="./Module_2_GLM_Cheat.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Module_3A_GEEs.html">Module 3A Marginal Models</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">BIOS 526 Modern Regression Analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_0_MLR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 0: Multiple Linear Regression Review</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1A_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1A Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1B_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1B Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1C_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1C Random Intercepts and Slopes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_1_LMM_Cheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2A_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2A Generalized Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2B_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2B Generalized Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2C_GLMMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2C Generalized Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2D_GLMMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2D Generalized Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_2_GLM_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3A_GEEs.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Module 3A Marginal Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3B_GEEs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3B Marginal Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_3_GEE_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4A_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4A Basis Expansion and Parametric Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4B_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4B Parametric Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4C_Splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4C Penalized Splines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_4_Splines_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5A_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5A Generalized Additive Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5B_GAMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5B Generalized Additive Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_5_GAM_Cheat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5 Cheat Sheet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Module_6_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 6 Model Selection, Diagnostics, &amp; Regression Workflow</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#weighted-least-squares" id="toc-weighted-least-squares" class="nav-link active" data-scroll-target="#weighted-least-squares">Weighted Least Squares</a>
  <ul class="collapse">
  <li><a href="#motivation-and-examples" id="toc-motivation-and-examples" class="nav-link" data-scroll-target="#motivation-and-examples">Motivation and Examples</a></li>
  </ul></li>
  <li><a href="#generalized-least-squares" id="toc-generalized-least-squares" class="nav-link" data-scroll-target="#generalized-least-squares">Generalized Least Squares</a></li>
  <li><a href="#choosing-a-covariance-structure-for-grouped-data" id="toc-choosing-a-covariance-structure-for-grouped-data" class="nav-link" data-scroll-target="#choosing-a-covariance-structure-for-grouped-data">Choosing a Covariance Structure for Grouped Data</a>
  <ul class="collapse">
  <li><a href="#tlc-example-ols-wls-and-gls" id="toc-tlc-example-ols-wls-and-gls" class="nav-link" data-scroll-target="#tlc-example-ols-wls-and-gls">TLC Example: OLS, WLS, and GLS</a></li>
  <li><a href="#robust-inference" id="toc-robust-inference" class="nav-link" data-scroll-target="#robust-inference">Robust Inference</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span style="color: purple;">Summary</span></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Module 3A Marginal Models</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Readings</strong></p>
<ul>
<li><p>A useful reference: Halekoh, I., S. Hojsgaard, and J. Yan. <em>The R Package geepack for Generalized Estimating Equations</em>. Journal of Statistical Software. 2006.</p></li>
<li><p>Informal Overview: <a href="https://rlbarter.github.io/Practical-Statistics/2017/05/10/generalized-estimating-equations-gee/" class="uri">https://rlbarter.github.io/Practical-Statistics/2017/05/10/generalized-estimating-equations-gee/</a></p></li>
</ul>
<p><strong>Basic Concept</strong></p>
<ul>
<li><p>Weighted and generalized least squares</p></li>
<li><p>Estimating equations</p></li>
<li><p>Marginal correlation structures</p></li>
<li><p>Robust standard errors</p></li>
</ul>
<p><span style="color: blue;">Foundations for Generalized Estimating Equations covered in Module 3B.</span></p>
<section id="weighted-least-squares" class="level2">
<h2 class="anchored" data-anchor-id="weighted-least-squares">Weighted Least Squares</h2>
<section id="motivation-and-examples" class="level3">
<h3 class="anchored" data-anchor-id="motivation-and-examples">Motivation and Examples</h3>
<div class="illustration callout callout-style-default callout-important callout-titled" style="color: red">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Motivation:
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Marginal Models</strong>: assess population-level associations in the presence of heteroscedastic and/or correlated errors without requiring assumptions about subject-specific random effects.</p>
<ul>
<li>Longitudinal data</li>
<li>Clustered data</li>
<li>Multilevel data</li>
</ul>
<p>For example, suppose we have a linear regression problem give below:</p>
<p><span class="math display">\[
\mathbf{y} = \mathbf{X} \beta + \epsilon, \quad \epsilon \sim N(0, \mathbf{V})
\]</span></p>
<p>Here we assume the <u>residual covariance matrix</u> <span class="math inline">\(\mathbf{V}\)</span> <u>is known and diagonal.</u> meaning there are non-constant errors across units.</p>
<p><span class="math display">\[
\mathbf{V} = \begin{bmatrix}
v_1 &amp; 0 &amp; ... &amp; 0 \\
0 &amp; v_2 &amp; ... &amp; 0 \\
\vdots &amp; \ddots &amp; \ddots &amp; \vdots\\
0 &amp; ... &amp; ... &amp; v_N \end{bmatrix}
\]</span></p>
<p>We are interested in learning the <strong>population-level associations</strong> between <span class="math inline">\(\mathbf{y}\)</span> and <span class="math inline">\(\mathbf{X}\)</span> across <span class="math inline">\(n\)</span> subjects, i.e., How can we estimate <span class="math inline">\(\hat{\beta}\)</span> when errors are heteroscedastic (unequal variances across units)?</p>
</div>
</div>
<section id="motivating-example-revisiting-tlc" class="level4">
<h4 class="anchored" data-anchor-id="motivating-example-revisiting-tlc">Motivating Example: Revisiting TLC</h4>
<p>The Treatment of Lead-Exposed Children (TLC) was examined using a placebo-controlled randomized study of succimer (a chelating agent) in children with blood lead levels of 20-44 micrograms/dL. These data consist of four repeated measurements of blood lead levels obtained at baseline (or week 0) , week 1, week 4, and week 6 on 100 children who were randomly assigned to chelation treament with succimer or placebo.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>id</code></td>
<td>child identifier</td>
</tr>
<tr class="even">
<td><code>treatment</code></td>
<td>succimer or placebo</td>
</tr>
<tr class="odd">
<td><code>week</code></td>
<td>measurement week</td>
</tr>
<tr class="even">
<td><code>lead</code></td>
<td>lead level (outcome)</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nlme)        <span class="co"># gls(), varIdent(), corAR1(), corCompSymm()</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sandwich)    <span class="co"># vcovHC(), vcovCL()</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)      <span class="co"># coeftest()</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(clubSandwich) <span class="co"># cluster-robust SEs for gls/lme</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>tlcdata <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/tlc.RDS"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">treatment =</span> <span class="fu">factor</span>(treatment),          <span class="co"># succimer / placebo</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">week_f    =</span> <span class="fu">factor</span>(week, <span class="at">ordered =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">week_num  =</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(week)) <span class="co"># for AR(1) correlation</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tlcdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    id treatment week lead week_f week_num
1    1   placebo    0 30.8      0        0
101  1   placebo    1 26.9      1        1
201  1   placebo    4 25.8      4        4
301  1   placebo    6 23.8      6        6
2    2  succimer    0 26.5      0        0
102  2  succimer    1 14.8      1        1</code></pre>
</div>
</div>
<p><strong>We are interested in assessing the population-level effect of</strong> <code>treatment</code> <strong>on the outcome of lead levels</strong>.</p>
<hr>
</section>
<section id="why-not-olslmm-the-wrong-tool-for-the-job" class="level4">
<h4 class="anchored" data-anchor-id="why-not-olslmm-the-wrong-tool-for-the-job">Why Not OLS/LMM? <u>The Wrong Tool for the Job</u></h4>
<ol type="1">
<li><strong>OLS</strong>: If we ignore clustering and fit the standard OLS model:</li>
</ol>
<p><span class="math display">\[
y_{ij} = \beta_0 + \beta_1 \text{trt}_i + \beta_2 \text{week}_j + \epsilon_{ij}
\]</span></p>
<ul>
<li>OLS requirements: linearity, independence, homoscedasticity. OLS does not require distributional assumption.</li>
<li>Errors <span class="math inline">\(\rightarrow\)</span> assumed independent and ignores repeated measures within the same child.</li>
<li>We have seen that this does not bias <span class="math inline">\(\mathbf{\hat{\beta}}\)</span>, but produces incorrect SEs leading to incorrect inference.</li>
</ul>
<ol start="2" type="1">
<li><strong>LMM</strong>: If we account for clustering using LMM, we include it in the mean function as follows:</li>
</ol>
<p><span class="math display">\[
\begin{align*}
y_{ij} &amp;= \beta_0 + \beta_1 \text{trt}_i + \beta_2 \text{week}_j + \theta_i + \epsilon_{ij}\\
\epsilon_{ij} &amp; \sim N(0, \sigma^2)\\
\theta_i &amp; \sim N(0, \tau^2)
\end{align*}
\]</span></p>
<ul>
<li><p>Assumes random effects are assumed to be normally distributed. Inference depends on correct specification of random effects distribution and covariance structure.</p></li>
<li><p>Estimate population level associations (fixed effects) <strong>conditional on random effects</strong>. <span class="math inline">\(E(y_{ij}|\theta_i) = X_{ij}^T \mathbf{\beta} + \theta_i\)</span>.</p></li>
<li><p><span class="math inline">\(V\)</span> is the variance–covariance matrix implied by the random effects structure. In a random intercept model, <span class="math inline">\(V\)</span> has compound symmetry form, with diagonal elements <span class="math inline">\(\tau^2+\sigma^2\)</span> and off-diagonal elements <span class="math inline">\(\tau^2\)</span> within each subject.</p></li>
</ul>
<!--### Why not just use GLMM for marginal inference?

Consider a random-intercept logistic mixed model:

$$
Y_{ij}\mid \theta_i \sim \text{Bernoulli}(p_{ij}), \quad 
\text{logit}(p_{ij}) = \eta_{ij} + \theta_i,\quad 
\theta_i \sim N(0,\tau^2),\; \eta_{ij}=x_{ij}^\top\beta.
$$

The **marginal mean** is

$$
\mathbb E[Y_{ij}\mid x_{ij}]
= \mathbb E_{\theta_i}\!\left[\operatorname{expit}(\eta_{ij}+\theta_i)\right]
= \int \frac{1}{1+e^{-(\eta_{ij}+\theta)}}\,\phi(\theta;0,\tau^2)\,d\theta,
$$

where $\phi(\cdot;0,\tau^2)$ is the normal density.  

- This integral has **no closed form** (it is a logistic–normal integral).  
- It is **not equal** to $\operatorname{expit}(\eta_{ij})$ because expectation and the logit link do not commute:

$$
\mathbb E[\operatorname{expit}(\eta+\theta)]
\;\neq\;\operatorname{expit}(\eta+\mathbb E[\theta])
=\operatorname{expit}(\eta).
$$

So the marginal mean is a nonlinear shrinkage of the conditional curve, and the marginal model is **not logistic with the same $\beta$**.

For comparison, with a Poisson log-link random intercept model:

$$
\log \mu_{ij} = \eta_{ij}+\theta_i,\quad \theta_i\sim N(0,\tau^2),
$$

the marginal mean does have a closed form:

$$
\mathbb E[Y_{ij}\mid x_{ij}] 
= e^{\eta_{ij}}\,\mathbb E[e^{\theta_i}] 
= e^{\eta_{ij}}\,e^{\tau^2/2}.
$$

Here the marginal and conditional models differ by a multiplicative factor.  

**Takeaway:**  
GLMMs estimate **subject-specific (conditional)** effects. Obtaining marginal effects requires evaluating intractable integrals (logistic–normal), while **Marginal models directly estimate the marginal (population-averaged) effects** we often care about in public health.
-->
<hr>
</section>
<section id="the-better-approach-weighted-least-squares" class="level4">
<h4 class="anchored" data-anchor-id="the-better-approach-weighted-least-squares"><u>The Better Approach: Weighted Least Squares</u></h4>
<p>Using our example, we extend OLS (for normal/continuous outcomes) to account for heteroscedasticity <span style="color: blue;">unequal variance</span>. Each observation is given a weight reflecting its reliability, improving efficiency when some points are noisier than others.</p>
<p>Let <span class="math inline">\(\mathbf{W}\)</span> be diagonal with <span class="math inline">\(\operatorname{diag}(\mathbf{W})=(v_1^{-1/2}, v_2^{-1/2},\ldots,v_N^{-1/2})\)</span>. Note that <span class="math inline">\(\mathbf{W}^\top \mathbf{W}=\mathbf{V}^{-1}\)</span>.</p>
<p>Now derive the WLS estimator <span class="math inline">\(\hat{\beta}_{\text{WLS}}\)</span>:</p>
<div class="callout callout-style-simple callout-tip no-icon callout-titled" style="color:gray">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Derivation of WLS estimator
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Define the transformed variables <span class="math display">\[
y^*=\mathbf{W}y,\quad X^*=\mathbf{W}X,\quad \epsilon^*=\mathbf{W}\epsilon.
\]</span> Then <span class="math display">\[
y^*=X^*\beta+\epsilon^*,\qquad \mathrm{Var}(\epsilon^*)=I \; (\text{equal variance}).
\]</span></p>
<p>Using the OLS form, <span class="math display">\[
\begin{aligned}
\hat\beta_{\text{WLS}}
&amp;=(X^{*^\top}X^*)^{-1}X^{*^\top}y^* \\
&amp;=([WX]^\top WX)^{-1}[WX]^\top Wy \\
&amp;=(X^\top W^\top WX)^{-1}X^\top W^\top Wy \\
&amp;=(X^\top V^{-1}X)^{-1}X^\top V^{-1}y.
\end{aligned}
\]</span></p>
<p>Its (model-based) covariance is <span class="math display">\[
\begin{aligned}
\operatorname{Cov}(\hat\beta_{\text{WLS}})
&amp;=(X^\top V^{-1}X)^{-1}X^\top V^{-1}\operatorname{Cov}(y)\,V^{-1}X\,(X^\top V^{-1}X)^{-1} \\
&amp;=(X^\top V^{-1}X)^{-1}X^\top V^{-1} V\, V^{-1}X\,(X^\top V^{-1}X)^{-1}\\
&amp;=(X^\top V^{-1}X)^{-1}.
\end{aligned}
\]</span></p>
</div>
</div>
</div>
<p><strong>Properties of the WLS estimator (when</strong> <span class="math inline">\(E[y|X]=X\beta\)</span> and <span class="math inline">\(V\)</span> is correctly specified):</p>
<ul>
<li>Unbiasedness: <span class="math inline">\(E[\hat\beta_{\text{WLS}}]=\beta\)</span> (same as OLS).<br>
</li>
<li>Efficiency: If errors are heteroscedastic and uncorrelated, WLS is more efficient (lower variance) than OLS. How do we know this?</li>
</ul>
<p>Under heteroscedasticity, the <strong>true covariance</strong> of the OLS estimator is given by: <span class="math inline">\(\operatorname{Cov}(\hat\beta_{\text{OLS}})
  =(X^\top X)^{-1}X^\top V X\,(X^\top X)^{-1}.\)</span></p>
<p>When <span class="math inline">\(V= \sigma^2I\)</span> this reduces to <span class="math inline">\(\hat\sigma^2 (X^\top X)^{-1}.\)</span></p>
<ul>
<li>When <span class="math inline">\(V\neq\sigma^2 I\)</span>, the usual SEs are biased. In that case we must either
<ol type="1">
<li>use <strong>robust (sandwich) SEs</strong>, or<br>
</li>
<li>explicitly model <span class="math inline">\(V\)</span> and fit WLS.</li>
</ol></li>
</ul>
<hr>
</section>
<section id="wls-tlc-example" class="level4">
<h4 class="anchored" data-anchor-id="wls-tlc-example">WLS: TLC example</h4>
<p>We’ll now apply WLS to the TLC blood lead dataset to account for heteroskedasticity across weeks. The model fit is given by:</p>
<p><span class="math display">\[
\begin{aligned}
y_{ij} &amp;= \beta_0
+ \beta_1 \,\mathbf{1}\{\text{trt}_i=\text{succimer}\}
+ \sum_{k=1}^K \gamma_k \,\mathbf{1}\{\text{week}_j=k\} \\
&amp;\quad + \sum_{k=1}^K \delta_k \,\mathbf{1}\{\text{trt}_i=\text{succimer}\}\,\mathbf{1}\{\text{week}_j=k\}
+ \epsilon_{ij},\qquad \boldsymbol{\epsilon}\sim N(\mathbf{0},\mathbf{V}).
\end{aligned}
\]</span> Note: <span class="math inline">\(N=\)</span> total number of observations.</p>
<ul>
<li>General model: allow variances to be non-constant.</li>
<li>Implementation: impose structure (by week, by group, by function of covariate) so the model is estimable.</li>
<li>Visual inspection of residuals by week (not shown here yet) suggests that variability in lead levels increases over time.</li>
</ul>
<p>We’ll allow a non-constant variance for each week using <span class="math inline">\(nlme::gls\)</span> with a <span class="math inline">\(varIdent\)</span> variance function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Different variance per week; no correlation structure</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>m_wls <span class="ot">&lt;-</span> <span class="fu">gls</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  lead <span class="sc">~</span> treatment <span class="sc">*</span> week_f,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> tlcdata,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> week_f),  <span class="co"># Var differs by weekd, but still no correlation among observations.</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"REML"</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_wls)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized least squares fit by REML
  Model: lead ~ treatment * week_f 
  Data: tlcdata 
       AIC      BIC    logLik
  2635.581 2683.237 -1305.791

Variance function:
 Structure: Different standard deviations per stratum
 Formula: ~1 | week_f 
 Parameter estimates:
       0        1        4        6 
1.000000 1.325880 1.370457 1.524810 

Coefficients:
                               Value Std.Error  t-value p-value
(Intercept)                24.662000 0.4685087 52.63936  0.0000
treatmentsuccimer          -5.577500 0.6625714 -8.41796  0.0000
week_f.L                   -1.893502 0.9201165 -2.05789  0.0403
week_f.Q                    0.594000 0.9370174  0.63393  0.5265
week_f.C                   -0.191407 0.9536188 -0.20072  0.8410
treatmentsuccimer:week_f.L -1.537073 1.3012413 -1.18124  0.2382
treatmentsuccimer:week_f.Q  8.539000 1.3251427  6.44383  0.0000
treatmentsuccimer:week_f.C -2.436867 1.3486206 -1.80693  0.0715

 Correlation: 
                           (Intr) trtmnt wk_f.L wk_f.Q wk_f.C tr:_.L tr:_.Q
treatmentsuccimer          -0.707                                          
week_f.L                    0.268 -0.189                                   
week_f.Q                   -0.045  0.032  0.252                            
week_f.C                    0.061 -0.043 -0.027  0.106                     
treatmentsuccimer:week_f.L -0.189  0.268 -0.707 -0.178  0.019              
treatmentsuccimer:week_f.Q  0.032 -0.045 -0.178 -0.707 -0.075  0.252       
treatmentsuccimer:week_f.C -0.043  0.061  0.019 -0.075 -0.707 -0.027  0.106

Standardized residuals:
       Min         Q1        Med         Q3        Max 
-2.1756515 -0.6849999 -0.1515551  0.5294188  5.6327724 

Residual standard error: 5.022524 
Degrees of freedom: 400 total; 392 residual</code></pre>
</div>
</div>
<p><strong>Model Interpretation</strong></p>
<ul>
<li><p><strong>Intercept (24.66, p &lt; 0.001):</strong><br>
Average baseline lead level (week 0) for children in the <strong>placebo group</strong>.</p></li>
<li><p><strong>Succimer main effect (–5.58, p &lt; 0.001):</strong><br>
At baseline, succimer-treated children had lead levels about <strong>5.6 µg/dL lower</strong> than placebo children.</p></li>
<li><p><strong>Time trend in placebo group (orthogonal polynomial coding):</strong></p>
<ul>
<li>Quadratic contrast = 0.59 (p = 0.53): no curvature beyond the linear decline.<br>
</li>
<li>Cubic contrast = –0.19 (p = 0.84): no higher-order trend.</li>
</ul></li>
<li><p><strong>Succimer × time interactions:</strong></p>
<ul>
<li>Linear interaction = –1.54 (p = 0.24): no evidence that succimer changed the linear decline relative to placebo.<br>
</li>
<li>Quadratic interaction = +8.54 (p &lt; 0.001): strong evidence that succimer altered the <strong>curvature</strong> of the time trend (nonlinear divergence from placebo).<br>
</li>
<li>Cubic interaction = –2.44 (p = 0.072): marginal evidence of a cubic pattern.</li>
</ul></li>
<li><p><strong>Variance function:</strong><br>
Residual standard deviations were allowed to differ by week (relative to week 0 = 1.00).</p>
<ul>
<li>Week 1: 1.33× larger<br>
</li>
<li>Week 4: 1.37× larger<br>
</li>
<li>Week 6: 1.52× larger<br>
This means variability in lead levels <strong>increased over time</strong>, and GLS down-weighted later observations accordingly.</li>
</ul></li>
</ul>
<hr>
</section>
</section>
</section>
<section id="generalized-least-squares" class="level2">
<h2 class="anchored" data-anchor-id="generalized-least-squares">Generalized Least Squares</h2>
<p>In <strong>WLS</strong>, we assumed the residual covariance matrix <span class="math inline">\(\mathbf{V}\)</span> was <strong>known and diagonal</strong> — errors were uncorrelated but had unequal variances.</p>
<p><strong>Generalized Least Squares (GLS)</strong> drops that restriction: <span class="math inline">\(\mathbf{V}\)</span> can be any <strong>known, positive definite covariance matrix</strong>, allowing for both:</p>
<ul>
<li><strong>Unequal variances</strong> (heteroskedasticity), and<br>
</li>
<li><strong>Correlations</strong> among observations.</li>
</ul>
<p>GLS solves the same weighted least squares problem, but now the “weights” come from <span class="math inline">\(\mathbf{V}^{-1}\)</span>, which accounts for the full error structure (variances <strong>and</strong> covariances).</p>
<ul>
<li>If <span class="math inline">\(\mathbf{V}\)</span> is diagonal ⟶ <strong>GLS = WLS</strong>.<br>
</li>
<li>If <span class="math inline">\(\mathbf{V} = \sigma^2 \mathbf{I}\)</span> ⟶ <strong>GLS = OLS</strong>.<br>
</li>
<li>If <span class="math inline">\(\mathbf{V}\)</span> is a full positive definite matrix with nonzero off-diagonals ⟶ <strong>GLS</strong> (allows both unequal variances and correlations among errors). Estimator and covariance:</li>
</ul>
<p><span class="math display">\[
\begin{align*}
\hat{\beta}_{GLS} &amp;= (X^T V^{-1} X)^{-1} X^T V^{-1} y, \\
\operatorname{Cov}(\hat{\beta}_{GLS}) &amp;= (X^T V^{-1} X)^{-1}.
\end{align*}
\]</span></p>
<p>Because <span class="math inline">\(V\)</span> is positive definite, we can always factor it as <span class="math inline">\(\mathbf{V}^{-1} = W^T W\)</span> with <span class="math inline">\(W = V^{-1/2}\)</span>, showing GLS is just OLS on transformed data.</p>
<p><span class="math inline">\(\hat{\beta}_{GLS}\)</span> is the <strong>best (minimum variance) linear unbiased estimator (BLUE)</strong> when <span class="math inline">\(V\)</span> is correctly specified under model assumptions.</p>
<hr>
</section>
<section id="choosing-a-covariance-structure-for-grouped-data" class="level2">
<h2 class="anchored" data-anchor-id="choosing-a-covariance-structure-for-grouped-data">Choosing a Covariance Structure for Grouped Data</h2>
<p>When data are grouped or repeatedly measured (e.g., patients within clinics, time points within subjects), the error terms are usually correlated. In GLS, we model this correlation by specifying the covariance matrix:</p>
<p><span class="math display">\[
V_i = \sigma^2 R_i(\alpha),
\]</span></p>
<p>where <span class="math inline">\(\sigma^2\)</span> is the <strong>common variance</strong> and <span class="math inline">\(R_i(\alpha)\)</span> is the “group” <strong>correlation matrix</strong> that depends on parameters <span class="math inline">\(\alpha\)</span> (e.g., a correlation <span class="math inline">\(-1 &lt; \alpha &lt; 1\)</span>, but in practice it is often positive).</p>
<p><span class="math inline">\(R_i(\alpha)=\)</span> working correlation structure where <span class="math inline">\(R_i[j, j'] = cor(y_{ij}, y_{ij'})\)</span>.</p>
<p>For example, for a group (or cluster) of size 3, common choices for correlation matrices <span class="math inline">\(R_i(\alpha)\)</span> look as follows:</p>
<ul>
<li><p><strong>Independent</strong></p>
<ul>
<li>Assumes no correlation among observations within a group.<br>
</li>
<li><span class="math display">\[
R_i(\alpha) = \begin{bmatrix}
1 &amp; 0 &amp; 0 \\
0 &amp; 1 &amp; 0 \\
0 &amp; 0 &amp; 1
\end{bmatrix}.
\]</span></li>
</ul></li>
<li><p><strong>Exchangeable (Compound Symmetry)</strong></p>
<ul>
<li>All pairs of observations in a group share the same correlation <span class="math inline">\(\rho\)</span>.<br>
</li>
<li><span class="math display">\[
R_i(\alpha) = \begin{bmatrix}
1 &amp; \alpha &amp; \alpha \\
\alpha &amp; 1 &amp; \alpha\\
\alpha &amp; \alpha &amp; 1
\end{bmatrix}.
\]</span></li>
</ul></li>
<li><p><strong>Unstructured</strong></p>
<ul>
<li>Every variance and covariance is estimated freely. For 3 observations we need 3 variances and 3 unique covariances.<br>
</li>
<li><span class="math display">\[
R_i(\alpha) = \begin{bmatrix}
1 &amp; \alpha_{12} &amp; \alpha_{13} \\
\alpha_{12} &amp; 1 &amp; \alpha_{23} \\
\alpha_{13} &amp; \alpha_{23} &amp; 1
\end{bmatrix}.
\]</span></li>
</ul></li>
<li><p><strong>AR(1) (First-Order Autoregressive)</strong></p>
<ul>
<li>Correlation decays with time lag: <span class="math inline">\(\text{Corr}(\varepsilon_t,\varepsilon_{t+k}) = \alpha^k\)</span>.<br>
</li>
<li><span class="math display">\[
R_i(\alpha) = \begin{bmatrix}
1 &amp; \alpha &amp; \alpha^2 \\
\alpha &amp; 1 &amp; \alpha \\
\alpha^2 &amp; \alpha &amp; 1
\end{bmatrix}.
\]</span></li>
</ul></li>
</ul>
<hr>
<section id="tlc-example-ols-wls-and-gls" class="level3">
<h3 class="anchored" data-anchor-id="tlc-example-ols-wls-and-gls">TLC Example: OLS, WLS, and GLS</h3>
<p>We model mean lead level by treatment and week, changing only the <strong>error covariance V</strong>.</p>
<p><span class="math display">\[
\begin{aligned}
y_{ij} &amp;= \beta_0
+ \beta_1 \,\mathbf{1}\{\text{trt}_i=\text{succimer}\}
+ \sum_{k=1}^K \gamma_k \,\mathbf{1}\{\text{week}_j=k\} \\
&amp;\quad + \sum_{k=1}^K \delta_k \,\mathbf{1}\{\text{trt}_i=\text{succimer}\}\,\mathbf{1}\{\text{week}_j=k\}
+ \epsilon_{ij},\qquad \boldsymbol{\epsilon}\sim N(\mathbf{0},\mathbf{V}).
\end{aligned}
\]</span></p>
<p>Only the <strong>covariance V</strong> changes across OLS/WLS/GLS.</p>
<section id="ols-homoskedastic-independent" class="level4">
<h4 class="anchored" data-anchor-id="ols-homoskedastic-independent">1) OLS (homoskedastic, independent)</h4>
<p><strong>Errors (matrix form):</strong> <span class="math inline">\(\mathbf{V} = \sigma^2 I_N\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>m_ols <span class="ot">&lt;-</span> <span class="fu">gls</span>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  lead <span class="sc">~</span> treatment <span class="sc">*</span> week_f,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data   =</span> tlcdata,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"REML"</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(m_ols)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="wls-heteroskedastic-by-week-independent" class="level4">
<h4 class="anchored" data-anchor-id="wls-heteroskedastic-by-week-independent">2) WLS (heteroskedastic by week, independent)</h4>
<p><strong>Matrix form:</strong> <span class="math inline">\(V = diag(\nu_1, ... \nu_N)\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>m_wls <span class="ot">&lt;-</span> <span class="fu">gls</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  lead <span class="sc">~</span> treatment <span class="sc">*</span> week_f,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data   =</span> tlcdata,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights=</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> week_f),   <span class="co"># different SD per week</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"REML"</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(m_wls)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="gls-with-ar1-within-child-heteroskedastic-by-week-correlation" class="level4">
<h4 class="anchored" data-anchor-id="gls-with-ar1-within-child-heteroskedastic-by-week-correlation">3) GLS with AR(1) within child (heteroskedastic by week + correlation)</h4>
<p>Variance block for child i:</p>
<p><span class="math display">\[
V_i = A_i^{1/2}\,R_i(\rho)\,A_i^{1/2},\quad
A_i \;=\; \operatorname{diag}\!\big( v_{i1},\, v_{i2},\, \ldots,\, v_{i n_i} \big),
\qquad v_{ij} \;=\; \operatorname{Var}(\epsilon_{ij}), \quad
\big[R_i(\rho)\big]_{tt'}=\rho^{\,|t-t'|}.
\]</span></p>
<p>Full covariance is block-diagonal: V = blockdiag(V₁,…,V₁₀₀).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>m_gls_ar1 <span class="ot">&lt;-</span> <span class="fu">gls</span>(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  lead <span class="sc">~</span> treatment <span class="sc">*</span> week_f,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data        =</span> tlcdata,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights     =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> week_f),      <span class="co"># week-specific SDs</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">correlation =</span> <span class="fu">corAR1</span>(<span class="at">form =</span> <span class="sc">~</span> week_num <span class="sc">|</span> id),     <span class="co"># AR(1) within child</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">method      =</span> <span class="st">"REML"</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(m_gls_ar1)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Error structure</th>
<th>AIC</th>
<th>Residual SE</th>
<th>Key variance/correlation estimates</th>
<th>Effect estimates (examples)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>OLS</strong></td>
<td>Homoskedastic, independent<br><span class="math inline">\(V=\sigma^2 I\)</span></td>
<td>2647.0</td>
<td>6.63</td>
<td>None (assumes equal variance, no correlation)</td>
<td>Succimer at baseline: –5.58 (SE 0.66, p&lt;0.001)<br>Succimer×Week.Q: 8.54 (SE 1.33, p&lt;0.001)</td>
</tr>
<tr class="even">
<td><strong>WLS</strong></td>
<td>Heteroskedastic by week<br><span class="math inline">\(V=\mathrm{diag}(\nu_1,\ldots,\nu_N)\)</span></td>
<td>2635.6</td>
<td>5.02</td>
<td>Week SD multipliers: 1.33 (wk1), 1.37 (wk4), 1.52 (wk6)</td>
<td>Similar fixed effects; SEs adjusted for unequal variance</td>
</tr>
<tr class="odd">
<td><strong>GLS-AR1</strong></td>
<td>Heteroskedastic by week + AR(1) correlation<br><span class="math inline">\(V_i=A_i^{1/2}R_i(\rho)A_i^{1/2}\)</span></td>
<td>2516.3</td>
<td>5.63</td>
<td>AR(1) ρ = 0.75<br>Week SD multipliers: 1.26 (wk1), 1.14 (wk4), 1.33 (wk6)</td>
<td>Succimer×Week.Q effect stronger (SE smaller, t=10.2)</td>
</tr>
</tbody>
</table>
<p><strong>Comparison Summary:</strong></p>
<ul>
<li>Coefficient estimates are typically similar across OLS, WLS, and GLS, but they need not be identical because each estimator applies different weights implied by the assumed error structure. The estimators remain unbiased for the population-level effects, while their <strong>precision</strong> differs depending on how well the covariance structure is modeled.Fixed effects <span class="math inline">\(\beta's\)</span> remain unbiased across the 3 models, i.e., <span class="math inline">\(\beta_0 = 24.662\)</span> across all models.</li>
<li><strong>OLS</strong> ignores heteroskedasticity and correlation → larger residual SE, higher AIC.<br>
</li>
<li><strong>WLS</strong> improves efficiency by modeling unequal variance across weeks.<br>
</li>
<li><strong>GLS(AR1)</strong> further improves model fit (lowest AIC) by capturing within-child correlation.<br>
</li>
<li>Fixed-effect estimates are broadly similar, but <strong>precision improves</strong> as error structure is modeled more realistically.</li>
</ul>
<!--


::: {.callout-tip collapse="true" style="color:gray" appearance="minimal" icon="false"}
## Derivation of GLS covariance (mirror WLS)

1.  We assume that the error term $(\epsilon)$ has the following structure:

$$
\epsilon \sim N(0, \mathbf{V})
$$

where $\mathbf{V}$ is the var-cov matrix of the errors.

2.  Substituting $\mathbf{y}$ into the expression for $\hat{\beta}_{GLS}$:

$$
\begin{align*}
\hat{\beta}_{GLS} = & (\mathbf{X}^T \mathbf{V}^{-1}\mathbf{X})^{-1}\mathbf{X}^T \mathbf{V}^{-1}\mathbf{y}\\
& =(\mathbf{X}^T \mathbf{V}^{-1}\mathbf{X})^{-1}\mathbf{X}^T \mathbf{V}^{-1} (\mathbf{X}\mathbf{\beta} + \mathbf{\epsilon})
\end{align*}
$$

This can be expanded to:

$$
\hat{\beta}_{GLS} = (\mathbf{X}^T \mathbf{V}^{-1}\mathbf{X})^{-1}\mathbf{X}^T \mathbf{V}^{-1} \mathbf{X}\mathbf{\beta} + (\mathbf{X}^T \mathbf{V}^{-1}\mathbf{X})^{-1}\mathbf{X}^T \mathbf{V}^{-1}\mathbf{\epsilon}
$$ The first term simplifies to:

$$
\hat{\beta}_{GLS} = \mathbf{\beta} + (\mathbf{X}^T \mathbf{V}^{-1}\mathbf{X})^{-1}\mathbf{X}^T \mathbf{V}^{-1}\mathbf{\epsilon}
$$

4.  To find $cov(\hat{\beta}_{GLS})$, we need the covariance of the error term $\epsilon$ where $E(\epsilon) =0$ and $cov(\epsilon) = V$.

$$
Var(\hat{\beta}_{GLS}) = Var((X^T V^{-1}X)^{-1}X^T V^{-1} \epsilon)
$$

Using the property that $cov(A\mathbf{Z}) = A cov(\mathbf{Z}) A^T$ for an constant matrix $A$ and random vector $Z$:

$$
Var(\hat{\beta}_{GLS}) = (\mathbf{X}^T \mathbf{V}^{-1} \mathbf{X})^{-1} Var(\mathbf{\epsilon}) \mathbf{V}^{-1} \mathbf{X}(\mathbf{X}^T\mathbf{V}^{-1} \mathbf{X})^{-1}
$$

Substituting $Var(\mathbf{\epsilon}) = \mathbf{V}$:

$$
Var(\hat{\beta}_{GLS}) = (\mathbf{X}^T \mathbf{V}^{-1} \mathbf{X})^{-1} \mathbf{V} \mathbf{V}^{-1} \mathbf{X}(\mathbf{X}^T\mathbf{V}^{-1} \mathbf{X})^{-1}
$$

This simplified to:

$$
Var(\hat{\beta}_{GLS}) = (\mathbf{X}^T\mathbf{V}^{-1}\mathbf{X})^{-1} \mathbf{X}^T \mathbf{V}^{-1}\mathbf{X} (\mathbf{X}^T\mathbf{V}^{-1}\mathbf{X})^{-1}
$$

The middle term cancels out:

$$
Var(\hat{\beta}_{GLS}) =  (\mathbf{X}^T\mathbf{V}^{-1}\mathbf{X})^{-1}
$$

This means that $\hat{\beta}_{GLS} = (X^T V^{-1}X)^{-1}X^T V^{-1}$ is the **best (minimum variance) linear unbiased estimator (BLUE)**. 
:::-->
<hr>
</section>
</section>
<section id="robust-inference" class="level3">
<h3 class="anchored" data-anchor-id="robust-inference">Robust Inference</h3>
<p>So far we have assumed the error covariance matrix <span class="math inline">\(V\)</span> is <strong>known and correctly specified</strong>.<br>
- If that is true, WLS/GLS give efficient estimates and valid standard errors.<br>
- But if <span class="math inline">\(V\)</span> is <strong>unknown or misspecified</strong>, the coefficient estimates remain unbiased, yet the usual standard errors can be wrong.</p>
<p><strong>Solution:</strong> use <strong>robust (sandwich) standard errors</strong>, which provide valid inference without needing the exact form of <span class="math inline">\(V\)</span>.</p>
<hr>
<section id="robust-ses-for-ols" class="level4">
<h4 class="anchored" data-anchor-id="robust-ses-for-ols">Robust SEs for OLS</h4>
<p>The general covariance of the OLS estimator is</p>
<p><span class="math display">\[
\operatorname{Cov}(\hat{\beta}_{OLS}) = (X^\top X)^{-1} X^\top V X (X^\top X)^{-1}.
\]</span></p>
<ul>
<li><p>If <span class="math inline">\(V = \sigma^2 I\)</span> (homoskedastic, independent errors), this reduces to<br>
<span class="math inline">\(\operatorname{Cov}(\hat\beta_{OLS}) = \sigma^2 (X^\top X)^{-1}\)</span>.</p></li>
<li><p>If <span class="math inline">\(V \neq \sigma^2 I\)</span>, the usual plug-in formula is invalid.</p></li>
</ul>
<p>A robust alternative replaces <span class="math inline">\(V\)</span> with an empirical variance estimate:</p>
<p><span class="math display">\[
\hat\Omega = \operatorname{diag}(\hat\epsilon_1^2,\,\hat\epsilon_2^2,\,\ldots,\,\hat\epsilon_N^2),
\quad \hat\epsilon_i = y_i - x_i^\top \hat\beta_{OLS}.
\]</span></p>
<p>The <strong>sandwich covariance matrix</strong> is then</p>
<p><span class="math display">\[
\widehat{\operatorname{Cov}}(\hat\beta_{OLS}) =
(X^\top X)^{-1} X^\top \hat\Omega X (X^\top X)^{-1}.
\]</span></p>
<p>This is called the <strong>sandwich estimator</strong> because the middle term (<span class="math inline">\(\hat\Omega\)</span>, the “meat”) is sandwiched between two “bread” pieces involving <span class="math inline">\(X\)</span>.</p>
<hr>
</section>
<section id="robust-ses-for-gls" class="level4">
<h4 class="anchored" data-anchor-id="robust-ses-for-gls">Robust SEs for GLS</h4>
<p>For GLS, the coefficient estimator is</p>
<p><span class="math display">\[
\hat{\beta}_{GLS} = (X^\top V^{-1} X)^{-1} X^\top V^{-1} y.
\]</span></p>
<ul>
<li>If the assumed <span class="math inline">\(V\)</span> is <strong>correct</strong>, then</li>
</ul>
<p><span class="math display">\[
  \operatorname{Cov}(\hat\beta_{GLS}) = (X^\top V^{-1} X)^{-1}.
\]</span></p>
<ul>
<li>If the assumed <span class="math inline">\(V\)</span> is <strong>misspecified</strong>, these SEs are invalid.<br>
We can again use the sandwich form, now weighted by <span class="math inline">\(V^{-1}\)</span>:</li>
</ul>
<p>The robust (sandwich) covariance of the GLS estimator is</p>
<p><span class="math display">\[
\widehat{\operatorname{Cov}}(\hat\beta_{\text{GLS}})
= (X^\top V^{-1} X)^{-1} \;
X^\top V^{-1}\,\hat\Omega\,V^{-1} X \;
(X^\top V^{-1} X)^{-1},
\]</span></p>
<p>where <span class="math inline">\(\hat\Omega\)</span> captures empirical residual variation:</p>
<ul>
<li><p><strong>Clustered data:</strong><br>
Let <span class="math inline">\(\hat{\boldsymbol\epsilon}_i = y_i - X_i \hat\beta_{\text{GLS}}\)</span> be the residual vector for cluster <span class="math inline">\(i\)</span>. Then<br>
<span class="math display">\[
\hat\Omega = \sum_{i=1}^m X_i^\top V_i^{-1}\,\hat{\boldsymbol\epsilon}_i \hat{\boldsymbol\epsilon}_i^\top\, V_i^{-1} X_i.
\]</span></p></li>
<li><p><strong>Independent data (special case):</strong><br>
Each cluster has size 1, so <span class="math inline">\(\hat{\boldsymbol\epsilon}_i = \hat\epsilon_i\)</span> is a scalar. Then<br>
<span class="math display">\[
\hat\Omega = \operatorname{diag}(\hat\epsilon_1^2, \ldots, \hat\epsilon_N^2),
\]</span> recovering the White heteroskedasticity-robust estimator. #### Summary</p></li>
<li><p><strong>OLS + robust SEs:</strong> makes no assumptions about <span class="math inline">\(V\)</span>. Inference is valid, but estimates may be inefficient.<br>
</p></li>
<li><p><strong>GLS + robust SEs:</strong> assumes some structure for <span class="math inline">\(V\)</span>. If that structure is close to the truth, estimates are more efficient; robust SEs protect inference if the structure is wrong.</p></li>
</ul>
<hr>
</section>
<section id="gee-tlc-example" class="level4">
<h4 class="anchored" data-anchor-id="gee-tlc-example">GEE: TLC Example</h4>
<p>We now fit a <strong>(GEE)</strong> model for lead level, with exchangeable correlation within each child. GEE automatically computes robust (“sandwich”) SEs. We will further discuss GEE in Module 3B.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geepack)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>m_gee <span class="ot">&lt;-</span> <span class="fu">geeglm</span>(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  lead <span class="sc">~</span> treatment <span class="sc">*</span> week_f,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">id     =</span> id,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data   =</span> tlcdata,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">corstr =</span> <span class="st">"exchangeable"</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_gee)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
geeglm(formula = lead ~ treatment * week_f, data = tlcdata, id = id, 
    corstr = "exchangeable")

 Coefficients:
                           Estimate Std.err     Wald Pr(&gt;|W|)    
(Intercept)                 24.6620  0.7122 1198.939  &lt; 2e-16 ***
treatmentsuccimer           -5.5775  1.0949   25.951 3.50e-07 ***
week_f.L                    -1.8935  0.3919   23.347 1.35e-06 ***
week_f.Q                     0.5940  0.3104    3.662  0.05567 .  
week_f.C                    -0.1914  0.2690    0.506  0.47674    
treatmentsuccimer:week_f.L  -1.5371  0.8608    3.189  0.07415 .  
treatmentsuccimer:week_f.Q   8.5390  0.9540   80.116  &lt; 2e-16 ***
treatmentsuccimer:week_f.C  -2.4369  0.6615   13.572  0.00023 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation structure = exchangeable 
Estimated Scale Parameters:

            Estimate Std.err
(Intercept)    43.02   6.583
  Link = identity 

Estimated Correlation Parameters:
      Estimate Std.err
alpha   0.5954 0.07201
Number of clusters:   100  Maximum cluster size: 4 </code></pre>
</div>
</div>
<p><strong>Model Interpretation</strong></p>
<ul>
<li><p>Estimates <em>population-averaged</em> effects, not subject-specific trajectories.<br>
</p></li>
<li><p>Uses a working correlation structure (“exchangeable”) to model repeated measures within child.<br>
</p></li>
<li><p>Robust (sandwich) standard errors are reported, so inference remains valid even if the correlation model is wrong.</p></li>
<li><p><strong>Intercept (24.66, SE = 0.71, p &lt; 0.001)</strong><br>
Average baseline blood lead level in the placebo group is ~24.7 µg/dL.</p></li>
<li><p><strong>Treatment main effect (−5.58, SE = 1.10, p &lt; 0.001)</strong><br>
At baseline, succimer-treated children have significantly lower mean lead levels than placebo, and the robust SE confirms this effect is precise.</p></li>
<li><p><strong>Week trends (placebo group)</strong></p>
<ul>
<li>Linear effect (−1.89, SE = 0.39, p &lt; 0.001): mean lead decreases linearly across weeks.<br>
</li>
<li>Quadratic effect (+0.59, SE = 0.31, p ≈ 0.056): weak evidence of curvature.<br>
</li>
<li>Cubic effect (−0.19, SE = 0.27, p ≈ 0.48): no evidence of additional curvature.</li>
</ul></li>
<li><p><strong>Treatment × Week interactions</strong></p>
<ul>
<li>Linear (−1.54, SE = 0.86, p ≈ 0.07): succimer shows a steeper linear decline, but evidence is modest.<br>
</li>
<li>Quadratic (+8.54, SE = 0.95, p &lt; 0.001): strong, robust evidence that succimer introduces a pronounced curved pattern of decline.<br>
</li>
<li>Cubic (−2.44, SE = 0.66, p &lt; 0.001): robust evidence of additional curvature in succimer group compared to placebo.</li>
</ul></li>
<li><p><strong>Correlation structure</strong></p>
<ul>
<li>Estimated exchangeable correlation α ≈ 0.60 (moderate within-child correlation).<br>
</li>
<li>Even if this structure is not perfectly correct, robust SEs protect our inference.</li>
</ul></li>
</ul>
<hr>
</section>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary"><span style="color: purple;">Summary</span></h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Section</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>What is the model?</strong></td>
<td><strong>Marginal models</strong> estimate <strong>population-level associations</strong> without specifying random effects. The general form is <span class="math inline">\(y = X\beta + \epsilon\)</span>, with <span class="math inline">\(\operatorname{Var}(\epsilon) = V\)</span>.</td>
</tr>
<tr class="even">
<td><strong>Motivation</strong></td>
<td>Standard OLS assumes independent, homoskedastic errors. Real-world data (longitudinal, clustered, multilevel) often violate these assumptions, leading to biased SEs and invalid inference.</td>
</tr>
<tr class="odd">
<td><strong>OLS vs.&nbsp;WLS vs.&nbsp;GLS</strong></td>
<td><strong>OLS:</strong> ignores correlation/heteroskedasticity → unbiased coefficients, wrong SEs if <span class="math inline">\(V \neq \sigma^2 I\)</span>. <br> <strong>WLS:</strong> handles heteroskedasticity with diagonal <span class="math inline">\(V\)</span>. <br> <strong>GLS:</strong> allows general <span class="math inline">\(V\)</span> with variances + covariances.</td>
</tr>
<tr class="even">
<td><strong>Estimators</strong></td>
<td>OLS: <span class="math inline">\(\hat{\beta}_{OLS} = (X^\top X)^{-1}X^\top y\)</span> <br> WLS: <span class="math inline">\(\hat{\beta}_{WLS} = (X^\top V^{-1}X)^{-1} X^\top V^{-1} y\)</span>, <span class="math inline">\(V\)</span> diagonal <br> GLS: same formula with full <span class="math inline">\(V\)</span>.</td>
</tr>
<tr class="odd">
<td><strong>Properties</strong></td>
<td>All are unbiased and consistent for <span class="math inline">\(\beta\)</span>. Efficiency differs: WLS/GLS improve efficiency when <span class="math inline">\(V\)</span> is correctly specified.</td>
</tr>
<tr class="even">
<td><strong>Robust Inference</strong></td>
<td><strong>OLS + robust SEs:</strong> no assumptions about <span class="math inline">\(V\)</span>, robust but inefficient. <br> <strong>GLS + robust SEs:</strong> assumes structure in <span class="math inline">\(V\)</span> for efficiency, robust SEs protect against misspecification.</td>
</tr>
<tr class="odd">
<td><strong>Covariance Structures</strong></td>
<td><span class="math inline">\(V_i = \sigma^2 R_i(\alpha)\)</span> with group correlation matrix <span class="math inline">\(R_i(\alpha)\)</span>. <br> <strong>Independent:</strong> no correlation. <br> <strong>Exchangeable:</strong> equal correlation <span class="math inline">\(\rho\)</span>. <br> <strong>Unstructured:</strong> free variances/covariances. <br> <strong>AR(1):</strong> correlation decays with lag.</td>
</tr>
<tr class="even">
<td><strong>Example (TLC data)</strong></td>
<td>WLS with <code>varIdent</code> model: succimer significantly reduced baseline lead levels (–5.6 µg/dL, p&lt;0.001) and showed a strong quadratic trajectory difference vs.&nbsp;placebo. Residual variability increased over time, modeled via week-specific variances.</td>
</tr>
<tr class="odd">
<td><strong>Takeaway</strong></td>
<td>Marginal models give valid population-level inference when correlation/heteroskedasticity is present. Efficiency gains come from modeling <span class="math inline">\(V\)</span>, while robust SEs ensure inference remains valid even if <span class="math inline">\(V\)</span> is misspecified.</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Module_2_GLM_Cheat.html" class="pagination-link" aria-label="Module 2 Cheat Sheet">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Module 2 Cheat Sheet</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Module_3B_GEEs.html" class="pagination-link" aria-label="Module 3B Marginal Models">
        <span class="nav-page-text">Module 3B Marginal Models</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>